#!/usr/bin/env python3
"""Clone propagation: every function that is byte-exact in some manifest also matches any other
function in .text with identical masked bytes and identical extent (start..next function start).
Writes match/clones.txt in manifest format (read by run_all.py) and prints the gain.
"""
import bisect, glob, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pefile
from cmpobj import parse_coff, REL_SIZES
from card import load_funcs
import run_all

ROOT = run_all.ROOT
starts, _ = load_funcs()
starts_set = set(starts)
pe = pefile.PE(run_all.IMAGE, fast_load=True)
t = pe.sections[0]; text = t.get_data(); base = pe.OPTIONAL_HEADER.ImageBase + t.VirtualAddress

def extent(va):
    i = bisect.bisect_right(starts, va)
    end = starts[i] if i < len(starts) else va + 16
    n = end - va
    d = text[va - base: va - base + n]
    while n and d[n - 1] == 0xCC:
        n -= 1
    return n

rows = []
manifests = [os.path.join(ROOT, "match", "manifest.txt")] + glob.glob(os.path.join(ROOT, "match", "slices", "*", "manifest.txt"))
for m in manifests:
    for line in open(m):
        p = line.split("#", 1)[0].split()
        if len(p) >= 3:
            rows.append((p[0], p[1], int(p[2], 16), p[3:] or run_all.DEFAULT_FLAGS))
known = set(r[2] for r in rows)
out, gain = [], 0
for src, sym, va, flags in rows:
    obj = os.path.join(run_all.OUT, src.replace("/", "_").rsplit(".", 1)[0] + "_" +
                       "".join(f.strip("/") for f in flags).replace(":", "") + ".obj")
    if not os.path.exists(obj):
        continue
    secs, syms = parse_coff(obj)
    cands = [s for s in syms if sym in s]
    if len(cands) != 1:
        continue
    si, off = syms[cands[0]]
    n = extent(va)
    code = secs[si]["data"][off:off + n]
    mask = {v + k - off for v, _, ty in secs[si]["relocs"] for k in range(REL_SIZES.get(ty, 4)) if off <= v + k < off + n}
    if len(code) != n or n < 8:
        continue
    anchor_off = next((i for i in range(n) if all(j not in mask for j in range(i, min(n, i + 8)))), None)
    if anchor_off is None:
        continue
    anchor = code[anchor_off:anchor_off + 8]
    p = text.find(anchor)
    while p != -1:
        s = base + p - anchor_off
        if s != va and s in starts_set and s not in known and extent(s) == n and \
                all(text[s - base + i] == code[i] for i in range(n) if i not in mask):
            out.append("%s  %s  %08x  %s  # clone of %08x\n" % (src, sym, s, " ".join(flags) if flags != run_all.DEFAULT_FLAGS else "", va))
            known.add(s); gain += 1
        p = text.find(anchor, p + 1)
open(os.path.join(ROOT, "match", "clones.txt"), "w").write("# Generated by tools/matching/propagate.py\n" + "".join(out))
print("clone propagation: +%d functions from %d matched" % (gain, len(rows)))
