// Generated by tools/matching/synth.py (template bool_vcall_member_ptr_and_ret_int). Do not edit by hand.

// @ 0x00692ea0
struct V_00692ea0 { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual void s4(); virtual void s5(); virtual bool v();};
struct C_00692ea0 { unsigned pad[2]; V_00692ea0* p; int FUN_00692ea0(); };
int C_00692ea0::FUN_00692ea0() { V_00692ea0* q = p; if (q && q->v()) return 1; return 0; }

// @ 0x00d1d970
struct V_00d1d970 { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual void s4(); virtual void s5(); virtual void s6(); virtual void s7(); virtual void s8(); virtual void s9(); virtual void s10(); virtual void s11(); virtual void s12(); virtual void s13(); virtual void s14(); virtual void s15(); virtual void s16(); virtual void s17(); virtual void s18(); virtual void s19(); virtual bool v();};
struct C_00d1d970 { unsigned pad[53]; V_00d1d970* p; int FUN_00d1d970(); };
int C_00d1d970::FUN_00d1d970() { V_00d1d970* q = p; if (q && q->v()) return 1; return 0; }

// @ 0x00d1d9c0
struct V_00d1d9c0 { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual void s4(); virtual void s5(); virtual void s6(); virtual void s7(); virtual void s8(); virtual void s9(); virtual void s10(); virtual void s11(); virtual void s12(); virtual void s13(); virtual void s14(); virtual void s15(); virtual void s16(); virtual void s17(); virtual void s18(); virtual void s19(); virtual void s20(); virtual void s21(); virtual bool v();};
struct C_00d1d9c0 { unsigned pad[53]; V_00d1d9c0* p; int FUN_00d1d9c0(); };
int C_00d1d9c0::FUN_00d1d9c0() { V_00d1d9c0* q = p; if (q && q->v()) return 1; return 0; }

// @ 0x00ff6360
struct V_00ff6360 { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual bool v();};
struct C_00ff6360 { unsigned pad[6]; V_00ff6360* p; int FUN_00ff6360(); };
int C_00ff6360::FUN_00ff6360() { V_00ff6360* q = p; if (q && q->v()) return 1; return 0; }

// @ 0x00ff6550
struct V_00ff6550 { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual bool v();};
struct C_00ff6550 { unsigned pad[119]; V_00ff6550* p; int FUN_00ff6550(); };
int C_00ff6550::FUN_00ff6550() { V_00ff6550* q = p; if (q && q->v()) return 1; return 0; }
