// Generated by tools/matching/synth.py (template cast_two_ids_dd_first). Do not edit by hand.

// @ 0x005a41b0
struct D_005a41b0 { int pad[2]; struct S {
  D_005a41b0* dd() { return (D_005a41b0*)((char*)this - 8); }
  void* F(unsigned id) {
  if (id != 0xd0d22119u) { if (id != 0xee3f516eu) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_005a41b0::S::*p_005a41b0)(unsigned) = &D_005a41b0::S::F;

// @ 0x00ad7290
struct D_00ad7290 { int pad[1]; struct S {
  D_00ad7290* dd() { return (D_00ad7290*)((char*)this - 4); }
  void* F(unsigned id) {
  if (id != 0x445ca2bu) { if (id != 0x2f009dd0u) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_00ad7290::S::*p_00ad7290)(unsigned) = &D_00ad7290::S::F;

// @ 0x00cc89b0
struct D_00cc89b0 { int pad[15]; struct S {
  D_00cc89b0* dd() { return (D_00cc89b0*)((char*)this - 60); }
  void* F(unsigned id) {
  if (id != 0x152256bcu) { if (id != 0x2f009dd0u) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_00cc89b0::S::*p_00cc89b0)(unsigned) = &D_00cc89b0::S::F;

// @ 0x00d08d40
struct D_00d08d40 { int pad[2]; struct S {
  D_00d08d40* dd() { return (D_00d08d40*)((char*)this - 8); }
  void* F(unsigned id) {
  if (id != 0x91d4af08u) { if (id != 0x2f009dd0u) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_00d08d40::S::*p_00d08d40)(unsigned) = &D_00d08d40::S::F;

// @ 0x00d15130
struct D_00d15130 { int pad[16]; struct S {
  D_00d15130* dd() { return (D_00d15130*)((char*)this - 64); }
  void* F(unsigned id) {
  if (id != 0x1356bb6u) { if (id != 0x2f009dd0u) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_00d15130::S::*p_00d15130)(unsigned) = &D_00d15130::S::F;

// @ 0x00f0e270
struct D_00f0e270 { int pad[14]; struct S {
  D_00f0e270* dd() { return (D_00f0e270*)((char*)this - 56); }
  void* F(unsigned id) {
  if (id != 0x107b7140u) { if (id != 0x2f009dd0u) return 0; return dd() ? this : 0; }
  return dd();
  } } s; };
void* (D_00f0e270::S::*p_00f0e270)(unsigned) = &D_00f0e270::S::F;
