// Generated by tools/matching/synth.py (template cdecl_fwd2_arg_const). Do not edit by hand.

// @ 0x01104740
void __cdecl FUN_01104420(void*, void*, void*);
void FUN_01104740(void* a, void* b) { FUN_01104420(a, b, (void*)0x1103b50); }

// @ 0x011895b0
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_011895b0(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e4cd0); }

// @ 0x01191840
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_01191840(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e5a94); }

// @ 0x01191e10
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_01191e10(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e5c38); }

// @ 0x01192e70
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_01192e70(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e63a4); }

// @ 0x01194f50
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_01194f50(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e6eb8); }

// @ 0x011973e0
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_011973e0(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e7288); }

// @ 0x01197420
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_01197420(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e72c0); }

// @ 0x011974d0
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_011974d0(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14e7448); }

// @ 0x011d0350
void __cdecl FUN_011980b0(void*, void*, void*);
void FUN_011d0350(void* a, void* b) { FUN_011980b0(a, b, (void*)0x14f2984); }
