// Generated by tools/matching/synth.py (template cdecl_this_arg_tailcall). Do not edit by hand.
struct Obj { void Method(); };

// @ 0x00831fd0
void FUN_00831fd0(Obj* p) { p->Method(); }

// @ 0x009616e0
void FUN_009616e0(Obj* p) { p->Method(); }

// @ 0x00980720
void FUN_00980720(Obj* p) { p->Method(); }

// @ 0x00c6fea0
void FUN_00c6fea0(Obj* p) { p->Method(); }

// @ 0x00c6feb0
void FUN_00c6feb0(Obj* p) { p->Method(); }

// @ 0x01081da0
void FUN_01081da0(Obj* p) { p->Method(); }

// @ 0x011ed9d0
void FUN_011ed9d0(Obj* p) { p->Method(); }

// @ 0x011efff0
void FUN_011efff0(Obj* p) { p->Method(); }

// @ 0x011f36c0
void FUN_011f36c0(Obj* p) { p->Method(); }

// @ 0x011f5000
void FUN_011f5000(Obj* p) { p->Method(); }

// @ 0x011fa200
void FUN_011fa200(Obj* p) { p->Method(); }
