// Generated by tools/matching/synth.py (template copy_forward_pod_void). Do not edit by hand.

// @ 0x00707630
struct S_00707630 { int d[9]; };
void FUN_00707630(S_00707630* first, S_00707630* last, S_00707630* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x0073fe20
struct S_0073fe20 { int d[12]; };
void FUN_0073fe20(S_0073fe20* first, S_0073fe20* last, S_0073fe20* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00a7a930
struct S_00a7a930 { int d[7]; };
void FUN_00a7a930(S_00a7a930* first, S_00a7a930* last, S_00a7a930* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00ac4360
struct S_00ac4360 { int d[15]; };
void FUN_00ac4360(S_00ac4360* first, S_00ac4360* last, S_00ac4360* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00b8e3c0
struct S_00b8e3c0 { int d[11]; };
void FUN_00b8e3c0(S_00b8e3c0* first, S_00b8e3c0* last, S_00b8e3c0* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00c06600
struct S_00c06600 { int d[8]; };
void FUN_00c06600(S_00c06600* first, S_00c06600* last, S_00c06600* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00dfb210
struct S_00dfb210 { int d[14]; };
void FUN_00dfb210(S_00dfb210* first, S_00dfb210* last, S_00dfb210* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}


// @ 0x00f6b470
struct S_00f6b470 { int d[113]; };
void FUN_00f6b470(S_00f6b470* first, S_00f6b470* last, S_00f6b470* dest) {
    for (; first != last; ++first, ++dest) *dest = *first;
}

