// Generated by tools/matching/synth.py (template creature_ability_deldtor_release). Do not edit by hand.
struct IAlloc { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void Free(void*, unsigned, int); };
extern IAlloc* gAlloc;
struct Counted { virtual void Destroy(int) = 0; unsigned short flag; short rc; };
struct cCreatureAbility {
  virtual ~cCreatureAbility() {}
  unsigned short mSize;
};

// @ 0x01094e10
struct C_01094e10 : cCreatureAbility { int pad[1]; Counted* m; C_01094e10(); __forceinline virtual ~C_01094e10() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 41); } };
C_01094e10::C_01094e10() {}

// @ 0x010980d0
struct C_010980d0 : cCreatureAbility { int pad[1]; Counted* m; C_010980d0(); __forceinline virtual ~C_010980d0() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 41); } };
C_010980d0::C_010980d0() {}

// @ 0x010c0110
struct C_010c0110 : cCreatureAbility { int pad[2]; Counted* m; C_010c0110(); __forceinline virtual ~C_010c0110() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 36); } };
C_010c0110::C_010c0110() {}

// @ 0x010c4d40
struct C_010c4d40 : cCreatureAbility { int pad[2]; Counted* m; C_010c4d40(); __forceinline virtual ~C_010c4d40() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 36); } };
C_010c4d40::C_010c4d40() {}

// @ 0x010c4ed0
struct C_010c4ed0 : cCreatureAbility { int pad[1]; Counted* m; C_010c4ed0(); __forceinline virtual ~C_010c4ed0() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 36); } };
C_010c4ed0::C_010c4ed0() {}

// @ 0x010c54b0
struct C_010c54b0 : cCreatureAbility { int pad[1]; Counted* m; C_010c54b0(); __forceinline virtual ~C_010c54b0() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 36); } };
C_010c54b0::C_010c54b0() {}

// @ 0x010ca5c0
struct C_010ca5c0 : cCreatureAbility { int pad[2]; Counted* m; C_010ca5c0(); __forceinline virtual ~C_010ca5c0() { Counted* q = m; if (q->flag) { if (--q->rc == 0) q->Destroy(1); } }
 static __forceinline void operator delete(void* p) { gAlloc->Free(p, ((cCreatureAbility*)p)->mSize, 36); } };
C_010ca5c0::C_010ca5c0() {}
