// Generated by tools/matching/synth.py (template ctor_base_dtor_two_u16_call_eh). Do not edit by hand.

// @ 0x00689e80
struct B_00689e80 { unsigned pad[4]; ~B_00689e80(); };
struct C_00689e80 : B_00689e80 { unsigned short a, b; void Set(unsigned); C_00689e80(unsigned x); };
C_00689e80::C_00689e80(unsigned x) { b = 19; a = 11; Set(x); }

// @ 0x006a1650
struct B_006a1650 { unsigned pad[4]; ~B_006a1650(); };
struct C_006a1650 : B_006a1650 { unsigned short a, b; void Set(unsigned); C_006a1650(unsigned x); };
C_006a1650::C_006a1650(unsigned x) { b = 9; a = 2; Set(x); }

// @ 0x006a16b0
struct B_006a16b0 { unsigned pad[4]; ~B_006a16b0(); };
struct C_006a16b0 : B_006a16b0 { unsigned short a, b; void Set(unsigned); C_006a16b0(unsigned x); };
C_006a16b0::C_006a16b0(unsigned x) { b = 13; a = 2; Set(x); }

// @ 0x006a19b0
struct B_006a19b0 { unsigned pad[4]; ~B_006a19b0(); };
struct C_006a19b0 : B_006a19b0 { unsigned short a, b; void Set(unsigned); C_006a19b0(unsigned x); };
C_006a19b0::C_006a19b0(unsigned x) { b = 1; a = 2; Set(x); }

// @ 0x006a1a10
struct B_006a1a10 { unsigned pad[4]; ~B_006a1a10(); };
struct C_006a1a10 : B_006a1a10 { unsigned short a, b; void Set(unsigned); C_006a1a10(unsigned x); };
C_006a1a10::C_006a1a10(unsigned x) { b = 13; a = 2; Set(x); }
