// Generated by tools/matching/synth.py (template deldtor_vcall_member_ptr_ext_base). Do not edit by hand.

// @ 0x00599590
struct I_00599590 { virtual void f0(); virtual void f1(); };
struct H_00599590 { I_00599590* p; ~H_00599590() { if (p) p->f1(); } };
struct B_00599590 { virtual ~B_00599590(); };
struct C_00599590 : B_00599590 { unsigned pad[41]; H_00599590 h; C_00599590(); };
C_00599590::C_00599590() {}

// @ 0x00c3f800
struct I_00c3f800 { virtual void f0(); virtual void f1(); };
struct H_00c3f800 { I_00c3f800* p; ~H_00c3f800() { if (p) p->f1(); } };
struct B_00c3f800 { virtual ~B_00c3f800(); };
struct C_00c3f800 : B_00c3f800 { unsigned pad[146]; H_00c3f800 h; C_00c3f800(); };
C_00c3f800::C_00c3f800() {}

// @ 0x00c5f4a0
struct I_00c5f4a0 { virtual void f0(); virtual void f1(); virtual void f2(); virtual void f3(); virtual void f4(); virtual void f5(); virtual void f6(); virtual void f7(); virtual void f8(); virtual void f9(); virtual void f10(); virtual void f11(); virtual void f12(); virtual void f13(); virtual void f14(); virtual void f15(); virtual void f16(); virtual void f17(); virtual void f18(); virtual void f19(); virtual void f20(); virtual void f21(); virtual void f22(); virtual void f23(); virtual void f24(); virtual void f25(); virtual void f26(); virtual void f27(); virtual void f28(); virtual void f29(); virtual void f30(); virtual void f31(); virtual void f32(); virtual void f33(); virtual void f34(); virtual void f35(); virtual void f36(); virtual void f37(); virtual void f38(); virtual void f39(); virtual void f40(); virtual void f41(); virtual void f42(); virtual void f43(); virtual void f44(); virtual void f45(); virtual void f46(); virtual void f47(); virtual void f48(); };
struct H_00c5f4a0 { I_00c5f4a0* p; ~H_00c5f4a0() { if (p) p->f48(); } };
struct B_00c5f4a0 { virtual ~B_00c5f4a0(); };
struct C_00c5f4a0 : B_00c5f4a0 { unsigned pad[124]; H_00c5f4a0 h; C_00c5f4a0(); };
C_00c5f4a0::C_00c5f4a0() {}

// @ 0x00e15430
struct I_00e15430 { virtual void f0(); virtual void f1(); };
struct H_00e15430 { I_00e15430* p; ~H_00e15430() { if (p) p->f1(); } };
struct B_00e15430 { virtual ~B_00e15430(); };
struct C_00e15430 : B_00e15430 { unsigned pad[38]; H_00e15430 h; C_00e15430(); };
C_00e15430::C_00e15430() {}

// @ 0x00e15490
struct I_00e15490 { virtual void f0(); virtual void f1(); virtual void f2(); };
struct H_00e15490 { I_00e15490* p; ~H_00e15490() { if (p) p->f2(); } };
struct B_00e15490 { virtual ~B_00e15490(); };
struct C_00e15490 : B_00e15490 { unsigned pad[60]; H_00e15490 h; C_00e15490(); };
C_00e15490::C_00e15490() {}

// @ 0x0101a2f0
struct I_0101a2f0 { virtual void f0(); virtual void f1(); };
struct H_0101a2f0 { I_0101a2f0* p; ~H_0101a2f0() { if (p) p->f1(); } };
struct B_0101a2f0 { virtual ~B_0101a2f0(); };
struct C_0101a2f0 : B_0101a2f0 { unsigned pad[32]; H_0101a2f0 h; C_0101a2f0(); };
C_0101a2f0::C_0101a2f0() {}
