// Generated by tools/matching/synth.py (template deldtor_implicit_member_inline_base). Do not edit by hand.
struct Mem { ~Mem(); };
struct Base { virtual ~Base() {} virtual void g(); };

// @ 0x0066afa0
struct C_0066afa0 : Base { unsigned pad[2]; Mem m; C_0066afa0(); };
C_0066afa0::C_0066afa0() {}

// @ 0x008087c0
struct C_008087c0 : Base { unsigned pad[1]; Mem m; C_008087c0(); };
C_008087c0::C_008087c0() {}

// @ 0x0082b850
struct C_0082b850 : Base { Mem m; C_0082b850(); };
C_0082b850::C_0082b850() {}

// @ 0x008e8050
struct C_008e8050 : Base { unsigned pad[5]; Mem m; C_008e8050(); };
C_008e8050::C_008e8050() {}

// @ 0x011378e0
struct C_011378e0 : Base { unsigned pad[15]; Mem m; C_011378e0(); };
C_011378e0::C_011378e0() {}

// @ 0x01139410
struct C_01139410 : Base { unsigned pad[8]; Mem m; C_01139410(); };
C_01139410::C_01139410() {}

// @ 0x0113ae80
struct C_0113ae80 : Base { unsigned pad[12]; Mem m; C_0113ae80(); };
C_0113ae80::C_0113ae80() {}

// @ 0x0113ba00
struct C_0113ba00 : Base { unsigned pad[11]; Mem m; C_0113ba00(); };
C_0113ba00::C_0113ba00() {}
