// Generated by tools/matching/synth.py (template derived_ctor_vptr_zero_member). Do not edit by hand.

// @ 0x00b01870
struct B_C_00b01870 { B_C_00b01870(); virtual void fb(); };
struct C_00b01870 : B_C_00b01870 { char pad[48]; int m; C_00b01870(); virtual void fb(); };
C_00b01870::C_00b01870() : m(0) {}


// @ 0x00b32470
struct B_C_00b32470 { B_C_00b32470(); virtual void fb(); };
struct C_00b32470 : B_C_00b32470 { char pad[4]; int m; C_00b32470(); virtual void fb(); };
C_00b32470::C_00b32470() : m(0) {}


// @ 0x00e88600
struct B_C_00e88600 { B_C_00e88600(); virtual void fb(); };
struct C_00e88600 : B_C_00e88600 { char pad[48]; int m; C_00e88600(); virtual void fb(); };
C_00e88600::C_00e88600() : m(0) {}


// @ 0x01157410
struct B_C_01157410 { B_C_01157410(); virtual void fb(); };
struct C_01157410 : B_C_01157410 { char pad[436]; int m; C_01157410(); virtual void fb(); };
C_01157410::C_01157410() : m(0) {}


// @ 0x01159900
struct B_C_01159900 { B_C_01159900(); virtual void fb(); };
struct C_01159900 : B_C_01159900 { char pad[460]; int m; C_01159900(); virtual void fb(); };
C_01159900::C_01159900() : m(0) {}


// @ 0x01163da0
struct B_C_01163da0 { B_C_01163da0(); virtual void fb(); };
struct C_01163da0 : B_C_01163da0 { char pad[428]; int m; C_01163da0(); virtual void fb(); };
C_01163da0::C_01163da0() : m(0) {}

