// Generated by tools/matching/synth.py (template eastl_vec_swap_alloc_check). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);
static inline void sw(int*& a, int*& b) { int* t = a; a = b; b = t; }

// @ 0x00643120
struct C_00643120 { int* b; int* e; int* c; int x; int y;
 C_00643120(const C_00643120&); void assign(const C_00643120&);
 ~C_00643120() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00643120(C_00643120& o); };
void C_00643120::FUN_00643120(C_00643120& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00643120 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x009c0ed0
struct C_009c0ed0 { int* b; int* e; int* c; int x; int y;
 C_009c0ed0(const C_009c0ed0&); void assign(const C_009c0ed0&);
 ~C_009c0ed0() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_009c0ed0(C_009c0ed0& o); };
void C_009c0ed0::FUN_009c0ed0(C_009c0ed0& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_009c0ed0 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x009e0610
struct C_009e0610 { int* b; int* e; int* c; int x; int y;
 C_009e0610(const C_009e0610&); void assign(const C_009e0610&);
 ~C_009e0610() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_009e0610(C_009e0610& o); };
void C_009e0610::FUN_009e0610(C_009e0610& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_009e0610 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00a8cf50
struct C_00a8cf50 { int* b; int* e; int* c; int x; int y;
 C_00a8cf50(const C_00a8cf50&); void assign(const C_00a8cf50&);
 ~C_00a8cf50() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00a8cf50(C_00a8cf50& o); };
void C_00a8cf50::FUN_00a8cf50(C_00a8cf50& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00a8cf50 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00ac4d50
struct C_00ac4d50 { int* b; int* e; int* c; int x; int y;
 C_00ac4d50(const C_00ac4d50&); void assign(const C_00ac4d50&);
 ~C_00ac4d50() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00ac4d50(C_00ac4d50& o); };
void C_00ac4d50::FUN_00ac4d50(C_00ac4d50& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00ac4d50 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00b85190
struct C_00b85190 { int* b; int* e; int* c; int x; int y;
 C_00b85190(const C_00b85190&); void assign(const C_00b85190&);
 ~C_00b85190() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00b85190(C_00b85190& o); };
void C_00b85190::FUN_00b85190(C_00b85190& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00b85190 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00b85ea0
struct C_00b85ea0 { int* b; int* e; int* c; int x; int y;
 C_00b85ea0(const C_00b85ea0&); void assign(const C_00b85ea0&);
 ~C_00b85ea0() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00b85ea0(C_00b85ea0& o); };
void C_00b85ea0::FUN_00b85ea0(C_00b85ea0& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00b85ea0 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00b86980
struct C_00b86980 { int* b; int* e; int* c; int x; int y;
 C_00b86980(const C_00b86980&); void assign(const C_00b86980&);
 ~C_00b86980() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00b86980(C_00b86980& o); };
void C_00b86980::FUN_00b86980(C_00b86980& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00b86980 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00baa080
struct C_00baa080 { int* b; int* e; int* c; int x; int y;
 C_00baa080(const C_00baa080&); void assign(const C_00baa080&);
 ~C_00baa080() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00baa080(C_00baa080& o); };
void C_00baa080::FUN_00baa080(C_00baa080& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00baa080 tmp(*this); assign(o); o.assign(tmp); } }

// @ 0x00f6b730
struct C_00f6b730 { int* b; int* e; int* c; int x; int y;
 C_00f6b730(const C_00f6b730&); void assign(const C_00f6b730&);
 ~C_00f6b730() { if (b && b[-1]) EASTL_allocator_deallocate(b); }
 void FUN_00f6b730(C_00f6b730& o); };
void C_00f6b730::FUN_00f6b730(C_00f6b730& o) {
 if ((!b || b[-1]) && (!o.b || o.b[-1])) { sw(b, o.b); sw(e, o.e); sw(c, o.c); }
 else { C_00f6b730 tmp(*this); assign(o); o.assign(tmp); } }
