// Generated by tools/matching/synth.py (template eastl_vec_reset_free). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);

// @ 0x006a5f40
struct C_006a5f40 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006a5f40(); };
void C_006a5f40::FUN_006a5f40() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x006aadd0
struct C_006aadd0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006aadd0(); };
void C_006aadd0::FUN_006aadd0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x006aae00
struct C_006aae00 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006aae00(); };
void C_006aae00::FUN_006aae00() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x006b68f0
struct C_006b68f0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006b68f0(); };
void C_006b68f0::FUN_006b68f0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x006f25f0
struct C_006f25f0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006f25f0(); };
void C_006f25f0::FUN_006f25f0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x006f2f80
struct C_006f2f80 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_006f2f80(); };
void C_006f2f80::FUN_006f2f80() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00702e70
struct C_00702e70 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00702e70(); };
void C_00702e70::FUN_00702e70() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00711320
struct C_00711320 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00711320(); };
void C_00711320::FUN_00711320() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00711350
struct C_00711350 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00711350(); };
void C_00711350::FUN_00711350() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00712820
struct C_00712820 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00712820(); };
void C_00712820::FUN_00712820() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00713530
struct C_00713530 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00713530(); };
void C_00713530::FUN_00713530() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00721fe0
struct C_00721fe0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00721fe0(); };
void C_00721fe0::FUN_00721fe0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x007c65e0
struct C_007c65e0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_007c65e0(); };
void C_007c65e0::FUN_007c65e0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x007c7470
struct C_007c7470 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_007c7470(); };
void C_007c7470::FUN_007c7470() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x007ebe40
struct C_007ebe40 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_007ebe40(); };
void C_007ebe40::FUN_007ebe40() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x0083cd60
struct C_0083cd60 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_0083cd60(); };
void C_0083cd60::FUN_0083cd60() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00840220
struct C_00840220 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00840220(); };
void C_00840220::FUN_00840220() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00846ad0
struct C_00846ad0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00846ad0(); };
void C_00846ad0::FUN_00846ad0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x008471d0
struct C_008471d0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_008471d0(); };
void C_008471d0::FUN_008471d0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00a2bde0
struct C_00a2bde0 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00a2bde0(); };
void C_00a2bde0::FUN_00a2bde0() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }

// @ 0x00a2e620
struct C_00a2e620 { unsigned pad; void* p; unsigned n; unsigned c;
 void H(void* p, unsigned n); void FUN_00a2e620(); };
void C_00a2e620::FUN_00a2e620() { H(p, n); c = 0; if (n > 1) EASTL_allocator_deallocate(p); }
