// Generated by tools/matching/synth.py (template eastl_new_ctor_then_init3). Do not edit by hand.
typedef unsigned int size_t;
void* operator new(size_t size, const char* name, int flags, unsigned debugFlags, const char* file, int line);

// @ 0x007d4410
struct T_007d4410 { T_007d4410(); char d[140]; };
void I_007d4410(int, int, T_007d4410*);
T_007d4410* FUN_007d4410(int a, int b) { T_007d4410* p = new("n", 0, 0u, (const char*)0, 0) T_007d4410; I_007d4410(a, b, p); return p; }

// @ 0x007edbc0
struct T_007edbc0 { T_007edbc0(); char d[128]; };
void I_007edbc0(int, int, T_007edbc0*);
T_007edbc0* FUN_007edbc0(int a, int b) { T_007edbc0* p = new("n", 0, 0u, (const char*)0, 0) T_007edbc0; I_007edbc0(a, b, p); return p; }

// @ 0x00a78150
struct T_00a78150 { T_00a78150(); char d[152]; };
void I_00a78150(int, int, T_00a78150*);
T_00a78150* FUN_00a78150(int a, int b) { T_00a78150* p = new("n", 0, 0u, (const char*)0, 0) T_00a78150; I_00a78150(a, b, p); return p; }

// @ 0x00a859a0
struct T_00a859a0 { T_00a859a0(); char d[176]; };
void I_00a859a0(int, int, T_00a859a0*);
T_00a859a0* FUN_00a859a0(int a, int b) { T_00a859a0* p = new("n", 0, 0u, (const char*)0, 0) T_00a859a0; I_00a859a0(a, b, p); return p; }

// @ 0x00a87160
struct T_00a87160 { T_00a87160(); char d[184]; };
void I_00a87160(int, int, T_00a87160*);
T_00a87160* FUN_00a87160(int a, int b) { T_00a87160* p = new("n", 0, 0u, (const char*)0, 0) T_00a87160; I_00a87160(a, b, p); return p; }

// @ 0x00a93880
struct T_00a93880 { T_00a93880(); char d[384]; };
void I_00a93880(int, int, T_00a93880*);
T_00a93880* FUN_00a93880(int a, int b) { T_00a93880* p = new("n", 0, 0u, (const char*)0, 0) T_00a93880; I_00a93880(a, b, p); return p; }

// @ 0x00a97ec0
struct T_00a97ec0 { T_00a97ec0(); char d[272]; };
void I_00a97ec0(int, int, T_00a97ec0*);
T_00a97ec0* FUN_00a97ec0(int a, int b) { T_00a97ec0* p = new("n", 0, 0u, (const char*)0, 0) T_00a97ec0; I_00a97ec0(a, b, p); return p; }

// @ 0x00aa1b60
struct T_00aa1b60 { T_00aa1b60(); char d[704]; };
void I_00aa1b60(int, int, T_00aa1b60*);
T_00aa1b60* FUN_00aa1b60(int a, int b) { T_00aa1b60* p = new("n", 0, 0u, (const char*)0, 0) T_00aa1b60; I_00aa1b60(a, b, p); return p; }

// @ 0x00ab28c0
struct T_00ab28c0 { T_00ab28c0(); char d[624]; };
void I_00ab28c0(int, int, T_00ab28c0*);
T_00ab28c0* FUN_00ab28c0(int a, int b) { T_00ab28c0* p = new("n", 0, 0u, (const char*)0, 0) T_00ab28c0; I_00ab28c0(a, b, p); return p; }

// @ 0x00abb560
struct T_00abb560 { T_00abb560(); char d[336]; };
void I_00abb560(int, int, T_00abb560*);
T_00abb560* FUN_00abb560(int a, int b) { T_00abb560* p = new("n", 0, 0u, (const char*)0, 0) T_00abb560; I_00abb560(a, b, p); return p; }

// @ 0x00abcda0
struct T_00abcda0 { T_00abcda0(); char d[232]; };
void I_00abcda0(int, int, T_00abcda0*);
T_00abcda0* FUN_00abcda0(int a, int b) { T_00abcda0* p = new("n", 0, 0u, (const char*)0, 0) T_00abcda0; I_00abcda0(a, b, p); return p; }

// @ 0x00f4b0c0
struct T_00f4b0c0 { T_00f4b0c0(); char d[264]; };
void I_00f4b0c0(int, int, T_00f4b0c0*);
T_00f4b0c0* FUN_00f4b0c0(int a, int b) { T_00f4b0c0* p = new("n", 0, 0u, (const char*)0, 0) T_00f4b0c0; I_00f4b0c0(a, b, p); return p; }

// @ 0x00f580a0
struct T_00f580a0 { T_00f580a0(); char d[616]; };
void I_00f580a0(int, int, T_00f580a0*);
T_00f580a0* FUN_00f580a0(int a, int b) { T_00f580a0* p = new("n", 0, 0u, (const char*)0, 0) T_00f580a0; I_00f580a0(a, b, p); return p; }

// @ 0x00f63d50
struct T_00f63d50 { T_00f63d50(); char d[212]; };
void I_00f63d50(int, int, T_00f63d50*);
T_00f63d50* FUN_00f63d50(int a, int b) { T_00f63d50* p = new("n", 0, 0u, (const char*)0, 0) T_00f63d50; I_00f63d50(a, b, p); return p; }
