// Generated by tools/matching/synth.py (template eastl_str_name_vcall_elem_loop). Do not edit by hand.
typedef unsigned short wchar16;
void EASTL_allocator_deallocate(void* p);
extern const wchar16 kEmpty[];
struct Alloc2 { const char* mpName; };
struct WString {
    wchar16* mpBegin; wchar16* mpEnd; wchar16* mpCap; Alloc2 a;
    WString(int n) : mpEnd(0), mpCap(0) { a.mpName = 0; Init(n); }
    void Init(int);
    const wchar16* c_str() const { return mpBegin != mpEnd ? mpBegin : kEmpty; }
    WString(const WString&);
    ~WString() { if ((mpCap - mpBegin) > 1 && mpBegin) EASTL_allocator_deallocate(mpBegin); }
};
struct Obj { virtual void v0(const wchar16*); virtual void v1(const wchar16*); };
struct Elem { int f0; int f4; int pad[6]; };
struct Vec { Elem* b; Elem* e; };
WString Mk(const wchar16*, int);
bool ElemFn(Obj*, int, void*);
extern const wchar16 kEmpty[];

// @ 0x00acb340
bool FUN_00acb340(Obj* o, const wchar16* name, Vec* v) {
    bool ok = true; const wchar16* b;
    if (v->b != v->e) {
        WString s(name ? Mk(name, -1) : WString(0));
        const wchar16* b = s.mpBegin; o->v0(b != s.mpEnd ? b : kEmpty);
        for (Elem* p = v->b, *e = v->e; p != e; ++p) ok = ok && ElemFn(o, 0, &p->f4);
        o->v1(b != s.mpEnd ? b : kEmpty);
    }
    return ok;
}


// @ 0x00b04120
bool FUN_00b04120(Obj* o, const wchar16* name, Vec* v) {
    bool ok = true; const wchar16* b;
    if (v->b != v->e) {
        WString s(name ? Mk(name, -1) : WString(0));
        const wchar16* b = s.mpBegin; o->v0(b != s.mpEnd ? b : kEmpty);
        for (Elem* p = v->b, *e = v->e; p != e; ++p) ok = ok && ElemFn(o, 0, &p->f4);
        o->v1(b != s.mpEnd ? b : kEmpty);
    }
    return ok;
}


// @ 0x00c78ea0
bool FUN_00c78ea0(Obj* o, const wchar16* name, Vec* v) {
    bool ok = true; const wchar16* b;
    if (v->b != v->e) {
        WString s(name ? Mk(name, -1) : WString(0));
        const wchar16* b = s.mpBegin; o->v0(b != s.mpEnd ? b : kEmpty);
        for (Elem* p = v->b, *e = v->e; p != e; ++p) ok = ok && ElemFn(o, 0, &p->f4);
        o->v1(b != s.mpEnd ? b : kEmpty);
    }
    return ok;
}


// @ 0x00c78ff0
bool FUN_00c78ff0(Obj* o, const wchar16* name, Vec* v) {
    bool ok = true; const wchar16* b;
    if (v->b != v->e) {
        WString s(name ? Mk(name, -1) : WString(0));
        const wchar16* b = s.mpBegin; o->v0(b != s.mpEnd ? b : kEmpty);
        for (Elem* p = v->b, *e = v->e; p != e; ++p) ok = ok && ElemFn(o, 0, &p->f4);
        o->v1(b != s.mpEnd ? b : kEmpty);
    }
    return ok;
}


// @ 0x00f29ce0
bool FUN_00f29ce0(Obj* o, const wchar16* name, Vec* v) {
    bool ok = true; const wchar16* b;
    if (v->b != v->e) {
        WString s(name ? Mk(name, -1) : WString(0));
        const wchar16* b = s.mpBegin; o->v0(b != s.mpEnd ? b : kEmpty);
        for (Elem* p = v->b, *e = v->e; p != e; ++p) ok = ok && ElemFn(o, 0, &p->f4);
        o->v1(b != s.mpEnd ? b : kEmpty);
    }
    return ok;
}

