// Generated by tools/matching/synth.py (template eastl_vec_intrusive_ptr_insert_n_value). Do not edit by hand.
#include <string.h>
extern "C" {
void* __cdecl EASTL_allocator_allocate(unsigned, const char*, int, int, const char*, int) throw();
void __cdecl EASTL_allocator_deallocate(void*);
}
struct RefObj {
  virtual int v0() throw();
  virtual int v1() throw();
  virtual int v2() throw();
  virtual int v3() throw();
  virtual int v4() throw();
  virtual int v5() throw();
  virtual int v6() throw();
  virtual int v7() throw();
  virtual int v8() throw();
  virtual int v9() throw();
  virtual int v10() throw();
  virtual int v11() throw();
  virtual int v12() throw();
  virtual int v13() throw();
  virtual int v14() throw();
  virtual int v15() throw();
  virtual int v16() throw();
  virtual int v17() throw();
  virtual int v18() throw();
  virtual int v19() throw();
  virtual int v20() throw();
  virtual int v21() throw();
  virtual int v22() throw();
  virtual int v23() throw();
  virtual int v24() throw();
  virtual int v25() throw();
  virtual int v26() throw();
  virtual int v27() throw();
  virtual int v28() throw();
  virtual int v29() throw();
  virtual int v30() throw();
  virtual int v31() throw();
  virtual int v32() throw();
  virtual int v33() throw();
  virtual int v34() throw();
  virtual int v35() throw();
  virtual int v36() throw();
  virtual int v37() throw();
  virtual int v38() throw();
  virtual int v39() throw();
  virtual int v40() throw();
  virtual int v41() throw();
  virtual int v42() throw();
  virtual int v43() throw();
  virtual int v44() throw();
  virtual int v45() throw();
  virtual int v46() throw();
  virtual int v47() throw();
  virtual int v48() throw();
  virtual int v49() throw();
  virtual int v50() throw();
  virtual int v51() throw();
  virtual int v52() throw();
  virtual int v53() throw();
  virtual int v54() throw();
  virtual int v55() throw();
  virtual int v56() throw();
  virtual int v57() throw();
  virtual int v58() throw();
  virtual int v59() throw();
  virtual int v60() throw();
  virtual int v61() throw();
  virtual int v62() throw();
  virtual int v63() throw();
};

// @ 0x0057f220
struct IP_0057f220 {
  RefObj* p;
  IP_0057f220(const IP_0057f220& o) throw() : p(o.p) { if (p) p->v1(); }
  ~IP_0057f220() throw() { if (p) p->v2(); }
};
void __cdecl um(void*, IP_0057f220*, IP_0057f220*, IP_0057f220*, IP_0057f220*) throw();
void __cdecl cb(IP_0057f220*, IP_0057f220*, IP_0057f220*) throw();
void __cdecl fl(IP_0057f220*, IP_0057f220*, IP_0057f220*) throw();
void __cdecl ufn(IP_0057f220*, unsigned, const IP_0057f220*, IP_0057f220*) throw();
extern const char s_0057f220[]; extern const char n_0057f220[];
struct V_0057f220 {
  IP_0057f220 *b, *e, *c;
  void f(IP_0057f220* pos, unsigned n, const IP_0057f220& v);
};
void V_0057f220::f(IP_0057f220* pos, unsigned n, const IP_0057f220& v) {
  IP_0057f220* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_0057f220 temp = v;
      IP_0057f220* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_0057f220*)EASTL_allocator_allocate(cap * 4, n_0057f220, 0, 0, s_0057f220, 0xd1) : 0;
    IP_0057f220* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_0057f220* np = (IP_0057f220*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_0057f220*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}



// @ 0x00a8c690
struct IP_00a8c690 {
  RefObj* p;
  IP_00a8c690(const IP_00a8c690& o) throw() : p(o.p) { if (p) p->v13(); }
  ~IP_00a8c690() throw() { if (p) p->v14(); }
};
void __cdecl um(void*, IP_00a8c690*, IP_00a8c690*, IP_00a8c690*, IP_00a8c690*) throw();
void __cdecl cb(IP_00a8c690*, IP_00a8c690*, IP_00a8c690*) throw();
void __cdecl fl(IP_00a8c690*, IP_00a8c690*, IP_00a8c690*) throw();
void __cdecl ufn(IP_00a8c690*, unsigned, const IP_00a8c690*, IP_00a8c690*) throw();
extern const char s_00a8c690[]; extern const char n_00a8c690[];
struct V_00a8c690 {
  IP_00a8c690 *b, *e, *c;
  void f(IP_00a8c690* pos, unsigned n, const IP_00a8c690& v);
};
void V_00a8c690::f(IP_00a8c690* pos, unsigned n, const IP_00a8c690& v) {
  IP_00a8c690* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_00a8c690 temp = v;
      IP_00a8c690* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_00a8c690*)EASTL_allocator_allocate(cap * 4, n_00a8c690, 0, 0, s_00a8c690, 0xd1) : 0;
    IP_00a8c690* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_00a8c690* np = (IP_00a8c690*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_00a8c690*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}



// @ 0x00b0d710
struct IP_00b0d710 {
  RefObj* p;
  IP_00b0d710(const IP_00b0d710& o) throw() : p(o.p) { if (p) p->v24(); }
  ~IP_00b0d710() throw() { if (p) p->v23(); }
};
void __cdecl um(void*, IP_00b0d710*, IP_00b0d710*, IP_00b0d710*, IP_00b0d710*) throw();
void __cdecl cb(IP_00b0d710*, IP_00b0d710*, IP_00b0d710*) throw();
void __cdecl fl(IP_00b0d710*, IP_00b0d710*, IP_00b0d710*) throw();
void __cdecl ufn(IP_00b0d710*, unsigned, const IP_00b0d710*, IP_00b0d710*) throw();
extern const char s_00b0d710[]; extern const char n_00b0d710[];
struct V_00b0d710 {
  IP_00b0d710 *b, *e, *c;
  void f(IP_00b0d710* pos, unsigned n, const IP_00b0d710& v);
};
void V_00b0d710::f(IP_00b0d710* pos, unsigned n, const IP_00b0d710& v) {
  IP_00b0d710* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_00b0d710 temp = v;
      IP_00b0d710* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_00b0d710*)EASTL_allocator_allocate(cap * 4, n_00b0d710, 0, 0, s_00b0d710, 0xd1) : 0;
    IP_00b0d710* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_00b0d710* np = (IP_00b0d710*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_00b0d710*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}



// @ 0x00bf4170
struct IP_00bf4170 {
  RefObj* p;
  IP_00bf4170(const IP_00bf4170& o) throw() : p(o.p) { if (p) p->v1(); }
  ~IP_00bf4170() throw() { if (p) p->v2(); }
};
void __cdecl um(void*, IP_00bf4170*, IP_00bf4170*, IP_00bf4170*, IP_00bf4170*) throw();
void __cdecl cb(IP_00bf4170*, IP_00bf4170*, IP_00bf4170*) throw();
void __cdecl fl(IP_00bf4170*, IP_00bf4170*, IP_00bf4170*) throw();
void __cdecl ufn(IP_00bf4170*, unsigned, const IP_00bf4170*, IP_00bf4170*) throw();
extern const char s_00bf4170[]; extern const char n_00bf4170[];
struct V_00bf4170 {
  IP_00bf4170 *b, *e, *c;
  void f(IP_00bf4170* pos, unsigned n, const IP_00bf4170& v);
};
void V_00bf4170::f(IP_00bf4170* pos, unsigned n, const IP_00bf4170& v) {
  IP_00bf4170* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_00bf4170 temp = v;
      IP_00bf4170* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_00bf4170*)EASTL_allocator_allocate(cap * 4, n_00bf4170, 0, 0, s_00bf4170, 0xd1) : 0;
    IP_00bf4170* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_00bf4170* np = (IP_00bf4170*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_00bf4170*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}



// @ 0x00c795f0
struct IP_00c795f0 {
  RefObj* p;
  IP_00c795f0(const IP_00c795f0& o) throw() : p(o.p) { if (p) p->v47(); }
  ~IP_00c795f0() throw() { if (p) p->v48(); }
};
void __cdecl um(void*, IP_00c795f0*, IP_00c795f0*, IP_00c795f0*, IP_00c795f0*) throw();
void __cdecl cb(IP_00c795f0*, IP_00c795f0*, IP_00c795f0*) throw();
void __cdecl fl(IP_00c795f0*, IP_00c795f0*, IP_00c795f0*) throw();
void __cdecl ufn(IP_00c795f0*, unsigned, const IP_00c795f0*, IP_00c795f0*) throw();
extern const char s_00c795f0[]; extern const char n_00c795f0[];
struct V_00c795f0 {
  IP_00c795f0 *b, *e, *c;
  void f(IP_00c795f0* pos, unsigned n, const IP_00c795f0& v);
};
void V_00c795f0::f(IP_00c795f0* pos, unsigned n, const IP_00c795f0& v) {
  IP_00c795f0* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_00c795f0 temp = v;
      IP_00c795f0* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_00c795f0*)EASTL_allocator_allocate(cap * 4, n_00c795f0, 0, 0, s_00c795f0, 0xd1) : 0;
    IP_00c795f0* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_00c795f0* np = (IP_00c795f0*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_00c795f0*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}



// @ 0x00dc8d10
struct IP_00dc8d10 {
  RefObj* p;
  IP_00dc8d10(const IP_00dc8d10& o) throw() : p(o.p) { if (p) p->v24(); }
  ~IP_00dc8d10() throw() { if (p) p->v25(); }
};
void __cdecl um(void*, IP_00dc8d10*, IP_00dc8d10*, IP_00dc8d10*, IP_00dc8d10*) throw();
void __cdecl cb(IP_00dc8d10*, IP_00dc8d10*, IP_00dc8d10*) throw();
void __cdecl fl(IP_00dc8d10*, IP_00dc8d10*, IP_00dc8d10*) throw();
void __cdecl ufn(IP_00dc8d10*, unsigned, const IP_00dc8d10*, IP_00dc8d10*) throw();
extern const char s_00dc8d10[]; extern const char n_00dc8d10[];
struct V_00dc8d10 {
  IP_00dc8d10 *b, *e, *c;
  void f(IP_00dc8d10* pos, unsigned n, const IP_00dc8d10& v);
};
void V_00dc8d10::f(IP_00dc8d10* pos, unsigned n, const IP_00dc8d10& v) {
  IP_00dc8d10* pNew;
  if (n <= (unsigned)(c - e)) {
    if (n > 0) {
      IP_00dc8d10 temp = v;
      IP_00dc8d10* oe = e;
      unsigned after = e - pos;
      if (n < after) {
        um(&pNew, e - n, oe, oe, pos);
        e += n;
        cb(pos, oe - n, oe);
        fl(pos, pos + n, &temp);
      } else {
        ufn(oe, n - after, &temp, pos);
        e += n - after;
        um(&pos, pos, oe, e, pos);
        e += after;
        fl(pos, oe, &temp);
      }
    }
  } else {
    unsigned sz = e - b;
    unsigned grow = sz > 0 ? 2 * sz : 1;
    unsigned cap = grow > sz + n ? grow : sz + n;
    pNew = cap ? (IP_00dc8d10*)EASTL_allocator_allocate(cap * 4, n_00dc8d10, 0, 0, s_00dc8d10, 0xd1) : 0;
    IP_00dc8d10* p = pos;
    int d1 = (char*)p - (char*)b;
    IP_00dc8d10* np = (IP_00dc8d10*)memcpy(pNew, b, d1);
    np += d1 >> 2;
    ufn(np, n, &v, pos);
    np += n;
    int d2 = (char*)e - (char*)p;
    np = (IP_00dc8d10*)memcpy(np, p, d2);
    np += d2 >> 2;
    if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
    b = pNew; e = np; c = pNew + cap;
  }
}


