// Generated by tools/matching/synth.py (template eastl_vec72_assign_trivial). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);

// @ 0x00680e70
struct T_00680e70 { char d[72]; ~T_00680e70() {} };
struct R_00680e70 { T_00680e70* p; };
struct V_00680e70 { T_00680e70* b; T_00680e70* e; T_00680e70* c;
 T_00680e70* Alloc(unsigned n, T_00680e70* f, T_00680e70* l);
 void Destroy(T_00680e70* f, T_00680e70* l);
 V_00680e70& FUN_00680e70(const V_00680e70& x); };
T_00680e70* Cp_00680e70(T_00680e70* f, T_00680e70* l, T_00680e70* d);
R_00680e70* Uc_00680e70(R_00680e70* o, T_00680e70* f, T_00680e70* l, T_00680e70* d, T_00680e70* e);
V_00680e70& V_00680e70::FUN_00680e70(const V_00680e70& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00680e70* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00680e70(x.b, x.b + (e - b), b);
      R_00680e70 r; Uc_00680e70(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00680e70* d = Cp_00680e70(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x006f9730
struct T_006f9730 { char d[72]; ~T_006f9730() {} };
struct R_006f9730 { T_006f9730* p; };
struct V_006f9730 { T_006f9730* b; T_006f9730* e; T_006f9730* c;
 T_006f9730* Alloc(unsigned n, T_006f9730* f, T_006f9730* l);
 void Destroy(T_006f9730* f, T_006f9730* l);
 V_006f9730& FUN_006f9730(const V_006f9730& x); };
T_006f9730* Cp_006f9730(T_006f9730* f, T_006f9730* l, T_006f9730* d);
R_006f9730* Uc_006f9730(R_006f9730* o, T_006f9730* f, T_006f9730* l, T_006f9730* d, T_006f9730* e);
V_006f9730& V_006f9730::FUN_006f9730(const V_006f9730& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_006f9730* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_006f9730(x.b, x.b + (e - b), b);
      R_006f9730 r; Uc_006f9730(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_006f9730* d = Cp_006f9730(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x00782270
struct T_00782270 { char d[72]; ~T_00782270() {} };
struct R_00782270 { T_00782270* p; };
struct V_00782270 { T_00782270* b; T_00782270* e; T_00782270* c;
 T_00782270* Alloc(unsigned n, T_00782270* f, T_00782270* l);
 void Destroy(T_00782270* f, T_00782270* l);
 V_00782270& FUN_00782270(const V_00782270& x); };
T_00782270* Cp_00782270(T_00782270* f, T_00782270* l, T_00782270* d);
R_00782270* Uc_00782270(R_00782270* o, T_00782270* f, T_00782270* l, T_00782270* d, T_00782270* e);
V_00782270& V_00782270::FUN_00782270(const V_00782270& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00782270* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00782270(x.b, x.b + (e - b), b);
      R_00782270 r; Uc_00782270(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00782270* d = Cp_00782270(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x007a0460
struct T_007a0460 { char d[72]; ~T_007a0460() {} };
struct R_007a0460 { T_007a0460* p; };
struct V_007a0460 { T_007a0460* b; T_007a0460* e; T_007a0460* c;
 T_007a0460* Alloc(unsigned n, T_007a0460* f, T_007a0460* l);
 void Destroy(T_007a0460* f, T_007a0460* l);
 V_007a0460& FUN_007a0460(const V_007a0460& x); };
T_007a0460* Cp_007a0460(T_007a0460* f, T_007a0460* l, T_007a0460* d);
R_007a0460* Uc_007a0460(R_007a0460* o, T_007a0460* f, T_007a0460* l, T_007a0460* d, T_007a0460* e);
V_007a0460& V_007a0460::FUN_007a0460(const V_007a0460& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_007a0460* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_007a0460(x.b, x.b + (e - b), b);
      R_007a0460 r; Uc_007a0460(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_007a0460* d = Cp_007a0460(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x00a0dd90
struct T_00a0dd90 { char d[72]; ~T_00a0dd90() {} };
struct R_00a0dd90 { T_00a0dd90* p; };
struct V_00a0dd90 { T_00a0dd90* b; T_00a0dd90* e; T_00a0dd90* c;
 T_00a0dd90* Alloc(unsigned n, T_00a0dd90* f, T_00a0dd90* l);
 void Destroy(T_00a0dd90* f, T_00a0dd90* l);
 V_00a0dd90& FUN_00a0dd90(const V_00a0dd90& x); };
T_00a0dd90* Cp_00a0dd90(T_00a0dd90* f, T_00a0dd90* l, T_00a0dd90* d);
R_00a0dd90* Uc_00a0dd90(R_00a0dd90* o, T_00a0dd90* f, T_00a0dd90* l, T_00a0dd90* d, T_00a0dd90* e);
V_00a0dd90& V_00a0dd90::FUN_00a0dd90(const V_00a0dd90& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00a0dd90* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00a0dd90(x.b, x.b + (e - b), b);
      R_00a0dd90 r; Uc_00a0dd90(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00a0dd90* d = Cp_00a0dd90(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x00a3ffa0
struct T_00a3ffa0 { char d[72]; ~T_00a3ffa0() {} };
struct R_00a3ffa0 { T_00a3ffa0* p; };
struct V_00a3ffa0 { T_00a3ffa0* b; T_00a3ffa0* e; T_00a3ffa0* c;
 T_00a3ffa0* Alloc(unsigned n, T_00a3ffa0* f, T_00a3ffa0* l);
 void Destroy(T_00a3ffa0* f, T_00a3ffa0* l);
 V_00a3ffa0& FUN_00a3ffa0(const V_00a3ffa0& x); };
T_00a3ffa0* Cp_00a3ffa0(T_00a3ffa0* f, T_00a3ffa0* l, T_00a3ffa0* d);
R_00a3ffa0* Uc_00a3ffa0(R_00a3ffa0* o, T_00a3ffa0* f, T_00a3ffa0* l, T_00a3ffa0* d, T_00a3ffa0* e);
V_00a3ffa0& V_00a3ffa0::FUN_00a3ffa0(const V_00a3ffa0& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00a3ffa0* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00a3ffa0(x.b, x.b + (e - b), b);
      R_00a3ffa0 r; Uc_00a3ffa0(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00a3ffa0* d = Cp_00a3ffa0(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x00acbd90
struct T_00acbd90 { char d[72]; ~T_00acbd90() {} };
struct R_00acbd90 { T_00acbd90* p; };
struct V_00acbd90 { T_00acbd90* b; T_00acbd90* e; T_00acbd90* c;
 T_00acbd90* Alloc(unsigned n, T_00acbd90* f, T_00acbd90* l);
 void Destroy(T_00acbd90* f, T_00acbd90* l);
 V_00acbd90& FUN_00acbd90(const V_00acbd90& x); };
T_00acbd90* Cp_00acbd90(T_00acbd90* f, T_00acbd90* l, T_00acbd90* d);
R_00acbd90* Uc_00acbd90(R_00acbd90* o, T_00acbd90* f, T_00acbd90* l, T_00acbd90* d, T_00acbd90* e);
V_00acbd90& V_00acbd90::FUN_00acbd90(const V_00acbd90& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00acbd90* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00acbd90(x.b, x.b + (e - b), b);
      R_00acbd90 r; Uc_00acbd90(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00acbd90* d = Cp_00acbd90(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}

// @ 0x00d5bdb0
struct T_00d5bdb0 { char d[72]; ~T_00d5bdb0() {} };
struct R_00d5bdb0 { T_00d5bdb0* p; };
struct V_00d5bdb0 { T_00d5bdb0* b; T_00d5bdb0* e; T_00d5bdb0* c;
 T_00d5bdb0* Alloc(unsigned n, T_00d5bdb0* f, T_00d5bdb0* l);
 void Destroy(T_00d5bdb0* f, T_00d5bdb0* l);
 V_00d5bdb0& FUN_00d5bdb0(const V_00d5bdb0& x); };
T_00d5bdb0* Cp_00d5bdb0(T_00d5bdb0* f, T_00d5bdb0* l, T_00d5bdb0* d);
R_00d5bdb0* Uc_00d5bdb0(R_00d5bdb0* o, T_00d5bdb0* f, T_00d5bdb0* l, T_00d5bdb0* d, T_00d5bdb0* e);
V_00d5bdb0& V_00d5bdb0::FUN_00d5bdb0(const V_00d5bdb0& x) {
  if (&x != this) {
    unsigned n = x.e - x.b;
    if (n > (unsigned)(c - b)) {
      T_00d5bdb0* p = Alloc(n, x.b, x.e);
      Destroy(b, e);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      c = p + n; b = p; e = p + n;
    } else if (n > (unsigned)(e - b)) {
      Cp_00d5bdb0(x.b, x.b + (e - b), b);
      R_00d5bdb0 r; Uc_00d5bdb0(&r, x.b + (e - b), x.e, e, x.e);
      e = b + n;
    } else {
      T_00d5bdb0* d = Cp_00d5bdb0(x.b, x.e, b);
      Destroy(d, e);
      e = b + n;
    }
  }
  return *this;
}
