// Generated by tools/matching/synth.py (template eastl_new_inline_mi_ctor_stdcall). Do not edit by hand.
typedef unsigned int size_t;
void* operator new(size_t size, const char* name, int flags, unsigned debugFlags, const char* file, int line);

// @ 0x01053740
struct T_01053740_A { virtual void ga(); };
struct T_01053740_B { virtual void fb(); int x; T_01053740_B() : x(0) {} };
struct T_01053740 : T_01053740_A, T_01053740_B { T_01053740() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01053740(int, int) { return new("T_01053740", 0, 0u, (const char*)0, 0) T_01053740; }

// @ 0x01054940
struct T_01054940_A { virtual void ga(); };
struct T_01054940_B { virtual void fb(); int x; T_01054940_B() : x(0) {} };
struct T_01054940 : T_01054940_A, T_01054940_B { T_01054940() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054940(int, int) { return new("T_01054940", 0, 0u, (const char*)0, 0) T_01054940; }

// @ 0x01054980
struct T_01054980_A { virtual void ga(); };
struct T_01054980_B { virtual void fb(); int x; T_01054980_B() : x(0) {} };
struct T_01054980 : T_01054980_A, T_01054980_B { T_01054980() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054980(int, int) { return new("T_01054980", 0, 0u, (const char*)0, 0) T_01054980; }

// @ 0x010549c0
struct T_010549c0_A { virtual void ga(); };
struct T_010549c0_B { virtual void fb(); int x; T_010549c0_B() : x(0) {} };
struct T_010549c0 : T_010549c0_A, T_010549c0_B { T_010549c0() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_010549c0(int, int) { return new("T_010549c0", 0, 0u, (const char*)0, 0) T_010549c0; }

// @ 0x01054a00
struct T_01054a00_A { virtual void ga(); };
struct T_01054a00_B { virtual void fb(); int x; T_01054a00_B() : x(0) {} };
struct T_01054a00 : T_01054a00_A, T_01054a00_B { T_01054a00() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054a00(int, int) { return new("T_01054a00", 0, 0u, (const char*)0, 0) T_01054a00; }

// @ 0x01054a40
struct T_01054a40_A { virtual void ga(); };
struct T_01054a40_B { virtual void fb(); int x; T_01054a40_B() : x(0) {} };
struct T_01054a40 : T_01054a40_A, T_01054a40_B { T_01054a40() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054a40(int, int) { return new("T_01054a40", 0, 0u, (const char*)0, 0) T_01054a40; }

// @ 0x01054a80
struct T_01054a80_A { virtual void ga(); };
struct T_01054a80_B { virtual void fb(); int x; T_01054a80_B() : x(0) {} };
struct T_01054a80 : T_01054a80_A, T_01054a80_B { T_01054a80() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054a80(int, int) { return new("T_01054a80", 0, 0u, (const char*)0, 0) T_01054a80; }

// @ 0x01054ac0
struct T_01054ac0_A { virtual void ga(); };
struct T_01054ac0_B { virtual void fb(); int x; T_01054ac0_B() : x(0) {} };
struct T_01054ac0 : T_01054ac0_A, T_01054ac0_B { T_01054ac0() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054ac0(int, int) { return new("T_01054ac0", 0, 0u, (const char*)0, 0) T_01054ac0; }

// @ 0x01054b00
struct T_01054b00_A { virtual void ga(); };
struct T_01054b00_B { virtual void fb(); int x; T_01054b00_B() : x(0) {} };
struct T_01054b00 : T_01054b00_A, T_01054b00_B { T_01054b00() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054b00(int, int) { return new("T_01054b00", 0, 0u, (const char*)0, 0) T_01054b00; }

// @ 0x01054b40
struct T_01054b40_A { virtual void ga(); };
struct T_01054b40_B { virtual void fb(); int x; T_01054b40_B() : x(0) {} };
struct T_01054b40 : T_01054b40_A, T_01054b40_B { T_01054b40() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054b40(int, int) { return new("T_01054b40", 0, 0u, (const char*)0, 0) T_01054b40; }

// @ 0x01054b80
struct T_01054b80_A { virtual void ga(); };
struct T_01054b80_B { virtual void fb(); int x; T_01054b80_B() : x(0) {} };
struct T_01054b80 : T_01054b80_A, T_01054b80_B { T_01054b80() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054b80(int, int) { return new("T_01054b80", 0, 0u, (const char*)0, 0) T_01054b80; }

// @ 0x01054bc0
struct T_01054bc0_A { virtual void ga(); };
struct T_01054bc0_B { virtual void fb(); int x; T_01054bc0_B() : x(0) {} };
struct T_01054bc0 : T_01054bc0_A, T_01054bc0_B { T_01054bc0() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054bc0(int, int) { return new("T_01054bc0", 0, 0u, (const char*)0, 0) T_01054bc0; }

// @ 0x01054c00
struct T_01054c00_A { virtual void ga(); };
struct T_01054c00_B { virtual void fb(); int x; T_01054c00_B() : x(0) {} };
struct T_01054c00 : T_01054c00_A, T_01054c00_B { T_01054c00() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054c00(int, int) { return new("T_01054c00", 0, 0u, (const char*)0, 0) T_01054c00; }

// @ 0x01054c40
struct T_01054c40_A { virtual void ga(); };
struct T_01054c40_B { virtual void fb(); int x; T_01054c40_B() : x(0) {} };
struct T_01054c40 : T_01054c40_A, T_01054c40_B { T_01054c40() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054c40(int, int) { return new("T_01054c40", 0, 0u, (const char*)0, 0) T_01054c40; }

// @ 0x01054c80
struct T_01054c80_A { virtual void ga(); };
struct T_01054c80_B { virtual void fb(); int x; T_01054c80_B() : x(0) {} };
struct T_01054c80 : T_01054c80_A, T_01054c80_B { T_01054c80() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054c80(int, int) { return new("T_01054c80", 0, 0u, (const char*)0, 0) T_01054c80; }

// @ 0x01054cc0
struct T_01054cc0_A { virtual void ga(); };
struct T_01054cc0_B { virtual void fb(); int x; T_01054cc0_B() : x(0) {} };
struct T_01054cc0 : T_01054cc0_A, T_01054cc0_B { T_01054cc0() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054cc0(int, int) { return new("T_01054cc0", 0, 0u, (const char*)0, 0) T_01054cc0; }

// @ 0x01054d00
struct T_01054d00_A { virtual void ga(); };
struct T_01054d00_B { virtual void fb(); int x; T_01054d00_B() : x(0) {} };
struct T_01054d00 : T_01054d00_A, T_01054d00_B { T_01054d00() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054d00(int, int) { return new("T_01054d00", 0, 0u, (const char*)0, 0) T_01054d00; }

// @ 0x01054d40
struct T_01054d40_A { virtual void ga(); };
struct T_01054d40_B { virtual void fb(); int x; T_01054d40_B() : x(0) {} };
struct T_01054d40 : T_01054d40_A, T_01054d40_B { T_01054d40() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054d40(int, int) { return new("T_01054d40", 0, 0u, (const char*)0, 0) T_01054d40; }

// @ 0x01054d80
struct T_01054d80_A { virtual void ga(); };
struct T_01054d80_B { virtual void fb(); int x; T_01054d80_B() : x(0) {} };
struct T_01054d80 : T_01054d80_A, T_01054d80_B { T_01054d80() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054d80(int, int) { return new("T_01054d80", 0, 0u, (const char*)0, 0) T_01054d80; }

// @ 0x01054dc0
struct T_01054dc0_A { virtual void ga(); };
struct T_01054dc0_B { virtual void fb(); int x; T_01054dc0_B() : x(0) {} };
struct T_01054dc0 : T_01054dc0_A, T_01054dc0_B { T_01054dc0() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054dc0(int, int) { return new("T_01054dc0", 0, 0u, (const char*)0, 0) T_01054dc0; }

// @ 0x01054e00
struct T_01054e00_A { virtual void ga(); };
struct T_01054e00_B { virtual void fb(); int x; T_01054e00_B() : x(0) {} };
struct T_01054e00 : T_01054e00_A, T_01054e00_B { T_01054e00() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054e00(int, int) { return new("T_01054e00", 0, 0u, (const char*)0, 0) T_01054e00; }

// @ 0x01054e40
struct T_01054e40_A { virtual void ga(); };
struct T_01054e40_B { virtual void fb(); int x; T_01054e40_B() : x(0) {} };
struct T_01054e40 : T_01054e40_A, T_01054e40_B { T_01054e40() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054e40(int, int) { return new("T_01054e40", 0, 0u, (const char*)0, 0) T_01054e40; }

// @ 0x01054e80
struct T_01054e80_A { virtual void ga(); };
struct T_01054e80_B { virtual void fb(); int x; T_01054e80_B() : x(0) {} };
struct T_01054e80 : T_01054e80_A, T_01054e80_B { T_01054e80() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01054e80(int, int) { return new("T_01054e80", 0, 0u, (const char*)0, 0) T_01054e80; }

// @ 0x01056120
struct T_01056120_A { virtual void ga(); };
struct T_01056120_B { virtual void fb(); int x; T_01056120_B() : x(0) {} };
struct T_01056120 : T_01056120_A, T_01056120_B { T_01056120() {} virtual void ga(); virtual void fb(); };
void* __stdcall FUN_01056120(int, int) { return new("T_01056120", 0, 0u, (const char*)0, 0) T_01056120; }
