// Generated by tools/matching/synth.py (template eastl_alloc_placement_ctor_set_field). Do not edit by hand.
typedef unsigned int size_t;
inline void* operator new(size_t, void* p) { return p; }
inline void operator delete(void*, void*) {}
void* eastl_alloc(size_t, const char*, int, unsigned, const char*, int);

// @ 0x0068cd80
extern const char s_013ebc58[];
extern const char f_013ebb38[];
struct T_0068cd80 { T_0068cd80(void*); char d[20]; int x; char e[0]; };
T_0068cd80* __stdcall FUN_0068cd80(void* a) { T_0068cd80* p = (T_0068cd80*)eastl_alloc(24, s_013ebc58, 0, 0u, f_013ebb38, 209); ::new(p) T_0068cd80(a); p->x = 0; return p; }

// @ 0x006a4850
extern const char s_013ebc58[];
extern const char f_013ebb38[];
struct T_006a4850 { T_006a4850(void*); char d[20]; int x; char e[0]; };
T_006a4850* __stdcall FUN_006a4850(void* a) { T_006a4850* p = (T_006a4850*)eastl_alloc(24, s_013ebc58, 0, 0u, f_013ebb38, 209); ::new(p) T_006a4850(a); p->x = 0; return p; }

// @ 0x006a48d0
extern const char s_013ebc58[];
extern const char f_013ebb38[];
struct T_006a48d0 { T_006a48d0(void*); char d[20]; int x; char e[0]; };
T_006a48d0* __stdcall FUN_006a48d0(void* a) { T_006a48d0* p = (T_006a48d0*)eastl_alloc(24, s_013ebc58, 0, 0u, f_013ebb38, 209); ::new(p) T_006a48d0(a); p->x = 0; return p; }

// @ 0x007128a0
extern const char s_013eb8a4[];
extern const char f_013ebb38[];
struct T_007128a0 { T_007128a0(void*); char d[76]; int x; char e[0]; };
T_007128a0* __stdcall FUN_007128a0(void* a) { T_007128a0* p = (T_007128a0*)eastl_alloc(80, s_013eb8a4, 0, 0u, f_013ebb38, 209); ::new(p) T_007128a0(a); p->x = 0; return p; }

// @ 0x0083c880
extern const char s_0141b18c[];
extern const char f_013ebb38[];
struct T_0083c880 { T_0083c880(void*); char d[20]; int x; char e[0]; };
T_0083c880* __stdcall FUN_0083c880(void* a) { T_0083c880* p = (T_0083c880*)eastl_alloc(24, s_0141b18c, 0, 0u, f_013ebb38, 209); ::new(p) T_0083c880(a); p->x = 0; return p; }

// @ 0x0083d0c0
extern const char s_0141b18c[];
extern const char f_013ebb38[];
struct T_0083d0c0 { T_0083d0c0(void*); char d[20]; int x; char e[0]; };
T_0083d0c0* __stdcall FUN_0083d0c0(void* a) { T_0083d0c0* p = (T_0083d0c0*)eastl_alloc(24, s_0141b18c, 0, 0u, f_013ebb38, 209); ::new(p) T_0083d0c0(a); p->x = 0; return p; }

// @ 0x0083fb40
extern const char s_0141b18c[];
extern const char f_013ebb38[];
struct T_0083fb40 { T_0083fb40(void*); char d[20]; int x; char e[0]; };
T_0083fb40* __stdcall FUN_0083fb40(void* a) { T_0083fb40* p = (T_0083fb40*)eastl_alloc(24, s_0141b18c, 0, 0u, f_013ebb38, 209); ::new(p) T_0083fb40(a); p->x = 0; return p; }

// @ 0x00842830
extern const char s_0141b18c[];
extern const char f_013ebb38[];
struct T_00842830 { T_00842830(void*); char d[32]; int x; char e[0]; };
T_00842830* __stdcall FUN_00842830(void* a) { T_00842830* p = (T_00842830*)eastl_alloc(36, s_0141b18c, 0, 0u, f_013ebb38, 209); ::new(p) T_00842830(a); p->x = 0; return p; }

// @ 0x00845660
extern const char s_0141b18c[];
extern const char f_013ebb38[];
struct T_00845660 { T_00845660(void*); char d[20]; int x; char e[0]; };
T_00845660* __stdcall FUN_00845660(void* a) { T_00845660* p = (T_00845660*)eastl_alloc(24, s_0141b18c, 0, 0u, f_013ebb38, 209); ::new(p) T_00845660(a); p->x = 0; return p; }

// @ 0x00a3b320
extern const char s_013f2150[];
extern const char f_013ebb38[];
struct T_00a3b320 { T_00a3b320(void*); char d[20]; int x; char e[0]; };
T_00a3b320* __stdcall FUN_00a3b320(void* a) { T_00a3b320* p = (T_00a3b320*)eastl_alloc(24, s_013f2150, 0, 0u, f_013ebb38, 209); ::new(p) T_00a3b320(a); p->x = 0; return p; }
