// Generated by tools/matching/synth.py (template eastl_rbtree_insert_hint_unique_u32). Do not edit by hand.

namespace eastl {
struct true_type {};
struct rbtree_node_base { rbtree_node_base* mpNodeRight; rbtree_node_base* mpNodeLeft; rbtree_node_base* mpNodeParent; char mColor; };
rbtree_node_base* RBTreeIncrement(const rbtree_node_base* pNode);
struct rbtree_node_u32 : rbtree_node_base { unsigned int mValue; };
struct rbtree_iterator_u32 { rbtree_node_u32* mpNode;
    rbtree_iterator_u32(rbtree_node_u32* p) : mpNode(p) {}
    rbtree_iterator_u32(const rbtree_iterator_u32& x) : mpNode(x.mpNode) {}
    rbtree_iterator_u32& operator++() { mpNode = (rbtree_node_u32*)RBTreeIncrement(mpNode); return *this; } };
struct pair_iterator_bool { rbtree_iterator_u32 first; bool second; };
}
#define RBTREE_INSERT_HINT_UNIQUE(T) \
struct T { \
    typedef eastl::rbtree_node_u32 node_type; typedef eastl::rbtree_iterator_u32 iterator; \
    int mCompare; eastl::rbtree_node_base mAnchor; unsigned mnSize; \
    iterator DoInsertValueImpl(eastl::rbtree_node_base* pParent, const unsigned int& value, bool bForceToLeft); \
    eastl::pair_iterator_bool DoInsertValue(const unsigned int& value, eastl::true_type); \
    iterator DoInsertValue(iterator position, const unsigned int& value, eastl::true_type); \
}; \
T::iterator T::DoInsertValue(iterator position, const unsigned int& value, eastl::true_type) \
{ \
    if((position.mpNode != mAnchor.mpNodeRight) && (position.mpNode != &mAnchor)) { \
        iterator itNext(position); \
        ++itNext; \
        const bool bPositionLessThanValue = position.mpNode->mValue < value; \
        if(bPositionLessThanValue) { \
            const bool bValueLessThanNext = value < itNext.mpNode->mValue; \
            if(bValueLessThanNext) { \
                if(position.mpNode->mpNodeRight) \
                    return DoInsertValueImpl(itNext.mpNode, value, true); \
                return DoInsertValueImpl(position.mpNode, value, false); \
            } \
        } \
        { eastl::pair_iterator_bool r = DoInsertValue(value, eastl::true_type()); return r.first; } \
    } \
    if(mnSize && (((node_type*)mAnchor.mpNodeRight)->mValue < value)) \
        return DoInsertValueImpl(mAnchor.mpNodeRight, value, false); \
    { eastl::pair_iterator_bool r = DoInsertValue(value, eastl::true_type()); return r.first; } \
}

// @ 0x0059c520
RBTREE_INSERT_HINT_UNIQUE(Tree_0059c520)

// @ 0x005a9820
RBTREE_INSERT_HINT_UNIQUE(Tree_005a9820)

// @ 0x005b8340
RBTREE_INSERT_HINT_UNIQUE(Tree_005b8340)

// @ 0x005bdd90
RBTREE_INSERT_HINT_UNIQUE(Tree_005bdd90)

// @ 0x005d9490
RBTREE_INSERT_HINT_UNIQUE(Tree_005d9490)

// @ 0x005dab20
RBTREE_INSERT_HINT_UNIQUE(Tree_005dab20)

// @ 0x005dabf0
RBTREE_INSERT_HINT_UNIQUE(Tree_005dabf0)

// @ 0x005dacc0
RBTREE_INSERT_HINT_UNIQUE(Tree_005dacc0)

// @ 0x005dad90
RBTREE_INSERT_HINT_UNIQUE(Tree_005dad90)

// @ 0x005f0640
RBTREE_INSERT_HINT_UNIQUE(Tree_005f0640)

// @ 0x005f0710
RBTREE_INSERT_HINT_UNIQUE(Tree_005f0710)

// @ 0x00605d90
RBTREE_INSERT_HINT_UNIQUE(Tree_00605d90)

// @ 0x00630c40
RBTREE_INSERT_HINT_UNIQUE(Tree_00630c40)

// @ 0x006432d0
RBTREE_INSERT_HINT_UNIQUE(Tree_006432d0)

// @ 0x00660ca0
RBTREE_INSERT_HINT_UNIQUE(Tree_00660ca0)

// @ 0x0082cac0
RBTREE_INSERT_HINT_UNIQUE(Tree_0082cac0)

// @ 0x0082cb90
RBTREE_INSERT_HINT_UNIQUE(Tree_0082cb90)

// @ 0x0091c3c0
RBTREE_INSERT_HINT_UNIQUE(Tree_0091c3c0)

// @ 0x009a3cd0
RBTREE_INSERT_HINT_UNIQUE(Tree_009a3cd0)

// @ 0x009e0c00
RBTREE_INSERT_HINT_UNIQUE(Tree_009e0c00)

// @ 0x009fd230
RBTREE_INSERT_HINT_UNIQUE(Tree_009fd230)

// @ 0x009fd300
RBTREE_INSERT_HINT_UNIQUE(Tree_009fd300)

// @ 0x009fe490
RBTREE_INSERT_HINT_UNIQUE(Tree_009fe490)

// @ 0x00a0ad10
RBTREE_INSERT_HINT_UNIQUE(Tree_00a0ad10)

// @ 0x00a0e180
RBTREE_INSERT_HINT_UNIQUE(Tree_00a0e180)

// @ 0x00a27cc0
RBTREE_INSERT_HINT_UNIQUE(Tree_00a27cc0)

// @ 0x00abff10
RBTREE_INSERT_HINT_UNIQUE(Tree_00abff10)

// @ 0x00b1ad00
RBTREE_INSERT_HINT_UNIQUE(Tree_00b1ad00)

// @ 0x00b1b8b0
RBTREE_INSERT_HINT_UNIQUE(Tree_00b1b8b0)

// @ 0x00b6ed20
RBTREE_INSERT_HINT_UNIQUE(Tree_00b6ed20)

// @ 0x00baa660
RBTREE_INSERT_HINT_UNIQUE(Tree_00baa660)

// @ 0x00bb6960
RBTREE_INSERT_HINT_UNIQUE(Tree_00bb6960)

// @ 0x00bf3620
RBTREE_INSERT_HINT_UNIQUE(Tree_00bf3620)

// @ 0x00c7aba0
RBTREE_INSERT_HINT_UNIQUE(Tree_00c7aba0)

// @ 0x00cc5c70
RBTREE_INSERT_HINT_UNIQUE(Tree_00cc5c70)

// @ 0x00d0d010
RBTREE_INSERT_HINT_UNIQUE(Tree_00d0d010)

// @ 0x00d54ed0
RBTREE_INSERT_HINT_UNIQUE(Tree_00d54ed0)

// @ 0x00d73280
RBTREE_INSERT_HINT_UNIQUE(Tree_00d73280)

// @ 0x00dd6f50
RBTREE_INSERT_HINT_UNIQUE(Tree_00dd6f50)

// @ 0x00e0f1f0
RBTREE_INSERT_HINT_UNIQUE(Tree_00e0f1f0)

// @ 0x00e2c770
RBTREE_INSERT_HINT_UNIQUE(Tree_00e2c770)

// @ 0x00e3db00
RBTREE_INSERT_HINT_UNIQUE(Tree_00e3db00)

// @ 0x00e3dbd0
RBTREE_INSERT_HINT_UNIQUE(Tree_00e3dbd0)

// @ 0x01011280
RBTREE_INSERT_HINT_UNIQUE(Tree_01011280)
