// Generated by tools/matching/synth.py (template eh_funclet_cdecl_str_arg_naked). Do not edit by hand.

// @ 0x0120cd20
extern "C" void X_00f47410();
extern "C" void X_ce20ca80();
extern "C" char g_0140370c[];
extern "C" char g_014fa510[];
__declspec(naked) void FUN_0120cd20() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_0140370c
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_014fa510
        jmp X_ce20ca80
    }
}

// @ 0x0120d290
extern "C" void X_00f47410();
extern "C" void X_ce20cfeb();
extern "C" char g_01408194[];
extern "C" char g_014faaf0[];
__declspec(naked) void FUN_0120d290() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_01408194
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_014faaf0
        jmp X_ce20cfeb
    }
}

// @ 0x012139c0
extern "C" void X_00f47410();
extern "C" void X_ce2136b4();
extern "C" char g_013eb8a4[];
extern "C" char g_015018c0[];
__declspec(naked) void FUN_012139c0() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_013eb8a4
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_015018c0
        jmp X_ce2136b4
    }
}

// @ 0x01213e00
extern "C" void X_00f47410();
extern "C" void X_ce213aef();
extern "C" char g_0140f628[];
extern "C" char g_01501d90[];
__declspec(naked) void FUN_01213e00() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_0140f628
        mov eax, dword ptr [ebp + 16]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_01501d90
        jmp X_ce213aef
    }
}

// @ 0x01215500
extern "C" void X_00f47410();
extern "C" void X_ce2151d8();
extern "C" char g_0141182c[];
extern "C" char g_015034ac[];
__declspec(naked) void FUN_01215500() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_0141182c
        mov eax, dword ptr [ebp + 8]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_015034ac
        jmp X_ce2151d8
    }
}

// @ 0x01215860
extern "C" void X_00f47410();
extern "C" void X_ce215535();
extern "C" char g_013ebc58[];
extern "C" char g_015037d8[];
__declspec(naked) void FUN_01215860() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_013ebc58
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_015037d8
        jmp X_ce215535
    }
}

// @ 0x012159f0
extern "C" void X_00f47410();
extern "C" void X_ce2156c3();
extern "C" char g_013ebc58[];
extern "C" char g_015039a0[];
__declspec(naked) void FUN_012159f0() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_013ebc58
        mov eax, dword ptr [ebp + 8]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_015039a0
        jmp X_ce2156c3
    }
}

// @ 0x01215d70
extern "C" void X_00f47410();
extern "C" void X_ce215a40();
extern "C" char g_013f1fdc[];
extern "C" char g_01503cb0[];
__declspec(naked) void FUN_01215d70() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_013f1fdc
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_01503cb0
        jmp X_ce215a40
    }
}

// @ 0x012177c0
extern "C" void X_00f47410();
extern "C" void X_ce217476();
extern "C" char g_0141b18c[];
extern "C" char g_01505874[];
__declspec(naked) void FUN_012177c0() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_0141b18c
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_01505874
        jmp X_ce217476
    }
}

// @ 0x01218520
extern "C" void X_00f47410();
extern "C" void X_ce2181c8();
extern "C" char g_014529f4[];
extern "C" char g_0150652c[];
__declspec(naked) void FUN_01218520() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_014529f4
        mov eax, dword ptr [ebp + 4]
        push eax
        call X_00f47410
        add esp, 18h
        ret
        mov eax, offset g_0150652c
        jmp X_ce2181c8
    }
}

// @ 0x012185b0
extern "C" void X_00926060();
extern "C" void X_ce218258();
extern "C" char g_0140a5a0[];
extern "C" char g_015065e4[];
__declspec(naked) void FUN_012185b0() {
    __asm {
        push 0
        push 0
        push 0
        push 0
        push offset g_0140a5a0
        mov eax, dword ptr [ebp + 8]
        push eax
        call X_00926060
        add esp, 18h
        ret
        mov eax, offset g_015065e4
        jmp X_ce218258
    }
}
