// Generated by tools/matching/synth.py (template eh_placement_fill_n_iter). Do not edit by hand.
inline void* operator new(unsigned, void* p) { return p; }
void operator delete(void*, void*);

// @ 0x00685bc0
struct C_00685bc0 { char d[40]; C_00685bc0(const C_00685bc0&); };
struct I_00685bc0 { C_00685bc0* p; I_00685bc0& operator++() { ++p; return *this; } C_00685bc0& operator*() const { return *p; } };
void FUN_00685bc0(I_00685bc0 first, unsigned n, const C_00685bc0& a) { I_00685bc0 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00685bc0(a); } }

// @ 0x006faa60
struct C_006faa60 { char d[28]; C_006faa60(const C_006faa60&); };
struct I_006faa60 { C_006faa60* p; I_006faa60& operator++() { ++p; return *this; } C_006faa60& operator*() const { return *p; } };
void FUN_006faa60(I_006faa60 first, unsigned n, const C_006faa60& a) { I_006faa60 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_006faa60(a); } }

// @ 0x00708480
struct C_00708480 { char d[324]; C_00708480(const C_00708480&); };
struct I_00708480 { C_00708480* p; I_00708480& operator++() { ++p; return *this; } C_00708480& operator*() const { return *p; } };
void FUN_00708480(I_00708480 first, unsigned n, const C_00708480& a) { I_00708480 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00708480(a); } }

// @ 0x00716440
struct C_00716440 { char d[208]; C_00716440(const C_00716440&); };
struct I_00716440 { C_00716440* p; I_00716440& operator++() { ++p; return *this; } C_00716440& operator*() const { return *p; } };
void FUN_00716440(I_00716440 first, unsigned n, const C_00716440& a) { I_00716440 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00716440(a); } }

// @ 0x00716540
struct C_00716540 { char d[80]; C_00716540(const C_00716540&); };
struct I_00716540 { C_00716540* p; I_00716540& operator++() { ++p; return *this; } C_00716540& operator*() const { return *p; } };
void FUN_00716540(I_00716540 first, unsigned n, const C_00716540& a) { I_00716540 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00716540(a); } }

// @ 0x007184a0
struct C_007184a0 { char d[40]; C_007184a0(const C_007184a0&); };
struct I_007184a0 { C_007184a0* p; I_007184a0& operator++() { ++p; return *this; } C_007184a0& operator*() const { return *p; } };
void FUN_007184a0(I_007184a0 first, unsigned n, const C_007184a0& a) { I_007184a0 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_007184a0(a); } }

// @ 0x0071f280
struct C_0071f280 { char d[140]; C_0071f280(const C_0071f280&); };
struct I_0071f280 { C_0071f280* p; I_0071f280& operator++() { ++p; return *this; } C_0071f280& operator*() const { return *p; } };
void FUN_0071f280(I_0071f280 first, unsigned n, const C_0071f280& a) { I_0071f280 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_0071f280(a); } }

// @ 0x00721ed0
struct C_00721ed0 { char d[100]; C_00721ed0(const C_00721ed0&); };
struct I_00721ed0 { C_00721ed0* p; I_00721ed0& operator++() { ++p; return *this; } C_00721ed0& operator*() const { return *p; } };
void FUN_00721ed0(I_00721ed0 first, unsigned n, const C_00721ed0& a) { I_00721ed0 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00721ed0(a); } }

// @ 0x00758d10
struct C_00758d10 { char d[80]; C_00758d10(const C_00758d10&); };
struct I_00758d10 { C_00758d10* p; I_00758d10& operator++() { ++p; return *this; } C_00758d10& operator*() const { return *p; } };
void FUN_00758d10(I_00758d10 first, unsigned n, const C_00758d10& a) { I_00758d10 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_00758d10(a); } }

// @ 0x007d0ee0
struct C_007d0ee0 { char d[104]; C_007d0ee0(const C_007d0ee0&); };
struct I_007d0ee0 { C_007d0ee0* p; I_007d0ee0& operator++() { ++p; return *this; } C_007d0ee0& operator*() const { return *p; } };
void FUN_007d0ee0(I_007d0ee0 first, unsigned n, const C_007d0ee0& a) { I_007d0ee0 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_007d0ee0(a); } }

// @ 0x007d13d0
struct C_007d13d0 { char d[44]; C_007d13d0(const C_007d13d0&); };
struct I_007d13d0 { C_007d13d0* p; I_007d13d0& operator++() { ++p; return *this; } C_007d13d0& operator*() const { return *p; } };
void FUN_007d13d0(I_007d13d0 first, unsigned n, const C_007d13d0& a) { I_007d13d0 cur = first; for (; n > 0; --n, ++cur) { void* v = &*cur; new (v) C_007d13d0(a); } }
