// Generated by tools/matching/synth.py (template eh_unwind_placement_delete). Do not edit by hand.
typedef unsigned int size_t;
void* operator new(size_t, const char*, int, unsigned, const char*, int);
void operator delete(void*, const char*, int, unsigned, const char*, int);

// @ 0x0120bce0
extern const char s_013f1fdc[];
void E_0120bce0(void*);
struct T_0120bce0 { T_0120bce0(); int d; };
void* F_0120bce0() {
  unsigned buf[2]; E_0120bce0(buf);
  return new(s_013f1fdc, 0, 0u, (const char*)0, 0) T_0120bce0; }

// @ 0x0120be20
extern const char s_013f25f4[];
void E_0120be20(void*);
struct T_0120be20 { T_0120be20(); int d; };
void* F_0120be20() {
  unsigned buf[1]; E_0120be20(buf);
  return new(s_013f25f4, 0, 0u, (const char*)0, 0) T_0120be20; }

// @ 0x0120bf00
extern const char s_013f1fdc[];
void E_0120bf00(void*);
struct T_0120bf00 { T_0120bf00(); int d; };
void* F_0120bf00() {
  unsigned buf[1]; E_0120bf00(buf);
  return new(s_013f1fdc, 0, 0u, (const char*)0, 0) T_0120bf00; }

// @ 0x0120cae0
extern const char s_014033d4[];
void E_0120cae0(void*);
struct T_0120cae0 { T_0120cae0(); int d; };
void* F_0120cae0() {
  return new(s_014033d4, 0, 0u, (const char*)0, 0) T_0120cae0; }

// @ 0x0120cd70
extern const char s_0140379c[];
void E_0120cd70(void*);
struct T_0120cd70 { T_0120cd70(); int d; };
void* F_0120cd70() {
  return new(s_0140379c, 0, 0u, (const char*)0, 0) T_0120cd70; }

// @ 0x0120ce70
extern const char s_01403830[];
void E_0120ce70(void*);
struct T_0120ce70 { T_0120ce70(); int d; };
void* F_0120ce70() {
  return new(s_01403830, 0, 0u, (const char*)0, 0) T_0120ce70; }

// @ 0x0120d380
extern const char s_0140834c[];
void E_0120d380(void*);
struct T_0120d380 { T_0120d380(); int d; };
void* F_0120d380() {
  return new(s_0140834c, 0, 0u, (const char*)0, 0) T_0120d380; }

// @ 0x0120d6f0
extern const char s_01408b44[];
void E_0120d6f0(void*);
struct T_0120d6f0 { T_0120d6f0(); int d; };
void* F_0120d6f0() {
  return new(s_01408b44, 0, 0u, (const char*)0, 0) T_0120d6f0; }

// @ 0x0120d720
extern const char s_013ebc58[];
void E_0120d720(void*);
struct T_0120d720 { T_0120d720(); int d; };
void* F_0120d720() {
  unsigned buf[3]; E_0120d720(buf);
  return new(s_013ebc58, 0, 0u, (const char*)0, 0) T_0120d720; }

// @ 0x0120ddf0
extern const char s_013ebc58[];
void E_0120ddf0(void*);
struct T_0120ddf0 { T_0120ddf0(); int d; };
void* F_0120ddf0() {
  return new(s_013ebc58, 0, 0u, (const char*)0, 0) T_0120ddf0; }

// @ 0x0120e200
extern const char s_0140967c[];
void E_0120e200(void*);
struct T_0120e200 { T_0120e200(); int d; };
void* F_0120e200() {
  return new(s_0140967c, 0, 0u, (const char*)0, 0) T_0120e200; }

// @ 0x0120e2e0
extern const char s_0140967c[];
void E_0120e2e0(void*);
struct T_0120e2e0 { T_0120e2e0(); int d; };
void* F_0120e2e0() {
  return new(s_0140967c, 0, 0u, (const char*)0, 0) T_0120e2e0; }

// @ 0x0120e350
extern const char s_01409704[];
void E_0120e350(void*);
struct T_0120e350 { T_0120e350(); int d; };
void* F_0120e350() {
  return new(s_01409704, 0, 0u, (const char*)0, 0) T_0120e350; }

// @ 0x01211d90
extern const char s_013eb8a4[];
void E_01211d90(void*);
struct T_01211d90 { T_01211d90(); int d; };
void* F_01211d90() {
  unsigned buf[14]; E_01211d90(buf);
  return new(s_013eb8a4, 0, 0u, (const char*)0, 0) T_01211d90; }

// @ 0x01211dc0
extern const char s_013eb8a4[];
void E_01211dc0(void*);
struct T_01211dc0 { T_01211dc0(); int d; };
void* F_01211dc0() {
  unsigned buf[15]; E_01211dc0(buf);
  return new(s_013eb8a4, 0, 0u, (const char*)0, 0) T_01211dc0; }

// @ 0x01213040
extern const char s_013eb430[];
void E_01213040(void*);
struct T_01213040 { T_01213040(); int d; };
void* F_01213040() {
  unsigned buf[6]; E_01213040(buf);
  return new(s_013eb430, 0, 0u, (const char*)0, 0) T_01213040; }

// @ 0x01213d70
extern const char s_0140f628[];
void E_01213d70(void*);
struct T_01213d70 { T_01213d70(); int d; };
void* F_01213d70() {
  return new(s_0140f628, 0, 0u, (const char*)0, 0) T_01213d70; }

// @ 0x01216350
extern const char s_01412f10[];
void E_01216350(void*);
struct T_01216350 { T_01216350(); int d; };
void* F_01216350() {
  return new(s_01412f10, 0, 0u, (const char*)0, 0) T_01216350; }

// @ 0x01216cc0
extern const char s_013ebc58[];
void E_01216cc0(void*);
struct T_01216cc0 { T_01216cc0(); int d; };
void* F_01216cc0() {
  return new(s_013ebc58, 0, 0u, (const char*)0, 0) T_01216cc0; }

// @ 0x012171f0
extern const char s_013f1fdc[];
void E_012171f0(void*);
struct T_012171f0 { T_012171f0(); int d; };
void* F_012171f0() {
  return new(s_013f1fdc, 0, 0u, (const char*)0, 0) T_012171f0; }

// @ 0x01217600
extern const char s_0141b18c[];
void E_01217600(void*);
struct T_01217600 { T_01217600(); int d; };
void* F_01217600() {
  return new(s_0141b18c, 0, 0u, (const char*)0, 0) T_01217600; }

// @ 0x012184f0
extern const char s_0143f71c[];
void E_012184f0(void*);
struct T_012184f0 { T_012184f0(); int d; };
void* F_012184f0() {
  return new(s_0143f71c, 0, 0u, (const char*)0, 0) T_012184f0; }

// @ 0x0121a060
extern const char s_0140a5a0[];
void E_0121a060(void*);
struct T_0121a060 { T_0121a060(); int d; };
void* F_0121a060() {
  return new(s_0140a5a0, 0, 0u, (const char*)0, 0) T_0121a060; }

// @ 0x0121a0f0
extern const char s_0140a5a0[];
void E_0121a0f0(void*);
struct T_0121a0f0 { T_0121a0f0(); int d; };
void* F_0121a0f0() {
  return new(s_0140a5a0, 0, 0u, (const char*)0, 0) T_0121a0f0; }
