// Generated by tools/matching/synth.py (template eh_unwind_placement_delete_local_dtor). Do not edit by hand.
typedef unsigned int size_t;
void* operator new(size_t, const char*, int, unsigned, const char*, int);
void operator delete(void*, const char*, int, unsigned, const char*, int);

// @ 0x0120bcb0
extern const char s_013f2140[];
struct T_0120bcb0 { T_0120bcb0(); int d; };
struct P_0120bcb0 { T_0120bcb0* p; P_0120bcb0(T_0120bcb0* q) : p(q) {} ~P_0120bcb0(); };
void eh_use(const P_0120bcb0&);
void F_0120bcb0() { eh_use(P_0120bcb0(new(s_013f2140, 0, 0u, (const char*)0, 0) T_0120bcb0)); }

// @ 0x0120be90
extern const char s_013f2648[];
struct T_0120be90 { T_0120be90(); int d; };
struct P_0120be90 { T_0120be90* p; P_0120be90(T_0120be90* q) : p(q) {} ~P_0120be90(); };
void eh_use(const P_0120be90&);
void F_0120be90() { eh_use(P_0120be90(new(s_013f2648, 0, 0u, (const char*)0, 0) T_0120be90)); }

// @ 0x0120f3d0
extern const char s_013f1fdc[];
struct T_0120f3d0 { T_0120f3d0(); int d; };
struct P_0120f3d0 { T_0120f3d0* p; P_0120f3d0(T_0120f3d0* q) : p(q) {} ~P_0120f3d0(); };
void eh_use(const P_0120f3d0&);
void F_0120f3d0() { eh_use(P_0120f3d0(new(s_013f1fdc, 0, 0u, (const char*)0, 0) T_0120f3d0)); }

// @ 0x01211540
extern const char s_013eb8a4[];
struct T_01211540 { T_01211540(); int d; };
struct P_01211540 { T_01211540* p; P_01211540(T_01211540* q) : p(q) {} ~P_01211540(); };
void eh_use(const P_01211540&);
void F_01211540() { eh_use(P_01211540(new(s_013eb8a4, 0, 0u, (const char*)0, 0) T_01211540)); }

// @ 0x01211ba0
extern const char s_0140d6d0[];
struct T_01211ba0 { T_01211ba0(); int d; };
struct P_01211ba0 { T_01211ba0* p; P_01211ba0(T_01211ba0* q) : p(q) {} ~P_01211ba0(); };
void eh_use(const P_01211ba0&);
void F_01211ba0() { eh_use(P_01211ba0(new(s_0140d6d0, 0, 0u, (const char*)0, 0) T_01211ba0)); }

// @ 0x01212350
extern const char s_013eb8a4[];
struct T_01212350 { T_01212350(); int d; };
struct P_01212350 { T_01212350* p; P_01212350(T_01212350* q) : p(q) {} ~P_01212350(); };
void eh_use(const P_01212350&);
void F_01212350() { eh_use(P_01212350(new(s_013eb8a4, 0, 0u, (const char*)0, 0) T_01212350)); }

// @ 0x012129d0
extern const char s_0140dc54[];
struct T_012129d0 { T_012129d0(); int d; };
struct P_012129d0 { T_012129d0* p; P_012129d0(T_012129d0* q) : p(q) {} ~P_012129d0(); };
void eh_use(const P_012129d0&);
void F_012129d0() { eh_use(P_012129d0(new(s_0140dc54, 0, 0u, (const char*)0, 0) T_012129d0)); }

// @ 0x01213ae0
extern const char s_013eb8a4[];
struct T_01213ae0 { T_01213ae0(); int d; };
struct P_01213ae0 { T_01213ae0* p; P_01213ae0(T_01213ae0* q) : p(q) {} ~P_01213ae0(); };
void eh_use(const P_01213ae0&);
void F_01213ae0() { eh_use(P_01213ae0(new(s_013eb8a4, 0, 0u, (const char*)0, 0) T_01213ae0)); }

// @ 0x01216ee0
extern const char s_013ebc58[];
struct T_01216ee0 { T_01216ee0(); int d; };
struct P_01216ee0 { T_01216ee0* p; P_01216ee0(T_01216ee0* q) : p(q) {} ~P_01216ee0(); };
void eh_use(const P_01216ee0&);
void F_01216ee0() { eh_use(P_01216ee0(new(s_013ebc58, 0, 0u, (const char*)0, 0) T_01216ee0)); }

// @ 0x01218a20
extern const char s_0140a5a0[];
struct T_01218a20 { T_01218a20(); int d; };
struct P_01218a20 { T_01218a20* p; P_01218a20(T_01218a20* q) : p(q) {} ~P_01218a20(); };
void eh_use(const P_01218a20&);
void F_01218a20() { eh_use(P_01218a20(new(s_0140a5a0, 0, 0u, (const char*)0, 0) T_01218a20)); }

// @ 0x01219d10
extern const char s_0140a5a0[];
struct T_01219d10 { T_01219d10(); int d; };
struct P_01219d10 { T_01219d10* p; P_01219d10(T_01219d10* q) : p(q) {} ~P_01219d10(); };
void eh_use(const P_01219d10&);
void F_01219d10() { eh_use(P_01219d10(new(s_0140a5a0, 0, 0u, (const char*)0, 0) T_01219d10)); }
