// Generated by tools/matching/synth.py (template fixed_vec_ctor_temp_alloc_od). Do not edit by hand.

// @ 0x00472560
struct Al_00472560 { int nm; void* pool; Al_00472560(void* p) { pool = p; } Al_00472560(const Al_00472560& o) { pool = o.pool; } };
struct VB_00472560 { int* b; int* e; int* c; Al_00472560 al; int pad; VB_00472560(const Al_00472560& a) : b(0), e(0), c(0), al(a) {} };
struct FV_00472560 : VB_00472560 { char buf[24]; FV_00472560(); };
FV_00472560::FV_00472560() : VB_00472560(Al_00472560(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 24); }


// @ 0x004725d0
struct Al_004725d0 { int nm; void* pool; Al_004725d0(void* p) { pool = p; } Al_004725d0(const Al_004725d0& o) { pool = o.pool; } };
struct VB_004725d0 { int* b; int* e; int* c; Al_004725d0 al; int pad; VB_004725d0(const Al_004725d0& a) : b(0), e(0), c(0), al(a) {} };
struct FV_004725d0 : VB_004725d0 { char buf[48]; FV_004725d0(); };
FV_004725d0::FV_004725d0() : VB_004725d0(Al_004725d0(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 48); }


// @ 0x004cd140
struct Al_004cd140 { int nm; void* pool; Al_004cd140(void* p) { pool = p; } Al_004cd140(const Al_004cd140& o) { pool = o.pool; } };
struct VB_004cd140 { int* b; int* e; int* c; Al_004cd140 al; int pad; VB_004cd140(const Al_004cd140& a) : b(0), e(0), c(0), al(a) {} };
struct FV_004cd140 : VB_004cd140 { char buf[1024]; FV_004cd140(); };
FV_004cd140::FV_004cd140() : VB_004cd140(Al_004cd140(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 1024); }


// @ 0x004fc4a0
struct Al_004fc4a0 { int nm; void* pool; Al_004fc4a0(void* p) { pool = p; } Al_004fc4a0(const Al_004fc4a0& o) { pool = o.pool; } };
struct VB_004fc4a0 { int* b; int* e; int* c; Al_004fc4a0 al; int pad; VB_004fc4a0(const Al_004fc4a0& a) : b(0), e(0), c(0), al(a) {} };
struct FV_004fc4a0 : VB_004fc4a0 { char buf[128]; FV_004fc4a0(); };
FV_004fc4a0::FV_004fc4a0() : VB_004fc4a0(Al_004fc4a0(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 128); }


// @ 0x0051d0d0
struct Al_0051d0d0 { int nm; void* pool; Al_0051d0d0(void* p) { pool = p; } Al_0051d0d0(const Al_0051d0d0& o) { pool = o.pool; } };
struct VB_0051d0d0 { int* b; int* e; int* c; Al_0051d0d0 al; int pad; VB_0051d0d0(const Al_0051d0d0& a) : b(0), e(0), c(0), al(a) {} };
struct FV_0051d0d0 : VB_0051d0d0 { char buf[768]; FV_0051d0d0(); };
FV_0051d0d0::FV_0051d0d0() : VB_0051d0d0(Al_0051d0d0(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 768); }


// @ 0x00533360
struct Al_00533360 { int nm; void* pool; Al_00533360(void* p) { pool = p; } Al_00533360(const Al_00533360& o) { pool = o.pool; } };
struct VB_00533360 { int* b; int* e; int* c; Al_00533360 al; int pad; VB_00533360(const Al_00533360& a) : b(0), e(0), c(0), al(a) {} };
struct FV_00533360 : VB_00533360 { char buf[32]; FV_00533360(); };
FV_00533360::FV_00533360() : VB_00533360(Al_00533360(buf)) { e = (int*)buf; b = e; c = (int*)((char*)b + 32); }

