// Generated by tools/matching/synth.py (template float_k_div_dbl_mul_init_x87_od). Do not edit by hand.

// @ 0x01254570
extern float g_015dc0e0;
extern const double g_013f1298;
extern float g_014763b0;
float g_015dbfbc = g_014763b0 / (float)(g_015dc0e0 * g_013f1298);


// @ 0x0125db60
extern float g_015de4bc;
extern const double g_013f1298;
extern float g_014763b0;
float g_015de268 = g_014763b0 / (float)(g_015de4bc * g_013f1298);


// @ 0x01267370
extern float g_015e1224;
extern const double g_013f1298;
extern float g_014763b0;
float g_015e1040 = g_014763b0 / (float)(g_015e1224 * g_013f1298);


// @ 0x012687a0
extern float g_015e16b4;
extern const double g_013f1298;
extern float g_014763b0;
float g_015e14d0 = g_014763b0 / (float)(g_015e16b4 * g_013f1298);


// @ 0x012699d0
extern float g_015e1b3c;
extern const double g_013f1298;
extern float g_014763b0;
float g_015e1958 = g_014763b0 / (float)(g_015e1b3c * g_013f1298);


// @ 0x0126ac10
extern float g_015e1f9c;
extern const double g_013f1298;
extern float g_014763b0;
float g_015e1de0 = g_014763b0 / (float)(g_015e1f9c * g_013f1298);


// @ 0x0126bd80
extern float g_015e2404;
extern const double g_013f1298;
extern float g_014763b0;
float g_015e2248 = g_014763b0 / (float)(g_015e2404 * g_013f1298);

