// Generated by tools/matching/synth.py (template fnptr_field_call_store_float_global). Do not edit by hand.

// @ 0x00aff980
struct S_00aff980 { unsigned int p[8]; float* (__cdecl *fn)(S_00aff980*); };
extern float g_0167badc;
void FUN_00aff980(S_00aff980* s) { *s->fn(s) = g_0167badc; }


// @ 0x00aff9a0
struct S_00aff9a0 { unsigned int p[8]; float* (__cdecl *fn)(S_00aff9a0*); };
extern float g_0167bae0;
void FUN_00aff9a0(S_00aff9a0* s) { *s->fn(s) = g_0167bae0; }


// @ 0x00aff9c0
struct S_00aff9c0 { unsigned int p[8]; float* (__cdecl *fn)(S_00aff9c0*); };
extern float g_0167bae4;
void FUN_00aff9c0(S_00aff9c0* s) { *s->fn(s) = g_0167bae4; }


// @ 0x00affa00
struct S_00affa00 { unsigned int p[8]; float* (__cdecl *fn)(S_00affa00*); };
extern float g_0167baec;
void FUN_00affa00(S_00affa00* s) { *s->fn(s) = g_0167baec; }


// @ 0x00affaa0
struct S_00affaa0 { unsigned int p[8]; float* (__cdecl *fn)(S_00affaa0*); };
extern float g_0167bb00;
void FUN_00affaa0(S_00affaa0* s) { *s->fn(s) = g_0167bb00; }


// @ 0x00affac0
struct S_00affac0 { unsigned int p[8]; float* (__cdecl *fn)(S_00affac0*); };
extern float g_0167bb04;
void FUN_00affac0(S_00affac0* s) { *s->fn(s) = g_0167bb04; }


// @ 0x00b8f8d0
struct S_00b8f8d0 { unsigned int p[8]; float* (__cdecl *fn)(S_00b8f8d0*); };
extern float g_016882f0;
void FUN_00b8f8d0(S_00b8f8d0* s) { *s->fn(s) = g_016882f0; }


// @ 0x00b8f8f0
struct S_00b8f8f0 { unsigned int p[8]; float* (__cdecl *fn)(S_00b8f8f0*); };
extern float g_016882f4;
void FUN_00b8f8f0(S_00b8f8f0* s) { *s->fn(s) = g_016882f4; }


// @ 0x00b8f910
struct S_00b8f910 { unsigned int p[8]; float* (__cdecl *fn)(S_00b8f910*); };
extern float g_016882f8;
void FUN_00b8f910(S_00b8f910* s) { *s->fn(s) = g_016882f8; }


// @ 0x00bfe3f0
struct S_00bfe3f0 { unsigned int p[8]; float* (__cdecl *fn)(S_00bfe3f0*); };
extern float g_0168d19c;
void FUN_00bfe3f0(S_00bfe3f0* s) { *s->fn(s) = g_0168d19c; }


// @ 0x00bfe410
struct S_00bfe410 { unsigned int p[8]; float* (__cdecl *fn)(S_00bfe410*); };
extern float g_0168d1a0;
void FUN_00bfe410(S_00bfe410* s) { *s->fn(s) = g_0168d1a0; }


// @ 0x00bfe430
struct S_00bfe430 { unsigned int p[8]; float* (__cdecl *fn)(S_00bfe430*); };
extern float g_0168d1a4;
void FUN_00bfe430(S_00bfe430* s) { *s->fn(s) = g_0168d1a4; }


// @ 0x00c6a0e0
struct S_00c6a0e0 { unsigned int p[8]; float* (__cdecl *fn)(S_00c6a0e0*); };
extern float g_01693e3c;
void FUN_00c6a0e0(S_00c6a0e0* s) { *s->fn(s) = g_01693e3c; }

