// Generated by tools/matching/synth.py (template fnv_hash_init_od). Do not edit by hand.
unsigned int FNVHash(const char* s, unsigned int basis, int flag);

// @ 0x0121b9a0
extern const char s_013eb198[];
unsigned int g_015d0cfc = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0121b9c0
extern const char s_013eb1a8[];
unsigned int g_015d0c44 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0121d560
extern const char s_013eb198[];
unsigned int g_015d124c = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0121d580
extern const char s_013eb1a8[];
unsigned int g_015d1190 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0121f4a0
extern const char s_013eb198[];
unsigned int g_015d17a8 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0121f4c0
extern const char s_013eb1a8[];
unsigned int g_015d16f0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01221150
extern const char s_013eb198[];
unsigned int g_015d1cf0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01221170
extern const char s_013eb1a8[];
unsigned int g_015d1c38 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01222d20
extern const char s_013eb198[];
unsigned int g_015d224c = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01222d40
extern const char s_013eb1a8[];
unsigned int g_015d2194 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01223720
extern const char s_013ec4dc[];
unsigned int g_015d2180 = FNVHash(s_013ec4dc, 0x811C9DC5, 1);

// @ 0x01223740
extern const char s_013ec4f0[];
unsigned int g_015d25b0 = FNVHash(s_013ec4f0, 0x811C9DC5, 1);

// @ 0x01223760
extern const char s_013ec504[];
unsigned int g_015d22a4 = FNVHash(s_013ec504, 0x811C9DC5, 1);

// @ 0x01224a00
extern const char s_013eb198[];
unsigned int g_015d2798 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01224a20
extern const char s_013eb1a8[];
unsigned int g_015d26e0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01226620
extern const char s_013eb198[];
unsigned int g_015d2d68 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01226640
extern const char s_013eb1a8[];
unsigned int g_015d2cb0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x012281d0
extern const char s_013eb198[];
unsigned int g_015d32a0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x012281f0
extern const char s_013eb1a8[];
unsigned int g_015d31e8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01229d70
extern const char s_013eb198[];
unsigned int g_015d37d0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01229d90
extern const char s_013eb1a8[];
unsigned int g_015d3718 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0122b910
extern const char s_013eb198[];
unsigned int g_015d3d04 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0122b930
extern const char s_013eb1a8[];
unsigned int g_015d3c48 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0122d670
extern const char s_013eb198[];
unsigned int g_015d4270 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0122d690
extern const char s_013eb1a8[];
unsigned int g_015d41b8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0122f210
extern const char s_013eb198[];
unsigned int g_015d47a0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0122f230
extern const char s_013eb1a8[];
unsigned int g_015d46e8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01230dc0
extern const char s_013eb198[];
unsigned int g_015d4cd0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01230de0
extern const char s_013eb1a8[];
unsigned int g_015d4c18 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01232960
extern const char s_013eb198[];
unsigned int g_015d5200 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01232980
extern const char s_013eb1a8[];
unsigned int g_015d5148 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01234500
extern const char s_013eb198[];
unsigned int g_015d5730 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01234520
extern const char s_013eb1a8[];
unsigned int g_015d5678 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01236090
extern const char s_013eb198[];
unsigned int g_015d5c60 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x012360b0
extern const char s_013eb1a8[];
unsigned int g_015d5ba8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01237c30
extern const char s_013eb198[];
unsigned int g_015d61c4 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01237c50
extern const char s_013eb1a8[];
unsigned int g_015d6108 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01239b20
extern const char s_013eb198[];
unsigned int g_015d6718 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01239b40
extern const char s_013eb1a8[];
unsigned int g_015d6660 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0123b7c0
extern const char s_013eb198[];
unsigned int g_015d6c60 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0123b7e0
extern const char s_013eb1a8[];
unsigned int g_015d6ba8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0123d350
extern const char s_013eb198[];
unsigned int g_015d7190 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0123d370
extern const char s_013eb1a8[];
unsigned int g_015d70d8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0123efd0
extern const char s_013eb198[];
unsigned int g_015d76d8 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0123eff0
extern const char s_013eb1a8[];
unsigned int g_015d7620 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01240b60
extern const char s_013eb198[];
unsigned int g_015d7c08 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01240b80
extern const char s_013eb1a8[];
unsigned int g_015d7b50 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01242700
extern const char s_013eb198[];
unsigned int g_015d8188 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01242720
extern const char s_013eb1a8[];
unsigned int g_015d80d0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x012443a0
extern const char s_013eb198[];
unsigned int g_015d86e0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x012443c0
extern const char s_013eb1a8[];
unsigned int g_015d8620 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01246560
extern const char s_013eb198[];
unsigned int g_015d8c34 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01246580
extern const char s_013eb1a8[];
unsigned int g_015d8b78 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01248320
extern const char s_013eb198[];
unsigned int g_015d91a4 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01248340
extern const char s_013eb1a8[];
unsigned int g_015d90e8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0124a090
extern const char s_013eb198[];
unsigned int g_015d9794 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0124a0b0
extern const char s_013eb1a8[];
unsigned int g_015d9694 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0124bf50
extern const char s_013eb198[];
unsigned int g_015d9d48 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0124bf70
extern const char s_013eb1a8[];
unsigned int g_015d9c90 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0124db40
extern const char s_013eb198[];
unsigned int g_015da280 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0124db60
extern const char s_013eb1a8[];
unsigned int g_015da1c8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0124f6d0
extern const char s_013eb198[];
unsigned int g_015da7e8 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0124f6f0
extern const char s_013eb1a8[];
unsigned int g_015da6fc = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0125d4f0
extern const char s_013eb198[];
unsigned int g_015de210 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0125d510
extern const char s_013eb1a8[];
unsigned int g_015de158 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01262a90
extern const char s_013eb198[];
unsigned int g_015df5d0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01262ab0
extern const char s_013eb1a8[];
unsigned int g_015df518 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x0126ffd0
extern const char s_013eb198[];
unsigned int g_015e3568 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x0126fff0
extern const char s_013eb1a8[];
unsigned int g_015e34b0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01271b60
extern const char s_013eb198[];
unsigned int g_015e3a98 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01271b80
extern const char s_013eb1a8[];
unsigned int g_015e39e0 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01273710
extern const char s_013eb198[];
unsigned int g_015e3fe0 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01273730
extern const char s_013eb1a8[];
unsigned int g_015e3f28 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01275330
extern const char s_013eb198[];
unsigned int g_015e453c = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01275350
extern const char s_013eb1a8[];
unsigned int g_015e4484 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);

// @ 0x01276f00
extern const char s_013eb198[];
unsigned int g_015e4a88 = FNVHash(s_013eb198, 0x811C9DC5, 1);

// @ 0x01276f20
extern const char s_013eb1a8[];
unsigned int g_015e49b8 = FNVHash(s_013eb1a8, 0x811C9DC5, 1);
