// Generated by tools/matching/synth.py (template global_vec_free_atexit_range). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);
struct V { void* b; void* e; void Destroy(void* b, void* e); };

// @ 0x013beb30
extern V g_015fea04;
void FUN_013beb30() { g_015fea04.Destroy(g_015fea04.b, g_015fea04.e); if (g_015fea04.b && ((int*)g_015fea04.b)[-1]) EASTL_allocator_deallocate(g_015fea04.b); }

// @ 0x013c2e60
extern V g_016888f0;
void FUN_013c2e60() { g_016888f0.Destroy(g_016888f0.b, g_016888f0.e); if (g_016888f0.b && ((int*)g_016888f0.b)[-1]) EASTL_allocator_deallocate(g_016888f0.b); }

// @ 0x013c3280
extern V g_0168c388;
void FUN_013c3280() { g_0168c388.Destroy(g_0168c388.b, g_0168c388.e); if (g_0168c388.b && ((int*)g_0168c388.b)[-1]) EASTL_allocator_deallocate(g_0168c388.b); }

// @ 0x013c94d0
extern V g_016c82c0;
void FUN_013c94d0() { g_016c82c0.Destroy(g_016c82c0.b, g_016c82c0.e); if (g_016c82c0.b && ((int*)g_016c82c0.b)[-1]) EASTL_allocator_deallocate(g_016c82c0.b); }

// @ 0x013c9500
extern V g_016c82d4;
void FUN_013c9500() { g_016c82d4.Destroy(g_016c82d4.b, g_016c82d4.e); if (g_016c82d4.b && ((int*)g_016c82d4.b)[-1]) EASTL_allocator_deallocate(g_016c82d4.b); }

// @ 0x013c9530
extern V g_016c82e8;
void FUN_013c9530() { g_016c82e8.Destroy(g_016c82e8.b, g_016c82e8.e); if (g_016c82e8.b && ((int*)g_016c82e8.b)[-1]) EASTL_allocator_deallocate(g_016c82e8.b); }

// @ 0x013c9560
extern V g_016c82fc;
void FUN_013c9560() { g_016c82fc.Destroy(g_016c82fc.b, g_016c82fc.e); if (g_016c82fc.b && ((int*)g_016c82fc.b)[-1]) EASTL_allocator_deallocate(g_016c82fc.b); }

// @ 0x013c9590
extern V g_016c84e0;
void FUN_013c9590() { g_016c84e0.Destroy(g_016c84e0.b, g_016c84e0.e); if (g_016c84e0.b && ((int*)g_016c84e0.b)[-1]) EASTL_allocator_deallocate(g_016c84e0.b); }
