// Generated by tools/matching/synth.py (template global_ptr_owned_dealloc). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);
bool FUN_00935ad0(void* p);

// @ 0x013c06b0
extern void* g_0164d348;
void FUN_013c06b0() { if (FUN_00935ad0(g_0164d348) && g_0164d348) EASTL_allocator_deallocate(g_0164d348); }

// @ 0x013c09f0
extern void* g_0164f0e0;
void FUN_013c09f0() { if (FUN_00935ad0(g_0164f0e0) && g_0164f0e0) EASTL_allocator_deallocate(g_0164f0e0); }

// @ 0x013c0a60
extern void* g_01650388;
void FUN_013c0a60() { if (FUN_00935ad0(g_01650388) && g_01650388) EASTL_allocator_deallocate(g_01650388); }

// @ 0x013c0d70
extern void* g_01668ea0;
void FUN_013c0d70() { if (FUN_00935ad0(g_01668ea0) && g_01668ea0) EASTL_allocator_deallocate(g_01668ea0); }

// @ 0x013c0f10
extern void* g_01668f00;
void FUN_013c0f10() { if (FUN_00935ad0(g_01668f00) && g_01668f00) EASTL_allocator_deallocate(g_01668f00); }
