// Generated by tools/matching/synth.py (template guarded_member_tailcall). Do not edit by hand.

// @ 0x005ca930
struct T_005ca930 { int callee_005ca930(); };
struct O_005ca930 { char pad[100]; T_005ca930* p; int FUN_005ca930(); };
int O_005ca930::FUN_005ca930() { if (p) return p->callee_005ca930(); return 0; }

// @ 0x005ca940
struct T_005ca940 { int callee_005ca940(); };
struct O_005ca940 { char pad[100]; T_005ca940* p; int FUN_005ca940(); };
int O_005ca940::FUN_005ca940() { if (p) return p->callee_005ca940(); return 0; }

// @ 0x005f2760
struct T_005f2760 { int callee_005f2760(); };
struct O_005f2760 { char pad[44]; T_005f2760* p; int FUN_005f2760(); };
int O_005f2760::FUN_005f2760() { if (p) return p->callee_005f2760(); return 0; }

// @ 0x005f2770
struct T_005f2770 { int callee_005f2770(); };
struct O_005f2770 { char pad[44]; T_005f2770* p; int FUN_005f2770(); };
int O_005f2770::FUN_005f2770() { if (p) return p->callee_005f2770(); return 0; }

// @ 0x00641810
struct T_00641810 { int callee_00641810(); };
struct O_00641810 { char pad[28]; T_00641810* p; int FUN_00641810(); };
int O_00641810::FUN_00641810() { if (p) return p->callee_00641810(); return 0; }

// @ 0x00641820
struct T_00641820 { int callee_00641820(); };
struct O_00641820 { char pad[28]; T_00641820* p; int FUN_00641820(); };
int O_00641820::FUN_00641820() { if (p) return p->callee_00641820(); return 0; }

// @ 0x00641850
struct T_00641850 { int callee_00641850(); };
struct O_00641850 { char pad[28]; T_00641850* p; int FUN_00641850(); };
int O_00641850::FUN_00641850() { if (p) return p->callee_00641850(); return 0; }

// @ 0x00a02ba0
struct T_00a02ba0 { int callee_00a02ba0(); };
struct O_00a02ba0 { char pad[388]; T_00a02ba0* p; int FUN_00a02ba0(); };
int O_00a02ba0::FUN_00a02ba0() { if (p) return p->callee_00a02ba0(); return 0; }
