// Generated by tools/matching/synth.py (template hashtable_insert_range_iter). Do not edit by hand.
struct Ft {};
struct Tag {};
struct Pr { bool b; unsigned n; };
struct Pol { void need(Pr*, unsigned, unsigned, unsigned); };

// @ 0x005959a0
struct N_005959a0 { char v[16]; N_005959a0* next; };
struct Res_005959a0 { N_005959a0* n; N_005959a0** b; bool x; };
struct It_005959a0 {
  N_005959a0* n; N_005959a0** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_005959a0& operator++() { inc(); return *this; }
  bool operator!=(const It_005959a0& o) const { return n != o.n; }
};
unsigned __cdecl dist_005959a0(It_005959a0, It_005959a0, Tag);
struct H_005959a0 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_005959a0 ins(N_005959a0*, Ft);
  void f(It_005959a0 first, It_005959a0 last);
};
void H_005959a0::f(It_005959a0 first, It_005959a0 last) {
  Tag t;
  unsigned n = dist_005959a0(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}

// @ 0x0060f0d0
struct N_0060f0d0 { char v[8]; N_0060f0d0* next; };
struct Res_0060f0d0 { N_0060f0d0* n; N_0060f0d0** b; bool x; };
struct It_0060f0d0 {
  N_0060f0d0* n; N_0060f0d0** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_0060f0d0& operator++() { inc(); return *this; }
  bool operator!=(const It_0060f0d0& o) const { return n != o.n; }
};
unsigned __cdecl dist_0060f0d0(It_0060f0d0, It_0060f0d0, Tag);
struct H_0060f0d0 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_0060f0d0 ins(N_0060f0d0*, Ft);
  void f(It_0060f0d0 first, It_0060f0d0 last);
};
void H_0060f0d0::f(It_0060f0d0 first, It_0060f0d0 last) {
  Tag t;
  unsigned n = dist_0060f0d0(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}

// @ 0x00a2b230
struct N_00a2b230 { char v[8]; N_00a2b230* next; };
struct Res_00a2b230 { N_00a2b230* n; N_00a2b230** b; bool x; };
struct It_00a2b230 {
  N_00a2b230* n; N_00a2b230** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_00a2b230& operator++() { inc(); return *this; }
  bool operator!=(const It_00a2b230& o) const { return n != o.n; }
};
unsigned __cdecl dist_00a2b230(It_00a2b230, It_00a2b230, Tag);
struct H_00a2b230 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_00a2b230 ins(N_00a2b230*, Ft);
  void f(It_00a2b230 first, It_00a2b230 last);
};
void H_00a2b230::f(It_00a2b230 first, It_00a2b230 last) {
  Tag t;
  unsigned n = dist_00a2b230(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}

// @ 0x00b53410
struct N_00b53410 { char v[8]; N_00b53410* next; };
struct Res_00b53410 { N_00b53410* n; N_00b53410** b; bool x; };
struct It_00b53410 {
  N_00b53410* n; N_00b53410** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_00b53410& operator++() { inc(); return *this; }
  bool operator!=(const It_00b53410& o) const { return n != o.n; }
};
unsigned __cdecl dist_00b53410(It_00b53410, It_00b53410, Tag);
struct H_00b53410 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_00b53410 ins(N_00b53410*, Ft);
  void f(It_00b53410 first, It_00b53410 last);
};
void H_00b53410::f(It_00b53410 first, It_00b53410 last) {
  Tag t;
  unsigned n = dist_00b53410(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}

// @ 0x00db5d70
struct N_00db5d70 { char v[16]; N_00db5d70* next; };
struct Res_00db5d70 { N_00db5d70* n; N_00db5d70** b; bool x; };
struct It_00db5d70 {
  N_00db5d70* n; N_00db5d70** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_00db5d70& operator++() { inc(); return *this; }
  bool operator!=(const It_00db5d70& o) const { return n != o.n; }
};
unsigned __cdecl dist_00db5d70(It_00db5d70, It_00db5d70, Tag);
struct H_00db5d70 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_00db5d70 ins(N_00db5d70*, Ft);
  void f(It_00db5d70 first, It_00db5d70 last);
};
void H_00db5d70::f(It_00db5d70 first, It_00db5d70 last) {
  Tag t;
  unsigned n = dist_00db5d70(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}

// @ 0x00ef9a20
struct N_00ef9a20 { char v[4]; N_00ef9a20* next; };
struct Res_00ef9a20 { N_00ef9a20* n; N_00ef9a20** b; bool x; };
struct It_00ef9a20 {
  N_00ef9a20* n; N_00ef9a20** b;
  void inc() { n = n->next; while (!n) n = *++b; }
  It_00ef9a20& operator++() { inc(); return *this; }
  bool operator!=(const It_00ef9a20& o) const { return n != o.n; }
};
unsigned __cdecl dist_00ef9a20(It_00ef9a20, It_00ef9a20, Tag);
struct H_00ef9a20 {
  void* pad[2]; unsigned nb; unsigned ne; Pol pol;
  void rehash(unsigned);
  Res_00ef9a20 ins(N_00ef9a20*, Ft);
  void f(It_00ef9a20 first, It_00ef9a20 last);
};
void H_00ef9a20::f(It_00ef9a20 first, It_00ef9a20 last) {
  Tag t;
  unsigned n = dist_00ef9a20(first, last, t);
  Pr r; pol.need(&r, nb, ne, n);
  if (r.b) rehash(r.n);
  for (; first != last; ++first) ins(first.n, Ft());
}
