// Generated by tools/matching/synth.py (template hash_registered_u32_atexit). Do not edit by hand.
unsigned int FNVHash(const char* s, unsigned int basis, int flag);
struct B { virtual ~B(); unsigned hash; B* next;
  B(const char* s, unsigned basis, int f, B*& head) : hash(FNVHash(s, basis, f)), next(head) { head = this; } };
struct F : B { unsigned v; F(const char* s, unsigned basis, int f, B*& head, unsigned b) : B(s, basis, f, head), v(b) {} virtual ~F(); };

// @ 0x0136b470
extern const char s_0147d0e0[];
extern B* h_015a2ca8;
F g_016a0a70(s_0147d0e0, 0x811C9DC5, 1, h_015a2ca8, 0x426D237Au);

// @ 0x0136b4c0
extern const char s_0147d0fc[];
extern B* h_015a2ca8;
F g_016a0a80(s_0147d0fc, 0x811C9DC5, 1, h_015a2ca8, 0x613FD1EAu);

// @ 0x0136b510
extern const char s_0147d118[];
extern B* h_015a2ca8;
F g_016a0a90(s_0147d118, 0x811C9DC5, 1, h_015a2ca8, 0xC43F92F4u);

// @ 0x0136b560
extern const char s_0147d134[];
extern B* h_015a2ca8;
F g_016a0aa0(s_0147d134, 0x811C9DC5, 1, h_015a2ca8, 0xC43F92F4u);

// @ 0x0136b5b0
extern const char s_0147d150[];
extern B* h_015a2ca8;
F g_016a0ab0(s_0147d150, 0x811C9DC5, 1, h_015a2ca8, 0xC43F92F4u);

// @ 0x0136b600
extern const char s_0147d170[];
extern B* h_015a2ca8;
F g_016a0ac0(s_0147d170, 0x811C9DC5, 1, h_015a2ca8, 0xFEBE4876u);

// @ 0x0136c240
extern const char s_0147d68c[];
extern B* h_015a2ff8;
F g_016a0e4c(s_0147d68c, 0x811C9DC5, 1, h_015a2ff8, 0x3615A30Bu);

// @ 0x0136cd20
extern const char s_0147da0c[];
extern B* h_015a2ff8;
F g_016a104c(s_0147da0c, 0x811C9DC5, 1, h_015a2ff8, 0xBF0CE0D0u);

// @ 0x0136cd70
extern const char s_0147da24[];
extern B* h_015a2ff8;
F g_016a105c(s_0147da24, 0x811C9DC5, 1, h_015a2ff8, 0x58102924u);

// @ 0x01370870
extern const char s_01481064[];
extern B* h_015a5524;
F g_016ac2bc(s_01481064, 0x811C9DC5, 1, h_015a5524, 0x613FD1EAu);

// @ 0x01370d70
extern const char s_01481394[];
extern B* h_015a55e8;
F g_016ac3d8(s_01481394, 0x811C9DC5, 1, h_015a55e8, 0xFF000000u);

// @ 0x01370f40
extern const char s_01481434[];
extern B* h_015a55e8;
F g_016ac428(s_01481434, 0x811C9DC5, 1, h_015a55e8, 0xFF83FF59u);

// @ 0x01370f90
extern const char s_0148144c[];
extern B* h_015a55e8;
F g_016ac438(s_0148144c, 0x811C9DC5, 1, h_015a55e8, 0xFFFF0000u);
