// Generated by tools/matching/synth.py (template hashmap_find_value_or_null). Do not edit by hand.

// @ 0x006a5970

typedef unsigned Key_006a5970;
struct Owner_006a5970 {
    struct node { unsigned pad[1]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_006a5970& k);
    };
    char pad[180]; HT ht;
    unsigned get(Key_006a5970 k);
};
unsigned Owner_006a5970::get(Key_006a5970 k) {
    Owner_006a5970::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x006a59b0

typedef unsigned Key_006a59b0;
struct Owner_006a59b0 {
    struct node { unsigned pad[1]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_006a59b0& k);
    };
    char pad[244]; HT ht;
    unsigned get(Key_006a59b0 k);
};
unsigned Owner_006a59b0::get(Key_006a59b0 k) {
    Owner_006a59b0::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00961950

typedef unsigned Key_00961950;
struct Owner_00961950 {
    struct node { unsigned pad[1]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00961950& k);
    };
    char pad[488]; HT ht;
    unsigned get(Key_00961950 k);
};
unsigned Owner_00961950::get(Key_00961950 k) {
    Owner_00961950::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00a6d560

typedef unsigned Key_00a6d560;
struct Owner_00a6d560 {
    struct node { unsigned pad[1]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00a6d560& k);
    };
    char pad[548]; HT ht;
    unsigned get(Key_00a6d560 k);
};
unsigned Owner_00a6d560::get(Key_00a6d560 k) {
    Owner_00a6d560::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00a7c080

typedef unsigned __int64 Key_00a7c080;
struct Owner_00a7c080 {
    struct node { unsigned pad[2]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00a7c080& k);
    };
    char pad[4]; HT ht;
    unsigned get(Key_00a7c080 k);
};
unsigned Owner_00a7c080::get(Key_00a7c080 k) {
    Owner_00a7c080::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00a7c0c0

typedef unsigned __int64 Key_00a7c0c0;
struct Owner_00a7c0c0 {
    struct node { unsigned pad[2]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00a7c0c0& k);
    };
    char pad[36]; HT ht;
    unsigned get(Key_00a7c0c0 k);
};
unsigned Owner_00a7c0c0::get(Key_00a7c0c0 k) {
    Owner_00a7c0c0::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00c77340

typedef unsigned Key_00c77340;
struct Owner_00c77340 {
    struct node { unsigned pad[1]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00c77340& k);
    };
    char pad[1688]; HT ht;
    unsigned get(Key_00c77340 k);
};
unsigned Owner_00c77340::get(Key_00c77340 k) {
    Owner_00c77340::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}


// @ 0x00fe4660

typedef unsigned Key_00fe4660;
struct Owner_00fe4660 {
    struct node { unsigned pad[2]; unsigned v; };
    struct iterator { node* mpNode; node** mpBucket; };
    struct HT {
        int f; node** mpBucketArray; unsigned mnBucketCount; unsigned cnt;
        iterator end() { iterator i; i.mpNode = mpBucketArray[mnBucketCount]; i.mpBucket = mpBucketArray + mnBucketCount; return i; }
        iterator find(const Key_00fe4660& k);
    };
    char pad[128]; HT ht;
    unsigned get(Key_00fe4660 k);
};
unsigned Owner_00fe4660::get(Key_00fe4660 k) {
    Owner_00fe4660::iterator it = ht.find(k);
    if (it.mpNode != ht.end().mpNode) return it.mpNode->v;
    return 0;
}

