// Generated by tools/matching/synth.py (template hk_finish_ctor_naked). Do not edit by hand.

// @ 0x0108ab50
extern "C" const void* g_0149e150;
__declspec(naked) void FUN_0108ab50(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e150
    done:
        ret
    }
}

// @ 0x0108ac90
extern "C" const void* g_0149e1c0;
__declspec(naked) void FUN_0108ac90(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e1c0
    done:
        ret
    }
}

// @ 0x0108ae10
extern "C" const void* g_0149e218;
__declspec(naked) void FUN_0108ae10(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e218
    done:
        ret
    }
}

// @ 0x0108bae0
extern "C" const void* g_0149e260;
__declspec(naked) void FUN_0108bae0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e260
    done:
        ret
    }
}

// @ 0x0108c030
extern "C" const void* g_0149e1a8;
__declspec(naked) void FUN_0108c030(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e1a8
    done:
        ret
    }
}

// @ 0x0108e8f0
extern "C" const void* g_014a17e4;
__declspec(naked) void FUN_0108e8f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a17e4
    done:
        ret
    }
}

// @ 0x0108f370
extern "C" const void* g_014a181c;
__declspec(naked) void FUN_0108f370(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a181c
    done:
        ret
    }
}

// @ 0x0108f930
extern "C" const void* g_014a1934;
__declspec(naked) void FUN_0108f930(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1934
    done:
        ret
    }
}

// @ 0x0108ffa0
extern "C" const void* g_0149df90;
__declspec(naked) void FUN_0108ffa0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149df90
    done:
        ret
    }
}

// @ 0x010903e0
extern "C" const void* g_014a1990;
__declspec(naked) void FUN_010903e0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1990
    done:
        ret
    }
}

// @ 0x010907f0
extern "C" const void* g_014a1a0c;
__declspec(naked) void FUN_010907f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1a0c
    done:
        ret
    }
}

// @ 0x01090e10
extern "C" const void* g_0149df10;
__declspec(naked) void FUN_01090e10(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149df10
    done:
        ret
    }
}

// @ 0x01091910
extern "C" const void* g_014a1a28;
__declspec(naked) void FUN_01091910(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1a28
    done:
        ret
    }
}

// @ 0x01091a40
extern "C" const void* g_014a1a3c;
__declspec(naked) void FUN_01091a40(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1a3c
    done:
        ret
    }
}

// @ 0x01092040
extern "C" const void* g_014a1a60;
__declspec(naked) void FUN_01092040(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1a60
    done:
        ret
    }
}

// @ 0x01092340
extern "C" const void* g_014a1aa8;
__declspec(naked) void FUN_01092340(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1aa8
    done:
        ret
    }
}

// @ 0x01092d60
extern "C" const void* g_0149e2c8;
__declspec(naked) void FUN_01092d60(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e2c8
    done:
        ret
    }
}

// @ 0x010937f0
extern "C" const void* g_014a1aec;
__declspec(naked) void FUN_010937f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1aec
    done:
        ret
    }
}

// @ 0x010941f0
extern "C" const void* g_014a1b14;
__declspec(naked) void FUN_010941f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1b14
    done:
        ret
    }
}

// @ 0x01094390
extern "C" const void* g_014a1b28;
__declspec(naked) void FUN_01094390(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1b28
    done:
        ret
    }
}

// @ 0x010944f0
extern "C" const void* g_014a1b64;
__declspec(naked) void FUN_010944f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1b64
    done:
        ret
    }
}

// @ 0x01094ba0
extern "C" const void* g_014a1b88;
__declspec(naked) void FUN_01094ba0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1b88
    done:
        ret
    }
}

// @ 0x01094df0
extern "C" const void* g_014a1b90;
__declspec(naked) void FUN_01094df0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1b90
    done:
        ret
    }
}

// @ 0x01095940
extern "C" const void* g_014a1bd4;
__declspec(naked) void FUN_01095940(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1bd4
    done:
        ret
    }
}

// @ 0x01095d60
extern "C" const void* g_014a1c08;
__declspec(naked) void FUN_01095d60(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1c08
    done:
        ret
    }
}

// @ 0x01096490
extern "C" const void* g_014a1ca8;
__declspec(naked) void FUN_01096490(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1ca8
    done:
        ret
    }
}

// @ 0x01096b10
extern "C" const void* g_014a1ce4;
__declspec(naked) void FUN_01096b10(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1ce4
    done:
        ret
    }
}

// @ 0x01097260
extern "C" const void* g_014a1d08;
__declspec(naked) void FUN_01097260(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1d08
    done:
        ret
    }
}

// @ 0x010972e0
extern "C" const void* g_014a1d8c;
__declspec(naked) void FUN_010972e0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1d8c
    done:
        ret
    }
}

// @ 0x01097320
extern "C" const void* g_0149e18c;
__declspec(naked) void FUN_01097320(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e18c
    done:
        ret
    }
}

// @ 0x01097d70
extern "C" const void* g_014a1e08;
__declspec(naked) void FUN_01097d70(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1e08
    done:
        ret
    }
}

// @ 0x01098590
extern "C" const void* g_014a18b8;
__declspec(naked) void FUN_01098590(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a18b8
    done:
        ret
    }
}

// @ 0x01099310
extern "C" const void* g_014a1e30;
__declspec(naked) void FUN_01099310(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a1e30
    done:
        ret
    }
}

// @ 0x010bfe90
extern "C" const void* g_014a2610;
__declspec(naked) void FUN_010bfe90(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a2610
    done:
        ret
    }
}

// @ 0x010c05b0
extern "C" const void* g_014a2790;
__declspec(naked) void FUN_010c05b0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a2790
    done:
        ret
    }
}

// @ 0x010c1fc0
extern "C" const void* g_014a2804;
__declspec(naked) void FUN_010c1fc0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a2804
    done:
        ret
    }
}

// @ 0x010c2710
extern "C" const void* g_014a2888;
__declspec(naked) void FUN_010c2710(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a2888
    done:
        ret
    }
}

// @ 0x010c3750
extern "C" const void* g_014a2900;
__declspec(naked) void FUN_010c3750(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a2900
    done:
        ret
    }
}

// @ 0x010c3fe0
extern "C" const void* g_014a3bfc;
__declspec(naked) void FUN_010c3fe0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3bfc
    done:
        ret
    }
}

// @ 0x010c4e00
extern "C" const void* g_014a3ccc;
__declspec(naked) void FUN_010c4e00(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3ccc
    done:
        ret
    }
}

// @ 0x010c5500
extern "C" const void* g_014a3d14;
__declspec(naked) void FUN_010c5500(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3d14
    done:
        ret
    }
}

// @ 0x010c5d10
extern "C" const void* g_014a3d58;
__declspec(naked) void FUN_010c5d10(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3d58
    done:
        ret
    }
}

// @ 0x010c6870
extern "C" const void* g_014a3e1c;
__declspec(naked) void FUN_010c6870(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3e1c
    done:
        ret
    }
}

// @ 0x010c69c0
extern "C" const void* g_014a3e5c;
__declspec(naked) void FUN_010c69c0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3e5c
    done:
        ret
    }
}

// @ 0x010c70e0
extern "C" const void* g_014a3eb4;
__declspec(naked) void FUN_010c70e0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3eb4
    done:
        ret
    }
}

// @ 0x010c7ab0
extern "C" const void* g_014a3f1c;
__declspec(naked) void FUN_010c7ab0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3f1c
    done:
        ret
    }
}

// @ 0x010c8110
extern "C" const void* g_014a3f7c;
__declspec(naked) void FUN_010c8110(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a3f7c
    done:
        ret
    }
}

// @ 0x010c8e20
extern "C" const void* g_014a4030;
__declspec(naked) void FUN_010c8e20(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a4030
    done:
        ret
    }
}

// @ 0x010ca610
extern "C" const void* g_014a4134;
__declspec(naked) void FUN_010ca610(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a4134
    done:
        ret
    }
}

// @ 0x010cb790
extern "C" const void* g_014a41c0;
__declspec(naked) void FUN_010cb790(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a41c0
    done:
        ret
    }
}

// @ 0x010cbae0
extern "C" const void* g_014a4220;
__declspec(naked) void FUN_010cbae0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a4220
    done:
        ret
    }
}

// @ 0x010ee530
extern "C" const void* g_014a5954;
__declspec(naked) void FUN_010ee530(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a5954
    done:
        ret
    }
}

// @ 0x010eedf0
extern "C" const void* g_0149e2a4;
__declspec(naked) void FUN_010eedf0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_0149e2a4
    done:
        ret
    }
}

// @ 0x010f0160
extern "C" const void* g_014a59b4;
__declspec(naked) void FUN_010f0160(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a59b4
    done:
        ret
    }
}

// @ 0x010f0180
extern "C" const void* g_014a59bc;
__declspec(naked) void FUN_010f0180(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a59bc
    done:
        ret
    }
}

// @ 0x011285d0
extern "C" const void* g_014a6ea4;
__declspec(naked) void FUN_011285d0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6ea4
    done:
        ret
    }
}

// @ 0x011288f0
extern "C" const void* g_014a6ec8;
__declspec(naked) void FUN_011288f0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6ec8
    done:
        ret
    }
}

// @ 0x011289a0
extern "C" const void* g_014a6ed8;
__declspec(naked) void FUN_011289a0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6ed8
    done:
        ret
    }
}

// @ 0x01128a90
extern "C" const void* g_014a6ee8;
__declspec(naked) void FUN_01128a90(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6ee8
    done:
        ret
    }
}

// @ 0x01128ab0
extern "C" const void* g_014a6f14;
__declspec(naked) void FUN_01128ab0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6f14
    done:
        ret
    }
}

// @ 0x01129110
extern "C" const void* g_014a6f38;
__declspec(naked) void FUN_01129110(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6f38
    done:
        ret
    }
}

// @ 0x01129270
extern "C" const void* g_014a6f48;
__declspec(naked) void FUN_01129270(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6f48
    done:
        ret
    }
}

// @ 0x01129700
extern "C" const void* g_014a6fa0;
__declspec(naked) void FUN_01129700(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a6fa0
    done:
        ret
    }
}

// @ 0x01129f90
extern "C" const void* g_014a7038;
__declspec(naked) void FUN_01129f90(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a7038
    done:
        ret
    }
}

// @ 0x0112a5a0
extern "C" const void* g_014a709c;
__declspec(naked) void FUN_0112a5a0(void* p) {
    __asm {
        mov eax, dword ptr [esp + 4]
        test eax, eax
        je done
        mov word ptr [eax + 6], 1
        mov dword ptr [eax], offset g_014a709c
    done:
        ret
    }
}
