// Generated by tools/matching/synth.py (template lazy_init_getter_member). Do not edit by hand.

// @ 0x0071c8e0
struct S_0071c8e0 { char pad[328]; int v; void Init(); int Get(); };
int S_0071c8e0::Get() { if (v == 0) Init(); return v; }

// @ 0x007a5c20
struct S_007a5c20 { char pad[124]; int v; void Init(); int Get(); };
int S_007a5c20::Get() { if (v == 0) Init(); return v; }

// @ 0x007a5c40
struct S_007a5c40 { char pad[120]; int v; void Init(); int Get(); };
int S_007a5c40::Get() { if (v == 0) Init(); return v; }

// @ 0x007a5c60
struct S_007a5c60 { char pad[116]; int v; void Init(); int Get(); };
int S_007a5c60::Get() { if (v == 0) Init(); return v; }

// @ 0x00c8b770
struct S_00c8b770 { char pad[64]; int v; void Init(); int Get(); };
int S_00c8b770::Get() { if (v == 0) Init(); return v; }
