// Generated by tools/matching/synth.py (template member_eq_either_imm_int). Do not edit by hand.

// @ 0x00ac80f0
int __fastcall FUN_00ac80f0(void* p) { int v = *(int*)((char*)p + 44); if (v == 1 || v == 2) return 1; return 0; }

// @ 0x00c4ed90
int __fastcall FUN_00c4ed90(void* p) { int v = *(int*)((char*)p + 500); if (v == 2 || v == 3) return 1; return 0; }

// @ 0x00c5f170
int __fastcall FUN_00c5f170(void* p) { int v = *(int*)((char*)p + 496); if (v == 2 || v == 3) return 1; return 0; }

// @ 0x00e21570
int __fastcall FUN_00e21570(void* p) { int v = *(int*)((char*)p + 148); if (v == 3 || v == 4) return 1; return 0; }

// @ 0x00e21ac0
int __fastcall FUN_00e21ac0(void* p) { int v = *(int*)((char*)p + 148); if (v == 4 || v == 2) return 1; return 0; }

// @ 0x00fcb470
int __fastcall FUN_00fcb470(void* p) { int v = *(int*)((char*)p + 336); if (v == 5 || v == 6) return 1; return 0; }
