// Generated by tools/matching/synth.py (template mi_ctor_base_two_vptrs). Do not edit by hand.

// @ 0x005a7890
struct B_C_005a7890 { B_C_005a7890(); virtual void fb(); };
struct __declspec(novtable) X_C_005a7890 { virtual void fx(); };
struct C_005a7890 : B_C_005a7890, X_C_005a7890 { C_005a7890(); virtual void fb(); virtual void fx(); };
C_005a7890::C_005a7890() {}


// @ 0x005a8580
struct B_C_005a8580 { B_C_005a8580(); virtual void fb(); };
struct __declspec(novtable) X_C_005a8580 { virtual void fx(); };
struct C_005a8580 : B_C_005a8580, X_C_005a8580 { C_005a8580(); virtual void fb(); virtual void fx(); };
C_005a8580::C_005a8580() {}


// @ 0x005a8e30
struct B_C_005a8e30 { B_C_005a8e30(); virtual void fb(); };
struct __declspec(novtable) X_C_005a8e30 { virtual void fx(); };
struct C_005a8e30 : B_C_005a8e30, X_C_005a8e30 { C_005a8e30(); virtual void fb(); virtual void fx(); };
C_005a8e30::C_005a8e30() {}


// @ 0x005e8920
struct B_C_005e8920 { B_C_005e8920(); virtual void fb(); };
struct __declspec(novtable) X_C_005e8920 { virtual void fx(); };
struct C_005e8920 : B_C_005e8920, X_C_005e8920 { C_005e8920(); virtual void fb(); virtual void fx(); };
C_005e8920::C_005e8920() {}


// @ 0x007f3160
struct B_C_007f3160 { B_C_007f3160(); virtual void fb(); };
struct __declspec(novtable) X_C_007f3160 { virtual void fx(); };
struct C_007f3160 : B_C_007f3160, X_C_007f3160 { C_007f3160(); virtual void fb(); virtual void fx(); };
C_007f3160::C_007f3160() {}


// @ 0x00ac0c70
struct B_C_00ac0c70 { B_C_00ac0c70(); virtual void fb(); };
struct __declspec(novtable) X_C_00ac0c70 { virtual void fx(); };
struct C_00ac0c70 : B_C_00ac0c70, X_C_00ac0c70 { C_00ac0c70(); virtual void fb(); virtual void fx(); };
C_00ac0c70::C_00ac0c70() {}


// @ 0x00f39df0
struct B_C_00f39df0 { B_C_00f39df0(); virtual void fb(); };
struct __declspec(novtable) X_C_00f39df0 { virtual void fx(); };
struct C_00f39df0 : B_C_00f39df0, X_C_00f39df0 { C_00f39df0(); virtual void fb(); virtual void fx(); };
C_00f39df0::C_00f39df0() {}

