// Generated by tools/matching/synth.py (template mi_deldtor_member_dtor_release). Do not edit by hand.
struct Iface { virtual void s0(); virtual void s1(); virtual void s2(); virtual void s3(); virtual void s4(); virtual void s5(); virtual void s6(); virtual void s7(); virtual void s8(); virtual void s9(); virtual void s10(); virtual void s11(); virtual void s12(); virtual void s13(); virtual void s14(); virtual void s15(); };

// @ 0x005aa4e0
typedef unsigned int uint32_t;
struct P_C_005aa4e0 { Iface* p; ~P_C_005aa4e0() { if (p) p->s2(); } };
struct Q_C_005aa4e0 { ~Q_C_005aa4e0(); };
struct X_C_005aa4e0 { virtual ~X_C_005aa4e0() {} char pad1[16]; };
struct Y_C_005aa4e0 { virtual ~Y_C_005aa4e0() {} };
struct C_005aa4e0 : X_C_005aa4e0, Y_C_005aa4e0 { uint32_t pad2[1]; P_C_005aa4e0 m; uint32_t pad3[3]; Q_C_005aa4e0 q; C_005aa4e0(); virtual ~C_005aa4e0() {} };
C_005aa4e0::C_005aa4e0() {}


// @ 0x005ada00
typedef unsigned int uint32_t;
struct P_C_005ada00 { Iface* p; ~P_C_005ada00() { if (p) p->s2(); } };
struct Q_C_005ada00 { ~Q_C_005ada00(); };
struct X_C_005ada00 { virtual ~X_C_005ada00() {} char pad1[16]; };
struct Y_C_005ada00 { virtual ~Y_C_005ada00() {} };
struct C_005ada00 : X_C_005ada00, Y_C_005ada00 { uint32_t pad2[1]; P_C_005ada00 m; uint32_t pad3[1]; Q_C_005ada00 q; C_005ada00(); virtual ~C_005ada00() {} };
C_005ada00::C_005ada00() {}


// @ 0x005b4ba0
typedef unsigned int uint32_t;
struct P_C_005b4ba0 { Iface* p; ~P_C_005b4ba0() { if (p) p->s2(); } };
struct Q_C_005b4ba0 { ~Q_C_005b4ba0(); };
struct X_C_005b4ba0 { virtual ~X_C_005b4ba0() {} char pad1[16]; };
struct Y_C_005b4ba0 { virtual ~Y_C_005b4ba0() {} };
struct C_005b4ba0 : X_C_005b4ba0, Y_C_005b4ba0 { uint32_t pad2[1]; P_C_005b4ba0 m; uint32_t pad3[1]; Q_C_005b4ba0 q; C_005b4ba0(); virtual ~C_005b4ba0() {} };
C_005b4ba0::C_005b4ba0() {}


// @ 0x005ba140
typedef unsigned int uint32_t;
struct P_C_005ba140 { Iface* p; ~P_C_005ba140() { if (p) p->s2(); } };
struct Q_C_005ba140 { ~Q_C_005ba140(); };
struct X_C_005ba140 { virtual ~X_C_005ba140() {} char pad1[16]; };
struct Y_C_005ba140 { virtual ~Y_C_005ba140() {} };
struct C_005ba140 : X_C_005ba140, Y_C_005ba140 { uint32_t pad2[3]; P_C_005ba140 m; Q_C_005ba140 q; C_005ba140(); virtual ~C_005ba140() {} };
C_005ba140::C_005ba140() {}


// @ 0x00607000
typedef unsigned int uint32_t;
struct P_C_00607000 { Iface* p; ~P_C_00607000() { if (p) p->s1(); } };
struct Q_C_00607000 { ~Q_C_00607000(); };
struct X_C_00607000 { virtual ~X_C_00607000() {} };
struct Y_C_00607000 { virtual ~Y_C_00607000() {} };
struct C_00607000 : X_C_00607000, Y_C_00607000 { uint32_t pad2[1]; P_C_00607000 m; uint32_t pad3[7]; Q_C_00607000 q; C_00607000(); virtual ~C_00607000() {} };
C_00607000::C_00607000() {}


// @ 0x0063bb40
typedef unsigned int uint32_t;
struct P_C_0063bb40 { Iface* p; ~P_C_0063bb40() { if (p) p->s1(); } };
struct Q_C_0063bb40 { ~Q_C_0063bb40(); };
struct X_C_0063bb40 { virtual ~X_C_0063bb40() {} };
struct Y_C_0063bb40 { virtual ~Y_C_0063bb40() {} };
struct C_0063bb40 : X_C_0063bb40, Y_C_0063bb40 { uint32_t pad2[1]; P_C_0063bb40 m; uint32_t pad3[7]; Q_C_0063bb40 q; C_0063bb40(); virtual ~C_0063bb40() {} };
C_0063bb40::C_0063bb40() {}

