// Generated by tools/matching/synth.py (template mi_two_base_deldtor_ext). Do not edit by hand.

// @ 0x005a78d0
struct B_C_005a78d0 { B_C_005a78d0(); virtual ~B_C_005a78d0(); };
struct X_C_005a78d0 { virtual ~X_C_005a78d0() {} };
struct C_005a78d0 : B_C_005a78d0, X_C_005a78d0 { C_005a78d0(); virtual ~C_005a78d0() {} };
C_005a78d0::C_005a78d0() {}

// @ 0x005a85c0
struct B_C_005a85c0 { B_C_005a85c0(); virtual ~B_C_005a85c0(); };
struct X_C_005a85c0 { virtual ~X_C_005a85c0() {} };
struct C_005a85c0 : B_C_005a85c0, X_C_005a85c0 { C_005a85c0(); virtual ~C_005a85c0() {} };
C_005a85c0::C_005a85c0() {}

// @ 0x005a8e70
struct B_C_005a8e70 { B_C_005a8e70(); virtual ~B_C_005a8e70(); };
struct X_C_005a8e70 { virtual ~X_C_005a8e70() {} };
struct C_005a8e70 : B_C_005a8e70, X_C_005a8e70 { C_005a8e70(); virtual ~C_005a8e70() {} };
C_005a8e70::C_005a8e70() {}

// @ 0x005e89c0
struct B_C_005e89c0 { B_C_005e89c0(); virtual ~B_C_005e89c0(); };
struct X_C_005e89c0 { virtual ~X_C_005e89c0() {} };
struct C_005e89c0 : B_C_005e89c0, X_C_005e89c0 { C_005e89c0(); virtual ~C_005e89c0() {} };
C_005e89c0::C_005e89c0() {}

// @ 0x0073cb10
struct B_C_0073cb10 { B_C_0073cb10(); virtual ~B_C_0073cb10(); };
struct X_C_0073cb10 { virtual ~X_C_0073cb10() {} };
struct C_0073cb10 : B_C_0073cb10, X_C_0073cb10 { C_0073cb10(); virtual ~C_0073cb10() {} };
C_0073cb10::C_0073cb10() {}

// @ 0x0073cb90
struct B_C_0073cb90 { B_C_0073cb90(); virtual ~B_C_0073cb90(); };
struct X_C_0073cb90 { virtual ~X_C_0073cb90() {} };
struct C_0073cb90 : B_C_0073cb90, X_C_0073cb90 { C_0073cb90(); virtual ~C_0073cb90() {} };
C_0073cb90::C_0073cb90() {}

// @ 0x00ac0f10
struct B_C_00ac0f10 { B_C_00ac0f10(); virtual ~B_C_00ac0f10(); };
struct X_C_00ac0f10 { virtual ~X_C_00ac0f10() {} };
struct C_00ac0f10 : B_C_00ac0f10, X_C_00ac0f10 { C_00ac0f10(); virtual ~C_00ac0f10() {} };
C_00ac0f10::C_00ac0f10() {}

// @ 0x00b1d840
struct B_C_00b1d840 { B_C_00b1d840(); virtual ~B_C_00b1d840(); };
struct X_C_00b1d840 { virtual ~X_C_00b1d840() {} };
struct C_00b1d840 : B_C_00b1d840, X_C_00b1d840 { C_00b1d840(); virtual ~C_00b1d840() {} };
C_00b1d840::C_00b1d840() {}

// @ 0x00b5cc50
struct B_C_00b5cc50 { B_C_00b5cc50(); virtual ~B_C_00b5cc50(); };
struct X_C_00b5cc50 { virtual ~X_C_00b5cc50() {} };
struct C_00b5cc50 : B_C_00b5cc50, X_C_00b5cc50 { C_00b5cc50(); virtual ~C_00b5cc50() {} };
C_00b5cc50::C_00b5cc50() {}

// @ 0x00d08f30
struct B_C_00d08f30 { B_C_00d08f30(); virtual ~B_C_00d08f30(); };
struct X_C_00d08f30 { virtual ~X_C_00d08f30() {} };
struct C_00d08f30 : B_C_00d08f30, X_C_00d08f30 { C_00d08f30(); virtual ~C_00d08f30() {} };
C_00d08f30::C_00d08f30() {}

// @ 0x00f39e50
struct B_C_00f39e50 { B_C_00f39e50(); virtual ~B_C_00f39e50(); };
struct X_C_00f39e50 { virtual ~X_C_00f39e50() {} };
struct C_00f39e50 : B_C_00f39e50, X_C_00f39e50 { C_00f39e50(); virtual ~C_00f39e50() {} };
C_00f39e50::C_00f39e50() {}
