// Generated by tools/matching/synth.py (template od_call_then_vcall_store). Do not edit by hand.

// @ 0x007f58b0
struct O_007f58b0 { int pad[3]; int v; };
void ext_007f58b0(O_007f58b0*, void*);
struct C_007f58b0 {
  virtual void v0();
  virtual void v1();
  virtual void v2();
  virtual void v3();
  virtual void v4();
  virtual int vf();
  void f(O_007f58b0* p);
};
void C_007f58b0::f(O_007f58b0* p) { ext_007f58b0(p, this); p->v = vf(); }


// @ 0x007fdf70
struct O_007fdf70 { int pad[3]; int v; };
void ext_007fdf70(O_007fdf70*, void*);
struct C_007fdf70 {
  virtual void v0();
  virtual void v1();
  virtual void v2();
  virtual void v3();
  virtual void v4();
  virtual int vf();
  void f(O_007fdf70* p);
};
void C_007fdf70::f(O_007fdf70* p) { ext_007fdf70(p, this); p->v = vf(); }


// @ 0x0081bcb0
struct O_0081bcb0 { int pad[3]; int v; };
void ext_0081bcb0(O_0081bcb0*, void*);
struct C_0081bcb0 {
  virtual void v0();
  virtual void v1();
  virtual void v2();
  virtual void v3();
  virtual void v4();
  virtual int vf();
  void f(O_0081bcb0* p);
};
void C_0081bcb0::f(O_0081bcb0* p) { ext_0081bcb0(p, this); p->v = vf(); }


// @ 0x0081cff0
struct O_0081cff0 { int pad[3]; int v; };
void ext_0081cff0(O_0081cff0*, void*);
struct C_0081cff0 {
  virtual void v0();
  virtual void v1();
  virtual void v2();
  virtual void v3();
  virtual void v4();
  virtual int vf();
  void f(O_0081cff0* p);
};
void C_0081cff0::f(O_0081cff0* p) { ext_0081cff0(p, this); p->v = vf(); }


// @ 0x008307e0
struct O_008307e0 { int pad[3]; int v; };
void ext_008307e0(O_008307e0*, void*);
struct C_008307e0 {
  virtual void v0();
  virtual void v1();
  virtual void v2();
  virtual void v3();
  virtual void v4();
  virtual int vf();
  void f(O_008307e0* p);
};
void C_008307e0::f(O_008307e0* p) { ext_008307e0(p, this); p->v = vf(); }

