// Generated by tools/matching/synth.py (template od_member_vec_size_shift). Do not edit by hand.

// @ 0x0044e800
struct E_0044e800 { char b[32]; };
struct V_0044e800 { E_0044e800* b; E_0044e800* e; int size() const { return (int)(e - b); } };
struct C_0044e800 { char pad[564]; V_0044e800 v; int FUN_0044e800(); };
int C_0044e800::FUN_0044e800() { return v.size(); }

// @ 0x00488a20
struct E_00488a20 { char b[4]; };
struct V_00488a20 { E_00488a20* b; E_00488a20* e; int size() const { return (int)(e - b); } };
struct C_00488a20 { char pad[44]; V_00488a20 v; int FUN_00488a20(); };
int C_00488a20::FUN_00488a20() { return v.size(); }

// @ 0x004accf0
struct E_004accf0 { char b[4]; };
struct V_004accf0 { E_004accf0* b; E_004accf0* e; int size() const { return (int)(e - b); } };
struct C_004accf0 { char pad[24]; V_004accf0 v; int FUN_004accf0(); };
int C_004accf0::FUN_004accf0() { return v.size(); }

// @ 0x004d9070
struct E_004d9070 { char b[4]; };
struct V_004d9070 { E_004d9070* b; E_004d9070* e; int size() const { return (int)(e - b); } };
struct C_004d9070 { char pad[2064]; V_004d9070 v; int FUN_004d9070(); };
int C_004d9070::FUN_004d9070() { return v.size(); }

// @ 0x005508e0
struct E_005508e0 { char b[16]; };
struct V_005508e0 { E_005508e0* b; E_005508e0* e; int size() const { return (int)(e - b); } };
struct C_005508e0 { char pad[152]; V_005508e0 v; int FUN_005508e0(); };
int C_005508e0::FUN_005508e0() { return v.size(); }

// @ 0x005509b0
struct E_005509b0 { char b[16]; };
struct V_005509b0 { E_005509b0* b; E_005509b0* e; int size() const { return (int)(e - b); } };
struct C_005509b0 { char pad[172]; V_005509b0 v; int FUN_005509b0(); };
int C_005509b0::FUN_005509b0() { return v.size(); }

// @ 0x00550a30
struct E_00550a30 { char b[4]; };
struct V_00550a30 { E_00550a30* b; E_00550a30* e; int size() const { return (int)(e - b); } };
struct C_00550a30 { char pad[192]; V_00550a30 v; int FUN_00550a30(); };
int C_00550a30::FUN_00550a30() { return v.size(); }
