// Generated by tools/matching/synth.py (template od_virtual_call_1arg). Do not edit by hand.

// @ 0x007fa910
struct C_007fa910 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int);
virtual void v14(int);
virtual void v15(int);
virtual void v16(int);
virtual void v17(int);
virtual void v18(int);
virtual void v19(int); };
void FUN_007fa910(C_007fa910* p, int a) { p->v19(a); }

// @ 0x007fa930
struct C_007fa930 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int);
virtual void v14(int);
virtual void v15(int);
virtual void v16(int);
virtual void v17(int);
virtual void v18(int);
virtual void v19(int);
virtual void v20(int); };
void FUN_007fa930(C_007fa930* p, int a) { p->v20(a); }

// @ 0x007fa970
struct C_007fa970 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int); };
void FUN_007fa970(C_007fa970* p, int a) { p->v13(a); }

// @ 0x007fa990
struct C_007fa990 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int);
virtual void v14(int); };
void FUN_007fa990(C_007fa990* p, int a) { p->v14(a); }

// @ 0x007fa9d0
struct C_007fa9d0 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int);
virtual void v14(int);
virtual void v15(int);
virtual void v16(int); };
void FUN_007fa9d0(C_007fa9d0* p, int a) { p->v16(a); }

// @ 0x007fa9f0
struct C_007fa9f0 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int);
virtual void v11(int);
virtual void v12(int);
virtual void v13(int);
virtual void v14(int);
virtual void v15(int);
virtual void v16(int);
virtual void v17(int); };
void FUN_007fa9f0(C_007fa9f0* p, int a) { p->v17(a); }

// @ 0x007fb070
struct C_007fb070 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int); };
void FUN_007fb070(C_007fb070* p, int a) { p->v7(a); }

// @ 0x007fb090
struct C_007fb090 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int); };
void FUN_007fb090(C_007fb090* p, int a) { p->v8(a); }

// @ 0x007fb1d0
struct C_007fb1d0 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int); };
void FUN_007fb1d0(C_007fb1d0* p, int a) { p->v9(a); }

// @ 0x007fb1f0
struct C_007fb1f0 { virtual void v0(int);
virtual void v1(int);
virtual void v2(int);
virtual void v3(int);
virtual void v4(int);
virtual void v5(int);
virtual void v6(int);
virtual void v7(int);
virtual void v8(int);
virtual void v9(int);
virtual void v10(int); };
void FUN_007fb1f0(C_007fb1f0* p, int a) { p->v10(a); }
