// Generated by tools/matching/synth.py (template or_two_member_vcalls). Do not edit by hand.

// @ 0x00a10a40
struct I_00a10a40 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {} virtual bool vf(int, int) { return false; } };
struct C_00a10a40 { char pad[12]; I_00a10a40* p1; I_00a10a40* p2;
  int f(int a, int b); };
int C_00a10a40::f(int a, int b) { I_00a10a40* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10a90
struct I_00a10a90 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {} virtual bool vf(int, int) { return false; } };
struct C_00a10a90 { char pad[12]; I_00a10a90* p1; I_00a10a90* p2;
  int f(int a, int b); };
int C_00a10a90::f(int a, int b) { I_00a10a90* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10ae0
struct I_00a10ae0 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {} virtual bool vf(int, int) { return false; } };
struct C_00a10ae0 { char pad[12]; I_00a10ae0* p1; I_00a10ae0* p2;
  int f(int a, int b); };
int C_00a10ae0::f(int a, int b) { I_00a10ae0* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10b30
struct I_00a10b30 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {}
virtual void v9() {} virtual bool vf(int, int) { return false; } };
struct C_00a10b30 { char pad[12]; I_00a10b30* p1; I_00a10b30* p2;
  int f(int a, int b); };
int C_00a10b30::f(int a, int b) { I_00a10b30* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10b80
struct I_00a10b80 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {}
virtual void v9() {}
virtual void v10() {} virtual bool vf(int, int) { return false; } };
struct C_00a10b80 { char pad[12]; I_00a10b80* p1; I_00a10b80* p2;
  int f(int a, int b); };
int C_00a10b80::f(int a, int b) { I_00a10b80* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10bd0
struct I_00a10bd0 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {}
virtual void v9() {}
virtual void v10() {}
virtual void v11() {} virtual bool vf(int, int) { return false; } };
struct C_00a10bd0 { char pad[12]; I_00a10bd0* p1; I_00a10bd0* p2;
  int f(int a, int b); };
int C_00a10bd0::f(int a, int b) { I_00a10bd0* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10c20
struct I_00a10c20 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {}
virtual void v9() {}
virtual void v10() {}
virtual void v11() {}
virtual void v12() {} virtual bool vf(int, int) { return false; } };
struct C_00a10c20 { char pad[12]; I_00a10c20* p1; I_00a10c20* p2;
  int f(int a, int b); };
int C_00a10c20::f(int a, int b) { I_00a10c20* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }


// @ 0x00a10c70
struct I_00a10c70 { virtual void v0() {}
virtual void v1() {}
virtual void v2() {}
virtual void v3() {}
virtual void v4() {}
virtual void v5() {}
virtual void v6() {}
virtual void v7() {}
virtual void v8() {}
virtual void v9() {}
virtual void v10() {}
virtual void v11() {}
virtual void v12() {}
virtual void v13() {} virtual bool vf(int, int) { return false; } };
struct C_00a10c70 { char pad[12]; I_00a10c70* p1; I_00a10c70* p2;
  int f(int a, int b); };
int C_00a10c70::f(int a, int b) { I_00a10c70* x; return ((x = p1) && x->vf(a, b)) || ((x = p2) && x->vf(a, b)); }

