// Generated by tools/matching/synth.py (template pair_float_setter). Do not edit by hand.
struct Obj { char pad[0x400]; };
struct PairP { Obj* a; Obj* b; };
extern PairP Helper(int, int);

// @ 0x009ffe80
struct O009ffe80 { char pad[140]; float f; };
struct P009ffe80 { O009ffe80* a; O009ffe80* b; };
extern void H009ffe80(P009ffe80*, int, int);
int FUN_009ffe80(int a, int b, float v) {
    P009ffe80 p;
    H009ffe80(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x009ffee0
struct O009ffee0 { char pad[160]; float f; };
struct P009ffee0 { O009ffee0* a; O009ffee0* b; };
extern void H009ffee0(P009ffee0*, int, int);
int FUN_009ffee0(int a, int b, float v) {
    P009ffee0 p;
    H009ffee0(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x009fff40
struct O009fff40 { char pad[112]; float f; };
struct P009fff40 { O009fff40* a; O009fff40* b; };
extern void H009fff40(P009fff40*, int, int);
int FUN_009fff40(int a, int b, float v) {
    P009fff40 p;
    H009fff40(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x009fff90
struct O009fff90 { char pad[116]; float f; };
struct P009fff90 { O009fff90* a; O009fff90* b; };
extern void H009fff90(P009fff90*, int, int);
int FUN_009fff90(int a, int b, float v) {
    P009fff90 p;
    H009fff90(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x009fffe0
struct O009fffe0 { char pad[120]; float f; };
struct P009fffe0 { O009fffe0* a; O009fffe0* b; };
extern void H009fffe0(P009fffe0*, int, int);
int FUN_009fffe0(int a, int b, float v) {
    P009fffe0 p;
    H009fffe0(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x00a000d0
struct O00a000d0 { char pad[200]; float f; };
struct P00a000d0 { O00a000d0* a; O00a000d0* b; };
extern void H00a000d0(P00a000d0*, int, int);
int FUN_00a000d0(int a, int b, float v) {
    P00a000d0 p;
    H00a000d0(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}

// @ 0x00a00290
struct O00a00290 { char pad[136]; float f; };
struct P00a00290 { O00a00290* a; O00a00290* b; };
extern void H00a00290(P00a00290*, int, int);
int FUN_00a00290(int a, int b, float v) {
    P00a00290 p;
    H00a00290(&p, a, b);
    if (p.a) p.a->f = v;
    if (p.b) p.b->f = v;
    if (!p.a && !p.b) return 0;
    return 1;
}
