// Generated by tools/matching/synth.py (template pre_increment_member_getter). Do not edit by hand.

// @ 0x00688d10
struct S_00688d10 { char pad[24]; int v; int f(); };
int S_00688d10::f() { return ++v; }

// @ 0x006e54c0
struct S_006e54c0 { char pad[60]; int v; int f(); };
int S_006e54c0::f() { return ++v; }

// @ 0x007e5e70
struct S_007e5e70 { char pad[352]; int v; int f(); };
int S_007e5e70::f() { return ++v; }

// @ 0x0083f5d0
struct S_0083f5d0 { char pad[8]; int v; int f(); };
int S_0083f5d0::f() { return ++v; }

// @ 0x00923490
struct S_00923490 { char pad[16]; int v; int f(); };
int S_00923490::f() { return ++v; }

// @ 0x00928e10
struct S_00928e10 { char pad[1072]; int v; int f(); };
int S_00928e10::f() { return ++v; }

// @ 0x009317b0
struct S_009317b0 { char pad[528]; int v; int f(); };
int S_009317b0::f() { return ++v; }

// @ 0x0093c3e0
struct S_0093c3e0 { char pad[4]; int v; int f(); };
int S_0093c3e0::f() { return ++v; }

// @ 0x00951490
struct S_00951490 { char pad[28]; int v; int f(); };
int S_00951490::f() { return ++v; }

// @ 0x0099c660
struct S_0099c660 { char pad[276]; int v; int f(); };
int S_0099c660::f() { return ++v; }

// @ 0x0099c970
struct S_0099c970 { char pad[220]; int v; int f(); };
int S_0099c970::f() { return ++v; }

// @ 0x0099c980
struct S_0099c980 { char pad[48]; int v; int f(); };
int S_0099c980::f() { return ++v; }

// @ 0x009ac2a0
struct S_009ac2a0 { char pad[272]; int v; int f(); };
int S_009ac2a0::f() { return ++v; }

// @ 0x009b3450
struct S_009b3450 { char pad[840]; int v; int f(); };
int S_009b3450::f() { return ++v; }

// @ 0x00a02c30
struct S_00a02c30 { char pad[408]; int v; int f(); };
int S_00a02c30::f() { return ++v; }

// @ 0x00a17060
struct S_00a17060 { char pad[20]; int v; int f(); };
int S_00a17060::f() { return ++v; }
