// Generated by tools/matching/synth.py (template range_ctor_lt_stdcall). Do not edit by hand.

// @ 0x0060e910
struct S_0060e910 { char d[0x70]; void f(); };
void __stdcall FUN_0060e910(S_0060e910* first, S_0060e910* last) {
    for (; first < last; ++first) first->f();
}


// @ 0x00717930
struct S_00717930 { char d[0x8c]; void f(); };
void __stdcall FUN_00717930(S_00717930* first, S_00717930* last) {
    for (; first < last; ++first) first->f();
}


// @ 0x007c9b90
struct S_007c9b90 { char d[0x18]; void f(); };
void __stdcall FUN_007c9b90(S_007c9b90* first, S_007c9b90* last) {
    for (; first < last; ++first) first->f();
}


// @ 0x007e2be0
struct S_007e2be0 { char d[0x24]; void f(); };
void __stdcall FUN_007e2be0(S_007e2be0* first, S_007e2be0* last) {
    for (; first < last; ++first) first->f();
}


// @ 0x00dfc660
struct S_00dfc660 { char d[0x4e0]; void f(); };
void __stdcall FUN_00dfc660(S_00dfc660* first, S_00dfc660* last) {
    for (; first < last; ++first) first->f();
}

