// Generated by tools/matching/synth.py (template range_erase_vcall_stride). Do not edit by hand.

// @ 0x0075fc00
struct I_0075fc00 { virtual void v0(); virtual void v1(); };
struct T_0075fc00 { I_0075fc00* p; char pad[16]; };
T_0075fc00* H_0075fc00(T_0075fc00*, T_0075fc00*, T_0075fc00*);
inline void destroy_0075fc00(T_0075fc00* a, T_0075fc00* b) { for (; a < b; ++a) if (a->p) a->p->v1(); }
struct S_0075fc00 { int a; T_0075fc00* e; T_0075fc00* end() { return e; } T_0075fc00* FUN_0075fc00(T_0075fc00* f, T_0075fc00* l); };
T_0075fc00* S_0075fc00::FUN_0075fc00(T_0075fc00* f, T_0075fc00* l) { T_0075fc00* p = H_0075fc00(l, end(), f); destroy_0075fc00(p, end());
  e -= (l - f); return f; }

// @ 0x007823b0
struct I_007823b0 { virtual void v0(); virtual void v1(); };
struct T_007823b0 { I_007823b0* p; char pad[8]; };
T_007823b0* H_007823b0(T_007823b0*, T_007823b0*, T_007823b0*);
inline void destroy_007823b0(T_007823b0* a, T_007823b0* b) { for (; a < b; ++a) if (a->p) a->p->v1(); }
struct S_007823b0 { int a; T_007823b0* e; T_007823b0* end() { return e; } T_007823b0* FUN_007823b0(T_007823b0* f, T_007823b0* l); };
T_007823b0* S_007823b0::FUN_007823b0(T_007823b0* f, T_007823b0* l) { T_007823b0* p = H_007823b0(l, end(), f); destroy_007823b0(p, end());
  e -= (l - f); return f; }

// @ 0x00c58590
struct I_00c58590 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); virtual void v15(); virtual void v16(); virtual void v17(); virtual void v18(); virtual void v19(); virtual void v20(); virtual void v21(); virtual void v22(); virtual void v23(); virtual void v24(); virtual void v25(); virtual void v26(); virtual void v27(); virtual void v28(); virtual void v29(); virtual void v30(); virtual void v31(); virtual void v32(); virtual void v33(); virtual void v34(); virtual void v35(); virtual void v36(); virtual void v37(); virtual void v38(); virtual void v39(); virtual void v40(); virtual void v41(); virtual void v42(); virtual void v43(); virtual void v44(); virtual void v45(); virtual void v46(); virtual void v47(); virtual void v48(); };
struct T_00c58590 { I_00c58590* p; char pad[8]; };
T_00c58590* H_00c58590(T_00c58590*, T_00c58590*, T_00c58590*);
inline void destroy_00c58590(T_00c58590* a, T_00c58590* b) { for (; a < b; ++a) if (a->p) a->p->v48(); }
struct S_00c58590 { int a; T_00c58590* e; T_00c58590* end() { return e; } T_00c58590* FUN_00c58590(T_00c58590* f, T_00c58590* l); };
T_00c58590* S_00c58590::FUN_00c58590(T_00c58590* f, T_00c58590* l) { T_00c58590* p = H_00c58590(l, end(), f); destroy_00c58590(p, end());
  e -= (l - f); return f; }

// @ 0x00c58770
struct I_00c58770 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); virtual void v15(); virtual void v16(); virtual void v17(); virtual void v18(); virtual void v19(); virtual void v20(); virtual void v21(); virtual void v22(); virtual void v23(); virtual void v24(); virtual void v25(); virtual void v26(); virtual void v27(); virtual void v28(); virtual void v29(); virtual void v30(); virtual void v31(); virtual void v32(); virtual void v33(); virtual void v34(); virtual void v35(); virtual void v36(); virtual void v37(); virtual void v38(); virtual void v39(); virtual void v40(); virtual void v41(); virtual void v42(); virtual void v43(); virtual void v44(); virtual void v45(); virtual void v46(); virtual void v47(); virtual void v48(); };
struct T_00c58770 { I_00c58770* p; char pad[16]; };
T_00c58770* H_00c58770(T_00c58770*, T_00c58770*, T_00c58770*);
inline void destroy_00c58770(T_00c58770* a, T_00c58770* b) { for (; a < b; ++a) if (a->p) a->p->v48(); }
struct S_00c58770 { int a; T_00c58770* e; T_00c58770* end() { return e; } T_00c58770* FUN_00c58770(T_00c58770* f, T_00c58770* l); };
T_00c58770* S_00c58770::FUN_00c58770(T_00c58770* f, T_00c58770* l) { T_00c58770* p = H_00c58770(l, end(), f); destroy_00c58770(p, end());
  e -= (l - f); return f; }

// @ 0x010799f0
struct I_010799f0 { virtual void v0(); virtual void v1(); virtual void v2(); };
struct T_010799f0 { I_010799f0* p; char pad[8]; };
T_010799f0* H_010799f0(T_010799f0*, T_010799f0*, T_010799f0*);
inline void destroy_010799f0(T_010799f0* a, T_010799f0* b) { for (; a < b; ++a) if (a->p) a->p->v2(); }
struct S_010799f0 { int a; T_010799f0* e; T_010799f0* end() { return e; } T_010799f0* FUN_010799f0(T_010799f0* f, T_010799f0* l); };
T_010799f0* S_010799f0::FUN_010799f0(T_010799f0* f, T_010799f0* l) { T_010799f0* p = H_010799f0(l, end(), f); destroy_010799f0(p, end());
  e -= (l - f); return f; }
