// Generated by tools/matching/synth.py (template rbtree_wstr_insert_key). Do not edit by hand.
struct S { wchar_t* b; wchar_t* e; wchar_t* c; };
struct Node { Node* right; Node* left; Node* parent; int color; S key; };
struct It { Node* p; };
struct R { Node* p; bool b; };
template<class T> __forceinline const T& mn(const T& a, const T& b) { return (b < a) ? b : a; }
static __forceinline int cmpi(const wchar_t* p, const wchar_t* q, unsigned n) {
  for (; n > 0; --n) { if (*p != *q) return *p < *q ? -1 : 1; ++p; ++q; }
  return 0;
}
static __forceinline bool lessf(const S& a, const S& b) {
  int la = (int)(a.e - a.b), lb = (int)(b.e - b.b);
  int r = cmpi(a.b, b.b, mn(la, lb));
  if (!r) r = (la < lb) ? -1 : (la > lb);
  return r < 0;
}

// @ 0x005e9b10
struct T_005e9b10 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_005e9b10(Node*);
int __cdecl cmpf_005e9b10(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_005e9b10::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_005e9b10(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_005e9b10(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}

// @ 0x005e9de0
struct T_005e9de0 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_005e9de0(Node*);
int __cdecl cmpf_005e9de0(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_005e9de0::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_005e9de0(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_005e9de0(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}

// @ 0x00614f20
struct T_00614f20 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_00614f20(Node*);
int __cdecl cmpf_00614f20(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_00614f20::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_00614f20(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_00614f20(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}

// @ 0x0087fbe0
struct T_0087fbe0 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_0087fbe0(Node*);
int __cdecl cmpf_0087fbe0(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_0087fbe0::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_0087fbe0(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_0087fbe0(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}

// @ 0x008d69f0
struct T_008d69f0 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_008d69f0(Node*);
int __cdecl cmpf_008d69f0(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_008d69f0::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_008d69f0(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_008d69f0(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}

// @ 0x00934260
struct T_00934260 {
  int cmp; Node* aRight; Node* aLeft; Node* aParent;
  It __thiscall ins(Node* parent, const S& key, bool);
  R __thiscall K(const S& key, bool);
};
Node* __cdecl dec_00934260(Node*);
int __cdecl cmpf_00934260(const wchar_t*, const wchar_t*, const wchar_t*, const wchar_t*);
R T_00934260::K(const S& key, bool) {
  Node* lb = (Node*)&aRight; Node* cur = aParent; bool less = true;
  while (cur) { less = lessf(key, cur->key); lb = cur; cur = less ? cur->left : cur->right; }
  Node* par = lb;
  R r;
  if (less) {
    if (lb != aLeft) lb = dec_00934260(lb);
    else { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  }
  if (cmpf_00934260(lb->key.b, lb->key.e, key.b, key.e) < 0) { It i = ins(par, key, false); r.p = i.p; r.b = true; return r; }
  r.p = lb; r.b = false; return r;
}
