// Generated by tools/matching/synth.py (template rbtree_insert_unique_key3_acb_partial_inline). Do not edit by hand.

namespace eastl {
struct true_type {};
struct nb { nb* r; nb* l; nb* p; char c; };
nb* RBTreeDecrement(const nb* n);
void __cdecl RBTreeInsert(nb* n, nb* parent, nb* anchor, int side);
struct K3 { unsigned a, b, c; };
struct node3 : nb { K3 v; };
struct iter3 { node3* n; iter3(node3* p) : n(p) {} };
struct pair_ib { iter3 first; bool second; pair_ib(const iter3& a, bool b) : first(a), second(b) {} };
inline bool Less(const K3& x, const K3& y) { if (x.a != y.a) return x.a < y.a; if (x.c != y.c) return x.c < y.c; return x.b < y.b; }
}
#define RBT3(T) \
struct T { \
    int cmp; eastl::nb anchor; unsigned size; \
    eastl::node3* Create(const eastl::K3& v); \
    eastl::iter3 Impl(eastl::nb* parent, const eastl::K3& v, bool left); \
    eastl::pair_ib Ins(const eastl::K3& v, eastl::true_type); \
}; \
eastl::pair_ib T::Ins(const eastl::K3& value, eastl::true_type) \
{ \
    using namespace eastl; \
    node3* cur = (node3*)anchor.p; \
    node3* lb = (node3*)&anchor; \
    bool lt = true; \
    while(cur) { lt = Less(value, cur->v); lb = cur; if(lt) cur = (node3*)cur->l; else cur = (node3*)cur->r; } \
    node3* parent = lb; \
    if(lt) { \
        if(lb != (node3*)anchor.l) lb = (node3*)RBTreeDecrement(lb); \
        else { const iter3 it(Impl(lb, value, false)); return pair_ib(it, true); } \
    } \
    if(Less(lb->v, value)) { \
        int side = (parent == (node3*)&anchor || Less(value, parent->v)) ? 0 : 1; \
        node3* nn = Create(value); \
        RBTreeInsert(nn, parent, &anchor, side); \
        ++size; \
        return pair_ib(iter3(nn), true); \
    } \
    return pair_ib(iter3(lb), false); \
}

// @ 0x00642b00
RBT3(Tree_00642b00)

// @ 0x006ae770
RBT3(Tree_006ae770)

// @ 0x00a2b120
RBT3(Tree_00a2b120)

// @ 0x00b8fc80
RBT3(Tree_00b8fc80)

// @ 0x00de5f60
RBT3(Tree_00de5f60)
