// Generated by tools/matching/synth.py (template rbtree_insert_value_key3_acb_cmp). Do not edit by hand.
struct It { void* p; It(void* q) : p(q) {} It(const It& o) : p(o.p) {} };
struct K3 { unsigned a, b, c; };
inline bool K3Less(const K3& x, const K3& y) { if (x.a != y.a) return x.a < y.a; if (x.c != y.c) return x.c < y.c; return x.b < y.b; }

// @ 0x00642a30
void __cdecl ins_00642a30(char*, char*, char*, int);
struct T_00642a30 { int cmp; char anchor[16]; unsigned sz;
  char* Create(const K3*);
  It Impl(char* parent, const K3* value, bool force);
};
It T_00642a30::Impl(char* parent, const K3* value, bool force) {
    int side = (!force && parent != anchor && !K3Less(*value, *(K3*)(parent + 0x10))) ? 1 : 0;
    char* node = Create(value);
    ins_00642a30(node, parent, anchor, side);
    ++sz; return It(node); }


// @ 0x006ae700
void __cdecl ins_006ae700(char*, char*, char*, int);
struct T_006ae700 { int cmp; char anchor[16]; unsigned sz;
  char* Create(const K3*);
  It Impl(char* parent, const K3* value, bool force);
};
It T_006ae700::Impl(char* parent, const K3* value, bool force) {
    int side = (!force && parent != anchor && !K3Less(*value, *(K3*)(parent + 0x10))) ? 1 : 0;
    char* node = Create(value);
    ins_006ae700(node, parent, anchor, side);
    ++sz; return It(node); }


// @ 0x00a27d90
void __cdecl ins_00a27d90(char*, char*, char*, int);
struct T_00a27d90 { int cmp; char anchor[16]; unsigned sz;
  char* Create(const K3*);
  It Impl(char* parent, const K3* value, bool force);
};
It T_00a27d90::Impl(char* parent, const K3* value, bool force) {
    int side = (!force && parent != anchor && !K3Less(*value, *(K3*)(parent + 0x10))) ? 1 : 0;
    char* node = Create(value);
    ins_00a27d90(node, parent, anchor, side);
    ++sz; return It(node); }


// @ 0x00b8fc10
void __cdecl ins_00b8fc10(char*, char*, char*, int);
struct T_00b8fc10 { int cmp; char anchor[16]; unsigned sz;
  char* Create(const K3*);
  It Impl(char* parent, const K3* value, bool force);
};
It T_00b8fc10::Impl(char* parent, const K3* value, bool force) {
    int side = (!force && parent != anchor && !K3Less(*value, *(K3*)(parent + 0x10))) ? 1 : 0;
    char* node = Create(value);
    ins_00b8fc10(node, parent, anchor, side);
    ++sz; return It(node); }


// @ 0x00de5740
void __cdecl ins_00de5740(char*, char*, char*, int);
struct T_00de5740 { int cmp; char anchor[16]; unsigned sz;
  char* Create(const K3*);
  It Impl(char* parent, const K3* value, bool force);
};
It T_00de5740::Impl(char* parent, const K3* value, bool force) {
    int side = (!force && parent != anchor && !K3Less(*value, *(K3*)(parent + 0x10))) ? 1 : 0;
    char* node = Create(value);
    ins_00de5740(node, parent, anchor, side);
    ++sz; return It(node); }

