// Generated by tools/matching/synth.py (template ret_true_stdcall_n). Do not edit by hand.

// @ 0x005a9bb0
bool __stdcall FUN_005a9bb0(int, int, int, int) { return true; }

// @ 0x005ac970
bool __stdcall FUN_005ac970(int, int, int) { return true; }

// @ 0x0088a280
bool __stdcall FUN_0088a280(int, int) { return true; }

// @ 0x00b7d400
bool __stdcall FUN_00b7d400(int) { return true; }

// @ 0x00e21b20
bool __stdcall FUN_00e21b20(int, int, int, int, int) { return true; }
