// Generated by tools/matching/synth.py (template scalar_deldtor_base_ext). Do not edit by hand.
struct Base { Base(); virtual ~Base(); };

// @ 0x00634610
struct C_00634610 : Base { C_00634610(); virtual ~C_00634610() {} };
C_00634610::C_00634610() {}

// @ 0x00925f60
struct C_00925f60 : Base { C_00925f60(); virtual ~C_00925f60() {} };
C_00925f60::C_00925f60() {}

// @ 0x00b33f10
struct C_00b33f10 : Base { C_00b33f10(); virtual ~C_00b33f10() {} };
C_00b33f10::C_00b33f10() {}

// @ 0x00b5cd10
struct C_00b5cd10 : Base { C_00b5cd10(); virtual ~C_00b5cd10() {} };
C_00b5cd10::C_00b5cd10() {}

// @ 0x00b5cd60
struct C_00b5cd60 : Base { C_00b5cd60(); virtual ~C_00b5cd60() {} };
C_00b5cd60::C_00b5cd60() {}

// @ 0x00b63980
struct C_00b63980 : Base { C_00b63980(); virtual ~C_00b63980() {} };
C_00b63980::C_00b63980() {}

// @ 0x00ba68c0
struct C_00ba68c0 : Base { C_00ba68c0(); virtual ~C_00ba68c0() {} };
C_00ba68c0::C_00ba68c0() {}

// @ 0x00c69850
struct C_00c69850 : Base { C_00c69850(); virtual ~C_00c69850() {} };
C_00c69850::C_00c69850() {}

// @ 0x00ce6630
struct C_00ce6630 : Base { C_00ce6630(); virtual ~C_00ce6630() {} };
C_00ce6630::C_00ce6630() {}

// @ 0x00cee0a0
struct C_00cee0a0 : Base { C_00cee0a0(); virtual ~C_00cee0a0() {} };
C_00cee0a0::C_00cee0a0() {}

// @ 0x00cee0d0
struct C_00cee0d0 : Base { C_00cee0d0(); virtual ~C_00cee0d0() {} };
C_00cee0d0::C_00cee0d0() {}

// @ 0x00cee100
struct C_00cee100 : Base { C_00cee100(); virtual ~C_00cee100() {} };
C_00cee100::C_00cee100() {}

// @ 0x00cfe750
struct C_00cfe750 : Base { C_00cfe750(); virtual ~C_00cfe750() {} };
C_00cfe750::C_00cfe750() {}

// @ 0x00d07a80
struct C_00d07a80 : Base { C_00d07a80(); virtual ~C_00d07a80() {} };
C_00d07a80::C_00d07a80() {}

// @ 0x00d144a0
struct C_00d144a0 : Base { C_00d144a0(); virtual ~C_00d144a0() {} };
C_00d144a0::C_00d144a0() {}

// @ 0x00d15060
struct C_00d15060 : Base { C_00d15060(); virtual ~C_00d15060() {} };
C_00d15060::C_00d15060() {}

// @ 0x00d48720
struct C_00d48720 : Base { C_00d48720(); virtual ~C_00d48720() {} };
C_00d48720::C_00d48720() {}

// @ 0x00e8cd00
struct C_00e8cd00 : Base { C_00e8cd00(); virtual ~C_00e8cd00() {} };
C_00e8cd00::C_00e8cd00() {}

// @ 0x00e8df20
struct C_00e8df20 : Base { C_00e8df20(); virtual ~C_00e8df20() {} };
C_00e8df20::C_00e8df20() {}

// @ 0x00e8e0a0
struct C_00e8e0a0 : Base { C_00e8e0a0(); virtual ~C_00e8e0a0() {} };
C_00e8e0a0::C_00e8e0a0() {}

// @ 0x00e8f1c0
struct C_00e8f1c0 : Base { C_00e8f1c0(); virtual ~C_00e8f1c0() {} };
C_00e8f1c0::C_00e8f1c0() {}

// @ 0x00e8f390
struct C_00e8f390 : Base { C_00e8f390(); virtual ~C_00e8f390() {} };
C_00e8f390::C_00e8f390() {}

// @ 0x00e8f520
struct C_00e8f520 : Base { C_00e8f520(); virtual ~C_00e8f520() {} };
C_00e8f520::C_00e8f520() {}

// @ 0x00e90bb0
struct C_00e90bb0 : Base { C_00e90bb0(); virtual ~C_00e90bb0() {} };
C_00e90bb0::C_00e90bb0() {}

// @ 0x00e90d50
struct C_00e90d50 : Base { C_00e90d50(); virtual ~C_00e90d50() {} };
C_00e90d50::C_00e90d50() {}

// @ 0x00e90dd0
struct C_00e90dd0 : Base { C_00e90dd0(); virtual ~C_00e90dd0() {} };
C_00e90dd0::C_00e90dd0() {}

// @ 0x00f47520
struct C_00f47520 : Base { C_00f47520(); virtual ~C_00f47520() {} };
C_00f47520::C_00f47520() {}

// @ 0x00ff5c20
struct C_00ff5c20 : Base { C_00ff5c20(); virtual ~C_00ff5c20() {} };
C_00ff5c20::C_00ff5c20() {}

// @ 0x01066360
struct C_01066360 : Base { C_01066360(); virtual ~C_01066360() {} };
C_01066360::C_01066360() {}

// @ 0x0107da70
struct C_0107da70 : Base { C_0107da70(); virtual ~C_0107da70() {} };
C_0107da70::C_0107da70() {}

// @ 0x01149fa0
struct C_01149fa0 : Base { C_01149fa0(); virtual ~C_01149fa0() {} };
C_01149fa0::C_01149fa0() {}
