// Generated by tools/matching/synth.py (template scalar_deleting_dtor_od). Do not edit by hand.
void EASTL_allocator_deallocate(void* p);

// @ 0x00457810
struct C_00457810 { void D(); void* F(unsigned f); };
void* C_00457810::F(unsigned f) {
  char pad[36];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x004612b0
struct C_004612b0 { void D(); void* F(unsigned f); };
void* C_004612b0::F(unsigned f) {
  char pad[44];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x00469760
struct C_00469760 { void D(); void* F(unsigned f); };
void* C_00469760::F(unsigned f) {
  char pad[48];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x00472a70
struct C_00472a70 { void D(); void* F(unsigned f); };
void* C_00472a70::F(unsigned f) {
  char pad[16];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x004b25b0
struct C_004b25b0 { void D(); void* F(unsigned f); };
void* C_004b25b0::F(unsigned f) {
  char pad[40];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x0051cfe0
struct C_0051cfe0 { void D(); void* F(unsigned f); };
void* C_0051cfe0::F(unsigned f) {
  char pad[40];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x0052eb10
struct C_0052eb10 { void D(); void* F(unsigned f); };
void* C_0052eb10::F(unsigned f) {
  char pad[32];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x0052fad0
struct C_0052fad0 { void D(); void* F(unsigned f); };
void* C_0052fad0::F(unsigned f) {
  char pad[48];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x00535b00
struct C_00535b00 { void D(); void* F(unsigned f); };
void* C_00535b00::F(unsigned f) {
  char pad[28];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x00538150
struct C_00538150 { void D(); void* F(unsigned f); };
void* C_00538150::F(unsigned f) {
  char pad[4];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x005382f0
struct C_005382f0 { void D(); void* F(unsigned f); };
void* C_005382f0::F(unsigned f) {
  char pad[56];
  char pad2[16];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x0053a1f0
struct C_0053a1f0 { void D(); void* F(unsigned f); };
void* C_0053a1f0::F(unsigned f) {
  char pad[16];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x0054dec0
struct C_0054dec0 { void D(); void* F(unsigned f); };
void* C_0054dec0::F(unsigned f) {
  char pad[64];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}

// @ 0x00561180
struct C_00561180 { void D(); void* F(unsigned f); };
void* C_00561180::F(unsigned f) {
  char pad[16];
  D();
  if (f & 1) EASTL_allocator_deallocate(this);
  return this;
}
