// Generated by tools/matching/synth.py (template serializable_write_scope_bool_chain). Do not edit by hand.

struct R { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void *v6(); };
struct S { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual R *v8(); };
struct Sub { bool Q(S *s); };
void __cdecl FUN_0093aa70(void *r, void *b, int one, int zero);

// @ 0x00bcbad0
struct Buf_00bcbad0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00bcbad0 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00bcbad0::W(S *s) {
    Buf_00bcbad0 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x61494bd;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x156d600, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00bfe0f0
struct Buf_00bfe0f0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00bfe0f0 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00bfe0f0::W(S *s) {
    Buf_00bfe0f0 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x403df5f;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x1570a60, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00c3e3b0
struct Buf_00c3e3b0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00c3e3b0 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00c3e3b0::W(S *s) {
    Buf_00c3e3b0 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0xaeb336b4;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x1573a60, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00c69c60
struct Buf_00c69c60 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00c69c60 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00c69c60::W(S *s) {
    Buf_00c69c60 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x1b92b27;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x1577a98, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00c6f990
struct Buf_00c6f990 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00c6f990 { char pad[112]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00c6f990::W(S *s) {
    Buf_00c6f990 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x175cdc9;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x1578698, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00c8d330
struct Buf_00c8d330 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00c8d330 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00c8d330::W(S *s) {
    Buf_00c8d330 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x55cf8e3;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x157a9e0, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00c9bc00
struct Buf_00c9bc00 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00c9bc00 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00c9bc00::W(S *s) {
    Buf_00c9bc00 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x629baec;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x157c320, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00eac360
struct Buf_00eac360 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00eac360 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00eac360::W(S *s) {
    Buf_00eac360 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x74e0069;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x15a912c, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}

// @ 0x00f0d6e0
struct Buf_00f0d6e0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); bool H(S *s); };
struct C_00f0d6e0 { char pad[52]; Sub sub; bool P(S *s); bool W(S *s); };
bool C_00f0d6e0::W(S *s) {
    Buf_00f0d6e0 b; unsigned int key[1];
    R *r = s->v8();
    key[0] = 0x7b38ba7;
    void *t = r->v6();
    FUN_0093aa70(t, key, 1, 0);
    bool ok = P(s) && sub.Q(s);
    b.G(this, 0x15ad5ac, 0x1a80d26);
    if (ok) { if (b.H(s)) return true; }
    return false;
}
