// Generated by tools/matching/synth.py (template serializable_write_scope_base_member_calls). Do not edit by hand.

struct R { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void *v6(); };
struct S { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual R *v8(); };
struct Sub { void X(S *s); };
void __cdecl FUN_0093aa70(void *r, void *b, int one, int zero);

// @ 0x00cb3940
struct Buf_00cb3940 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb3940 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb3940::W(S *s) {
    Buf_00cb3940 b; unsigned int key;
    R *r = s->v8();
    key = 0x240e3b7;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157d7d8, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb3b70
struct Buf_00cb3b70 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb3b70 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb3b70::W(S *s) {
    Buf_00cb3b70 b; unsigned int key;
    R *r = s->v8();
    key = 0x244d3c0;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157dd7c, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb3d20
struct Buf_00cb3d20 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb3d20 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb3d20::W(S *s) {
    Buf_00cb3d20 b; unsigned int key;
    R *r = s->v8();
    key = 0x24630ce;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157ddb8, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb3e90
struct Buf_00cb3e90 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb3e90 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb3e90::W(S *s) {
    Buf_00cb3e90 b; unsigned int key;
    R *r = s->v8();
    key = 0x4167194;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157e358, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb41c0
struct Buf_00cb41c0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb41c0 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb41c0::W(S *s) {
    Buf_00cb41c0 b; unsigned int key;
    R *r = s->v8();
    key = 0x4f76f08;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157e578, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb4350
struct Buf_00cb4350 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb4350 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb4350::W(S *s) {
    Buf_00cb4350 b; unsigned int key;
    R *r = s->v8();
    key = 0x5776a28;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157e758, 0x1a80d26);
    b.H(s);
}

// @ 0x00cb44b0
struct Buf_00cb44b0 { unsigned int d[645]; void G(void *o, unsigned a, unsigned b); void H(S *s); };
struct C_00cb44b0 { char pad[0x34]; Sub sub; void P(S *s); void W(S *s); };
void C_00cb44b0::W(S *s) {
    Buf_00cb44b0 b; unsigned int key;
    R *r = s->v8();
    key = 0x49cec5c;
    void *t = r->v6();
    FUN_0093aa70(t, (void*)&key, 1, 0);
    P(s);
    sub.X(s);
    b.G(this, 0x157e888, 0x1a80d26);
    b.H(s);
}
