// Generated by tools/matching/synth.py (template set_flag_mask_vcall). Do not edit by hand.

// @ 0x00963fa0
struct C_00963fa0 {
  virtual void s0(unsigned);
  virtual void s1(unsigned);
  virtual void s2(unsigned);
  virtual void s3(unsigned);
  virtual void s4(unsigned);
  virtual void s5(unsigned);
  virtual void s6(unsigned);
  virtual void s7(unsigned);
  virtual void s8(unsigned);
  virtual void s9(unsigned);
  virtual void s10(unsigned);
  virtual void s11(unsigned);
  virtual void s12(unsigned);
  unsigned pad[2];
  unsigned fld;
  void f_00963fa0(unsigned m, bool on);
};
void C_00963fa0::f_00963fa0(unsigned m, bool on) {
  unsigned x = fld; if (on) x |= m; else x &= ~m; s12(x);
}


// @ 0x00967a90
struct C_00967a90 {
  virtual void s0(unsigned);
  virtual void s1(unsigned);
  virtual void s2(unsigned);
  virtual void s3(unsigned);
  virtual void s4(unsigned);
  virtual void s5(unsigned);
  virtual void s6(unsigned);
  unsigned pad[11];
  unsigned fld;
  void f_00967a90(unsigned m, bool on);
};
void C_00967a90::f_00967a90(unsigned m, bool on) {
  unsigned x = fld; if (on) x |= m; else x &= ~m; s6(x);
}


// @ 0x0096b430
struct C_0096b430 {
  virtual void s0(unsigned);
  virtual void s1(unsigned);
  virtual void s2(unsigned);
  virtual void s3(unsigned);
  virtual void s4(unsigned);
  virtual void s5(unsigned);
  virtual void s6(unsigned);
  unsigned pad[1];
  unsigned fld;
  void f_0096b430(unsigned m, bool on);
};
void C_0096b430::f_0096b430(unsigned m, bool on) {
  unsigned x = fld; if (on) x |= m; else x &= ~m; s6(x);
}


// @ 0x009705d0
struct C_009705d0 {
  virtual void s0(unsigned);
  virtual void s1(unsigned);
  virtual void s2(unsigned);
  virtual void s3(unsigned);
  virtual void s4(unsigned);
  virtual void s5(unsigned);
  virtual void s6(unsigned);
  virtual void s7(unsigned);
  virtual void s8(unsigned);
  virtual void s9(unsigned);
  virtual void s10(unsigned);
  unsigned fld;
  void f_009705d0(unsigned m, bool on);
};
void C_009705d0::f_009705d0(unsigned m, bool on) {
  unsigned x = fld; if (on) x |= m; else x &= ~m; s10(x);
}


// @ 0x0097d130
struct C_0097d130 {
  virtual void s0(unsigned);
  virtual void s1(unsigned);
  virtual void s2(unsigned);
  virtual void s3(unsigned);
  virtual void s4(unsigned);
  virtual void s5(unsigned);
  virtual void s6(unsigned);
  virtual void s7(unsigned);
  virtual void s8(unsigned);
  unsigned pad[1];
  unsigned fld;
  void f_0097d130(unsigned m, bool on);
};
void C_0097d130::f_0097d130(unsigned m, bool on) {
  unsigned x = fld; if (on) x |= m; else x &= ~m; s8(x);
}

