// Generated by tools/matching/synth.py (template set_field_from_vcall_arg). Do not edit by hand.
struct Arg { unsigned* conv(int); };
struct Tgt { virtual void v0(); };

// @ 0x009c8a30
struct T009c8a30 { char p[1008]; unsigned f; };
struct U009c8a30 { char p[68]; T009c8a30* t; };
struct I009c8a30 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual unsigned call(unsigned); };
struct S009c8a30 {
  char p0[4]; I009c8a30* a; char p1[4]; U009c8a30* b;
  void FUN_009c8a30(Arg* x);
};
void S009c8a30::FUN_009c8a30(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c8a60
struct T009c8a60 { char p[888]; unsigned f; };
struct U009c8a60 { char p[68]; T009c8a60* t; };
struct I009c8a60 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual unsigned call(unsigned); };
struct S009c8a60 {
  char p0[4]; I009c8a60* a; char p1[4]; U009c8a60* b;
  void FUN_009c8a60(Arg* x);
};
void S009c8a60::FUN_009c8a60(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c9100
struct T009c9100 { char p[260]; unsigned f; };
struct U009c9100 { char p[64]; T009c9100* t; };
struct I009c9100 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual void p39(); virtual unsigned call(unsigned); };
struct S009c9100 {
  char p0[4]; I009c9100* a; char p1[4]; U009c9100* b;
  void FUN_009c9100(Arg* x);
};
void S009c9100::FUN_009c9100(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c9140
struct T009c9140 { char p[512]; unsigned f; };
struct U009c9140 { char p[64]; T009c9140* t; };
struct I009c9140 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual unsigned call(unsigned); };
struct S009c9140 {
  char p0[4]; I009c9140* a; char p1[4]; U009c9140* b;
  void FUN_009c9140(Arg* x);
};
void S009c9140::FUN_009c9140(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c91d0
struct T009c91d0 { char p[828]; unsigned f; };
struct U009c91d0 { char p[64]; T009c91d0* t; };
struct I009c91d0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual unsigned call(unsigned); };
struct S009c91d0 {
  char p0[4]; I009c91d0* a; char p1[4]; U009c91d0* b;
  void FUN_009c91d0(Arg* x);
};
void S009c91d0::FUN_009c91d0(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c9580
struct T009c9580 { char p[1060]; unsigned f; };
struct U009c9580 { char p[64]; T009c9580* t; };
struct I009c9580 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual void p39(); virtual unsigned call(unsigned); };
struct S009c9580 {
  char p0[4]; I009c9580* a; char p1[4]; U009c9580* b;
  void FUN_009c9580(Arg* x);
};
void S009c9580::FUN_009c9580(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009c95b0
struct T009c95b0 { char p[1064]; unsigned f; };
struct U009c95b0 { char p[64]; T009c95b0* t; };
struct I009c95b0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual void p39(); virtual unsigned call(unsigned); };
struct S009c95b0 {
  char p0[4]; I009c95b0* a; char p1[4]; U009c95b0* b;
  void FUN_009c95b0(Arg* x);
};
void S009c95b0::FUN_009c95b0(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }


// @ 0x009ddc40
struct T009ddc40 { char p[292]; unsigned f; };
struct U009ddc40 { char p[4]; T009ddc40* t; };
struct I009ddc40 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7(); virtual void p8(); virtual void p9(); virtual void p10(); virtual void p11(); virtual void p12(); virtual void p13(); virtual void p14(); virtual void p15(); virtual void p16(); virtual void p17(); virtual void p18(); virtual void p19(); virtual void p20(); virtual void p21(); virtual void p22(); virtual void p23(); virtual void p24(); virtual void p25(); virtual void p26(); virtual void p27(); virtual void p28(); virtual void p29(); virtual void p30(); virtual void p31(); virtual void p32(); virtual void p33(); virtual void p34(); virtual void p35(); virtual void p36(); virtual void p37(); virtual void p38(); virtual unsigned call(unsigned); };
struct S009ddc40 {
  char p0[4]; I009ddc40* a; char p1[4]; U009ddc40* b;
  void FUN_009ddc40(Arg* x);
};
void S009ddc40::FUN_009ddc40(Arg* x) { unsigned* v = x->conv(1); b->t->f = a->call(*v); }

