// Generated by tools/matching/synth.py (template sorted_map_find_unique_value). Do not edit by hand.

struct KV { unsigned k; unsigned v; };
struct RNG { KV* a; KV* b; };
RNG* __cdecl equal_range_ext(RNG* out, KV* first, KV* last, const unsigned& key);

// @ 0x00896390
struct T00896390 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_00896390(char* o, unsigned* out); };
bool T00896390::FUN_00896390(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 216), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008964b0
struct T008964b0 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008964b0(char* o, unsigned* out); };
bool T008964b0::FUN_008964b0(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 24), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x00896510
struct T00896510 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_00896510(char* o, unsigned* out); };
bool T00896510::FUN_00896510(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 48), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x00896570
struct T00896570 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_00896570(char* o, unsigned* out); };
bool T00896570::FUN_00896570(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 32), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008965d0
struct T008965d0 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008965d0(char* o, unsigned* out); };
bool T008965d0::FUN_008965d0(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 56), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x00896630
struct T00896630 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_00896630(char* o, unsigned* out); };
bool T00896630::FUN_00896630(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 40), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x00896690
struct T00896690 { char p0[16]; unsigned key; char p1[16]; int kind; void post(); bool FUN_00896690(char* o, unsigned* out); };
bool T00896690::FUN_00896690(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 16), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5140
struct T008f5140 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5140(char* o, unsigned* out); };
bool T008f5140::FUN_008f5140(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 72), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f51a0
struct T008f51a0 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f51a0(char* o, unsigned* out); };
bool T008f51a0::FUN_008f51a0(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 1152), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5200
struct T008f5200 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5200(char* o, unsigned* out); };
bool T008f5200::FUN_008f5200(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 48), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5260
struct T008f5260 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5260(char* o, unsigned* out); };
bool T008f5260::FUN_008f5260(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 120), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f52c0
struct T008f52c0 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f52c0(char* o, unsigned* out); };
bool T008f52c0::FUN_008f52c0(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 24), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5320
struct T008f5320 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5320(char* o, unsigned* out); };
bool T008f5320::FUN_008f5320(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 32), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5380
struct T008f5380 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5380(char* o, unsigned* out); };
bool T008f5380::FUN_008f5380(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 56), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5440
struct T008f5440 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5440(char* o, unsigned* out); };
bool T008f5440::FUN_008f5440(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 64), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f54a0
struct T008f54a0 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f54a0(char* o, unsigned* out); };
bool T008f54a0::FUN_008f54a0(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 40), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }


// @ 0x008f5500
struct T008f5500 { char p0[20]; unsigned key; char p1[16]; int kind; void post(); bool FUN_008f5500(char* o, unsigned* out); };
bool T008f5500::FUN_008f5500(char* o, unsigned* out) {
  if (kind == 3) { unsigned k = key; RNG r;
    equal_range_ext(&r, (KV*)o, (KV*)(o + 704), k);
    if (r.a + 1 == r.b) { *out = r.a->v; post(); return true; } }
  return false; }

