// Generated by tools/matching/synth.py (template stack_obj_ctor_call_true). Do not edit by hand.

// @ 0x00bf1c70
struct O00bf1c70 { char b[0xa14]; O00bf1c70(int, const void*, int); void m(int); };
extern int g_0156fa30;
bool FUN_00bf1c70(int a, int b) { O00bf1c70 o(b, &g_0156fa30, 0x1a80d26); o.m(a); return true; }

// @ 0x00bf1cb0
struct O00bf1cb0 { char b[0xa14]; O00bf1cb0(int, const void*, int); void m(int); };
extern int g_0156fa30;
bool FUN_00bf1cb0(int a, int b) { O00bf1cb0 o(b, &g_0156fa30, 0x1a80d26); o.m(a); return true; }

// @ 0x00c463f0
struct O00c463f0 { char b[0xa14]; O00c463f0(int, const void*, int); void m(int); };
extern int g_01574d38;
bool FUN_00c463f0(int a, int b) { O00c463f0 o(b, &g_01574d38, 0x1a80d26); o.m(a); return true; }

// @ 0x00c46430
struct O00c46430 { char b[0xa14]; O00c46430(int, const void*, int); void m(int); };
extern int g_01574d38;
bool FUN_00c46430(int a, int b) { O00c46430 o(b, &g_01574d38, 0x1a80d26); o.m(a); return true; }

// @ 0x00de4d10
struct O00de4d10 { char b[0xa14]; O00de4d10(int, const void*, int); void m(int); };
extern int g_015a3a60;
bool FUN_00de4d10(int a, int b) { O00de4d10 o(b, &g_015a3a60, 0x1a80d26); o.m(a); return true; }

// @ 0x00de4d50
struct O00de4d50 { char b[0xa14]; O00de4d50(int, const void*, int); void m(int); };
extern int g_015a3a60;
bool FUN_00de4d50(int a, int b) { O00de4d50 o(b, &g_015a3a60, 0x1a80d26); o.m(a); return true; }

// @ 0x00f268b0
struct O00f268b0 { char b[0xa14]; O00f268b0(int, const void*, int); void m(int); };
extern int g_015aff90;
bool FUN_00f268b0(int a, int b) { O00f268b0 o(b, &g_015aff90, 0x1a80d26); o.m(a); return true; }

// @ 0x00f26be0
struct O00f26be0 { char b[0xa14]; O00f26be0(int, const void*, int); void m(int); };
extern int g_015adbd0;
bool FUN_00f26be0(int a, int b) { O00f26be0 o(b, &g_015adbd0, 0x1a80d26); o.m(a); return true; }

// @ 0x00f26c20
struct O00f26c20 { char b[0xa14]; O00f26c20(int, const void*, int); void m(int); };
extern int g_015adbd0;
bool FUN_00f26c20(int a, int b) { O00f26c20 o(b, &g_015adbd0, 0x1a80d26); o.m(a); return true; }

// @ 0x0100e8f0
struct O0100e8f0 { char b[0xa14]; O0100e8f0(int, const void*, int); void m(int); };
extern int g_015b6a80;
bool FUN_0100e8f0(int a, int b) { O0100e8f0 o(b, &g_015b6a80, 0x1a80d26); o.m(a); return true; }

// @ 0x0100e930
struct O0100e930 { char b[0xa14]; O0100e930(int, const void*, int); void m(int); };
extern int g_015b6a80;
bool FUN_0100e930(int a, int b) { O0100e930 o(b, &g_015b6a80, 0x1a80d26); o.m(a); return true; }
