// Generated by tools/matching/synth.py (template stdcall4_swap_vptr_obj). Do not edit by hand.
struct Obj { void* vt; char b; int v; };

// @ 0x010d25b0
void __stdcall ext_010d25b0(int,int,int,Obj*);
extern char vt_010d25b0[];
void __stdcall FUN_010d25b0(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010d25b0; ext_010d25b0(b,a,c,&o); }

// @ 0x010d4070
void __stdcall ext_010d4070(int,int,int,Obj*);
extern char vt_010d4070[];
void __stdcall FUN_010d4070(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010d4070; ext_010d4070(b,a,c,&o); }

// @ 0x010d7470
void __stdcall ext_010d7470(int,int,int,Obj*);
extern char vt_010d7470[];
void __stdcall FUN_010d7470(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010d7470; ext_010d7470(b,a,c,&o); }

// @ 0x010defc0
void __stdcall ext_010defc0(int,int,int,Obj*);
extern char vt_010defc0[];
void __stdcall FUN_010defc0(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010defc0; ext_010defc0(b,a,c,&o); }

// @ 0x010e0200
void __stdcall ext_010e0200(int,int,int,Obj*);
extern char vt_010e0200[];
void __stdcall FUN_010e0200(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010e0200; ext_010e0200(b,a,c,&o); }

// @ 0x010e1220
void __stdcall ext_010e1220(int,int,int,Obj*);
extern char vt_010e1220[];
void __stdcall FUN_010e1220(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010e1220; ext_010e1220(b,a,c,&o); }

// @ 0x010e1aa0
void __stdcall ext_010e1aa0(int,int,int,Obj*);
extern char vt_010e1aa0[];
void __stdcall FUN_010e1aa0(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010e1aa0; ext_010e1aa0(b,a,c,&o); }

// @ 0x010e67d0
void __stdcall ext_010e67d0(int,int,int,Obj*);
extern char vt_010e67d0[];
void __stdcall FUN_010e67d0(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010e67d0; ext_010e67d0(b,a,c,&o); }

// @ 0x010e7930
void __stdcall ext_010e7930(int,int,int,Obj*);
extern char vt_010e7930[];
void __stdcall FUN_010e7930(int a,int b,int c,int d){ Obj o; o.v=d; o.b=0; o.vt=vt_010e7930; ext_010e7930(b,a,c,&o); }
