// Generated by tools/matching/synth.py (template struct15_stack_copy). Do not edit by hand.
struct S15 { const char *name; unsigned id; unsigned size; unsigned u0, u1, u2; unsigned z0, z1; void *f[7]; };

// @ 0x013131e0
extern S15 g_01565c60;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8020();void fn_00ac8050();void fn_00b6f550();void fn_00bca960();void fn_00c2e4e0(); }
void FUN_013131e0() {
  S15 s;
  s.name = (const char*)0x145a07c; s.id = 0x225212b;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00ac8020;
  s.f[2] = (void*)fn_00bca960;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f550;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x1c;
  g_01565c60 = s;
}

// @ 0x01319050
extern S15 g_01567d18;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00b0d540();void fn_00b0e320();void fn_00b1fbf0();void fn_00c2e4e0();void fn_00c6c390(); }
void FUN_01319050() {
  S15 s;
  s.name = (const char*)0x145cca0; s.id = 0x6ba6e9b;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00b0e320;
  s.f[2] = (void*)fn_00b0d540;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_00c6c390;
  s.size = 0x24;
  g_01567d18 = s;
}

// @ 0x0131c570
extern S15 g_01568d40;
extern "C" { void fn_00572810();void fn_00572840();void fn_0057cde0();void fn_00692ca0();void fn_00692ff0();void fn_00694ee0();void fn_00b1fbf0(); }
void FUN_0131c570() {
  S15 s;
  s.name = (const char*)0x145fe70; s.id = 0x224252d;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00572810;
  s.f[2] = (void*)fn_00572840;
  s.f[3] = (void*)fn_00692ff0;
  s.f[4] = (void*)fn_00694ee0;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_0057cde0;
  s.size = 0x30;
  g_01568d40 = s;
}

// @ 0x0131d6b0
extern S15 g_01569a10;
extern "C" { void fn_00572810();void fn_00572840();void fn_00675ca0();void fn_00692ca0();void fn_00693090();void fn_00694f00();void fn_00b1fbf0(); }
void FUN_0131d6b0() {
  S15 s;
  s.name = (const char*)0x146127c; s.id = 0x49309fd;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00572810;
  s.f[2] = (void*)fn_00572840;
  s.f[3] = (void*)fn_00693090;
  s.f[4] = (void*)fn_00694f00;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_00675ca0;
  s.size = 0x20;
  g_01569a10 = s;
}

// @ 0x013212f0
extern S15 g_0156b308;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00b71570();void fn_00b71680();void fn_00b71b90();void fn_00baa2b0();void fn_00c2e4e0(); }
void FUN_013212f0() {
  S15 s;
  s.name = (const char*)0x1464f8c; s.id = 0x6ef53d5;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00b71b90;
  s.f[2] = (void*)fn_00b71680;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b71570;
  s.f[6] = (void*)fn_00baa2b0;
  s.size = 0x1c;
  g_0156b308 = s;
}

// @ 0x01324ba0
extern S15 g_0156c370;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ba2ca0();void fn_00ba2d80();void fn_00ba33e0();void fn_00ba3b10();void fn_00c2e4e0(); }
void FUN_01324ba0() {
  S15 s;
  s.name = (const char*)0x1465e30; s.id = 0x931d0fa7;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00ba33e0;
  s.f[2] = (void*)fn_00ba2ca0;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00ba2d80;
  s.f[6] = (void*)fn_00ba3b10;
  s.size = 0x20;
  g_0156c370 = s;
}

// @ 0x01328dc0
extern S15 g_0156cf40;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00aca730();void fn_00b6f860();void fn_00bbf780();void fn_00c2e4e0();void fn_00c6c390(); }
void FUN_01328dc0() {
  S15 s;
  s.name = (const char*)0x14666c4; s.id = 0x6ba6e9c;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00bbf780;
  s.f[2] = (void*)fn_00aca730;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f860;
  s.f[6] = (void*)fn_00c6c390;
  s.size = 0x68;
  g_0156cf40 = s;
}

// @ 0x01336cd0
extern S15 g_01572a18;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8050();void fn_00aca090();void fn_00b6f550();void fn_00bca960();void fn_00c2e4e0(); }
void FUN_01336cd0() {
  S15 s;
  s.name = (const char*)0x146b65c; s.id = 0x343c79ed;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00aca090;
  s.f[2] = (void*)fn_00bca960;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f550;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x80;
  g_01572a18 = s;
}

// @ 0x013395b0
extern S15 g_01573a60;
extern "C" { void fn_00692ca0();void fn_00693150();void fn_00695080();void fn_00ae3430();void fn_00ae3450();void fn_00ae5720();void fn_00b1fbf0(); }
void FUN_013395b0() {
  S15 s;
  s.name = (const char*)0x146c378; s.id = 0x3f6663b;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00ae3430;
  s.f[2] = (void*)fn_00ae3450;
  s.f[3] = (void*)fn_00693150;
  s.f[4] = (void*)fn_00695080;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_00ae5720;
  s.size = 0x650;
  g_01573a60 = s;
}

// @ 0x013491a0
extern S15 g_01577008;
extern "C" { void fn_00572810();void fn_00572840();void fn_0057cde0();void fn_00692ca0();void fn_00692ff0();void fn_00694ee0();void fn_00b1fbf0(); }
void FUN_013491a0() {
  S15 s;
  s.name = (const char*)0x146fdc0; s.id = 0x3855028;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00572810;
  s.f[2] = (void*)fn_00572840;
  s.f[3] = (void*)fn_00692ff0;
  s.f[4] = (void*)fn_00694ee0;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_0057cde0;
  s.size = 0x1f0;
  g_01577008 = s;
}

// @ 0x0134b8c0
extern S15 g_01577530;
extern "C" { void fn_00572810();void fn_00572840();void fn_0057cde0();void fn_00692ca0();void fn_00692ff0();void fn_00694ee0();void fn_00b1fbf0(); }
void FUN_0134b8c0() {
  S15 s;
  s.name = (const char*)0x147093c; s.id = 0x4855028;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00572810;
  s.f[2] = (void*)fn_00572840;
  s.f[3] = (void*)fn_00692ff0;
  s.f[4] = (void*)fn_00694ee0;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_0057cde0;
  s.size = 0x1f0;
  g_01577530 = s;
}

// @ 0x0134cda0
extern S15 g_01577820;
extern "C" { void fn_00572810();void fn_00572840();void fn_0057cde0();void fn_00692ca0();void fn_00692ff0();void fn_00694ee0();void fn_00b1fbf0(); }
void FUN_0134cda0() {
  S15 s;
  s.name = (const char*)0x147185c; s.id = 0x6f3384d;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00572810;
  s.f[2] = (void*)fn_00572840;
  s.f[3] = (void*)fn_00692ff0;
  s.f[4] = (void*)fn_00694ee0;
  s.f[5] = (void*)fn_00b1fbf0;
  s.f[6] = (void*)fn_0057cde0;
  s.size = 0x1d4;
  g_01577820 = s;
}

// @ 0x0134e470
extern S15 g_01578618;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8050();void fn_00aca060();void fn_00b6f550();void fn_00bca960();void fn_00c2e4e0(); }
void FUN_0134e470() {
  S15 s;
  s.name = (const char*)0x1472094; s.id = 0x739097d;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00aca060;
  s.f[2] = (void*)fn_00bca960;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f550;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x7c;
  g_01578618 = s;
}

// @ 0x0134fb40
extern S15 g_01578ba0;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8050();void fn_00b6f550();void fn_00bdd350();void fn_00c2e4e0();void fn_00c3b930(); }
void FUN_0134fb40() {
  S15 s;
  s.name = (const char*)0x14727a0; s.id = 0x4457f99;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00c3b930;
  s.f[2] = (void*)fn_00bdd350;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f550;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x108;
  g_01578ba0 = s;
}

// @ 0x01353770
extern S15 g_01579ed8;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00c2e4e0();void fn_00c6c390();void fn_00c875f0();void fn_00c87c00();void fn_00c87f80(); }
void FUN_01353770() {
  S15 s;
  s.name = (const char*)0x14736bc; s.id = 0x21ffbe8;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00c87f80;
  s.f[2] = (void*)fn_00c87c00;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00c875f0;
  s.f[6] = (void*)fn_00c6c390;
  s.size = 0x34;
  g_01579ed8 = s;
}

// @ 0x01356080
extern S15 g_0157c320;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8050();void fn_00aca090();void fn_00b6f550();void fn_00bca960();void fn_00c2e4e0(); }
void FUN_01356080() {
  S15 s;
  s.name = (const char*)0x145a45c; s.id = 0x62d4f39;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00aca090;
  s.f[2] = (void*)fn_00bca960;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f550;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x10c;
  g_0157c320 = s;
}

// @ 0x0135bec0
extern S15 g_0157e888;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00ac8050();void fn_00bcd450();void fn_00bd0d50();void fn_00bd17b0();void fn_00c2e4e0(); }
void FUN_0135bec0() {
  S15 s;
  s.name = (const char*)0x14669f8; s.id = 0x49cf69f;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00bd0d50;
  s.f[2] = (void*)fn_00bd17b0;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00bcd450;
  s.f[6] = (void*)fn_00ac8050;
  s.size = 0x520;
  g_0157e888 = s;
}

// @ 0x01361e60
extern S15 g_01581cc8;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00aca730();void fn_00b6f860();void fn_00c2e4e0();void fn_00c6c390();void fn_00cfed20(); }
void FUN_01361e60() {
  S15 s;
  s.name = (const char*)0x1478c60; s.id = 0x4474bd5;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00cfed20;
  s.f[2] = (void*)fn_00aca730;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f860;
  s.f[6] = (void*)fn_00c6c390;
  s.size = 0x1c;
  g_01581cc8 = s;
}

// @ 0x01363c70
extern S15 g_015826c0;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00b6f860();void fn_00bf50f0();void fn_00c2e4e0();void fn_00c43790();void fn_00c6c390(); }
void FUN_01363c70() {
  S15 s;
  s.name = (const char*)0x147417c; s.id = 0x6ba6e9a;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_00bf50f0;
  s.f[2] = (void*)fn_00c43790;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_00b6f860;
  s.f[6] = (void*)fn_00c6c390;
  s.size = 0x40;
  g_015826c0 = s;
}

// @ 0x013a5f40
extern S15 g_015b7fe0;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00c2e4e0();void fn_00d022e0();void fn_01037ce0();void fn_01037fd0();void fn_010390d0(); }
void FUN_013a5f40() {
  S15 s;
  s.name = (const char*)0x1499acc; s.id = 0x552740f;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_010390d0;
  s.f[2] = (void*)fn_01037fd0;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_01037ce0;
  s.f[6] = (void*)fn_00d022e0;
  s.size = 0x4;
  g_015b7fe0 = s;
}

// @ 0x013a9450
extern S15 g_015b85a0;
extern "C" { void fn_00692ca0();void fn_00692fb0();void fn_00c2e4e0();void fn_01044e70();void fn_01044f30();void fn_010453f0();void fn_010455e0(); }
void FUN_013a9450() {
  S15 s;
  s.name = (const char*)0x1499db4; s.id = 0x3dee991;
  s.z0 = 0; s.z1 = 0;
  s.f[0] = (void*)fn_00692ca0;
  s.f[1] = (void*)fn_010453f0;
  s.f[2] = (void*)fn_01044e70;
  s.f[3] = (void*)fn_00c2e4e0;
  s.f[4] = (void*)fn_00692fb0;
  s.f[5] = (void*)fn_01044f30;
  s.f[6] = (void*)fn_010455e0;
  s.size = 0x20;
  g_015b85a0 = s;
}
