// Generated by tools/matching/synth.py (template thiscall_field_getter). Do not edit by hand.

// @ 0x005723d0
#pragma pack(push, 1)
struct C_005723d0 { char pad[0x18c]; int field; int Get(); };
#pragma pack(pop)
int C_005723d0::Get() { return field; }

// @ 0x005723e0
#pragma pack(push, 1)
struct C_005723e0 { char pad[0x2fc]; int field; int Get(); };
#pragma pack(pop)
int C_005723e0::Get() { return field; }

// @ 0x005723f0
#pragma pack(push, 1)
struct C_005723f0 { char pad[0x300]; int field; int Get(); };
#pragma pack(pop)
int C_005723f0::Get() { return field; }

// @ 0x00574a50
#pragma pack(push, 1)
struct C_00574a50 { char pad[0x98]; int field; int Get(); };
#pragma pack(pop)
int C_00574a50::Get() { return field; }

// @ 0x00575ea0
#pragma pack(push, 1)
struct C_00575ea0 { char pad[0xa4]; int field; int Get(); };
#pragma pack(pop)
int C_00575ea0::Get() { return field; }

// @ 0x005aacf0
#pragma pack(push, 1)
struct C_005aacf0 { char pad[0x30]; int field; int Get(); };
#pragma pack(pop)
int C_005aacf0::Get() { return field; }

// @ 0x005dc2b0
#pragma pack(push, 1)
struct C_005dc2b0 { char pad[0xf8]; int field; int Get(); };
#pragma pack(pop)
int C_005dc2b0::Get() { return field; }

// @ 0x005dc2c0
#pragma pack(push, 1)
struct C_005dc2c0 { char pad[0xfc]; int field; int Get(); };
#pragma pack(pop)
int C_005dc2c0::Get() { return field; }

// @ 0x005e1fc0
#pragma pack(push, 1)
struct C_005e1fc0 { char pad[0x64]; int field; int Get(); };
#pragma pack(pop)
int C_005e1fc0::Get() { return field; }

// @ 0x005e2cb0
#pragma pack(push, 1)
struct C_005e2cb0 { char pad[0x174]; int field; int Get(); };
#pragma pack(pop)
int C_005e2cb0::Get() { return field; }

// @ 0x005e2d00
#pragma pack(push, 1)
struct C_005e2d00 { char pad[0x170]; int field; int Get(); };
#pragma pack(pop)
int C_005e2d00::Get() { return field; }

// @ 0x005f2cf0
#pragma pack(push, 1)
struct C_005f2cf0 { char pad[0xf0]; int field; int Get(); };
#pragma pack(pop)
int C_005f2cf0::Get() { return field; }

// @ 0x005f33f0
#pragma pack(push, 1)
struct C_005f33f0 { char pad[0x180]; int field; int Get(); };
#pragma pack(pop)
int C_005f33f0::Get() { return field; }

// @ 0x00641770
#pragma pack(push, 1)
struct C_00641770 { char pad[0x28]; int field; int Get(); };
#pragma pack(pop)
int C_00641770::Get() { return field; }

// @ 0x006447b0
#pragma pack(push, 1)
struct C_006447b0 { char pad[0x238]; int field; int Get(); };
#pragma pack(pop)
int C_006447b0::Get() { return field; }

// @ 0x006c0200
#pragma pack(push, 1)
struct C_006c0200 { char pad[0x18]; int field; int Get(); };
#pragma pack(pop)
int C_006c0200::Get() { return field; }

// @ 0x006c10e0
#pragma pack(push, 1)
struct C_006c10e0 { char pad[0x3c]; int field; int Get(); };
#pragma pack(pop)
int C_006c10e0::Get() { return field; }

// @ 0x006e87e0
#pragma pack(push, 1)
struct C_006e87e0 { char pad[0x1e0]; int field; int Get(); };
#pragma pack(pop)
int C_006e87e0::Get() { return field; }

// @ 0x00745100
#pragma pack(push, 1)
struct C_00745100 { char pad[0x5c8]; int field; int Get(); };
#pragma pack(pop)
int C_00745100::Get() { return field; }

// @ 0x007a4ba0
#pragma pack(push, 1)
struct C_007a4ba0 { char pad[0x88]; int field; int Get(); };
#pragma pack(pop)
int C_007a4ba0::Get() { return field; }

// @ 0x007f54d0
#pragma pack(push, 1)
struct C_007f54d0 { char pad[0x10]; int field; int Get(); };
#pragma pack(pop)
int C_007f54d0::Get() { return field; }

// @ 0x00801920
#pragma pack(push, 1)
struct C_00801920 { char pad[0x48]; int field; int Get(); };
#pragma pack(pop)
int C_00801920::Get() { return field; }

// @ 0x00812da0
#pragma pack(push, 1)
struct C_00812da0 { char pad[0x264]; int field; int Get(); };
#pragma pack(pop)
int C_00812da0::Get() { return field; }

// @ 0x008414c0
#pragma pack(push, 1)
struct C_008414c0 { char pad[0x154]; int field; int Get(); };
#pragma pack(pop)
int C_008414c0::Get() { return field; }

// @ 0x00885c90
#pragma pack(push, 1)
struct C_00885c90 { char pad[0x1d8]; int field; int Get(); };
#pragma pack(pop)
int C_00885c90::Get() { return field; }

// @ 0x00897680
#pragma pack(push, 1)
struct C_00897680 { char pad[0x414]; int field; int Get(); };
#pragma pack(pop)
int C_00897680::Get() { return field; }

// @ 0x00897690
#pragma pack(push, 1)
struct C_00897690 { char pad[0x40c]; int field; int Get(); };
#pragma pack(pop)
int C_00897690::Get() { return field; }

// @ 0x008d5f20
#pragma pack(push, 1)
struct C_008d5f20 { char pad[0xac]; int field; int Get(); };
#pragma pack(pop)
int C_008d5f20::Get() { return field; }

// @ 0x008d86b0
#pragma pack(push, 1)
struct C_008d86b0 { char pad[0x260]; int field; int Get(); };
#pragma pack(pop)
int C_008d86b0::Get() { return field; }

// @ 0x008e7f80
#pragma pack(push, 1)
struct C_008e7f80 { char pad[0x34]; int field; int Get(); };
#pragma pack(pop)
int C_008e7f80::Get() { return field; }

// @ 0x00928f70
#pragma pack(push, 1)
struct C_00928f70 { char pad[0x444]; int field; int Get(); };
#pragma pack(pop)
int C_00928f70::Get() { return field; }

// @ 0x00931ac0
#pragma pack(push, 1)
struct C_00931ac0 { char pad[0x214]; int field; int Get(); };
#pragma pack(pop)
int C_00931ac0::Get() { return field; }

// @ 0x009330b0
#pragma pack(push, 1)
struct C_009330b0 { char pad[0x438]; int field; int Get(); };
#pragma pack(pop)
int C_009330b0::Get() { return field; }

// @ 0x0093b6c0
#pragma pack(push, 1)
struct C_0093b6c0 { char pad[0x8]; int field; int Get(); };
#pragma pack(pop)
int C_0093b6c0::Get() { return field; }

// @ 0x00957f20
#pragma pack(push, 1)
struct C_00957f20 { char pad[0x82c]; int field; int Get(); };
#pragma pack(pop)
int C_00957f20::Get() { return field; }

// @ 0x0095f9e0
#pragma pack(push, 1)
struct C_0095f9e0 { char pad[0x1d4]; int field; int Get(); };
#pragma pack(pop)
int C_0095f9e0::Get() { return field; }

// @ 0x0095fa50
#pragma pack(push, 1)
struct C_0095fa50 { char pad[0xbc]; int field; int Get(); };
#pragma pack(pop)
int C_0095fa50::Get() { return field; }

// @ 0x0095fd50
#pragma pack(push, 1)
struct C_0095fd50 { char pad[0x1e4]; int field; int Get(); };
#pragma pack(pop)
int C_0095fd50::Get() { return field; }

// @ 0x009600f0
#pragma pack(push, 1)
struct C_009600f0 { char pad[0x1dc]; int field; int Get(); };
#pragma pack(pop)
int C_009600f0::Get() { return field; }

// @ 0x00967e70
#pragma pack(push, 1)
struct C_00967e70 { char pad[0x2c]; int field; int Get(); };
#pragma pack(pop)
int C_00967e70::Get() { return field; }

// @ 0x0096b7a0
#pragma pack(push, 1)
struct C_0096b7a0 { char pad[0x118]; int field; int Get(); };
#pragma pack(pop)
int C_0096b7a0::Get() { return field; }

// @ 0x0096b8f0
#pragma pack(push, 1)
struct C_0096b8f0 { char pad[0x114]; int field; int Get(); };
#pragma pack(pop)
int C_0096b8f0::Get() { return field; }

// @ 0x00970b30
#pragma pack(push, 1)
struct C_00970b30 { char pad[0x1e8]; int field; int Get(); };
#pragma pack(pop)
int C_00970b30::Get() { return field; }

// @ 0x00985e40
#pragma pack(push, 1)
struct C_00985e40 { char pad[0x1c]; int field; int Get(); };
#pragma pack(pop)
int C_00985e40::Get() { return field; }

// @ 0x00989360
#pragma pack(push, 1)
struct C_00989360 { char pad[0x58]; int field; int Get(); };
#pragma pack(pop)
int C_00989360::Get() { return field; }

// @ 0x00989480
#pragma pack(push, 1)
struct C_00989480 { char pad[0x318]; int field; int Get(); };
#pragma pack(pop)
int C_00989480::Get() { return field; }

// @ 0x0098f940
#pragma pack(push, 1)
struct C_0098f940 { char pad[0xa8]; int field; int Get(); };
#pragma pack(pop)
int C_0098f940::Get() { return field; }

// @ 0x009ce410
#pragma pack(push, 1)
struct C_009ce410 { char pad[0xb8]; int field; int Get(); };
#pragma pack(pop)
int C_009ce410::Get() { return field; }

// @ 0x00a02700
#pragma pack(push, 1)
struct C_00a02700 { char pad[0x190]; int field; int Get(); };
#pragma pack(pop)
int C_00a02700::Get() { return field; }

// @ 0x00a02d30
#pragma pack(push, 1)
struct C_00a02d30 { char pad[0x7c]; int field; int Get(); };
#pragma pack(pop)
int C_00a02d30::Get() { return field; }

// @ 0x00a17150
#pragma pack(push, 1)
struct C_00a17150 { char pad[0x380]; int field; int Get(); };
#pragma pack(pop)
int C_00a17150::Get() { return field; }

// @ 0x00a171d0
#pragma pack(push, 1)
struct C_00a171d0 { char pad[0x388]; int field; int Get(); };
#pragma pack(pop)
int C_00a171d0::Get() { return field; }

// @ 0x00a1ad10
#pragma pack(push, 1)
struct C_00a1ad10 { char pad[0x38]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ad10::Get() { return field; }

// @ 0x00a1ad60
#pragma pack(push, 1)
struct C_00a1ad60 { char pad[0x40]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ad60::Get() { return field; }

// @ 0x00a1ad70
#pragma pack(push, 1)
struct C_00a1ad70 { char pad[0x330]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ad70::Get() { return field; }

// @ 0x00a1ad80
#pragma pack(push, 1)
struct C_00a1ad80 { char pad[0xcd8]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ad80::Get() { return field; }

// @ 0x00a1ad90
#pragma pack(push, 1)
struct C_00a1ad90 { char pad[0xcdc]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ad90::Get() { return field; }

// @ 0x00a1ada0
#pragma pack(push, 1)
struct C_00a1ada0 { char pad[0xce0]; int field; int Get(); };
#pragma pack(pop)
int C_00a1ada0::Get() { return field; }

// @ 0x00a1b3f0
#pragma pack(push, 1)
struct C_00a1b3f0 { char pad[0xc90]; int field; int Get(); };
#pragma pack(pop)
int C_00a1b3f0::Get() { return field; }

// @ 0x00a21120
#pragma pack(push, 1)
struct C_00a21120 { char pad[0xb0]; int field; int Get(); };
#pragma pack(pop)
int C_00a21120::Get() { return field; }

// @ 0x00a2fa80
#pragma pack(push, 1)
struct C_00a2fa80 { char pad[0x970]; int field; int Get(); };
#pragma pack(pop)
int C_00a2fa80::Get() { return field; }

// @ 0x00a42730
#pragma pack(push, 1)
struct C_00a42730 { char pad[0x20]; int field; int Get(); };
#pragma pack(pop)
int C_00a42730::Get() { return field; }

// @ 0x00a649a0
#pragma pack(push, 1)
struct C_00a649a0 { char pad[0x6c]; int field; int Get(); };
#pragma pack(pop)
int C_00a649a0::Get() { return field; }

// @ 0x00ad2830
#pragma pack(push, 1)
struct C_00ad2830 { char pad[0xa0]; int field; int Get(); };
#pragma pack(pop)
int C_00ad2830::Get() { return field; }

// @ 0x00b11780
#pragma pack(push, 1)
struct C_00b11780 { char pad[0x30c]; int field; int Get(); };
#pragma pack(pop)
int C_00b11780::Get() { return field; }

// @ 0x00b1fdb0
#pragma pack(push, 1)
struct C_00b1fdb0 { char pad[0x54]; int field; int Get(); };
#pragma pack(pop)
int C_00b1fdb0::Get() { return field; }

// @ 0x00b2fbc0
#pragma pack(push, 1)
struct C_00b2fbc0 { char pad[0x15c]; int field; int Get(); };
#pragma pack(pop)
int C_00b2fbc0::Get() { return field; }

// @ 0x00b2fe80
#pragma pack(push, 1)
struct C_00b2fe80 { char pad[0x168]; int field; int Get(); };
#pragma pack(pop)
int C_00b2fe80::Get() { return field; }

// @ 0x00b35b60
#pragma pack(push, 1)
struct C_00b35b60 { char pad[0xe4]; int field; int Get(); };
#pragma pack(pop)
int C_00b35b60::Get() { return field; }

// @ 0x00b35b70
#pragma pack(push, 1)
struct C_00b35b70 { char pad[0x108]; int field; int Get(); };
#pragma pack(pop)
int C_00b35b70::Get() { return field; }

// @ 0x00b8dab0
#pragma pack(push, 1)
struct C_00b8dab0 { char pad[0x194]; int field; int Get(); };
#pragma pack(pop)
int C_00b8dab0::Get() { return field; }

// @ 0x00ba70a0
#pragma pack(push, 1)
struct C_00ba70a0 { char pad[0x148]; int field; int Get(); };
#pragma pack(pop)
int C_00ba70a0::Get() { return field; }

// @ 0x00bb9ae0
#pragma pack(push, 1)
struct C_00bb9ae0 { char pad[0x4c]; int field; int Get(); };
#pragma pack(pop)
int C_00bb9ae0::Get() { return field; }

// @ 0x00bce3d0
#pragma pack(push, 1)
struct C_00bce3d0 { char pad[0x698]; int field; int Get(); };
#pragma pack(pop)
int C_00bce3d0::Get() { return field; }

// @ 0x00bce3e0
#pragma pack(push, 1)
struct C_00bce3e0 { char pad[0x69c]; int field; int Get(); };
#pragma pack(pop)
int C_00bce3e0::Get() { return field; }

// @ 0x00bce3f0
#pragma pack(push, 1)
struct C_00bce3f0 { char pad[0x694]; int field; int Get(); };
#pragma pack(pop)
int C_00bce3f0::Get() { return field; }

// @ 0x00bce470
#pragma pack(push, 1)
struct C_00bce470 { char pad[0x6a0]; int field; int Get(); };
#pragma pack(pop)
int C_00bce470::Get() { return field; }

// @ 0x00bce4c0
#pragma pack(push, 1)
struct C_00bce4c0 { char pad[0x104]; int field; int Get(); };
#pragma pack(pop)
int C_00bce4c0::Get() { return field; }

// @ 0x00bce5c0
#pragma pack(push, 1)
struct C_00bce5c0 { char pad[0x688]; int field; int Get(); };
#pragma pack(pop)
int C_00bce5c0::Get() { return field; }

// @ 0x00bce890
#pragma pack(push, 1)
struct C_00bce890 { char pad[0x278]; int field; int Get(); };
#pragma pack(pop)
int C_00bce890::Get() { return field; }

// @ 0x00bce8a0
#pragma pack(push, 1)
struct C_00bce8a0 { char pad[0x1f0]; int field; int Get(); };
#pragma pack(pop)
int C_00bce8a0::Get() { return field; }

// @ 0x00bd8120
#pragma pack(push, 1)
struct C_00bd8120 { char pad[0x64c]; int field; int Get(); };
#pragma pack(pop)
int C_00bd8120::Get() { return field; }

// @ 0x00bd8160
#pragma pack(push, 1)
struct C_00bd8160 { char pad[0x2f4]; int field; int Get(); };
#pragma pack(pop)
int C_00bd8160::Get() { return field; }

// @ 0x00bd8190
#pragma pack(push, 1)
struct C_00bd8190 { char pad[0x2f8]; int field; int Get(); };
#pragma pack(pop)
int C_00bd8190::Get() { return field; }

// @ 0x00bd81d0
#pragma pack(push, 1)
struct C_00bd81d0 { char pad[0x540]; int field; int Get(); };
#pragma pack(pop)
int C_00bd81d0::Get() { return field; }

// @ 0x00bd81f0
#pragma pack(push, 1)
struct C_00bd81f0 { char pad[0x2f0]; int field; int Get(); };
#pragma pack(pop)
int C_00bd81f0::Get() { return field; }

// @ 0x00bd9b40
#pragma pack(push, 1)
struct C_00bd9b40 { char pad[0x320]; int field; int Get(); };
#pragma pack(pop)
int C_00bd9b40::Get() { return field; }

// @ 0x00bd9bf0
#pragma pack(push, 1)
struct C_00bd9bf0 { char pad[0x590]; int field; int Get(); };
#pragma pack(pop)
int C_00bd9bf0::Get() { return field; }

// @ 0x00bd9e20
#pragma pack(push, 1)
struct C_00bd9e20 { char pad[0x324]; int field; int Get(); };
#pragma pack(pop)
int C_00bd9e20::Get() { return field; }

// @ 0x00bd9e30
#pragma pack(push, 1)
struct C_00bd9e30 { char pad[0x328]; int field; int Get(); };
#pragma pack(pop)
int C_00bd9e30::Get() { return field; }

// @ 0x00bddd00
#pragma pack(push, 1)
struct C_00bddd00 { char pad[0xc4]; int field; int Get(); };
#pragma pack(pop)
int C_00bddd00::Get() { return field; }

// @ 0x00bddd10
#pragma pack(push, 1)
struct C_00bddd10 { char pad[0xd4]; int field; int Get(); };
#pragma pack(pop)
int C_00bddd10::Get() { return field; }

// @ 0x00bebdb0
#pragma pack(push, 1)
struct C_00bebdb0 { char pad[0x344]; int field; int Get(); };
#pragma pack(pop)
int C_00bebdb0::Get() { return field; }

// @ 0x00bebdc0
#pragma pack(push, 1)
struct C_00bebdc0 { char pad[0x254]; int field; int Get(); };
#pragma pack(pop)
int C_00bebdc0::Get() { return field; }

// @ 0x00bef8e0
#pragma pack(push, 1)
struct C_00bef8e0 { char pad[0x42c]; int field; int Get(); };
#pragma pack(pop)
int C_00bef8e0::Get() { return field; }

// @ 0x00bf3a90
#pragma pack(push, 1)
struct C_00bf3a90 { char pad[0x244]; int field; int Get(); };
#pragma pack(pop)
int C_00bf3a90::Get() { return field; }

// @ 0x00bfc5f0
#pragma pack(push, 1)
struct C_00bfc5f0 { char pad[0x70]; int field; int Get(); };
#pragma pack(pop)
int C_00bfc5f0::Get() { return field; }

// @ 0x00c00650
#pragma pack(push, 1)
struct C_00c00650 { char pad[0x11c]; int field; int Get(); };
#pragma pack(pop)
int C_00c00650::Get() { return field; }

// @ 0x00c02c70
#pragma pack(push, 1)
struct C_00c02c70 { char pad[0x1678]; int field; int Get(); };
#pragma pack(pop)
int C_00c02c70::Get() { return field; }

// @ 0x00c03180
#pragma pack(push, 1)
struct C_00c03180 { char pad[0x1680]; int field; int Get(); };
#pragma pack(pop)
int C_00c03180::Get() { return field; }

// @ 0x00c04590
#pragma pack(push, 1)
struct C_00c04590 { char pad[0x1674]; int field; int Get(); };
#pragma pack(pop)
int C_00c04590::Get() { return field; }

// @ 0x00c0b750
#pragma pack(push, 1)
struct C_00c0b750 { char pad[0xf98]; int field; int Get(); };
#pragma pack(pop)
int C_00c0b750::Get() { return field; }

// @ 0x00c0b760
#pragma pack(push, 1)
struct C_00c0b760 { char pad[0xb34]; int field; int Get(); };
#pragma pack(pop)
int C_00c0b760::Get() { return field; }

// @ 0x00c0b8d0
#pragma pack(push, 1)
struct C_00c0b8d0 { char pad[0xb88]; int field; int Get(); };
#pragma pack(pop)
int C_00c0b8d0::Get() { return field; }

// @ 0x00c0b900
#pragma pack(push, 1)
struct C_00c0b900 { char pad[0xcc4]; int field; int Get(); };
#pragma pack(pop)
int C_00c0b900::Get() { return field; }

// @ 0x00c0bbd0
#pragma pack(push, 1)
struct C_00c0bbd0 { char pad[0xb20]; int field; int Get(); };
#pragma pack(pop)
int C_00c0bbd0::Get() { return field; }

// @ 0x00c0c1a0
#pragma pack(push, 1)
struct C_00c0c1a0 { char pad[0xe84]; int field; int Get(); };
#pragma pack(pop)
int C_00c0c1a0::Get() { return field; }

// @ 0x00c0c1b0
#pragma pack(push, 1)
struct C_00c0c1b0 { char pad[0xb74]; int field; int Get(); };
#pragma pack(pop)
int C_00c0c1b0::Get() { return field; }

// @ 0x00c0c2f0
#pragma pack(push, 1)
struct C_00c0c2f0 { char pad[0xeac]; int field; int Get(); };
#pragma pack(pop)
int C_00c0c2f0::Get() { return field; }

// @ 0x00c0ee60
#pragma pack(push, 1)
struct C_00c0ee60 { char pad[0xe7c]; int field; int Get(); };
#pragma pack(pop)
int C_00c0ee60::Get() { return field; }

// @ 0x00c227b0
#pragma pack(push, 1)
struct C_00c227b0 { char pad[0xff8]; int field; int Get(); };
#pragma pack(pop)
int C_00c227b0::Get() { return field; }

// @ 0x00c227e0
#pragma pack(push, 1)
struct C_00c227e0 { char pad[0xff4]; int field; int Get(); };
#pragma pack(pop)
int C_00c227e0::Get() { return field; }

// @ 0x00c22820
#pragma pack(push, 1)
struct C_00c22820 { char pad[0xfc4]; int field; int Get(); };
#pragma pack(pop)
int C_00c22820::Get() { return field; }

// @ 0x00c22a70
#pragma pack(push, 1)
struct C_00c22a70 { char pad[0xffc]; int field; int Get(); };
#pragma pack(pop)
int C_00c22a70::Get() { return field; }

// @ 0x00c22dc0
#pragma pack(push, 1)
struct C_00c22dc0 { char pad[0x102c]; int field; int Get(); };
#pragma pack(pop)
int C_00c22dc0::Get() { return field; }

// @ 0x00c22f50
#pragma pack(push, 1)
struct C_00c22f50 { char pad[0x1014]; int field; int Get(); };
#pragma pack(pop)
int C_00c22f50::Get() { return field; }

// @ 0x00c23e40
#pragma pack(push, 1)
struct C_00c23e40 { char pad[0x1010]; int field; int Get(); };
#pragma pack(pop)
int C_00c23e40::Get() { return field; }

// @ 0x00c2f680
#pragma pack(push, 1)
struct C_00c2f680 { char pad[0x80]; int field; int Get(); };
#pragma pack(pop)
int C_00c2f680::Get() { return field; }

// @ 0x00c30cb0
#pragma pack(push, 1)
struct C_00c30cb0 { char pad[0xd0]; int field; int Get(); };
#pragma pack(pop)
int C_00c30cb0::Get() { return field; }

// @ 0x00c37710
#pragma pack(push, 1)
struct C_00c37710 { char pad[0x800]; int field; int Get(); };
#pragma pack(pop)
int C_00c37710::Get() { return field; }

// @ 0x00c37720
#pragma pack(push, 1)
struct C_00c37720 { char pad[0x7a4]; int field; int Get(); };
#pragma pack(pop)
int C_00c37720::Get() { return field; }

// @ 0x00c37730
#pragma pack(push, 1)
struct C_00c37730 { char pad[0x288]; int field; int Get(); };
#pragma pack(pop)
int C_00c37730::Get() { return field; }

// @ 0x00c38b00
#pragma pack(push, 1)
struct C_00c38b00 { char pad[0x7a8]; int field; int Get(); };
#pragma pack(pop)
int C_00c38b00::Get() { return field; }

// @ 0x00c38b80
#pragma pack(push, 1)
struct C_00c38b80 { char pad[0x7ac]; int field; int Get(); };
#pragma pack(pop)
int C_00c38b80::Get() { return field; }

// @ 0x00c3e2a0
#pragma pack(push, 1)
struct C_00c3e2a0 { char pad[0x668]; int field; int Get(); };
#pragma pack(pop)
int C_00c3e2a0::Get() { return field; }

// @ 0x00c3e790
#pragma pack(push, 1)
struct C_00c3e790 { char pad[0x670]; int field; int Get(); };
#pragma pack(pop)
int C_00c3e790::Get() { return field; }

// @ 0x00c45ce0
#pragma pack(push, 1)
struct C_00c45ce0 { char pad[0x9c]; int field; int Get(); };
#pragma pack(pop)
int C_00c45ce0::Get() { return field; }

// @ 0x00c4f020
#pragma pack(push, 1)
struct C_00c4f020 { char pad[0x208]; int field; int Get(); };
#pragma pack(pop)
int C_00c4f020::Get() { return field; }

// @ 0x00c4f030
#pragma pack(push, 1)
struct C_00c4f030 { char pad[0x204]; int field; int Get(); };
#pragma pack(pop)
int C_00c4f030::Get() { return field; }

// @ 0x00c6ff90
#pragma pack(push, 1)
struct C_00c6ff90 { char pad[0x158]; int field; int Get(); };
#pragma pack(pop)
int C_00c6ff90::Get() { return field; }

// @ 0x00c71460
#pragma pack(push, 1)
struct C_00c71460 { char pad[0x138]; int field; int Get(); };
#pragma pack(pop)
int C_00c71460::Get() { return field; }

// @ 0x00c71530
#pragma pack(push, 1)
struct C_00c71530 { char pad[0x1c0]; int field; int Get(); };
#pragma pack(pop)
int C_00c71530::Get() { return field; }

// @ 0x00c75420
#pragma pack(push, 1)
struct C_00c75420 { char pad[0x1248]; int field; int Get(); };
#pragma pack(pop)
int C_00c75420::Get() { return field; }

// @ 0x00c75570
#pragma pack(push, 1)
struct C_00c75570 { char pad[0x1244]; int field; int Get(); };
#pragma pack(pop)
int C_00c75570::Get() { return field; }

// @ 0x00c87040
#pragma pack(push, 1)
struct C_00c87040 { char pad[0x5c]; int field; int Get(); };
#pragma pack(pop)
int C_00c87040::Get() { return field; }

// @ 0x00c8e7e0
#pragma pack(push, 1)
struct C_00c8e7e0 { char pad[0x18c8]; int field; int Get(); };
#pragma pack(pop)
int C_00c8e7e0::Get() { return field; }

// @ 0x00c8ea40
#pragma pack(push, 1)
struct C_00c8ea40 { char pad[0x2d8]; int field; int Get(); };
#pragma pack(pop)
int C_00c8ea40::Get() { return field; }

// @ 0x00c8f6d0
#pragma pack(push, 1)
struct C_00c8f6d0 { char pad[0x368]; int field; int Get(); };
#pragma pack(pop)
int C_00c8f6d0::Get() { return field; }

// @ 0x00c8fed0
#pragma pack(push, 1)
struct C_00c8fed0 { char pad[0x19c4]; int field; int Get(); };
#pragma pack(pop)
int C_00c8fed0::Get() { return field; }

// @ 0x00c8fee0
#pragma pack(push, 1)
struct C_00c8fee0 { char pad[0x19cc]; int field; int Get(); };
#pragma pack(pop)
int C_00c8fee0::Get() { return field; }

// @ 0x00c90460
#pragma pack(push, 1)
struct C_00c90460 { char pad[0x19d0]; int field; int Get(); };
#pragma pack(pop)
int C_00c90460::Get() { return field; }

// @ 0x00c9c2b0
#pragma pack(push, 1)
struct C_00c9c2b0 { char pad[0x230]; int field; int Get(); };
#pragma pack(pop)
int C_00c9c2b0::Get() { return field; }

// @ 0x00c9d080
#pragma pack(push, 1)
struct C_00c9d080 { char pad[0x1fc]; int field; int Get(); };
#pragma pack(pop)
int C_00c9d080::Get() { return field; }

// @ 0x00c9d9e0
#pragma pack(push, 1)
struct C_00c9d9e0 { char pad[0x1f8]; int field; int Get(); };
#pragma pack(pop)
int C_00c9d9e0::Get() { return field; }

// @ 0x00c9fff0
#pragma pack(push, 1)
struct C_00c9fff0 { char pad[0xbc0]; int field; int Get(); };
#pragma pack(pop)
int C_00c9fff0::Get() { return field; }

// @ 0x00cb37c0
#pragma pack(push, 1)
struct C_00cb37c0 { char pad[0x530]; int field; int Get(); };
#pragma pack(pop)
int C_00cb37c0::Get() { return field; }

// @ 0x00cd8000
#pragma pack(push, 1)
struct C_00cd8000 { char pad[0x23c]; int field; int Get(); };
#pragma pack(pop)
int C_00cd8000::Get() { return field; }

// @ 0x00ce6950
#pragma pack(push, 1)
struct C_00ce6950 { char pad[0x184]; int field; int Get(); };
#pragma pack(pop)
int C_00ce6950::Get() { return field; }

// @ 0x00cf74f0
#pragma pack(push, 1)
struct C_00cf74f0 { char pad[0xe8]; int field; int Get(); };
#pragma pack(pop)
int C_00cf74f0::Get() { return field; }

// @ 0x00cf7500
#pragma pack(push, 1)
struct C_00cf7500 { char pad[0xec]; int field; int Get(); };
#pragma pack(pop)
int C_00cf7500::Get() { return field; }

// @ 0x00d1d8a0
#pragma pack(push, 1)
struct C_00d1d8a0 { char pad[0x10c]; int field; int Get(); };
#pragma pack(pop)
int C_00d1d8a0::Get() { return field; }

// @ 0x00d1dcd0
#pragma pack(push, 1)
struct C_00d1dcd0 { char pad[0x130]; int field; int Get(); };
#pragma pack(pop)
int C_00d1dcd0::Get() { return field; }

// @ 0x00d20940
#pragma pack(push, 1)
struct C_00d20940 { char pad[0x1ec]; int field; int Get(); };
#pragma pack(pop)
int C_00d20940::Get() { return field; }

// @ 0x00d2ba50
#pragma pack(push, 1)
struct C_00d2ba50 { char pad[0x60]; int field; int Get(); };
#pragma pack(pop)
int C_00d2ba50::Get() { return field; }

// @ 0x00e21610
#pragma pack(push, 1)
struct C_00e21610 { char pad[0x94]; int field; int Get(); };
#pragma pack(pop)
int C_00e21610::Get() { return field; }

// @ 0x00e9dd70
#pragma pack(push, 1)
struct C_00e9dd70 { char pad[0x7bc]; int field; int Get(); };
#pragma pack(pop)
int C_00e9dd70::Get() { return field; }

// @ 0x00f19190
#pragma pack(push, 1)
struct C_00f19190 { char pad[0xc0]; int field; int Get(); };
#pragma pack(pop)
int C_00f19190::Get() { return field; }

// @ 0x00f3e2a0
#pragma pack(push, 1)
struct C_00f3e2a0 { char pad[0x68]; int field; int Get(); };
#pragma pack(pop)
int C_00f3e2a0::Get() { return field; }

// @ 0x00f67d90
#pragma pack(push, 1)
struct C_00f67d90 { char pad[0x74]; int field; int Get(); };
#pragma pack(pop)
int C_00f67d90::Get() { return field; }

// @ 0x00fa0d60
#pragma pack(push, 1)
struct C_00fa0d60 { char pad[0x20c]; int field; int Get(); };
#pragma pack(pop)
int C_00fa0d60::Get() { return field; }

// @ 0x00fa0d70
#pragma pack(push, 1)
struct C_00fa0d70 { char pad[0x1cc]; int field; int Get(); };
#pragma pack(pop)
int C_00fa0d70::Get() { return field; }

// @ 0x00fa0da0
#pragma pack(push, 1)
struct C_00fa0da0 { char pad[0x1d0]; int field; int Get(); };
#pragma pack(pop)
int C_00fa0da0::Get() { return field; }

// @ 0x00fb7bb0
#pragma pack(push, 1)
struct C_00fb7bb0 { char pad[0x5c0]; int field; int Get(); };
#pragma pack(pop)
int C_00fb7bb0::Get() { return field; }

// @ 0x00fb7bc0
#pragma pack(push, 1)
struct C_00fb7bc0 { char pad[0x5c4]; int field; int Get(); };
#pragma pack(pop)
int C_00fb7bc0::Get() { return field; }

// @ 0x00fc7e50
#pragma pack(push, 1)
struct C_00fc7e50 { char pad[0xc]; int field; int Get(); };
#pragma pack(pop)
int C_00fc7e50::Get() { return field; }

// @ 0x00fcc210
#pragma pack(push, 1)
struct C_00fcc210 { char pad[0x4]; int field; int Get(); };
#pragma pack(pop)
int C_00fcc210::Get() { return field; }

// @ 0x00ff0420
#pragma pack(push, 1)
struct C_00ff0420 { char pad[0x14]; int field; int Get(); };
#pragma pack(pop)
int C_00ff0420::Get() { return field; }

// @ 0x00ff35d0
#pragma pack(push, 1)
struct C_00ff35d0 { char pad[0x24]; int field; int Get(); };
#pragma pack(pop)
int C_00ff35d0::Get() { return field; }

// @ 0x00ff3f00
#pragma pack(push, 1)
struct C_00ff3f00 { char pad[0x8c]; int field; int Get(); };
#pragma pack(pop)
int C_00ff3f00::Get() { return field; }

// @ 0x00ff3f10
#pragma pack(push, 1)
struct C_00ff3f10 { char pad[0x90]; int field; int Get(); };
#pragma pack(pop)
int C_00ff3f10::Get() { return field; }

// @ 0x00ffc2d0
#pragma pack(push, 1)
struct C_00ffc2d0 { char pad[0xd8]; int field; int Get(); };
#pragma pack(pop)
int C_00ffc2d0::Get() { return field; }

// @ 0x00ffc320
#pragma pack(push, 1)
struct C_00ffc320 { char pad[0xdc]; int field; int Get(); };
#pragma pack(pop)
int C_00ffc320::Get() { return field; }

// @ 0x01030e10
#pragma pack(push, 1)
struct C_01030e10 { char pad[0x78]; int field; int Get(); };
#pragma pack(pop)
int C_01030e10::Get() { return field; }

// @ 0x0104bd80
#pragma pack(push, 1)
struct C_0104bd80 { char pad[0x17c]; int field; int Get(); };
#pragma pack(pop)
int C_0104bd80::Get() { return field; }

// @ 0x0104bd90
#pragma pack(push, 1)
struct C_0104bd90 { char pad[0x188]; int field; int Get(); };
#pragma pack(pop)
int C_0104bd90::Get() { return field; }

// @ 0x0104bef0
#pragma pack(push, 1)
struct C_0104bef0 { char pad[0x218]; int field; int Get(); };
#pragma pack(pop)
int C_0104bef0::Get() { return field; }

// @ 0x0104bf00
#pragma pack(push, 1)
struct C_0104bf00 { char pad[0x21c]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf00::Get() { return field; }

// @ 0x0104bf10
#pragma pack(push, 1)
struct C_0104bf10 { char pad[0x220]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf10::Get() { return field; }

// @ 0x0104bf20
#pragma pack(push, 1)
struct C_0104bf20 { char pad[0x224]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf20::Get() { return field; }

// @ 0x0104bf30
#pragma pack(push, 1)
struct C_0104bf30 { char pad[0x228]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf30::Get() { return field; }

// @ 0x0104bf40
#pragma pack(push, 1)
struct C_0104bf40 { char pad[0x22c]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf40::Get() { return field; }

// @ 0x0104bf50
#pragma pack(push, 1)
struct C_0104bf50 { char pad[0x234]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf50::Get() { return field; }

// @ 0x0104bf70
#pragma pack(push, 1)
struct C_0104bf70 { char pad[0x248]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf70::Get() { return field; }

// @ 0x0104bf80
#pragma pack(push, 1)
struct C_0104bf80 { char pad[0x24c]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf80::Get() { return field; }

// @ 0x0104bf90
#pragma pack(push, 1)
struct C_0104bf90 { char pad[0x250]; int field; int Get(); };
#pragma pack(pop)
int C_0104bf90::Get() { return field; }

// @ 0x0104bfe0
#pragma pack(push, 1)
struct C_0104bfe0 { char pad[0x240]; int field; int Get(); };
#pragma pack(pop)
int C_0104bfe0::Get() { return field; }

// @ 0x0104c100
#pragma pack(push, 1)
struct C_0104c100 { char pad[0x178]; int field; int Get(); };
#pragma pack(pop)
int C_0104c100::Get() { return field; }

// @ 0x0104c110
#pragma pack(push, 1)
struct C_0104c110 { char pad[0x210]; int field; int Get(); };
#pragma pack(pop)
int C_0104c110::Get() { return field; }

// @ 0x01067e60
#pragma pack(push, 1)
struct C_01067e60 { char pad[0x31c]; int field; int Get(); };
#pragma pack(pop)
int C_01067e60::Get() { return field; }

// @ 0x01137690
#pragma pack(push, 1)
struct C_01137690 { char pad[0x50]; int field; int Get(); };
#pragma pack(pop)
int C_01137690::Get() { return field; }

// @ 0x01139ea0
#pragma pack(push, 1)
struct C_01139ea0 { char pad[0x14c]; int field; int Get(); };
#pragma pack(pop)
int C_01139ea0::Get() { return field; }

// @ 0x0113ae10
#pragma pack(push, 1)
struct C_0113ae10 { char pad[0x44]; int field; int Get(); };
#pragma pack(pop)
int C_0113ae10::Get() { return field; }

// @ 0x011e23a0
#pragma pack(push, 1)
struct C_011e23a0 { char pad[0x24]; int field; int Get(); };
#pragma pack(pop)
int C_011e23a0::Get() { return field; }

// @ 0x011e69c0
#pragma pack(push, 1)
struct C_011e69c0 { char pad[0x8]; int field; int Get(); };
#pragma pack(pop)
int C_011e69c0::Get() { return field; }

// @ 0x011e6bf0
#pragma pack(push, 1)
struct C_011e6bf0 { char pad[0xc]; int field; int Get(); };
#pragma pack(pop)
int C_011e6bf0::Get() { return field; }

// @ 0x011eb150
#pragma pack(push, 1)
struct C_011eb150 { char pad[0x14]; int field; int Get(); };
#pragma pack(pop)
int C_011eb150::Get() { return field; }

// @ 0x011eb160
#pragma pack(push, 1)
struct C_011eb160 { char pad[0x34]; int field; int Get(); };
#pragma pack(pop)
int C_011eb160::Get() { return field; }

// @ 0x011eb170
#pragma pack(push, 1)
struct C_011eb170 { char pad[0x1c]; int field; int Get(); };
#pragma pack(pop)
int C_011eb170::Get() { return field; }

// @ 0x011f9c20
#pragma pack(push, 1)
struct C_011f9c20 { char pad[0x1230]; int field; int Get(); };
#pragma pack(pop)
int C_011f9c20::Get() { return field; }

// @ 0x011f9c30
#pragma pack(push, 1)
struct C_011f9c30 { char pad[0x1234]; int field; int Get(); };
#pragma pack(pop)
int C_011f9c30::Get() { return field; }
