// Generated by tools/matching/synth.py (template uninit_copy_pod_ref_cursor_void). Do not edit by hand.
#include <new>

// @ 0x006fa800
struct S006fa800 { char d[0x130]; };
struct I006fa800 { S006fa800* p; S006fa800& operator*() const { return *p; } I006fa800& operator++() { ++p; return *this; }
  bool operator!=(const I006fa800& o) const { return p != o.p; } };
struct R006fa800 { S006fa800* p; R006fa800(S006fa800* q) : p(q) {} };
R006fa800 FUN_006fa800(I006fa800 first, I006fa800 last, S006fa800* dest) {
    R006fa800 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S006fa800(*first);
    return r;
}


// @ 0x006fd170
struct S006fd170 { char d[0x1c]; };
struct I006fd170 { S006fd170* p; S006fd170& operator*() const { return *p; } I006fd170& operator++() { ++p; return *this; }
  bool operator!=(const I006fd170& o) const { return p != o.p; } };
struct R006fd170 { S006fd170* p; R006fd170(S006fd170* q) : p(q) {} };
R006fd170 FUN_006fd170(I006fd170 first, I006fd170 last, S006fd170* dest) {
    R006fd170 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S006fd170(*first);
    return r;
}


// @ 0x009527c0
struct S009527c0 { char d[0x28]; };
struct I009527c0 { S009527c0* p; S009527c0& operator*() const { return *p; } I009527c0& operator++() { ++p; return *this; }
  bool operator!=(const I009527c0& o) const { return p != o.p; } };
struct R009527c0 { S009527c0* p; R009527c0(S009527c0* q) : p(q) {} };
R009527c0 FUN_009527c0(I009527c0 first, I009527c0 last, S009527c0* dest) {
    R009527c0 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S009527c0(*first);
    return r;
}


// @ 0x009c64c0
struct S009c64c0 { char d[0x30]; };
struct I009c64c0 { S009c64c0* p; S009c64c0& operator*() const { return *p; } I009c64c0& operator++() { ++p; return *this; }
  bool operator!=(const I009c64c0& o) const { return p != o.p; } };
struct R009c64c0 { S009c64c0* p; R009c64c0(S009c64c0* q) : p(q) {} };
R009c64c0 FUN_009c64c0(I009c64c0 first, I009c64c0 last, S009c64c0* dest) {
    R009c64c0 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S009c64c0(*first);
    return r;
}


// @ 0x00c04920
struct S00c04920 { char d[0x20]; };
struct I00c04920 { S00c04920* p; S00c04920& operator*() const { return *p; } I00c04920& operator++() { ++p; return *this; }
  bool operator!=(const I00c04920& o) const { return p != o.p; } };
struct R00c04920 { S00c04920* p; R00c04920(S00c04920* q) : p(q) {} };
R00c04920 FUN_00c04920(I00c04920 first, I00c04920 last, S00c04920* dest) {
    R00c04920 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S00c04920(*first);
    return r;
}


// @ 0x00dfa3c0
struct S00dfa3c0 { char d[0x38]; };
struct I00dfa3c0 { S00dfa3c0* p; S00dfa3c0& operator*() const { return *p; } I00dfa3c0& operator++() { ++p; return *this; }
  bool operator!=(const I00dfa3c0& o) const { return p != o.p; } };
struct R00dfa3c0 { S00dfa3c0* p; R00dfa3c0(S00dfa3c0* q) : p(q) {} };
R00dfa3c0 FUN_00dfa3c0(I00dfa3c0 first, I00dfa3c0 last, S00dfa3c0* dest) {
    R00dfa3c0 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S00dfa3c0(*first);
    return r;
}


// @ 0x00fe8db0
struct S00fe8db0 { char d[0x2c]; };
struct I00fe8db0 { S00fe8db0* p; S00fe8db0& operator*() const { return *p; } I00fe8db0& operator++() { ++p; return *this; }
  bool operator!=(const I00fe8db0& o) const { return p != o.p; } };
struct R00fe8db0 { S00fe8db0* p; R00fe8db0(S00fe8db0* q) : p(q) {} };
R00fe8db0 FUN_00fe8db0(I00fe8db0 first, I00fe8db0 last, S00fe8db0* dest) {
    R00fe8db0 r(dest);
    for (; first != last; ++first, ++r.p) new (r.p) S00fe8db0(*first);
    return r;
}

