// Generated by tools/matching/synth.py (template variant_set_u32_member). Do not edit by hand.
typedef unsigned int u32; typedef unsigned short u16;
void __stdcall Release(int);

// @ 0x0081d800
struct V_0081d800 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081d800* Set(u32 x);
};
V_0081d800* V_0081d800::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 9) { Retype(9, 0x20, x, 4, 1); return this; }
  type = 9; flags = (flags & 2) | 0x20; a = x; b = 4; c = 1;
  return this;
}

// @ 0x0081d870
struct V_0081d870 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081d870* Set(u32 x);
};
V_0081d870* V_0081d870::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 10) { Retype(10, 0x20, x, 4, 1); return this; }
  type = 10; flags = (flags & 2) | 0x20; a = x; b = 4; c = 1;
  return this;
}

// @ 0x0081d8e0
struct V_0081d8e0 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081d8e0* Set(u32 x);
};
V_0081d8e0* V_0081d8e0::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 13) { Retype(13, 0x20, x, 4, 1); return this; }
  type = 13; flags = (flags & 2) | 0x20; a = x; b = 4; c = 1;
  return this;
}

// @ 0x0081d950
struct V_0081d950 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081d950* Set(u32 x);
};
V_0081d950* V_0081d950::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 18) { Retype(18, 0x20, x, 16, 1); return this; }
  type = 18; flags = (flags & 2) | 0x20; a = x; b = 16; c = 1;
  return this;
}

// @ 0x0081d9c0
struct V_0081d9c0 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081d9c0* Set(u32 x);
};
V_0081d9c0* V_0081d9c0::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 19) { Retype(19, 0x20, x, 16, 1); return this; }
  type = 19; flags = (flags & 2) | 0x20; a = x; b = 16; c = 1;
  return this;
}

// @ 0x0081daa0
struct V_0081daa0 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081daa0* Set(u32 x);
};
V_0081daa0* V_0081daa0::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 48) { Retype(48, 0x20, x, 8, 1); return this; }
  type = 48; flags = (flags & 2) | 0x20; a = x; b = 8; c = 1;
  return this;
}

// @ 0x0081db10
struct V_0081db10 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081db10* Set(u32 x);
};
V_0081db10* V_0081db10::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 49) { Retype(49, 0x20, x, 12, 1); return this; }
  type = 49; flags = (flags & 2) | 0x20; a = x; b = 12; c = 1;
  return this;
}

// @ 0x0081db80
struct V_0081db80 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081db80* Set(u32 x);
};
V_0081db80* V_0081db80::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 50) { Retype(50, 0x20, x, 12, 1); return this; }
  type = 50; flags = (flags & 2) | 0x20; a = x; b = 12; c = 1;
  return this;
}

// @ 0x0081dbf0
struct V_0081dbf0 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081dbf0* Set(u32 x);
};
V_0081dbf0* V_0081dbf0::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 52) { Retype(52, 0x20, x, 16, 1); return this; }
  type = 52; flags = (flags & 2) | 0x20; a = x; b = 16; c = 1;
  return this;
}

// @ 0x0081dc60
struct V_0081dc60 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_0081dc60* Set(u32 x);
};
V_0081dc60* V_0081dc60::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 51) { Retype(51, 0x20, x, 16, 1); return this; }
  type = 51; flags = (flags & 2) | 0x20; a = x; b = 16; c = 1;
  return this;
}

// @ 0x00e21b30
struct V_00e21b30 {
  u32 a, b, c, d; u16 flags, type;
  void Retype(int, int, u32, int, int);
  V_00e21b30* Set(u32 x);
};
V_00e21b30* V_00e21b30::Set(u32 x) {
  if (flags & 4) Release(1);
  if ((flags & 2) && type != 16) { Retype(16, 0x20, x, 52, 1); return this; }
  type = 16; flags = (flags & 2) | 0x20; a = x; b = 52; c = 1;
  return this;
}
