// Generated by tools/matching/synth.py (template vcall_cast_push_back_intrusive). Do not edit by hand.
struct Src {
    virtual void* v0(unsigned int id) = 0;
    virtual void* v1(unsigned int id) = 0;
    virtual void* v2(unsigned int id) = 0;
    virtual void* v3(unsigned int id) = 0;
    virtual void* v4(unsigned int id) = 0;
    virtual void* v5(unsigned int id) = 0;
    virtual void* v6(unsigned int id) = 0;
    virtual void* v7(unsigned int id) = 0;
    virtual void* v8(unsigned int id) = 0;
    virtual void* v9(unsigned int id) = 0;
    virtual void* v10(unsigned int id) = 0;
    virtual void* v11(unsigned int id) = 0;
    virtual void* v12(unsigned int id) = 0;
    virtual void* v13(unsigned int id) = 0;
    virtual void* v14(unsigned int id) = 0;
    virtual void* v15(unsigned int id) = 0;
    virtual void* v16(unsigned int id) = 0;
    virtual void* v17(unsigned int id) = 0;
    virtual void* v18(unsigned int id) = 0;
    virtual void* v19(unsigned int id) = 0;
    virtual void* v20(unsigned int id) = 0;
    virtual void* v21(unsigned int id) = 0;
    virtual void* v22(unsigned int id) = 0;
    virtual void* v23(unsigned int id) = 0;
    virtual void* v24(unsigned int id) = 0;
    virtual void* v25(unsigned int id) = 0;
    virtual void* v26(unsigned int id) = 0;
    virtual void* v27(unsigned int id) = 0;
    virtual void* v28(unsigned int id) = 0;
    virtual void* v29(unsigned int id) = 0;
    virtual void* v30(unsigned int id) = 0;
    virtual void* v31(unsigned int id) = 0;
    virtual void* v32(unsigned int id) = 0;
    virtual void* v33(unsigned int id) = 0;
    virtual void* v34(unsigned int id) = 0;
    virtual void* v35(unsigned int id) = 0;
    virtual void* v36(unsigned int id) = 0;
    virtual void* v37(unsigned int id) = 0;
    virtual void* v38(unsigned int id) = 0;
    virtual void* v39(unsigned int id) = 0;
    virtual void* v40(unsigned int id) = 0;
    virtual void* v41(unsigned int id) = 0;
    virtual void* v42(unsigned int id) = 0;
    virtual void* v43(unsigned int id) = 0;
    virtual void* v44(unsigned int id) = 0;
    virtual void* v45(unsigned int id) = 0;
    virtual void* v46(unsigned int id) = 0;
    virtual void* v47(unsigned int id) = 0;
    virtual void* v48(unsigned int id) = 0;
    virtual void* v49(unsigned int id) = 0;
    virtual void* v50(unsigned int id) = 0;
    virtual void* v51(unsigned int id) = 0;
    virtual void* v52(unsigned int id) = 0;
    virtual void* v53(unsigned int id) = 0;
    virtual void* v54(unsigned int id) = 0;
    virtual void* v55(unsigned int id) = 0;
    virtual void* v56(unsigned int id) = 0;
    virtual void* v57(unsigned int id) = 0;
    virtual void* v58(unsigned int id) = 0;
    virtual void* v59(unsigned int id) = 0;
    virtual void* v60(unsigned int id) = 0;
    virtual void* v61(unsigned int id) = 0;
    virtual void* v62(unsigned int id) = 0;
    virtual void* v63(unsigned int id) = 0;
};
struct RefObj { virtual void AddRef() = 0; virtual void Release() = 0; };
struct Vec { RefObj** b; RefObj** e; RefObj** c; void ins(RefObj** pos, RefObj** v); };
struct Owner { int pad; Vec v; };

// @ 0x00accb30
void FUN_00accb30(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x4f176642u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00accbb0
void FUN_00accbb0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x4f396a66u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00accc30
void FUN_00accc30(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x52aa6117u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00acdff0
void FUN_00acdff0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0xee9b2232u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ace070
void FUN_00ace070(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x036be278u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ace0f0
void FUN_00ace0f0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0xd0036e08u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ad48b0
void FUN_00ad48b0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0xb033b403u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ad4930
void FUN_00ad4930(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02dd8c33u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ae05c0
void FUN_00ae05c0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0398420du) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ae5ea0
void FUN_00ae5ea0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0403df5fu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ae72d0
void FUN_00ae72d0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0137e8e0u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b1a4c0
void FUN_00b1a4c0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x017f243bu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b22f20
void FUN_00b22f20(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02c216edu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b22fa0
void FUN_00b22fa0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02e71a5au) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b236c0
void FUN_00b236c0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x901f1362u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b2d1d0
void FUN_00b2d1d0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02a8fe3cu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b2d9d0
void FUN_00b2d9d0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0xaeb336b4u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b5f990
void FUN_00b5f990(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0e9cb8bau) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b5fa10
void FUN_00b5fa10(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0436f315u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00b71d40
void FUN_00b71d40(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x06ef0ec9u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00bbf9b0
void FUN_00bbf9b0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x01b92b27u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00be2e60
void FUN_00be2e60(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x024270c4u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00bf6e00
void FUN_00bf6e00(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x00ee02c7u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00c5fc70
void FUN_00c5fc70(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x0175cdc9u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00cdb110
void FUN_00cdb110(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0xce9f6639u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00cdb620
void FUN_00cdb620(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x061494bdu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00d384b0
void FUN_00d384b0(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x7406a570u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00d3d440
void FUN_00d3d440(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x03a25119u) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00dc3250
void FUN_00dc3250(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x04e3faafu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00e10060
void FUN_00e10060(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02bca14bu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00ef2640
void FUN_00ef2640(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x070704dbu) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x00fed010
void FUN_00fed010(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x02aa5adau) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}

// @ 0x0100a740
void FUN_0100a740(Owner* o, Src* s) {
    RefObj* r = (RefObj*)(s ? s->v3(0x03960c0au) : 0);
    RefObj* t = r;
    if (r) r->AddRef();
    Vec* v = &o->v;
    if (v->e < v->c) { RefObj** d = v->e++; if (d) { *d = r; if (r) r->AddRef(); } }
    else { v->ins(v->e, &t); r = t; }
    if (r) r->Release();
}
