// Generated by tools/matching/synth.py (template vcall_float_store_direct). Do not edit by hand.
struct Src { int* Lookup(int); };

// @ 0x009c9520
struct V_009c9520 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_009c9520 { char p[12]; float f; };
struct R_009c9520 { int a; V_009c9520* v; int b; Q_009c9520* q; void FUN_009c9520(Src* s); };
void R_009c9520::FUN_009c9520(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00a07ab0
struct V_00a07ab0 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00a07ab0 { char p[4]; float f; };
struct R_00a07ab0 { int a; V_00a07ab0* v; int b; Q_00a07ab0* q; void FUN_00a07ab0(Src* s); };
void R_00a07ab0::FUN_00a07ab0(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00a07b10
struct V_00a07b10 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00a07b10 { char p[84]; float f; };
struct R_00a07b10 { int a; V_00a07b10* v; int b; Q_00a07b10* q; void FUN_00a07b10(Src* s); };
void R_00a07b10::FUN_00a07b10(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00a07b40
struct V_00a07b40 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00a07b40 { char p[80]; float f; };
struct R_00a07b40 { int a; V_00a07b40* v; int b; Q_00a07b40* q; void FUN_00a07b40(Src* s); };
void R_00a07b40::FUN_00a07b40(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00a07bd0
struct V_00a07bd0 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00a07bd0 { char p[36]; float f; };
struct R_00a07bd0 { int a; V_00a07bd0* v; int b; Q_00a07bd0* q; void FUN_00a07bd0(Src* s); };
void R_00a07bd0::FUN_00a07bd0(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00a07d30
struct V_00a07d30 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00a07d30 { char p[32]; float f; };
struct R_00a07d30 { int a; V_00a07d30* v; int b; Q_00a07d30* q; void FUN_00a07d30(Src* s); };
void R_00a07d30::FUN_00a07d30(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00aa4390
struct V_00aa4390 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00aa4390 { char p[364]; float f; };
struct R_00aa4390 { int a; V_00aa4390* v; int b; Q_00aa4390* q; void FUN_00aa4390(Src* s); };
void R_00aa4390::FUN_00aa4390(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }


// @ 0x00f544a0
struct V_00f544a0 { virtual void d0();virtual void d1();virtual void d2();virtual void d3();virtual void d4();virtual void d5();virtual void d6();virtual void d7();virtual void d8();virtual void d9();virtual void d10();virtual void d11();virtual void d12();virtual void d13();virtual void d14();virtual void d15();virtual void d16();virtual void d17();virtual void d18();virtual void d19();virtual void d20();virtual void d21();virtual void d22();virtual void d23();virtual void d24();virtual void d25();virtual void d26();virtual void d27();virtual void d28();virtual void d29();virtual void d30();virtual void d31();virtual void d32();virtual void d33();virtual void d34();virtual void d35();virtual void d36();virtual void d37(); virtual float vf(int x); };
struct Q_00f544a0 { char p[356]; float f; };
struct R_00f544a0 { int a; V_00f544a0* v; int b; Q_00f544a0* q; void FUN_00f544a0(Src* s); };
void R_00f544a0::FUN_00f544a0(Src* s) { int* a = s->Lookup(1); q->f = v->vf(*a); }

