// Generated by tools/matching/synth.py (template vcall2_chain_cdecl_ext4). Do not edit by hand.

// @ 0x00572810
struct C00572810 {};
struct B00572810 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00572810* m(); };
struct A00572810 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00572810* m(); };
void __cdecl FUN_0093a780(C00572810*, int, int, int);
bool FUN_00572810(A00572810* a, int x) { C00572810* c = a->m()->m(); FUN_0093a780(c, x, 1, 0); return true; }

// @ 0x00ac88c0
struct C00ac88c0 {};
struct B00ac88c0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00ac88c0* m(); };
struct A00ac88c0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00ac88c0* m(); };
void __cdecl FUN_0093aa70(C00ac88c0*, int, int, int);
bool FUN_00ac88c0(A00ac88c0* a, int x) { C00ac88c0* c = a->m()->m(); FUN_0093aa70(c, x, 3, 0); return true; }

// @ 0x00ae33d0
struct C00ae33d0 {};
struct B00ae33d0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00ae33d0* m(); };
struct A00ae33d0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00ae33d0* m(); };
void __cdecl FUN_0093a780(C00ae33d0*, int, int, int);
bool FUN_00ae33d0(A00ae33d0* a, int x) { C00ae33d0* c = a->m()->m(); FUN_0093a780(c, x, 4, 0); return true; }

// @ 0x00ae3400
struct C00ae3400 {};
struct B00ae3400 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00ae3400* m(); };
struct A00ae3400 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00ae3400* m(); };
void __cdecl FUN_0093aa70(C00ae3400*, int, int, int);
bool FUN_00ae3400(A00ae3400* a, int x) { C00ae3400* c = a->m()->m(); FUN_0093aa70(c, x, 4, 0); return true; }

// @ 0x00aff840
struct C00aff840 {};
struct B00aff840 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00aff840* m(); };
struct A00aff840 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00aff840* m(); };
void __cdecl FUN_0093a800(C00aff840*, int, int, int);
bool FUN_00aff840(A00aff840* a, int x) { C00aff840* c = a->m()->m(); FUN_0093a800(c, x, 1, 0); return true; }

// @ 0x00b6e3a0
struct C00b6e3a0 {};
struct B00b6e3a0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00b6e3a0* m(); };
struct A00b6e3a0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00b6e3a0* m(); };
void __cdecl FUN_0093a780(C00b6e3a0*, int, int, int);
bool FUN_00b6e3a0(A00b6e3a0* a, int x) { C00b6e3a0* c = a->m()->m(); FUN_0093a780(c, x, 3, 0); return true; }

// @ 0x00bc3270
struct C00bc3270 {};
struct B00bc3270 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00bc3270* m(); };
struct A00bc3270 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00bc3270* m(); };
void __cdecl FUN_0093a700(C00bc3270*, int, int, int);
bool FUN_00bc3270(A00bc3270* a, int x) { C00bc3270* c = a->m()->m(); FUN_0093a700(c, x, 1, 0); return true; }

// @ 0x00c6a080
struct C00c6a080 {};
struct B00c6a080 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00c6a080* m(); };
struct A00c6a080 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00c6a080* m(); };
void __cdecl FUN_0093a780(C00c6a080*, int, int, int);
bool FUN_00c6a080(A00c6a080* a, int x) { C00c6a080* c = a->m()->m(); FUN_0093a780(c, x, 2, 0); return true; }

// @ 0x00c6a0b0
struct C00c6a0b0 {};
struct B00c6a0b0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5();  virtual C00c6a0b0* m(); };
struct A00c6a0b0 { virtual void p0(); virtual void p1(); virtual void p2(); virtual void p3(); virtual void p4(); virtual void p5(); virtual void p6(); virtual void p7();  virtual B00c6a0b0* m(); };
void __cdecl FUN_0093aa70(C00c6a0b0*, int, int, int);
bool FUN_00c6a0b0(A00c6a0b0* a, int x) { C00c6a0b0* c = a->m()->m(); FUN_0093aa70(c, x, 2, 0); return true; }
