// Generated by tools/matching/synth.py (template vec3_zero_y_extern_sse). Do not edit by hand.

// @ 0x01277bf0
extern const float g_01485720;
extern float g_015e5040;
extern float g_015e5044;
extern float g_015e5048;
void FUN_01277bf0() { g_015e5040 = 0.0f; g_015e5044 = g_01485720; g_015e5048 = 0.0f; }

// @ 0x01278600
extern const float g_01485720;
extern float g_015e52bc;
extern float g_015e52c0;
extern float g_015e52c4;
void FUN_01278600() { g_015e52bc = 0.0f; g_015e52c0 = g_01485720; g_015e52c4 = 0.0f; }

// @ 0x01278db0
extern const float g_01485720;
extern float g_015e5534;
extern float g_015e5538;
extern float g_015e553c;
void FUN_01278db0() { g_015e5534 = 0.0f; g_015e5538 = g_01485720; g_015e553c = 0.0f; }

// @ 0x01279430
extern const float g_01485720;
extern float g_015e57ac;
extern float g_015e57b0;
extern float g_015e57b4;
void FUN_01279430() { g_015e57ac = 0.0f; g_015e57b0 = g_01485720; g_015e57b4 = 0.0f; }

// @ 0x01279ac0
extern const float g_01485720;
extern float g_015e5a28;
extern float g_015e5a2c;
extern float g_015e5a30;
void FUN_01279ac0() { g_015e5a28 = 0.0f; g_015e5a2c = g_01485720; g_015e5a30 = 0.0f; }

// @ 0x0127a140
extern const float g_01485720;
extern float g_015e5cb0;
extern float g_015e5cb4;
extern float g_015e5cb8;
void FUN_0127a140() { g_015e5cb0 = 0.0f; g_015e5cb4 = g_01485720; g_015e5cb8 = 0.0f; }

// @ 0x0127a7a0
extern const float g_01485720;
extern float g_015e5f2c;
extern float g_015e5f30;
extern float g_015e5f34;
void FUN_0127a7a0() { g_015e5f2c = 0.0f; g_015e5f30 = g_01485720; g_015e5f34 = 0.0f; }

// @ 0x0127ae00
extern const float g_01485720;
extern float g_015e61a4;
extern float g_015e61a8;
extern float g_015e61ac;
void FUN_0127ae00() { g_015e61a4 = 0.0f; g_015e61a8 = g_01485720; g_015e61ac = 0.0f; }

// @ 0x0127b490
extern const float g_01485720;
extern float g_015e641c;
extern float g_015e6420;
extern float g_015e6424;
void FUN_0127b490() { g_015e641c = 0.0f; g_015e6420 = g_01485720; g_015e6424 = 0.0f; }

// @ 0x0127baf0
extern const float g_01485720;
extern float g_015e6694;
extern float g_015e6698;
extern float g_015e669c;
void FUN_0127baf0() { g_015e6694 = 0.0f; g_015e6698 = g_01485720; g_015e669c = 0.0f; }

// @ 0x0127c150
extern const float g_01485720;
extern float g_015e690c;
extern float g_015e6910;
extern float g_015e6914;
void FUN_0127c150() { g_015e690c = 0.0f; g_015e6910 = g_01485720; g_015e6914 = 0.0f; }

// @ 0x0127c7e0
extern const float g_01485720;
extern float g_015e6b84;
extern float g_015e6b88;
extern float g_015e6b8c;
void FUN_0127c7e0() { g_015e6b84 = 0.0f; g_015e6b88 = g_01485720; g_015e6b8c = 0.0f; }

// @ 0x0127ce80
extern const float g_01485720;
extern float g_015e6e04;
extern float g_015e6e08;
extern float g_015e6e0c;
void FUN_0127ce80() { g_015e6e04 = 0.0f; g_015e6e08 = g_01485720; g_015e6e0c = 0.0f; }

// @ 0x0127d4f0
extern const float g_01485720;
extern float g_015e707c;
extern float g_015e7080;
extern float g_015e7084;
void FUN_0127d4f0() { g_015e707c = 0.0f; g_015e7080 = g_01485720; g_015e7084 = 0.0f; }

// @ 0x0127db50
extern const float g_01485720;
extern float g_015e72f4;
extern float g_015e72f8;
extern float g_015e72fc;
void FUN_0127db50() { g_015e72f4 = 0.0f; g_015e72f8 = g_01485720; g_015e72fc = 0.0f; }

// @ 0x0127e1b0
extern const float g_01485720;
extern float g_015e756c;
extern float g_015e7570;
extern float g_015e7574;
void FUN_0127e1b0() { g_015e756c = 0.0f; g_015e7570 = g_01485720; g_015e7574 = 0.0f; }

// @ 0x0127e810
extern const float g_01485720;
extern float g_015e77e4;
extern float g_015e77e8;
extern float g_015e77ec;
void FUN_0127e810() { g_015e77e4 = 0.0f; g_015e77e8 = g_01485720; g_015e77ec = 0.0f; }

// @ 0x0127ee70
extern const float g_01485720;
extern float g_015e7a5c;
extern float g_015e7a60;
extern float g_015e7a64;
void FUN_0127ee70() { g_015e7a5c = 0.0f; g_015e7a60 = g_01485720; g_015e7a64 = 0.0f; }

// @ 0x0127f4f0
extern const float g_01485720;
extern float g_015e7cd4;
extern float g_015e7cd8;
extern float g_015e7cdc;
void FUN_0127f4f0() { g_015e7cd4 = 0.0f; g_015e7cd8 = g_01485720; g_015e7cdc = 0.0f; }

// @ 0x0127fb50
extern const float g_01485720;
extern float g_015e7f4c;
extern float g_015e7f50;
extern float g_015e7f54;
void FUN_0127fb50() { g_015e7f4c = 0.0f; g_015e7f50 = g_01485720; g_015e7f54 = 0.0f; }

// @ 0x012801b0
extern const float g_01485720;
extern float g_015e81c4;
extern float g_015e81c8;
extern float g_015e81cc;
void FUN_012801b0() { g_015e81c4 = 0.0f; g_015e81c8 = g_01485720; g_015e81cc = 0.0f; }

// @ 0x01280810
extern const float g_01485720;
extern float g_015e843c;
extern float g_015e8440;
extern float g_015e8444;
void FUN_01280810() { g_015e843c = 0.0f; g_015e8440 = g_01485720; g_015e8444 = 0.0f; }

// @ 0x01280e80
extern const float g_01485720;
extern float g_015e86b4;
extern float g_015e86b8;
extern float g_015e86bc;
void FUN_01280e80() { g_015e86b4 = 0.0f; g_015e86b8 = g_01485720; g_015e86bc = 0.0f; }

// @ 0x012814f0
extern const float g_01485720;
extern float g_015e8938;
extern float g_015e893c;
extern float g_015e8940;
void FUN_012814f0() { g_015e8938 = 0.0f; g_015e893c = g_01485720; g_015e8940 = 0.0f; }

// @ 0x01281bf0
extern const float g_01485720;
extern float g_015e8bbc;
extern float g_015e8bc0;
extern float g_015e8bc4;
void FUN_01281bf0() { g_015e8bbc = 0.0f; g_015e8bc0 = g_01485720; g_015e8bc4 = 0.0f; }

// @ 0x01282250
extern const float g_01485720;
extern float g_015e8e34;
extern float g_015e8e38;
extern float g_015e8e3c;
void FUN_01282250() { g_015e8e34 = 0.0f; g_015e8e38 = g_01485720; g_015e8e3c = 0.0f; }

// @ 0x012828b0
extern const float g_01485720;
extern float g_015e90ac;
extern float g_015e90b0;
extern float g_015e90b4;
void FUN_012828b0() { g_015e90ac = 0.0f; g_015e90b0 = g_01485720; g_015e90b4 = 0.0f; }

// @ 0x01282f10
extern const float g_01485720;
extern float g_015e9324;
extern float g_015e9328;
extern float g_015e932c;
void FUN_01282f10() { g_015e9324 = 0.0f; g_015e9328 = g_01485720; g_015e932c = 0.0f; }

// @ 0x01283580
extern const float g_01485720;
extern float g_015e959c;
extern float g_015e95a0;
extern float g_015e95a4;
void FUN_01283580() { g_015e959c = 0.0f; g_015e95a0 = g_01485720; g_015e95a4 = 0.0f; }

// @ 0x01283be0
extern const float g_01485720;
extern float g_015e9814;
extern float g_015e9818;
extern float g_015e981c;
void FUN_01283be0() { g_015e9814 = 0.0f; g_015e9818 = g_01485720; g_015e981c = 0.0f; }

// @ 0x01284240
extern const float g_01485720;
extern float g_015e9a8c;
extern float g_015e9a90;
extern float g_015e9a94;
void FUN_01284240() { g_015e9a8c = 0.0f; g_015e9a90 = g_01485720; g_015e9a94 = 0.0f; }

// @ 0x012848a0
extern const float g_01485720;
extern float g_015e9d04;
extern float g_015e9d08;
extern float g_015e9d0c;
void FUN_012848a0() { g_015e9d04 = 0.0f; g_015e9d08 = g_01485720; g_015e9d0c = 0.0f; }

// @ 0x01284f00
extern const float g_01485720;
extern float g_015e9f7c;
extern float g_015e9f80;
extern float g_015e9f84;
void FUN_01284f00() { g_015e9f7c = 0.0f; g_015e9f80 = g_01485720; g_015e9f84 = 0.0f; }

// @ 0x01285580
extern const float g_01485720;
extern float g_015ea1f4;
extern float g_015ea1f8;
extern float g_015ea1fc;
void FUN_01285580() { g_015ea1f4 = 0.0f; g_015ea1f8 = g_01485720; g_015ea1fc = 0.0f; }

// @ 0x01285be0
extern const float g_01485720;
extern float g_015ea46c;
extern float g_015ea470;
extern float g_015ea474;
void FUN_01285be0() { g_015ea46c = 0.0f; g_015ea470 = g_01485720; g_015ea474 = 0.0f; }

// @ 0x01286240
extern const float g_01485720;
extern float g_015ea6e8;
extern float g_015ea6ec;
extern float g_015ea6f0;
void FUN_01286240() { g_015ea6e8 = 0.0f; g_015ea6ec = g_01485720; g_015ea6f0 = 0.0f; }

// @ 0x012868a0
extern const float g_01485720;
extern float g_015ea964;
extern float g_015ea968;
extern float g_015ea96c;
void FUN_012868a0() { g_015ea964 = 0.0f; g_015ea968 = g_01485720; g_015ea96c = 0.0f; }

// @ 0x01286f00
extern const float g_01485720;
extern float g_015eabdc;
extern float g_015eabe0;
extern float g_015eabe4;
void FUN_01286f00() { g_015eabdc = 0.0f; g_015eabe0 = g_01485720; g_015eabe4 = 0.0f; }

// @ 0x01287580
extern const float g_01485720;
extern float g_015eae54;
extern float g_015eae58;
extern float g_015eae5c;
void FUN_01287580() { g_015eae54 = 0.0f; g_015eae58 = g_01485720; g_015eae5c = 0.0f; }

// @ 0x01287be0
extern const float g_01485720;
extern float g_015eb0cc;
extern float g_015eb0d0;
extern float g_015eb0d4;
void FUN_01287be0() { g_015eb0cc = 0.0f; g_015eb0d0 = g_01485720; g_015eb0d4 = 0.0f; }

// @ 0x01288240
extern const float g_01485720;
extern float g_015eb344;
extern float g_015eb348;
extern float g_015eb34c;
void FUN_01288240() { g_015eb344 = 0.0f; g_015eb348 = g_01485720; g_015eb34c = 0.0f; }

// @ 0x012888a0
extern const float g_01485720;
extern float g_015eb5bc;
extern float g_015eb5c0;
extern float g_015eb5c4;
void FUN_012888a0() { g_015eb5bc = 0.0f; g_015eb5c0 = g_01485720; g_015eb5c4 = 0.0f; }

// @ 0x01288f00
extern const float g_01485720;
extern float g_015eb834;
extern float g_015eb838;
extern float g_015eb83c;
void FUN_01288f00() { g_015eb834 = 0.0f; g_015eb838 = g_01485720; g_015eb83c = 0.0f; }

// @ 0x012895f0
extern const float g_01485720;
extern float g_015ebabc;
extern float g_015ebac0;
extern float g_015ebac4;
void FUN_012895f0() { g_015ebabc = 0.0f; g_015ebac0 = g_01485720; g_015ebac4 = 0.0f; }

// @ 0x01289c50
extern const float g_01485720;
extern float g_015ebd34;
extern float g_015ebd38;
extern float g_015ebd3c;
void FUN_01289c50() { g_015ebd34 = 0.0f; g_015ebd38 = g_01485720; g_015ebd3c = 0.0f; }

// @ 0x0128a2e0
extern const float g_01485720;
extern float g_015ebfac;
extern float g_015ebfb0;
extern float g_015ebfb4;
void FUN_0128a2e0() { g_015ebfac = 0.0f; g_015ebfb0 = g_01485720; g_015ebfb4 = 0.0f; }

// @ 0x0128a940
extern const float g_01485720;
extern float g_015ec224;
extern float g_015ec228;
extern float g_015ec22c;
void FUN_0128a940() { g_015ec224 = 0.0f; g_015ec228 = g_01485720; g_015ec22c = 0.0f; }

// @ 0x0128afa0
extern const float g_01485720;
extern float g_015ec49c;
extern float g_015ec4a0;
extern float g_015ec4a4;
void FUN_0128afa0() { g_015ec49c = 0.0f; g_015ec4a0 = g_01485720; g_015ec4a4 = 0.0f; }

// @ 0x0128b600
extern const float g_01485720;
extern float g_015ec714;
extern float g_015ec718;
extern float g_015ec71c;
void FUN_0128b600() { g_015ec714 = 0.0f; g_015ec718 = g_01485720; g_015ec71c = 0.0f; }

// @ 0x0128bc60
extern const float g_01485720;
extern float g_015ec98c;
extern float g_015ec990;
extern float g_015ec994;
void FUN_0128bc60() { g_015ec98c = 0.0f; g_015ec990 = g_01485720; g_015ec994 = 0.0f; }

// @ 0x0128c2c0
extern const float g_01485720;
extern float g_015ecc04;
extern float g_015ecc08;
extern float g_015ecc0c;
void FUN_0128c2c0() { g_015ecc04 = 0.0f; g_015ecc08 = g_01485720; g_015ecc0c = 0.0f; }

// @ 0x0128c920
extern const float g_01485720;
extern float g_015ece7c;
extern float g_015ece80;
extern float g_015ece84;
void FUN_0128c920() { g_015ece7c = 0.0f; g_015ece80 = g_01485720; g_015ece84 = 0.0f; }

// @ 0x0128cf80
extern const float g_01485720;
extern float g_015ed0f4;
extern float g_015ed0f8;
extern float g_015ed0fc;
void FUN_0128cf80() { g_015ed0f4 = 0.0f; g_015ed0f8 = g_01485720; g_015ed0fc = 0.0f; }

// @ 0x0128d5e0
extern const float g_01485720;
extern float g_015ed36c;
extern float g_015ed370;
extern float g_015ed374;
void FUN_0128d5e0() { g_015ed36c = 0.0f; g_015ed370 = g_01485720; g_015ed374 = 0.0f; }

// @ 0x0128dc40
extern const float g_01485720;
extern float g_015ed5e4;
extern float g_015ed5e8;
extern float g_015ed5ec;
void FUN_0128dc40() { g_015ed5e4 = 0.0f; g_015ed5e8 = g_01485720; g_015ed5ec = 0.0f; }

// @ 0x0128e2a0
extern const float g_01485720;
extern float g_015ed85c;
extern float g_015ed860;
extern float g_015ed864;
void FUN_0128e2a0() { g_015ed85c = 0.0f; g_015ed860 = g_01485720; g_015ed864 = 0.0f; }

// @ 0x0128e900
extern const float g_01485720;
extern float g_015edad4;
extern float g_015edad8;
extern float g_015edadc;
void FUN_0128e900() { g_015edad4 = 0.0f; g_015edad8 = g_01485720; g_015edadc = 0.0f; }

// @ 0x0128ef60
extern const float g_01485720;
extern float g_015edd4c;
extern float g_015edd50;
extern float g_015edd54;
void FUN_0128ef60() { g_015edd4c = 0.0f; g_015edd50 = g_01485720; g_015edd54 = 0.0f; }

// @ 0x0128f5f0
extern const float g_01485720;
extern float g_015edfc4;
extern float g_015edfc8;
extern float g_015edfcc;
void FUN_0128f5f0() { g_015edfc4 = 0.0f; g_015edfc8 = g_01485720; g_015edfcc = 0.0f; }

// @ 0x0128fc80
extern const float g_01485720;
extern float g_015ee23c;
extern float g_015ee240;
extern float g_015ee244;
void FUN_0128fc80() { g_015ee23c = 0.0f; g_015ee240 = g_01485720; g_015ee244 = 0.0f; }

// @ 0x01290320
extern const float g_01485720;
extern float g_015ee4c4;
extern float g_015ee4c8;
extern float g_015ee4cc;
void FUN_01290320() { g_015ee4c4 = 0.0f; g_015ee4c8 = g_01485720; g_015ee4cc = 0.0f; }

// @ 0x012909a0
extern const float g_01485720;
extern float g_015ee73c;
extern float g_015ee740;
extern float g_015ee744;
void FUN_012909a0() { g_015ee73c = 0.0f; g_015ee740 = g_01485720; g_015ee744 = 0.0f; }

// @ 0x01291000
extern const float g_01485720;
extern float g_015ee9cc;
extern float g_015ee9d0;
extern float g_015ee9d4;
void FUN_01291000() { g_015ee9cc = 0.0f; g_015ee9d0 = g_01485720; g_015ee9d4 = 0.0f; }

// @ 0x01291720
extern const float g_01485720;
extern float g_015eec58;
extern float g_015eec5c;
extern float g_015eec60;
void FUN_01291720() { g_015eec58 = 0.0f; g_015eec5c = g_01485720; g_015eec60 = 0.0f; }

// @ 0x01291dc0
extern const float g_01485720;
extern float g_015eeedc;
extern float g_015eeee0;
extern float g_015eeee4;
void FUN_01291dc0() { g_015eeedc = 0.0f; g_015eeee0 = g_01485720; g_015eeee4 = 0.0f; }

// @ 0x01292460
extern const float g_01485720;
extern float g_015ef154;
extern float g_015ef158;
extern float g_015ef15c;
void FUN_01292460() { g_015ef154 = 0.0f; g_015ef158 = g_01485720; g_015ef15c = 0.0f; }

// @ 0x01292ac0
extern const float g_01485720;
extern float g_015ef3cc;
extern float g_015ef3d0;
extern float g_015ef3d4;
void FUN_01292ac0() { g_015ef3cc = 0.0f; g_015ef3d0 = g_01485720; g_015ef3d4 = 0.0f; }

// @ 0x01293120
extern const float g_01485720;
extern float g_015ef644;
extern float g_015ef648;
extern float g_015ef64c;
void FUN_01293120() { g_015ef644 = 0.0f; g_015ef648 = g_01485720; g_015ef64c = 0.0f; }

// @ 0x01293780
extern const float g_01485720;
extern float g_015ef8bc;
extern float g_015ef8c0;
extern float g_015ef8c4;
void FUN_01293780() { g_015ef8bc = 0.0f; g_015ef8c0 = g_01485720; g_015ef8c4 = 0.0f; }

// @ 0x01293e10
extern const float g_01485720;
extern float g_015efb34;
extern float g_015efb38;
extern float g_015efb3c;
void FUN_01293e10() { g_015efb34 = 0.0f; g_015efb38 = g_01485720; g_015efb3c = 0.0f; }

// @ 0x01294490
extern const float g_01485720;
extern float g_015efdac;
extern float g_015efdb0;
extern float g_015efdb4;
void FUN_01294490() { g_015efdac = 0.0f; g_015efdb0 = g_01485720; g_015efdb4 = 0.0f; }

// @ 0x01294af0
extern const float g_01485720;
extern float g_015f0034;
extern float g_015f0038;
extern float g_015f003c;
void FUN_01294af0() { g_015f0034 = 0.0f; g_015f0038 = g_01485720; g_015f003c = 0.0f; }

// @ 0x012951a0
extern const float g_01485720;
extern float g_015f02b4;
extern float g_015f02b8;
extern float g_015f02bc;
void FUN_012951a0() { g_015f02b4 = 0.0f; g_015f02b8 = g_01485720; g_015f02bc = 0.0f; }

// @ 0x01295800
extern const float g_01485720;
extern float g_015f053c;
extern float g_015f0540;
extern float g_015f0544;
void FUN_01295800() { g_015f053c = 0.0f; g_015f0540 = g_01485720; g_015f0544 = 0.0f; }

// @ 0x01295e90
extern const float g_01485720;
extern float g_015f07b4;
extern float g_015f07b8;
extern float g_015f07bc;
void FUN_01295e90() { g_015f07b4 = 0.0f; g_015f07b8 = g_01485720; g_015f07bc = 0.0f; }

// @ 0x012964f0
extern const float g_01485720;
extern float g_015f0a3c;
extern float g_015f0a40;
extern float g_015f0a44;
void FUN_012964f0() { g_015f0a3c = 0.0f; g_015f0a40 = g_01485720; g_015f0a44 = 0.0f; }

// @ 0x01296b70
extern const float g_01485720;
extern float g_015f0cb4;
extern float g_015f0cb8;
extern float g_015f0cbc;
void FUN_01296b70() { g_015f0cb4 = 0.0f; g_015f0cb8 = g_01485720; g_015f0cbc = 0.0f; }

// @ 0x01297200
extern const float g_01485720;
extern float g_015f0f2c;
extern float g_015f0f30;
extern float g_015f0f34;
void FUN_01297200() { g_015f0f2c = 0.0f; g_015f0f30 = g_01485720; g_015f0f34 = 0.0f; }

// @ 0x01297860
extern const float g_01485720;
extern float g_015f11a4;
extern float g_015f11a8;
extern float g_015f11ac;
void FUN_01297860() { g_015f11a4 = 0.0f; g_015f11a8 = g_01485720; g_015f11ac = 0.0f; }

// @ 0x01297ec0
extern const float g_01485720;
extern float g_015f141c;
extern float g_015f1420;
extern float g_015f1424;
void FUN_01297ec0() { g_015f141c = 0.0f; g_015f1420 = g_01485720; g_015f1424 = 0.0f; }

// @ 0x01298520
extern const float g_01485720;
extern float g_015f1694;
extern float g_015f1698;
extern float g_015f169c;
void FUN_01298520() { g_015f1694 = 0.0f; g_015f1698 = g_01485720; g_015f169c = 0.0f; }

// @ 0x01298b80
extern const float g_01485720;
extern float g_015f190c;
extern float g_015f1910;
extern float g_015f1914;
void FUN_01298b80() { g_015f190c = 0.0f; g_015f1910 = g_01485720; g_015f1914 = 0.0f; }

// @ 0x012991e0
extern const float g_01485720;
extern float g_015f1b84;
extern float g_015f1b88;
extern float g_015f1b8c;
void FUN_012991e0() { g_015f1b84 = 0.0f; g_015f1b88 = g_01485720; g_015f1b8c = 0.0f; }

// @ 0x01299870
extern const float g_01485720;
extern float g_015f1dfc;
extern float g_015f1e00;
extern float g_015f1e04;
void FUN_01299870() { g_015f1dfc = 0.0f; g_015f1e00 = g_01485720; g_015f1e04 = 0.0f; }

// @ 0x01299ed0
extern const float g_01485720;
extern float g_015f2078;
extern float g_015f207c;
extern float g_015f2080;
void FUN_01299ed0() { g_015f2078 = 0.0f; g_015f207c = g_01485720; g_015f2080 = 0.0f; }

// @ 0x0129a590
extern const float g_01485720;
extern float g_015f22ec;
extern float g_015f22f0;
extern float g_015f22f4;
void FUN_0129a590() { g_015f22ec = 0.0f; g_015f22f0 = g_01485720; g_015f22f4 = 0.0f; }

// @ 0x0129abf0
extern const float g_01485720;
extern float g_015f2564;
extern float g_015f2568;
extern float g_015f256c;
void FUN_0129abf0() { g_015f2564 = 0.0f; g_015f2568 = g_01485720; g_015f256c = 0.0f; }

// @ 0x0129b280
extern const float g_01485720;
extern float g_015f27dc;
extern float g_015f27e0;
extern float g_015f27e4;
void FUN_0129b280() { g_015f27dc = 0.0f; g_015f27e0 = g_01485720; g_015f27e4 = 0.0f; }

// @ 0x0129b8e0
extern const float g_01485720;
extern float g_015f2a64;
extern float g_015f2a68;
extern float g_015f2a6c;
void FUN_0129b8e0() { g_015f2a64 = 0.0f; g_015f2a68 = g_01485720; g_015f2a6c = 0.0f; }

// @ 0x0129bf40
extern const float g_01485720;
extern float g_015f2cdc;
extern float g_015f2ce0;
extern float g_015f2ce4;
void FUN_0129bf40() { g_015f2cdc = 0.0f; g_015f2ce0 = g_01485720; g_015f2ce4 = 0.0f; }

// @ 0x0129c5d0
extern const float g_01485720;
extern float g_015f2f54;
extern float g_015f2f58;
extern float g_015f2f5c;
void FUN_0129c5d0() { g_015f2f54 = 0.0f; g_015f2f58 = g_01485720; g_015f2f5c = 0.0f; }

// @ 0x0129cc30
extern const float g_01485720;
extern float g_015f31cc;
extern float g_015f31d0;
extern float g_015f31d4;
void FUN_0129cc30() { g_015f31cc = 0.0f; g_015f31d0 = g_01485720; g_015f31d4 = 0.0f; }

// @ 0x0129d290
extern const float g_01485720;
extern float g_015f344c;
extern float g_015f3450;
extern float g_015f3454;
void FUN_0129d290() { g_015f344c = 0.0f; g_015f3450 = g_01485720; g_015f3454 = 0.0f; }

// @ 0x0129d8f0
extern const float g_01485720;
extern float g_015f36dc;
extern float g_015f36e0;
extern float g_015f36e4;
void FUN_0129d8f0() { g_015f36dc = 0.0f; g_015f36e0 = g_01485720; g_015f36e4 = 0.0f; }

// @ 0x0129e660
extern const float g_01485720;
extern float g_015f3bcc;
extern float g_015f3bd0;
extern float g_015f3bd4;
void FUN_0129e660() { g_015f3bcc = 0.0f; g_015f3bd0 = g_01485720; g_015f3bd4 = 0.0f; }

// @ 0x0129ecc0
extern const float g_01485720;
extern float g_015f3e44;
extern float g_015f3e48;
extern float g_015f3e4c;
void FUN_0129ecc0() { g_015f3e44 = 0.0f; g_015f3e48 = g_01485720; g_015f3e4c = 0.0f; }

// @ 0x0129f320
extern const float g_01485720;
extern float g_015f40c0;
extern float g_015f40c4;
extern float g_015f40c8;
void FUN_0129f320() { g_015f40c0 = 0.0f; g_015f40c4 = g_01485720; g_015f40c8 = 0.0f; }

// @ 0x0129f9b0
extern const float g_01485720;
extern float g_015f4340;
extern float g_015f4344;
extern float g_015f4348;
void FUN_0129f9b0() { g_015f4340 = 0.0f; g_015f4344 = g_01485720; g_015f4348 = 0.0f; }

// @ 0x012a0040
extern const float g_01485720;
extern float g_015f45bc;
extern float g_015f45c0;
extern float g_015f45c4;
void FUN_012a0040() { g_015f45bc = 0.0f; g_015f45c0 = g_01485720; g_015f45c4 = 0.0f; }

// @ 0x012a06a0
extern const float g_01485720;
extern float g_015f4834;
extern float g_015f4838;
extern float g_015f483c;
void FUN_012a06a0() { g_015f4834 = 0.0f; g_015f4838 = g_01485720; g_015f483c = 0.0f; }

// @ 0x012a0d00
extern const float g_01485720;
extern float g_015f4abc;
extern float g_015f4ac0;
extern float g_015f4ac4;
void FUN_012a0d00() { g_015f4abc = 0.0f; g_015f4ac0 = g_01485720; g_015f4ac4 = 0.0f; }

// @ 0x012a1390
extern const float g_01485720;
extern float g_015f4d38;
extern float g_015f4d3c;
extern float g_015f4d40;
void FUN_012a1390() { g_015f4d38 = 0.0f; g_015f4d3c = g_01485720; g_015f4d40 = 0.0f; }

// @ 0x012a1a00
extern const float g_01485720;
extern float g_015f4fc4;
extern float g_015f4fc8;
extern float g_015f4fcc;
void FUN_012a1a00() { g_015f4fc4 = 0.0f; g_015f4fc8 = g_01485720; g_015f4fcc = 0.0f; }

// @ 0x012a2080
extern const float g_01485720;
extern float g_015f53ac;
extern float g_015f53b0;
extern float g_015f53b4;
void FUN_012a2080() { g_015f53ac = 0.0f; g_015f53b0 = g_01485720; g_015f53b4 = 0.0f; }

// @ 0x012a2ab0
extern const float g_01485720;
extern float g_015f5768;
extern float g_015f576c;
extern float g_015f5770;
void FUN_012a2ab0() { g_015f5768 = 0.0f; g_015f576c = g_01485720; g_015f5770 = 0.0f; }

// @ 0x012a3230
extern const float g_01485720;
extern float g_015f5a0c;
extern float g_015f5a10;
extern float g_015f5a14;
void FUN_012a3230() { g_015f5a0c = 0.0f; g_015f5a10 = g_01485720; g_015f5a14 = 0.0f; }

// @ 0x012a38c0
extern const float g_01485720;
extern float g_015f5cb4;
extern float g_015f5cb8;
extern float g_015f5cbc;
void FUN_012a38c0() { g_015f5cb4 = 0.0f; g_015f5cb8 = g_01485720; g_015f5cbc = 0.0f; }

// @ 0x012a3f40
extern const float g_01485720;
extern float g_015f5f30;
extern float g_015f5f34;
extern float g_015f5f38;
void FUN_012a3f40() { g_015f5f30 = 0.0f; g_015f5f34 = g_01485720; g_015f5f38 = 0.0f; }

// @ 0x012a45b0
extern const float g_01485720;
extern float g_015f6204;
extern float g_015f6208;
extern float g_015f620c;
void FUN_012a45b0() { g_015f6204 = 0.0f; g_015f6208 = g_01485720; g_015f620c = 0.0f; }

// @ 0x012a4e90
extern const float g_01485720;
extern float g_015f6490;
extern float g_015f6494;
extern float g_015f6498;
void FUN_012a4e90() { g_015f6490 = 0.0f; g_015f6494 = g_01485720; g_015f6498 = 0.0f; }

// @ 0x012a5500
extern const float g_01485720;
extern float g_015f6714;
extern float g_015f6718;
extern float g_015f671c;
void FUN_012a5500() { g_015f6714 = 0.0f; g_015f6718 = g_01485720; g_015f671c = 0.0f; }

// @ 0x012a5b60
extern const float g_01485720;
extern float g_015f6990;
extern float g_015f6994;
extern float g_015f6998;
void FUN_012a5b60() { g_015f6990 = 0.0f; g_015f6994 = g_01485720; g_015f6998 = 0.0f; }

// @ 0x012a61e0
extern const float g_01485720;
extern float g_015f6c0c;
extern float g_015f6c10;
extern float g_015f6c14;
void FUN_012a61e0() { g_015f6c0c = 0.0f; g_015f6c10 = g_01485720; g_015f6c14 = 0.0f; }

// @ 0x012a6840
extern const float g_01485720;
extern float g_015f6e88;
extern float g_015f6e8c;
extern float g_015f6e90;
void FUN_012a6840() { g_015f6e88 = 0.0f; g_015f6e8c = g_01485720; g_015f6e90 = 0.0f; }

// @ 0x012a6ef0
extern const float g_01485720;
extern float g_015f7104;
extern float g_015f7108;
extern float g_015f710c;
void FUN_012a6ef0() { g_015f7104 = 0.0f; g_015f7108 = g_01485720; g_015f710c = 0.0f; }

// @ 0x012a7550
extern const float g_01485720;
extern float g_015f737c;
extern float g_015f7380;
extern float g_015f7384;
void FUN_012a7550() { g_015f737c = 0.0f; g_015f7380 = g_01485720; g_015f7384 = 0.0f; }

// @ 0x012a7bb0
extern const float g_01485720;
extern float g_015f75f4;
extern float g_015f75f8;
extern float g_015f75fc;
void FUN_012a7bb0() { g_015f75f4 = 0.0f; g_015f75f8 = g_01485720; g_015f75fc = 0.0f; }

// @ 0x012a8240
extern const float g_01485720;
extern float g_015f786c;
extern float g_015f7870;
extern float g_015f7874;
void FUN_012a8240() { g_015f786c = 0.0f; g_015f7870 = g_01485720; g_015f7874 = 0.0f; }

// @ 0x012a88d0
extern const float g_01485720;
extern float g_015f7ae4;
extern float g_015f7ae8;
extern float g_015f7aec;
void FUN_012a88d0() { g_015f7ae4 = 0.0f; g_015f7ae8 = g_01485720; g_015f7aec = 0.0f; }

// @ 0x012a8fa0
extern const float g_01485720;
extern float g_015f7d60;
extern float g_015f7d64;
extern float g_015f7d68;
void FUN_012a8fa0() { g_015f7d60 = 0.0f; g_015f7d64 = g_01485720; g_015f7d68 = 0.0f; }

// @ 0x012a9640
extern const float g_01485720;
extern float g_015f7fdc;
extern float g_015f7fe0;
extern float g_015f7fe4;
void FUN_012a9640() { g_015f7fdc = 0.0f; g_015f7fe0 = g_01485720; g_015f7fe4 = 0.0f; }

// @ 0x012a9cd0
extern const float g_01485720;
extern float g_015f8258;
extern float g_015f825c;
extern float g_015f8260;
void FUN_012a9cd0() { g_015f8258 = 0.0f; g_015f825c = g_01485720; g_015f8260 = 0.0f; }

// @ 0x012aa350
extern const float g_01485720;
extern float g_015f84d4;
extern float g_015f84d8;
extern float g_015f84dc;
void FUN_012aa350() { g_015f84d4 = 0.0f; g_015f84d8 = g_01485720; g_015f84dc = 0.0f; }

// @ 0x012aa9b0
extern const float g_01485720;
extern float g_015f874c;
extern float g_015f8750;
extern float g_015f8754;
void FUN_012aa9b0() { g_015f874c = 0.0f; g_015f8750 = g_01485720; g_015f8754 = 0.0f; }

// @ 0x012ab020
extern const float g_01485720;
extern float g_015f89c4;
extern float g_015f89c8;
extern float g_015f89cc;
void FUN_012ab020() { g_015f89c4 = 0.0f; g_015f89c8 = g_01485720; g_015f89cc = 0.0f; }

// @ 0x012ab6d0
extern const float g_01485720;
extern float g_015f8c44;
extern float g_015f8c48;
extern float g_015f8c4c;
void FUN_012ab6d0() { g_015f8c44 = 0.0f; g_015f8c48 = g_01485720; g_015f8c4c = 0.0f; }

// @ 0x012abdb0
extern const float g_01485720;
extern float g_015f8ebc;
extern float g_015f8ec0;
extern float g_015f8ec4;
void FUN_012abdb0() { g_015f8ebc = 0.0f; g_015f8ec0 = g_01485720; g_015f8ec4 = 0.0f; }

// @ 0x012ac430
extern const float g_01485720;
extern float g_015f9134;
extern float g_015f9138;
extern float g_015f913c;
void FUN_012ac430() { g_015f9134 = 0.0f; g_015f9138 = g_01485720; g_015f913c = 0.0f; }

// @ 0x012aca90
extern const float g_01485720;
extern float g_015f93ac;
extern float g_015f93b0;
extern float g_015f93b4;
void FUN_012aca90() { g_015f93ac = 0.0f; g_015f93b0 = g_01485720; g_015f93b4 = 0.0f; }

// @ 0x012ad0f0
extern const float g_01485720;
extern float g_015f9628;
extern float g_015f962c;
extern float g_015f9630;
void FUN_012ad0f0() { g_015f9628 = 0.0f; g_015f962c = g_01485720; g_015f9630 = 0.0f; }

// @ 0x012ad780
extern const float g_01485720;
extern float g_015f9910;
extern float g_015f9914;
extern float g_015f9918;
void FUN_012ad780() { g_015f9910 = 0.0f; g_015f9914 = g_01485720; g_015f9918 = 0.0f; }

// @ 0x012ade10
extern const float g_01485720;
extern float g_015f9b8c;
extern float g_015f9b90;
extern float g_015f9b94;
void FUN_012ade10() { g_015f9b8c = 0.0f; g_015f9b90 = g_01485720; g_015f9b94 = 0.0f; }

// @ 0x012ae4c0
extern const float g_01485720;
extern float g_015f9e04;
extern float g_015f9e08;
extern float g_015f9e0c;
void FUN_012ae4c0() { g_015f9e04 = 0.0f; g_015f9e08 = g_01485720; g_015f9e0c = 0.0f; }

// @ 0x012aeb20
extern const float g_01485720;
extern float g_015fa094;
extern float g_015fa098;
extern float g_015fa09c;
void FUN_012aeb20() { g_015fa094 = 0.0f; g_015fa098 = g_01485720; g_015fa09c = 0.0f; }

// @ 0x012af1d0
extern const float g_01485720;
extern float g_015fa324;
extern float g_015fa328;
extern float g_015fa32c;
void FUN_012af1d0() { g_015fa324 = 0.0f; g_015fa328 = g_01485720; g_015fa32c = 0.0f; }

// @ 0x012af980
extern const float g_01485720;
extern float g_015fa5ac;
extern float g_015fa5b0;
extern float g_015fa5b4;
void FUN_012af980() { g_015fa5ac = 0.0f; g_015fa5b0 = g_01485720; g_015fa5b4 = 0.0f; }

// @ 0x012b0040
extern const float g_01485720;
extern float g_015fa824;
extern float g_015fa828;
extern float g_015fa82c;
void FUN_012b0040() { g_015fa824 = 0.0f; g_015fa828 = g_01485720; g_015fa82c = 0.0f; }

// @ 0x012b06a0
extern const float g_01485720;
extern float g_015faa9c;
extern float g_015faaa0;
extern float g_015faaa4;
void FUN_012b06a0() { g_015faa9c = 0.0f; g_015faaa0 = g_01485720; g_015faaa4 = 0.0f; }

// @ 0x012b0d00
extern const float g_01485720;
extern float g_015fad14;
extern float g_015fad18;
extern float g_015fad1c;
void FUN_012b0d00() { g_015fad14 = 0.0f; g_015fad18 = g_01485720; g_015fad1c = 0.0f; }

// @ 0x012b1360
extern const float g_01485720;
extern float g_015faf8c;
extern float g_015faf90;
extern float g_015faf94;
void FUN_012b1360() { g_015faf8c = 0.0f; g_015faf90 = g_01485720; g_015faf94 = 0.0f; }

// @ 0x012b19f0
extern const float g_01485720;
extern float g_015fb22c;
extern float g_015fb230;
extern float g_015fb234;
void FUN_012b19f0() { g_015fb22c = 0.0f; g_015fb230 = g_01485720; g_015fb234 = 0.0f; }

// @ 0x012b2080
extern const float g_01485720;
extern float g_015fb4a4;
extern float g_015fb4a8;
extern float g_015fb4ac;
void FUN_012b2080() { g_015fb4a4 = 0.0f; g_015fb4a8 = g_01485720; g_015fb4ac = 0.0f; }

// @ 0x012b2710
extern const float g_01485720;
extern float g_015fb71c;
extern float g_015fb720;
extern float g_015fb724;
void FUN_012b2710() { g_015fb71c = 0.0f; g_015fb720 = g_01485720; g_015fb724 = 0.0f; }

// @ 0x012b2da0
extern const float g_01485720;
extern float g_015fb998;
extern float g_015fb99c;
extern float g_015fb9a0;
void FUN_012b2da0() { g_015fb998 = 0.0f; g_015fb99c = g_01485720; g_015fb9a0 = 0.0f; }

// @ 0x012b3430
extern const float g_01485720;
extern float g_015fbc18;
extern float g_015fbc1c;
extern float g_015fbc20;
void FUN_012b3430() { g_015fbc18 = 0.0f; g_015fbc1c = g_01485720; g_015fbc20 = 0.0f; }

// @ 0x012b3ac0
extern const float g_01485720;
extern float g_015fbe94;
extern float g_015fbe98;
extern float g_015fbe9c;
void FUN_012b3ac0() { g_015fbe94 = 0.0f; g_015fbe98 = g_01485720; g_015fbe9c = 0.0f; }

// @ 0x012b4120
extern const float g_01485720;
extern float g_015fc110;
extern float g_015fc114;
extern float g_015fc118;
void FUN_012b4120() { g_015fc110 = 0.0f; g_015fc114 = g_01485720; g_015fc118 = 0.0f; }

// @ 0x012b47b0
extern const float g_01485720;
extern float g_015fc390;
extern float g_015fc394;
extern float g_015fc398;
void FUN_012b47b0() { g_015fc390 = 0.0f; g_015fc394 = g_01485720; g_015fc398 = 0.0f; }

// @ 0x012b5020
extern const float g_01485720;
extern float g_015fc60c;
extern float g_015fc610;
extern float g_015fc614;
void FUN_012b5020() { g_015fc60c = 0.0f; g_015fc610 = g_01485720; g_015fc614 = 0.0f; }

// @ 0x012b5680
extern const float g_01485720;
extern float g_015fc894;
extern float g_015fc898;
extern float g_015fc89c;
void FUN_012b5680() { g_015fc894 = 0.0f; g_015fc898 = g_01485720; g_015fc89c = 0.0f; }

// @ 0x012b5d40
extern const float g_01485720;
extern float g_015fcb0c;
extern float g_015fcb10;
extern float g_015fcb14;
void FUN_012b5d40() { g_015fcb0c = 0.0f; g_015fcb10 = g_01485720; g_015fcb14 = 0.0f; }

// @ 0x012b6300
extern const float g_01485720;
extern float g_015fcdbc;
extern float g_015fcdc0;
extern float g_015fcdc4;
void FUN_012b6300() { g_015fcdbc = 0.0f; g_015fcdc0 = g_01485720; g_015fcdc4 = 0.0f; }

// @ 0x012b68c0
extern const float g_01485720;
extern float g_015fd020;
extern float g_015fd024;
extern float g_015fd028;
void FUN_012b68c0() { g_015fd020 = 0.0f; g_015fd024 = g_01485720; g_015fd028 = 0.0f; }

// @ 0x012b6e80
extern const float g_01485720;
extern float g_015fd288;
extern float g_015fd28c;
extern float g_015fd290;
void FUN_012b6e80() { g_015fd288 = 0.0f; g_015fd28c = g_01485720; g_015fd290 = 0.0f; }

// @ 0x012b7490
extern const float g_01485720;
extern float g_015fd4f0;
extern float g_015fd4f4;
extern float g_015fd4f8;
void FUN_012b7490() { g_015fd4f0 = 0.0f; g_015fd4f4 = g_01485720; g_015fd4f8 = 0.0f; }

// @ 0x012b7a90
extern const float g_01485720;
extern float g_015fd758;
extern float g_015fd75c;
extern float g_015fd760;
void FUN_012b7a90() { g_015fd758 = 0.0f; g_015fd75c = g_01485720; g_015fd760 = 0.0f; }

// @ 0x012b8050
extern const float g_01485720;
extern float g_015fda5c;
extern float g_015fda60;
extern float g_015fda64;
void FUN_012b8050() { g_015fda5c = 0.0f; g_015fda60 = g_01485720; g_015fda64 = 0.0f; }

// @ 0x012b8610
extern const float g_01485720;
extern float g_015fdcc0;
extern float g_015fdcc4;
extern float g_015fdcc8;
void FUN_012b8610() { g_015fdcc0 = 0.0f; g_015fdcc4 = g_01485720; g_015fdcc8 = 0.0f; }

// @ 0x012b8c10
extern const float g_01485720;
extern float g_015fdf28;
extern float g_015fdf2c;
extern float g_015fdf30;
void FUN_012b8c10() { g_015fdf28 = 0.0f; g_015fdf2c = g_01485720; g_015fdf30 = 0.0f; }

// @ 0x012b9210
extern const float g_01485720;
extern float g_015fe198;
extern float g_015fe19c;
extern float g_015fe1a0;
void FUN_012b9210() { g_015fe198 = 0.0f; g_015fe19c = g_01485720; g_015fe1a0 = 0.0f; }

// @ 0x012b9810
extern const float g_01485720;
extern float g_015fe408;
extern float g_015fe40c;
extern float g_015fe410;
void FUN_012b9810() { g_015fe408 = 0.0f; g_015fe40c = g_01485720; g_015fe410 = 0.0f; }

// @ 0x012b9e10
extern const float g_01485720;
extern float g_015fe678;
extern float g_015fe67c;
extern float g_015fe680;
void FUN_012b9e10() { g_015fe678 = 0.0f; g_015fe67c = g_01485720; g_015fe680 = 0.0f; }

// @ 0x012ba430
extern const float g_01485720;
extern float g_015fe8ec;
extern float g_015fe8f0;
extern float g_015fe8f4;
void FUN_012ba430() { g_015fe8ec = 0.0f; g_015fe8f0 = g_01485720; g_015fe8f4 = 0.0f; }

// @ 0x012baa70
extern const float g_01485720;
extern float g_015feb68;
extern float g_015feb6c;
extern float g_015feb70;
void FUN_012baa70() { g_015feb68 = 0.0f; g_015feb6c = g_01485720; g_015feb70 = 0.0f; }

// @ 0x012bb080
extern const float g_01485720;
extern float g_015fedd8;
extern float g_015feddc;
extern float g_015fede0;
void FUN_012bb080() { g_015fedd8 = 0.0f; g_015feddc = g_01485720; g_015fede0 = 0.0f; }

// @ 0x012bb680
extern const float g_01485720;
extern float g_015ff048;
extern float g_015ff04c;
extern float g_015ff050;
void FUN_012bb680() { g_015ff048 = 0.0f; g_015ff04c = g_01485720; g_015ff050 = 0.0f; }

// @ 0x012bbc80
extern const float g_01485720;
extern float g_015ff2b8;
extern float g_015ff2bc;
extern float g_015ff2c0;
void FUN_012bbc80() { g_015ff2b8 = 0.0f; g_015ff2bc = g_01485720; g_015ff2c0 = 0.0f; }

// @ 0x012bc240
extern const float g_01485720;
extern float g_015ff528;
extern float g_015ff52c;
extern float g_015ff530;
void FUN_012bc240() { g_015ff528 = 0.0f; g_015ff52c = g_01485720; g_015ff530 = 0.0f; }

// @ 0x012bc840
extern const float g_01485720;
extern float g_015ff794;
extern float g_015ff798;
extern float g_015ff79c;
void FUN_012bc840() { g_015ff794 = 0.0f; g_015ff798 = g_01485720; g_015ff79c = 0.0f; }

// @ 0x012bce40
extern const float g_01485720;
extern float g_015ffa10;
extern float g_015ffa14;
extern float g_015ffa18;
void FUN_012bce40() { g_015ffa10 = 0.0f; g_015ffa14 = g_01485720; g_015ffa18 = 0.0f; }

// @ 0x012bd440
extern const float g_01485720;
extern float g_015ffc80;
extern float g_015ffc84;
extern float g_015ffc88;
void FUN_012bd440() { g_015ffc80 = 0.0f; g_015ffc84 = g_01485720; g_015ffc88 = 0.0f; }

// @ 0x012bda50
extern const float g_01485720;
extern float g_015ffef0;
extern float g_015ffef4;
extern float g_015ffef8;
void FUN_012bda50() { g_015ffef0 = 0.0f; g_015ffef4 = g_01485720; g_015ffef8 = 0.0f; }

// @ 0x012be050
extern const float g_01485720;
extern float g_01600160;
extern float g_01600164;
extern float g_01600168;
void FUN_012be050() { g_01600160 = 0.0f; g_01600164 = g_01485720; g_01600168 = 0.0f; }

// @ 0x012be690
extern const float g_01485720;
extern float g_016003c8;
extern float g_016003cc;
extern float g_016003d0;
void FUN_012be690() { g_016003c8 = 0.0f; g_016003cc = g_01485720; g_016003d0 = 0.0f; }

// @ 0x012bec90
extern const float g_01485720;
extern float g_0160063c;
extern float g_01600640;
extern float g_01600644;
void FUN_012bec90() { g_0160063c = 0.0f; g_01600640 = g_01485720; g_01600644 = 0.0f; }

// @ 0x012bf290
extern const float g_01485720;
extern float g_016008b0;
extern float g_016008b4;
extern float g_016008b8;
void FUN_012bf290() { g_016008b0 = 0.0f; g_016008b4 = g_01485720; g_016008b8 = 0.0f; }

// @ 0x012bf850
extern const float g_01485720;
extern float g_01600b20;
extern float g_01600b24;
extern float g_01600b28;
void FUN_012bf850() { g_01600b20 = 0.0f; g_01600b24 = g_01485720; g_01600b28 = 0.0f; }

// @ 0x012bfe50
extern const float g_01485720;
extern float g_01600d90;
extern float g_01600d94;
extern float g_01600d98;
void FUN_012bfe50() { g_01600d90 = 0.0f; g_01600d94 = g_01485720; g_01600d98 = 0.0f; }

// @ 0x012c0460
extern const float g_01485720;
extern float g_01601000;
extern float g_01601004;
extern float g_01601008;
void FUN_012c0460() { g_01601000 = 0.0f; g_01601004 = g_01485720; g_01601008 = 0.0f; }

// @ 0x012c0a50
extern const float g_01485720;
extern float g_01601270;
extern float g_01601274;
extern float g_01601278;
void FUN_012c0a50() { g_01601270 = 0.0f; g_01601274 = g_01485720; g_01601278 = 0.0f; }

// @ 0x012c1050
extern const float g_01485720;
extern float g_016014d8;
extern float g_016014dc;
extern float g_016014e0;
void FUN_012c1050() { g_016014d8 = 0.0f; g_016014dc = g_01485720; g_016014e0 = 0.0f; }

// @ 0x012c1650
extern const float g_01485720;
extern float g_01601748;
extern float g_0160174c;
extern float g_01601750;
void FUN_012c1650() { g_01601748 = 0.0f; g_0160174c = g_01485720; g_01601750 = 0.0f; }

// @ 0x012c1c20
extern const float g_01485720;
extern float g_016019b8;
extern float g_016019bc;
extern float g_016019c0;
void FUN_012c1c20() { g_016019b8 = 0.0f; g_016019bc = g_01485720; g_016019c0 = 0.0f; }

// @ 0x012c2220
extern const float g_01485720;
extern float g_01601c20;
extern float g_01601c24;
extern float g_01601c28;
void FUN_012c2220() { g_01601c20 = 0.0f; g_01601c24 = g_01485720; g_01601c28 = 0.0f; }

// @ 0x012c2820
extern const float g_01485720;
extern float g_01601e88;
extern float g_01601e8c;
extern float g_01601e90;
void FUN_012c2820() { g_01601e88 = 0.0f; g_01601e8c = g_01485720; g_01601e90 = 0.0f; }

// @ 0x012c2e20
extern const float g_01485720;
extern float g_016020f0;
extern float g_016020f4;
extern float g_016020f8;
void FUN_012c2e20() { g_016020f0 = 0.0f; g_016020f4 = g_01485720; g_016020f8 = 0.0f; }

// @ 0x012c33f0
extern const float g_01485720;
extern float g_01602360;
extern float g_01602364;
extern float g_01602368;
void FUN_012c33f0() { g_01602360 = 0.0f; g_01602364 = g_01485720; g_01602368 = 0.0f; }

// @ 0x012c39f0
extern const float g_01485720;
extern float g_016025c8;
extern float g_016025cc;
extern float g_016025d0;
void FUN_012c39f0() { g_016025c8 = 0.0f; g_016025cc = g_01485720; g_016025d0 = 0.0f; }

// @ 0x012c4000
extern const float g_01485720;
extern float g_0160284c;
extern float g_01602850;
extern float g_01602854;
void FUN_012c4000() { g_0160284c = 0.0f; g_01602850 = g_01485720; g_01602854 = 0.0f; }

// @ 0x012c4610
extern const float g_01485720;
extern float g_01602af8;
extern float g_01602afc;
extern float g_01602b00;
void FUN_012c4610() { g_01602af8 = 0.0f; g_01602afc = g_01485720; g_01602b00 = 0.0f; }

// @ 0x012c4c10
extern const float g_01485720;
extern float g_01602d68;
extern float g_01602d6c;
extern float g_01602d70;
void FUN_012c4c10() { g_01602d68 = 0.0f; g_01602d6c = g_01485720; g_01602d70 = 0.0f; }

// @ 0x012c5210
extern const float g_01485720;
extern float g_01602fd8;
extern float g_01602fdc;
extern float g_01602fe0;
void FUN_012c5210() { g_01602fd8 = 0.0f; g_01602fdc = g_01485720; g_01602fe0 = 0.0f; }

// @ 0x012c5810
extern const float g_01485720;
extern float g_0160324c;
extern float g_01603250;
extern float g_01603254;
void FUN_012c5810() { g_0160324c = 0.0f; g_01603250 = g_01485720; g_01603254 = 0.0f; }

// @ 0x012c5e50
extern const float g_01485720;
extern float g_01604328;
extern float g_0160432c;
extern float g_01604330;
void FUN_012c5e50() { g_01604328 = 0.0f; g_0160432c = g_01485720; g_01604330 = 0.0f; }

// @ 0x012c6450
extern const float g_01485720;
extern float g_01604598;
extern float g_0160459c;
extern float g_016045a0;
void FUN_012c6450() { g_01604598 = 0.0f; g_0160459c = g_01485720; g_016045a0 = 0.0f; }

// @ 0x012c6a50
extern const float g_01485720;
extern float g_0160480c;
extern float g_01604810;
extern float g_01604814;
void FUN_012c6a50() { g_0160480c = 0.0f; g_01604810 = g_01485720; g_01604814 = 0.0f; }

// @ 0x012c7070
extern const float g_01485720;
extern float g_01604a78;
extern float g_01604a7c;
extern float g_01604a80;
void FUN_012c7070() { g_01604a78 = 0.0f; g_01604a7c = g_01485720; g_01604a80 = 0.0f; }

// @ 0x012c7640
extern const float g_01485720;
extern float g_01604d28;
extern float g_01604d2c;
extern float g_01604d30;
void FUN_012c7640() { g_01604d28 = 0.0f; g_01604d2c = g_01485720; g_01604d30 = 0.0f; }

// @ 0x012c7ca0
extern const float g_01485720;
extern float g_01604fa4;
extern float g_01604fa8;
extern float g_01604fac;
void FUN_012c7ca0() { g_01604fa4 = 0.0f; g_01604fa8 = g_01485720; g_01604fac = 0.0f; }

// @ 0x012c82a0
extern const float g_01485720;
extern float g_01605210;
extern float g_01605214;
extern float g_01605218;
void FUN_012c82a0() { g_01605210 = 0.0f; g_01605214 = g_01485720; g_01605218 = 0.0f; }

// @ 0x012c88a0
extern const float g_01485720;
extern float g_01605488;
extern float g_0160548c;
extern float g_01605490;
void FUN_012c88a0() { g_01605488 = 0.0f; g_0160548c = g_01485720; g_01605490 = 0.0f; }

// @ 0x012c8ee0
extern const float g_01485720;
extern float g_016056f8;
extern float g_016056fc;
extern float g_01605700;
void FUN_012c8ee0() { g_016056f8 = 0.0f; g_016056fc = g_01485720; g_01605700 = 0.0f; }

// @ 0x012c9520
extern const float g_01485720;
extern float g_01605968;
extern float g_0160596c;
extern float g_01605970;
void FUN_012c9520() { g_01605968 = 0.0f; g_0160596c = g_01485720; g_01605970 = 0.0f; }

// @ 0x012c9b50
extern const float g_01485720;
extern float g_01605be8;
extern float g_01605bec;
extern float g_01605bf0;
void FUN_012c9b50() { g_01605be8 = 0.0f; g_01605bec = g_01485720; g_01605bf0 = 0.0f; }

// @ 0x012ca170
extern const float g_01485720;
extern float g_01605f08;
extern float g_01605f0c;
extern float g_01605f10;
void FUN_012ca170() { g_01605f08 = 0.0f; g_01605f0c = g_01485720; g_01605f10 = 0.0f; }

// @ 0x012ca760
extern const float g_01485720;
extern float g_01606178;
extern float g_0160617c;
extern float g_01606180;
void FUN_012ca760() { g_01606178 = 0.0f; g_0160617c = g_01485720; g_01606180 = 0.0f; }

// @ 0x012cad60
extern const float g_01485720;
extern float g_016063e0;
extern float g_016063e4;
extern float g_016063e8;
void FUN_012cad60() { g_016063e0 = 0.0f; g_016063e4 = g_01485720; g_016063e8 = 0.0f; }

// @ 0x012cb360
extern const float g_01485720;
extern float g_01606678;
extern float g_0160667c;
extern float g_01606680;
void FUN_012cb360() { g_01606678 = 0.0f; g_0160667c = g_01485720; g_01606680 = 0.0f; }

// @ 0x012cb980
extern const float g_01485720;
extern float g_016068ec;
extern float g_016068f0;
extern float g_016068f4;
void FUN_012cb980() { g_016068ec = 0.0f; g_016068f0 = g_01485720; g_016068f4 = 0.0f; }

// @ 0x012cbf40
extern const float g_01485720;
extern float g_01606bf4;
extern float g_01606bf8;
extern float g_01606bfc;
void FUN_012cbf40() { g_01606bf4 = 0.0f; g_01606bf8 = g_01485720; g_01606bfc = 0.0f; }

// @ 0x012cc7b0
extern const float g_01485720;
extern float g_01606eb0;
extern float g_01606eb4;
extern float g_01606eb8;
void FUN_012cc7b0() { g_01606eb0 = 0.0f; g_01606eb4 = g_01485720; g_01606eb8 = 0.0f; }

// @ 0x012ccdf0
extern const float g_01485720;
extern float g_01607118;
extern float g_0160711c;
extern float g_01607120;
void FUN_012ccdf0() { g_01607118 = 0.0f; g_0160711c = g_01485720; g_01607120 = 0.0f; }

// @ 0x012cd470
extern const float g_01485720;
extern float g_01607388;
extern float g_0160738c;
extern float g_01607390;
void FUN_012cd470() { g_01607388 = 0.0f; g_0160738c = g_01485720; g_01607390 = 0.0f; }

// @ 0x012cdab0
extern const float g_01485720;
extern float g_016075f0;
extern float g_016075f4;
extern float g_016075f8;
void FUN_012cdab0() { g_016075f0 = 0.0f; g_016075f4 = g_01485720; g_016075f8 = 0.0f; }

// @ 0x012ce0f0
extern const float g_01485720;
extern float g_01607864;
extern float g_01607868;
extern float g_0160786c;
void FUN_012ce0f0() { g_01607864 = 0.0f; g_01607868 = g_01485720; g_0160786c = 0.0f; }

// @ 0x012ce730
extern const float g_01485720;
extern float g_01607adc;
extern float g_01607ae0;
extern float g_01607ae4;
void FUN_012ce730() { g_01607adc = 0.0f; g_01607ae0 = g_01485720; g_01607ae4 = 0.0f; }

// @ 0x012ced70
extern const float g_01485720;
extern float g_01607d48;
extern float g_01607d4c;
extern float g_01607d50;
void FUN_012ced70() { g_01607d48 = 0.0f; g_01607d4c = g_01485720; g_01607d50 = 0.0f; }

// @ 0x012cf3b0
extern const float g_01485720;
extern float g_01607fb0;
extern float g_01607fb4;
extern float g_01607fb8;
void FUN_012cf3b0() { g_01607fb0 = 0.0f; g_01607fb4 = g_01485720; g_01607fb8 = 0.0f; }

// @ 0x012cf9f0
extern const float g_01485720;
extern float g_01618220;
extern float g_01618224;
extern float g_01618228;
void FUN_012cf9f0() { g_01618220 = 0.0f; g_01618224 = g_01485720; g_01618228 = 0.0f; }

// @ 0x012d0030
extern const float g_01485720;
extern float g_01618488;
extern float g_0161848c;
extern float g_01618490;
void FUN_012d0030() { g_01618488 = 0.0f; g_0161848c = g_01485720; g_01618490 = 0.0f; }

// @ 0x012d0670
extern const float g_01485720;
extern float g_016186f0;
extern float g_016186f4;
extern float g_016186f8;
void FUN_012d0670() { g_016186f0 = 0.0f; g_016186f4 = g_01485720; g_016186f8 = 0.0f; }

// @ 0x012d0cb0
extern const float g_01485720;
extern float g_01618958;
extern float g_0161895c;
extern float g_01618960;
void FUN_012d0cb0() { g_01618958 = 0.0f; g_0161895c = g_01485720; g_01618960 = 0.0f; }

// @ 0x012d12f0
extern const float g_01485720;
extern float g_01618bc4;
extern float g_01618bc8;
extern float g_01618bcc;
void FUN_012d12f0() { g_01618bc4 = 0.0f; g_01618bc8 = g_01485720; g_01618bcc = 0.0f; }

// @ 0x012d1930
extern const float g_01485720;
extern float g_01618e48;
extern float g_01618e4c;
extern float g_01618e50;
void FUN_012d1930() { g_01618e48 = 0.0f; g_01618e4c = g_01485720; g_01618e50 = 0.0f; }

// @ 0x012d2210
extern const float g_01485720;
extern float g_0161913c;
extern float g_01619140;
extern float g_01619144;
void FUN_012d2210() { g_0161913c = 0.0f; g_01619140 = g_01485720; g_01619144 = 0.0f; }

// @ 0x012d28a0
extern const float g_01485720;
extern float g_016193a8;
extern float g_016193ac;
extern float g_016193b0;
void FUN_012d28a0() { g_016193a8 = 0.0f; g_016193ac = g_01485720; g_016193b0 = 0.0f; }

// @ 0x012d2ee0
extern const float g_01485720;
extern float g_01619620;
extern float g_01619624;
extern float g_01619628;
void FUN_012d2ee0() { g_01619620 = 0.0f; g_01619624 = g_01485720; g_01619628 = 0.0f; }

// @ 0x012d3530
extern const float g_01485720;
extern float g_0161fcd0;
extern float g_0161fcd4;
extern float g_0161fcd8;
void FUN_012d3530() { g_0161fcd0 = 0.0f; g_0161fcd4 = g_01485720; g_0161fcd8 = 0.0f; }

// @ 0x012d3c00
extern const float g_01485720;
extern float g_0161ff60;
extern float g_0161ff64;
extern float g_0161ff68;
void FUN_012d3c00() { g_0161ff60 = 0.0f; g_0161ff64 = g_01485720; g_0161ff68 = 0.0f; }

// @ 0x012d4240
extern const float g_01485720;
extern float g_016201c8;
extern float g_016201cc;
extern float g_016201d0;
void FUN_012d4240() { g_016201c8 = 0.0f; g_016201cc = g_01485720; g_016201d0 = 0.0f; }

// @ 0x012d4890
extern const float g_01485720;
extern float g_01624430;
extern float g_01624434;
extern float g_01624438;
void FUN_012d4890() { g_01624430 = 0.0f; g_01624434 = g_01485720; g_01624438 = 0.0f; }

// @ 0x012d4ed0
extern const float g_01485720;
extern float g_0162469c;
extern float g_016246a0;
extern float g_016246a4;
void FUN_012d4ed0() { g_0162469c = 0.0f; g_016246a0 = g_01485720; g_016246a4 = 0.0f; }

// @ 0x012d55c0
extern const float g_01485720;
extern float g_01628d6c;
extern float g_01628d70;
extern float g_01628d74;
void FUN_012d55c0() { g_01628d6c = 0.0f; g_01628d70 = g_01485720; g_01628d74 = 0.0f; }

// @ 0x012d5c00
extern const float g_01485720;
extern float g_01628fd8;
extern float g_01628fdc;
extern float g_01628fe0;
void FUN_012d5c00() { g_01628fd8 = 0.0f; g_01628fdc = g_01485720; g_01628fe0 = 0.0f; }

// @ 0x012d6240
extern const float g_01485720;
extern float g_01629240;
extern float g_01629244;
extern float g_01629248;
void FUN_012d6240() { g_01629240 = 0.0f; g_01629244 = g_01485720; g_01629248 = 0.0f; }

// @ 0x012d6880
extern const float g_01485720;
extern float g_016294b0;
extern float g_016294b4;
extern float g_016294b8;
void FUN_012d6880() { g_016294b0 = 0.0f; g_016294b4 = g_01485720; g_016294b8 = 0.0f; }

// @ 0x012d6ec0
extern const float g_01485720;
extern float g_01629718;
extern float g_0162971c;
extern float g_01629720;
void FUN_012d6ec0() { g_01629718 = 0.0f; g_0162971c = g_01485720; g_01629720 = 0.0f; }

// @ 0x012d7500
extern const float g_01485720;
extern float g_01629994;
extern float g_01629998;
extern float g_0162999c;
void FUN_012d7500() { g_01629994 = 0.0f; g_01629998 = g_01485720; g_0162999c = 0.0f; }

// @ 0x012d7c70
extern const float g_01485720;
extern float g_01629c10;
extern float g_01629c14;
extern float g_01629c18;
void FUN_012d7c70() { g_01629c10 = 0.0f; g_01629c14 = g_01485720; g_01629c18 = 0.0f; }

// @ 0x012d82b0
extern const float g_01485720;
extern float g_01629e78;
extern float g_01629e7c;
extern float g_01629e80;
void FUN_012d82b0() { g_01629e78 = 0.0f; g_01629e7c = g_01485720; g_01629e80 = 0.0f; }

// @ 0x012d8900
extern const float g_01485720;
extern float g_0162a0e0;
extern float g_0162a0e4;
extern float g_0162a0e8;
void FUN_012d8900() { g_0162a0e0 = 0.0f; g_0162a0e4 = g_01485720; g_0162a0e8 = 0.0f; }

// @ 0x012d8f40
extern const float g_01485720;
extern float g_0162a394;
extern float g_0162a398;
extern float g_0162a39c;
void FUN_012d8f40() { g_0162a394 = 0.0f; g_0162a398 = g_01485720; g_0162a39c = 0.0f; }

// @ 0x012d95b0
extern const float g_01485720;
extern float g_0162a618;
extern float g_0162a61c;
extern float g_0162a620;
void FUN_012d95b0() { g_0162a618 = 0.0f; g_0162a61c = g_01485720; g_0162a620 = 0.0f; }

// @ 0x012d9bf0
extern const float g_01485720;
extern float g_0162a880;
extern float g_0162a884;
extern float g_0162a888;
void FUN_012d9bf0() { g_0162a880 = 0.0f; g_0162a884 = g_01485720; g_0162a888 = 0.0f; }

// @ 0x012da230
extern const float g_01485720;
extern float g_0162aaf8;
extern float g_0162aafc;
extern float g_0162ab00;
void FUN_012da230() { g_0162aaf8 = 0.0f; g_0162aafc = g_01485720; g_0162ab00 = 0.0f; }

// @ 0x012da880
extern const float g_01485720;
extern float g_0162ad60;
extern float g_0162ad64;
extern float g_0162ad68;
void FUN_012da880() { g_0162ad60 = 0.0f; g_0162ad64 = g_01485720; g_0162ad68 = 0.0f; }

// @ 0x012daec0
extern const float g_01485720;
extern float g_0162afdc;
extern float g_0162afe0;
extern float g_0162afe4;
void FUN_012daec0() { g_0162afdc = 0.0f; g_0162afe0 = g_01485720; g_0162afe4 = 0.0f; }

// @ 0x012db500
extern const float g_01485720;
extern float g_0162b268;
extern float g_0162b26c;
extern float g_0162b270;
void FUN_012db500() { g_0162b268 = 0.0f; g_0162b26c = g_01485720; g_0162b270 = 0.0f; }

// @ 0x012dbb70
extern const float g_01485720;
extern float g_0162b4d0;
extern float g_0162b4d4;
extern float g_0162b4d8;
void FUN_012dbb70() { g_0162b4d0 = 0.0f; g_0162b4d4 = g_01485720; g_0162b4d8 = 0.0f; }

// @ 0x012dc1b0
extern const float g_01485720;
extern float g_0162b738;
extern float g_0162b73c;
extern float g_0162b740;
void FUN_012dc1b0() { g_0162b738 = 0.0f; g_0162b73c = g_01485720; g_0162b740 = 0.0f; }

// @ 0x012dc7f0
extern const float g_01485720;
extern float g_0162e9b4;
extern float g_0162e9b8;
extern float g_0162e9bc;
void FUN_012dc7f0() { g_0162e9b4 = 0.0f; g_0162e9b8 = g_01485720; g_0162e9bc = 0.0f; }

// @ 0x012dce30
extern const float g_01485720;
extern float g_0162ec34;
extern float g_0162ec38;
extern float g_0162ec3c;
void FUN_012dce30() { g_0162ec34 = 0.0f; g_0162ec38 = g_01485720; g_0162ec3c = 0.0f; }

// @ 0x012dd4e0
extern const float g_01485720;
extern float g_0162eee0;
extern float g_0162eee4;
extern float g_0162eee8;
void FUN_012dd4e0() { g_0162eee0 = 0.0f; g_0162eee4 = g_01485720; g_0162eee8 = 0.0f; }

// @ 0x012ddb20
extern const float g_01485720;
extern float g_0162f154;
extern float g_0162f158;
extern float g_0162f15c;
void FUN_012ddb20() { g_0162f154 = 0.0f; g_0162f158 = g_01485720; g_0162f15c = 0.0f; }

// @ 0x012de180
extern const float g_01485720;
extern float g_0162f3c0;
extern float g_0162f3c4;
extern float g_0162f3c8;
void FUN_012de180() { g_0162f3c0 = 0.0f; g_0162f3c4 = g_01485720; g_0162f3c8 = 0.0f; }

// @ 0x012de7c0
extern const float g_01485720;
extern float g_0162f628;
extern float g_0162f62c;
extern float g_0162f630;
void FUN_012de7c0() { g_0162f628 = 0.0f; g_0162f62c = g_01485720; g_0162f630 = 0.0f; }

// @ 0x012dee00
extern const float g_01485720;
extern float g_0162f890;
extern float g_0162f894;
extern float g_0162f898;
void FUN_012dee00() { g_0162f890 = 0.0f; g_0162f894 = g_01485720; g_0162f898 = 0.0f; }

// @ 0x012df470
extern const float g_01485720;
extern float g_0162fafc;
extern float g_0162fb00;
extern float g_0162fb04;
void FUN_012df470() { g_0162fafc = 0.0f; g_0162fb00 = g_01485720; g_0162fb04 = 0.0f; }

// @ 0x012dfb90
extern const float g_01485720;
extern float g_0162fd98;
extern float g_0162fd9c;
extern float g_0162fda0;
void FUN_012dfb90() { g_0162fd98 = 0.0f; g_0162fd9c = g_01485720; g_0162fda0 = 0.0f; }

// @ 0x012e01d0
extern const float g_01485720;
extern float g_01630008;
extern float g_0163000c;
extern float g_01630010;
void FUN_012e01d0() { g_01630008 = 0.0f; g_0163000c = g_01485720; g_01630010 = 0.0f; }

// @ 0x012e0840
extern const float g_01485720;
extern float g_016302b4;
extern float g_016302b8;
extern float g_016302bc;
void FUN_012e0840() { g_016302b4 = 0.0f; g_016302b8 = g_01485720; g_016302bc = 0.0f; }

// @ 0x012e0e80
extern const float g_01485720;
extern float g_01630548;
extern float g_0163054c;
extern float g_01630550;
void FUN_012e0e80() { g_01630548 = 0.0f; g_0163054c = g_01485720; g_01630550 = 0.0f; }

// @ 0x012e1530
extern const float g_01485720;
extern float g_016307c0;
extern float g_016307c4;
extern float g_016307c8;
void FUN_012e1530() { g_016307c0 = 0.0f; g_016307c4 = g_01485720; g_016307c8 = 0.0f; }

// @ 0x012e1b70
extern const float g_01485720;
extern float g_01630a28;
extern float g_01630a2c;
extern float g_01630a30;
void FUN_012e1b70() { g_01630a28 = 0.0f; g_01630a2c = g_01485720; g_01630a30 = 0.0f; }

// @ 0x012e21b0
extern const float g_01485720;
extern float g_01630cb4;
extern float g_01630cb8;
extern float g_01630cbc;
void FUN_012e21b0() { g_01630cb4 = 0.0f; g_01630cb8 = g_01485720; g_01630cbc = 0.0f; }

// @ 0x012e27f0
extern const float g_01485720;
extern float g_01630f20;
extern float g_01630f24;
extern float g_01630f28;
void FUN_012e27f0() { g_01630f20 = 0.0f; g_01630f24 = g_01485720; g_01630f28 = 0.0f; }

// @ 0x012e2f20
extern const float g_01485720;
extern float g_016311b0;
extern float g_016311b4;
extern float g_016311b8;
void FUN_012e2f20() { g_016311b0 = 0.0f; g_016311b4 = g_01485720; g_016311b8 = 0.0f; }

// @ 0x012e3560
extern const float g_01485720;
extern float g_01632d64;
extern float g_01632d68;
extern float g_01632d6c;
void FUN_012e3560() { g_01632d64 = 0.0f; g_01632d68 = g_01485720; g_01632d6c = 0.0f; }

// @ 0x012e3c10
extern const float g_01485720;
extern float g_01633cfc;
extern float g_01633d00;
extern float g_01633d04;
void FUN_012e3c10() { g_01633cfc = 0.0f; g_01633d00 = g_01485720; g_01633d04 = 0.0f; }

// @ 0x012e42d0
extern const float g_01485720;
extern float g_01633fa0;
extern float g_01633fa4;
extern float g_01633fa8;
void FUN_012e42d0() { g_01633fa0 = 0.0f; g_01633fa4 = g_01485720; g_01633fa8 = 0.0f; }

// @ 0x012e4fb0
extern const float g_01485720;
extern float g_016343f4;
extern float g_016343f8;
extern float g_016343fc;
void FUN_012e4fb0() { g_016343f4 = 0.0f; g_016343f8 = g_01485720; g_016343fc = 0.0f; }

// @ 0x012e5620
extern const float g_01485720;
extern float g_01634638;
extern float g_0163463c;
extern float g_01634640;
void FUN_012e5620() { g_01634638 = 0.0f; g_0163463c = g_01485720; g_01634640 = 0.0f; }

// @ 0x012e5c60
extern const float g_01485720;
extern float g_016348d0;
extern float g_016348d4;
extern float g_016348d8;
void FUN_012e5c60() { g_016348d0 = 0.0f; g_016348d4 = g_01485720; g_016348d8 = 0.0f; }

// @ 0x012e62a0
extern const float g_01485720;
extern float g_01634b40;
extern float g_01634b44;
extern float g_01634b48;
void FUN_012e62a0() { g_01634b40 = 0.0f; g_01634b44 = g_01485720; g_01634b48 = 0.0f; }

// @ 0x012e68e0
extern const float g_01485720;
extern float g_01634dac;
extern float g_01634db0;
extern float g_01634db4;
void FUN_012e68e0() { g_01634dac = 0.0f; g_01634db0 = g_01485720; g_01634db4 = 0.0f; }

// @ 0x012e6f20
extern const float g_01485720;
extern float g_01635038;
extern float g_0163503c;
extern float g_01635040;
void FUN_012e6f20() { g_01635038 = 0.0f; g_0163503c = g_01485720; g_01635040 = 0.0f; }

// @ 0x012e7590
extern const float g_01485720;
extern float g_016352a0;
extern float g_016352a4;
extern float g_016352a8;
void FUN_012e7590() { g_016352a0 = 0.0f; g_016352a4 = g_01485720; g_016352a8 = 0.0f; }

// @ 0x012e7bd0
extern const float g_01485720;
extern float g_01635508;
extern float g_0163550c;
extern float g_01635510;
void FUN_012e7bd0() { g_01635508 = 0.0f; g_0163550c = g_01485720; g_01635510 = 0.0f; }

// @ 0x012e8210
extern const float g_01485720;
extern float g_01635770;
extern float g_01635774;
extern float g_01635778;
void FUN_012e8210() { g_01635770 = 0.0f; g_01635774 = g_01485720; g_01635778 = 0.0f; }

// @ 0x012e8850
extern const float g_01485720;
extern float g_016359d8;
extern float g_016359dc;
extern float g_016359e0;
void FUN_012e8850() { g_016359d8 = 0.0f; g_016359dc = g_01485720; g_016359e0 = 0.0f; }

// @ 0x012e8e90
extern const float g_01485720;
extern float g_01635c40;
extern float g_01635c44;
extern float g_01635c48;
void FUN_012e8e90() { g_01635c40 = 0.0f; g_01635c44 = g_01485720; g_01635c48 = 0.0f; }

// @ 0x012e94e0
extern const float g_01485720;
extern float g_01635ea8;
extern float g_01635eac;
extern float g_01635eb0;
void FUN_012e94e0() { g_01635ea8 = 0.0f; g_01635eac = g_01485720; g_01635eb0 = 0.0f; }

// @ 0x012e9b20
extern const float g_01485720;
extern float g_01636110;
extern float g_01636114;
extern float g_01636118;
void FUN_012e9b20() { g_01636110 = 0.0f; g_01636114 = g_01485720; g_01636118 = 0.0f; }

// @ 0x012ea160
extern const float g_01485720;
extern float g_01636390;
extern float g_01636394;
extern float g_01636398;
void FUN_012ea160() { g_01636390 = 0.0f; g_01636394 = g_01485720; g_01636398 = 0.0f; }

// @ 0x012ea760
extern const float g_01485720;
extern float g_01636600;
extern float g_01636604;
extern float g_01636608;
void FUN_012ea760() { g_01636600 = 0.0f; g_01636604 = g_01485720; g_01636608 = 0.0f; }

// @ 0x012ead70
extern const float g_01485720;
extern float g_01636874;
extern float g_01636878;
extern float g_0163687c;
void FUN_012ead70() { g_01636874 = 0.0f; g_01636878 = g_01485720; g_0163687c = 0.0f; }

// @ 0x012eb3c0
extern const float g_01485720;
extern float g_01636ae8;
extern float g_01636aec;
extern float g_01636af0;
void FUN_012eb3c0() { g_01636ae8 = 0.0f; g_01636aec = g_01485720; g_01636af0 = 0.0f; }

// @ 0x012eba00
extern const float g_01485720;
extern float g_01636d58;
extern float g_01636d5c;
extern float g_01636d60;
void FUN_012eba00() { g_01636d58 = 0.0f; g_01636d5c = g_01485720; g_01636d60 = 0.0f; }

// @ 0x012ec070
extern const float g_01485720;
extern float g_01636fd0;
extern float g_01636fd4;
extern float g_01636fd8;
void FUN_012ec070() { g_01636fd0 = 0.0f; g_01636fd4 = g_01485720; g_01636fd8 = 0.0f; }

// @ 0x012ec670
extern const float g_01485720;
extern float g_01637244;
extern float g_01637248;
extern float g_0163724c;
void FUN_012ec670() { g_01637244 = 0.0f; g_01637248 = g_01485720; g_0163724c = 0.0f; }

// @ 0x012eccc0
extern const float g_01485720;
extern float g_016374b8;
extern float g_016374bc;
extern float g_016374c0;
void FUN_012eccc0() { g_016374b8 = 0.0f; g_016374bc = g_01485720; g_016374c0 = 0.0f; }

// @ 0x012ed2c0
extern const float g_01485720;
extern float g_01637728;
extern float g_0163772c;
extern float g_01637730;
void FUN_012ed2c0() { g_01637728 = 0.0f; g_0163772c = g_01485720; g_01637730 = 0.0f; }

// @ 0x012ed8c0
extern const float g_01485720;
extern float g_01637998;
extern float g_0163799c;
extern float g_016379a0;
void FUN_012ed8c0() { g_01637998 = 0.0f; g_0163799c = g_01485720; g_016379a0 = 0.0f; }

// @ 0x012edf00
extern const float g_01485720;
extern float g_01637c28;
extern float g_01637c2c;
extern float g_01637c30;
void FUN_012edf00() { g_01637c28 = 0.0f; g_01637c2c = g_01485720; g_01637c30 = 0.0f; }

// @ 0x012ee590
extern const float g_01485720;
extern float g_01637ea0;
extern float g_01637ea4;
extern float g_01637ea8;
void FUN_012ee590() { g_01637ea0 = 0.0f; g_01637ea4 = g_01485720; g_01637ea8 = 0.0f; }

// @ 0x012eeb90
extern const float g_01485720;
extern float g_01638114;
extern float g_01638118;
extern float g_0163811c;
void FUN_012eeb90() { g_01638114 = 0.0f; g_01638118 = g_01485720; g_0163811c = 0.0f; }

// @ 0x012ef1e0
extern const float g_01485720;
extern float g_016383b8;
extern float g_016383bc;
extern float g_016383c0;
void FUN_012ef1e0() { g_016383b8 = 0.0f; g_016383bc = g_01485720; g_016383c0 = 0.0f; }

// @ 0x012ef7e0
extern const float g_01485720;
extern float g_01638628;
extern float g_0163862c;
extern float g_01638630;
void FUN_012ef7e0() { g_01638628 = 0.0f; g_0163862c = g_01485720; g_01638630 = 0.0f; }

// @ 0x012efda0
extern const float g_01485720;
extern float g_01638898;
extern float g_0163889c;
extern float g_016388a0;
void FUN_012efda0() { g_01638898 = 0.0f; g_0163889c = g_01485720; g_016388a0 = 0.0f; }

// @ 0x012f03d0
extern const float g_01485720;
extern float g_01638b04;
extern float g_01638b08;
extern float g_01638b0c;
void FUN_012f03d0() { g_01638b04 = 0.0f; g_01638b08 = g_01485720; g_01638b0c = 0.0f; }

// @ 0x012f09d0
extern const float g_01485720;
extern float g_01638d70;
extern float g_01638d74;
extern float g_01638d78;
void FUN_012f09d0() { g_01638d70 = 0.0f; g_01638d74 = g_01485720; g_01638d78 = 0.0f; }

// @ 0x012f0fd0
extern const float g_01485720;
extern float g_01638fe4;
extern float g_01638fe8;
extern float g_01638fec;
void FUN_012f0fd0() { g_01638fe4 = 0.0f; g_01638fe8 = g_01485720; g_01638fec = 0.0f; }

// @ 0x012f1620
extern const float g_01485720;
extern float g_01639258;
extern float g_0163925c;
extern float g_01639260;
void FUN_012f1620() { g_01639258 = 0.0f; g_0163925c = g_01485720; g_01639260 = 0.0f; }

// @ 0x012f1c20
extern const float g_01485720;
extern float g_0163952c;
extern float g_01639530;
extern float g_01639534;
void FUN_012f1c20() { g_0163952c = 0.0f; g_01639530 = g_01485720; g_01639534 = 0.0f; }

// @ 0x012f22b0
extern const float g_01485720;
extern float g_01639798;
extern float g_0163979c;
extern float g_016397a0;
void FUN_012f22b0() { g_01639798 = 0.0f; g_0163979c = g_01485720; g_016397a0 = 0.0f; }

// @ 0x012f28b0
extern const float g_01485720;
extern float g_01639a0c;
extern float g_01639a10;
extern float g_01639a14;
void FUN_012f28b0() { g_01639a0c = 0.0f; g_01639a10 = g_01485720; g_01639a14 = 0.0f; }

// @ 0x012f2f00
extern const float g_01485720;
extern float g_01639c80;
extern float g_01639c84;
extern float g_01639c88;
void FUN_012f2f00() { g_01639c80 = 0.0f; g_01639c84 = g_01485720; g_01639c88 = 0.0f; }

// @ 0x012f3560
extern const float g_01485720;
extern float g_01639ef0;
extern float g_01639ef4;
extern float g_01639ef8;
void FUN_012f3560() { g_01639ef0 = 0.0f; g_01639ef4 = g_01485720; g_01639ef8 = 0.0f; }

// @ 0x012f3b60
extern const float g_01485720;
extern float g_0163a160;
extern float g_0163a164;
extern float g_0163a168;
void FUN_012f3b60() { g_0163a160 = 0.0f; g_0163a164 = g_01485720; g_0163a168 = 0.0f; }

// @ 0x012f4160
extern const float g_01485720;
extern float g_0163a3e4;
extern float g_0163a3e8;
extern float g_0163a3ec;
void FUN_012f4160() { g_0163a3e4 = 0.0f; g_0163a3e8 = g_01485720; g_0163a3ec = 0.0f; }

// @ 0x012f4770
extern const float g_01485720;
extern float g_0163a658;
extern float g_0163a65c;
extern float g_0163a660;
void FUN_012f4770() { g_0163a658 = 0.0f; g_0163a65c = g_01485720; g_0163a660 = 0.0f; }

// @ 0x012f4d30
extern const float g_01485720;
extern float g_0163a8c0;
extern float g_0163a8c4;
extern float g_0163a8c8;
void FUN_012f4d30() { g_0163a8c0 = 0.0f; g_0163a8c4 = g_01485720; g_0163a8c8 = 0.0f; }

// @ 0x012f5330
extern const float g_01485720;
extern float g_0163ab30;
extern float g_0163ab34;
extern float g_0163ab38;
void FUN_012f5330() { g_0163ab30 = 0.0f; g_0163ab34 = g_01485720; g_0163ab38 = 0.0f; }

// @ 0x012f8af0
extern const float g_01485720;
extern float g_0164c2a4;
extern float g_0164c2a8;
extern float g_0164c2ac;
void FUN_012f8af0() { g_0164c2a4 = 0.0f; g_0164c2a8 = g_01485720; g_0164c2ac = 0.0f; }

// @ 0x012f9ec0
extern const float g_01485720;
extern float g_0164ce14;
extern float g_0164ce18;
extern float g_0164ce1c;
void FUN_012f9ec0() { g_0164ce14 = 0.0f; g_0164ce18 = g_01485720; g_0164ce1c = 0.0f; }

// @ 0x012faa30
extern const float g_01485720;
extern float g_0164d350;
extern float g_0164d354;
extern float g_0164d358;
void FUN_012faa30() { g_0164d350 = 0.0f; g_0164d354 = g_01485720; g_0164d358 = 0.0f; }

// @ 0x012fb090
extern const float g_01485720;
extern float g_0164d5c0;
extern float g_0164d5c4;
extern float g_0164d5c8;
void FUN_012fb090() { g_0164d5c0 = 0.0f; g_0164d5c4 = g_01485720; g_0164d5c8 = 0.0f; }

// @ 0x012fb970
extern const float g_01485720;
extern float g_0164d990;
extern float g_0164d994;
extern float g_0164d998;
void FUN_012fb970() { g_0164d990 = 0.0f; g_0164d994 = g_01485720; g_0164d998 = 0.0f; }

// @ 0x012feae0
extern const float g_01485720;
extern float g_0164eeb0;
extern float g_0164eeb4;
extern float g_0164eeb8;
void FUN_012feae0() { g_0164eeb0 = 0.0f; g_0164eeb4 = g_01485720; g_0164eeb8 = 0.0f; }

// @ 0x01301580
extern const float g_01485720;
extern float g_0166bea0;
extern float g_0166bea4;
extern float g_0166bea8;
void FUN_01301580() { g_0166bea0 = 0.0f; g_0166bea4 = g_01485720; g_0166bea8 = 0.0f; }

// @ 0x013022e0
extern const float g_01485720;
extern float g_0166c52c;
extern float g_0166c530;
extern float g_0166c534;
void FUN_013022e0() { g_0166c52c = 0.0f; g_0166c530 = g_01485720; g_0166c534 = 0.0f; }

// @ 0x01302bd0
extern const float g_01485720;
extern float g_0166c7f4;
extern float g_0166c7f8;
extern float g_0166c7fc;
void FUN_01302bd0() { g_0166c7f4 = 0.0f; g_0166c7f8 = g_01485720; g_0166c7fc = 0.0f; }

// @ 0x013030a0
extern const float g_01485720;
extern float g_0166ca9c;
extern float g_0166caa0;
extern float g_0166caa4;
void FUN_013030a0() { g_0166ca9c = 0.0f; g_0166caa0 = g_01485720; g_0166caa4 = 0.0f; }

// @ 0x01303990
extern const float g_01485720;
extern float g_0166d708;
extern float g_0166d70c;
extern float g_0166d710;
void FUN_01303990() { g_0166d708 = 0.0f; g_0166d70c = g_01485720; g_0166d710 = 0.0f; }

// @ 0x013043c0
extern const float g_01485720;
extern float g_0166df28;
extern float g_0166df2c;
extern float g_0166df30;
void FUN_013043c0() { g_0166df28 = 0.0f; g_0166df2c = g_01485720; g_0166df30 = 0.0f; }

// @ 0x01304710
extern const float g_01485720;
extern float g_0166e050;
extern float g_0166e054;
extern float g_0166e058;
void FUN_01304710() { g_0166e050 = 0.0f; g_0166e054 = g_01485720; g_0166e058 = 0.0f; }

// @ 0x01304e90
extern const float g_01485720;
extern float g_0166e378;
extern float g_0166e37c;
extern float g_0166e380;
void FUN_01304e90() { g_0166e378 = 0.0f; g_0166e37c = g_01485720; g_0166e380 = 0.0f; }

// @ 0x013063b0
extern const float g_01485720;
extern float g_0166ecb0;
extern float g_0166ecb4;
extern float g_0166ecb8;
void FUN_013063b0() { g_0166ecb0 = 0.0f; g_0166ecb4 = g_01485720; g_0166ecb8 = 0.0f; }

// @ 0x01306700
extern const float g_01485720;
extern float g_0166edd8;
extern float g_0166eddc;
extern float g_0166ede0;
void FUN_01306700() { g_0166edd8 = 0.0f; g_0166eddc = g_01485720; g_0166ede0 = 0.0f; }

// @ 0x013071c0
extern const float g_01485720;
extern float g_0166f25c;
extern float g_0166f260;
extern float g_0166f264;
void FUN_013071c0() { g_0166f25c = 0.0f; g_0166f260 = g_01485720; g_0166f264 = 0.0f; }

// @ 0x01307890
extern const float g_01485720;
extern float g_01675940;
extern float g_01675944;
extern float g_01675948;
void FUN_01307890() { g_01675940 = 0.0f; g_01675944 = g_01485720; g_01675948 = 0.0f; }

// @ 0x01307be0
extern const float g_01485720;
extern float g_016766d8;
extern float g_016766dc;
extern float g_016766e0;
void FUN_01307be0() { g_016766d8 = 0.0f; g_016766dc = g_01485720; g_016766e0 = 0.0f; }

// @ 0x01307f80
extern const float g_01485720;
extern float g_016767f0;
extern float g_016767f4;
extern float g_016767f8;
void FUN_01307f80() { g_016767f0 = 0.0f; g_016767f4 = g_01485720; g_016767f8 = 0.0f; }

// @ 0x013082d0
extern const float g_01485720;
extern float g_01676904;
extern float g_01676908;
extern float g_0167690c;
void FUN_013082d0() { g_01676904 = 0.0f; g_01676908 = g_01485720; g_0167690c = 0.0f; }

// @ 0x01308670
extern const float g_01485720;
extern float g_01676a24;
extern float g_01676a28;
extern float g_01676a2c;
void FUN_01308670() { g_01676a24 = 0.0f; g_01676a28 = g_01485720; g_01676a2c = 0.0f; }

// @ 0x01308a10
extern const float g_01485720;
extern float g_01676b44;
extern float g_01676b48;
extern float g_01676b4c;
void FUN_01308a10() { g_01676b44 = 0.0f; g_01676b48 = g_01485720; g_01676b4c = 0.0f; }

// @ 0x013090a0
extern const float g_01485720;
extern float g_01676c74;
extern float g_01676c78;
extern float g_01676c7c;
void FUN_013090a0() { g_01676c74 = 0.0f; g_01676c78 = g_01485720; g_01676c7c = 0.0f; }

// @ 0x01309440
extern const float g_01485720;
extern float g_01676d94;
extern float g_01676d98;
extern float g_01676d9c;
void FUN_01309440() { g_01676d94 = 0.0f; g_01676d98 = g_01485720; g_01676d9c = 0.0f; }

// @ 0x013097e0
extern const float g_01485720;
extern float g_01676eb4;
extern float g_01676eb8;
extern float g_01676ebc;
void FUN_013097e0() { g_01676eb4 = 0.0f; g_01676eb8 = g_01485720; g_01676ebc = 0.0f; }

// @ 0x01309b80
extern const float g_01485720;
extern float g_01676fd4;
extern float g_01676fd8;
extern float g_01676fdc;
void FUN_01309b80() { g_01676fd4 = 0.0f; g_01676fd8 = g_01485720; g_01676fdc = 0.0f; }

// @ 0x01309f20
extern const float g_01485720;
extern float g_016770f4;
extern float g_016770f8;
extern float g_016770fc;
void FUN_01309f20() { g_016770f4 = 0.0f; g_016770f8 = g_01485720; g_016770fc = 0.0f; }

// @ 0x0130a2c0
extern const float g_01485720;
extern float g_01677210;
extern float g_01677214;
extern float g_01677218;
void FUN_0130a2c0() { g_01677210 = 0.0f; g_01677214 = g_01485720; g_01677218 = 0.0f; }

// @ 0x0130a610
extern const float g_01485720;
extern float g_01677328;
extern float g_0167732c;
extern float g_01677330;
void FUN_0130a610() { g_01677328 = 0.0f; g_0167732c = g_01485720; g_01677330 = 0.0f; }

// @ 0x0130a940
extern const float g_01485720;
extern float g_01677440;
extern float g_01677444;
extern float g_01677448;
void FUN_0130a940() { g_01677440 = 0.0f; g_01677444 = g_01485720; g_01677448 = 0.0f; }

// @ 0x0130ac70
extern const float g_01485720;
extern float g_01677550;
extern float g_01677554;
extern float g_01677558;
void FUN_0130ac70() { g_01677550 = 0.0f; g_01677554 = g_01485720; g_01677558 = 0.0f; }

// @ 0x0130afc0
extern const float g_01485720;
extern float g_01677664;
extern float g_01677668;
extern float g_0167766c;
void FUN_0130afc0() { g_01677664 = 0.0f; g_01677668 = g_01485720; g_0167766c = 0.0f; }

// @ 0x0130b370
extern const float g_01485720;
extern float g_01677784;
extern float g_01677788;
extern float g_0167778c;
void FUN_0130b370() { g_01677784 = 0.0f; g_01677788 = g_01485720; g_0167778c = 0.0f; }

// @ 0x0130b710
extern const float g_01485720;
extern float g_01677928;
extern float g_0167792c;
extern float g_01677930;
void FUN_0130b710() { g_01677928 = 0.0f; g_0167792c = g_01485720; g_01677930 = 0.0f; }

// @ 0x0130bad0
extern const float g_01485720;
extern float g_01677a44;
extern float g_01677a48;
extern float g_01677a4c;
void FUN_0130bad0() { g_01677a44 = 0.0f; g_01677a48 = g_01485720; g_01677a4c = 0.0f; }

// @ 0x0130be70
extern const float g_01485720;
extern float g_01677b60;
extern float g_01677b64;
extern float g_01677b68;
void FUN_0130be70() { g_01677b60 = 0.0f; g_01677b64 = g_01485720; g_01677b68 = 0.0f; }

// @ 0x0130c1e0
extern const float g_01485720;
extern float g_01677c78;
extern float g_01677c7c;
extern float g_01677c80;
void FUN_0130c1e0() { g_01677c78 = 0.0f; g_01677c7c = g_01485720; g_01677c80 = 0.0f; }

// @ 0x0130c530
extern const float g_01485720;
extern float g_01677d94;
extern float g_01677d98;
extern float g_01677d9c;
void FUN_0130c530() { g_01677d94 = 0.0f; g_01677d98 = g_01485720; g_01677d9c = 0.0f; }

// @ 0x0130c8d0
extern const float g_01485720;
extern float g_01677eb4;
extern float g_01677eb8;
extern float g_01677ebc;
void FUN_0130c8d0() { g_01677eb4 = 0.0f; g_01677eb8 = g_01485720; g_01677ebc = 0.0f; }

// @ 0x0130cc70
extern const float g_01485720;
extern float g_01677fd4;
extern float g_01677fd8;
extern float g_01677fdc;
void FUN_0130cc70() { g_01677fd4 = 0.0f; g_01677fd8 = g_01485720; g_01677fdc = 0.0f; }

// @ 0x0130d020
extern const float g_01485720;
extern float g_016780f4;
extern float g_016780f8;
extern float g_016780fc;
void FUN_0130d020() { g_016780f4 = 0.0f; g_016780f8 = g_01485720; g_016780fc = 0.0f; }

// @ 0x0130d3c0
extern const float g_01485720;
extern float g_01678294;
extern float g_01678298;
extern float g_0167829c;
void FUN_0130d3c0() { g_01678294 = 0.0f; g_01678298 = g_01485720; g_0167829c = 0.0f; }

// @ 0x0130d740
extern const float g_01485720;
extern float g_016783b0;
extern float g_016783b4;
extern float g_016783b8;
void FUN_0130d740() { g_016783b0 = 0.0f; g_016783b4 = g_01485720; g_016783b8 = 0.0f; }

// @ 0x0130da90
extern const float g_01485720;
extern float g_016784c0;
extern float g_016784c4;
extern float g_016784c8;
void FUN_0130da90() { g_016784c0 = 0.0f; g_016784c4 = g_01485720; g_016784c8 = 0.0f; }

// @ 0x0130dde0
extern const float g_01485720;
extern float g_016785d8;
extern float g_016785dc;
extern float g_016785e0;
void FUN_0130dde0() { g_016785d8 = 0.0f; g_016785dc = g_01485720; g_016785e0 = 0.0f; }

// @ 0x0130e130
extern const float g_01485720;
extern float g_016786f4;
extern float g_016786f8;
extern float g_016786fc;
void FUN_0130e130() { g_016786f4 = 0.0f; g_016786f8 = g_01485720; g_016786fc = 0.0f; }

// @ 0x0130e4d0
extern const float g_01485720;
extern float g_016788b4;
extern float g_016788b8;
extern float g_016788bc;
void FUN_0130e4d0() { g_016788b4 = 0.0f; g_016788b8 = g_01485720; g_016788bc = 0.0f; }

// @ 0x0130e8a0
extern const float g_01485720;
extern float g_016789d0;
extern float g_016789d4;
extern float g_016789d8;
void FUN_0130e8a0() { g_016789d0 = 0.0f; g_016789d4 = g_01485720; g_016789d8 = 0.0f; }

// @ 0x0130ebf0
extern const float g_01485720;
extern float g_01678ae8;
extern float g_01678aec;
extern float g_01678af0;
void FUN_0130ebf0() { g_01678ae8 = 0.0f; g_01678aec = g_01485720; g_01678af0 = 0.0f; }

// @ 0x0130ef40
extern const float g_01485720;
extern float g_01678c00;
extern float g_01678c04;
extern float g_01678c08;
void FUN_0130ef40() { g_01678c00 = 0.0f; g_01678c04 = g_01485720; g_01678c08 = 0.0f; }

// @ 0x0130f290
extern const float g_01485720;
extern float g_01678d18;
extern float g_01678d1c;
extern float g_01678d20;
void FUN_0130f290() { g_01678d18 = 0.0f; g_01678d1c = g_01485720; g_01678d20 = 0.0f; }

// @ 0x0130f5e0
extern const float g_01485720;
extern float g_01678e34;
extern float g_01678e38;
extern float g_01678e3c;
void FUN_0130f5e0() { g_01678e34 = 0.0f; g_01678e38 = g_01485720; g_01678e3c = 0.0f; }

// @ 0x0130f980
extern const float g_01485720;
extern float g_01678f5c;
extern float g_01678f60;
extern float g_01678f64;
void FUN_0130f980() { g_01678f5c = 0.0f; g_01678f60 = g_01485720; g_01678f64 = 0.0f; }

// @ 0x0130fd90
extern const float g_01485720;
extern float g_016790a0;
extern float g_016790a4;
extern float g_016790a8;
void FUN_0130fd90() { g_016790a0 = 0.0f; g_016790a4 = g_01485720; g_016790a8 = 0.0f; }

// @ 0x01310120
extern const float g_01485720;
extern float g_016791bc;
extern float g_016791c0;
extern float g_016791c4;
void FUN_01310120() { g_016791bc = 0.0f; g_016791c0 = g_01485720; g_016791c4 = 0.0f; }

// @ 0x013104c0
extern const float g_01485720;
extern float g_016792dc;
extern float g_016792e0;
extern float g_016792e4;
void FUN_013104c0() { g_016792dc = 0.0f; g_016792e0 = g_01485720; g_016792e4 = 0.0f; }

// @ 0x01310880
extern const float g_01485720;
extern float g_016794ac;
extern float g_016794b0;
extern float g_016794b4;
void FUN_01310880() { g_016794ac = 0.0f; g_016794b0 = g_01485720; g_016794b4 = 0.0f; }

// @ 0x01310c90
extern const float g_01485720;
extern float g_016795d4;
extern float g_016795d8;
extern float g_016795dc;
void FUN_01310c90() { g_016795d4 = 0.0f; g_016795d8 = g_01485720; g_016795dc = 0.0f; }

// @ 0x01311030
extern const float g_01485720;
extern float g_016797f4;
extern float g_016797f8;
extern float g_016797fc;
void FUN_01311030() { g_016797f4 = 0.0f; g_016797f8 = g_01485720; g_016797fc = 0.0f; }

// @ 0x013113d0
extern const float g_01485720;
extern float g_01679914;
extern float g_01679918;
extern float g_0167991c;
void FUN_013113d0() { g_01679914 = 0.0f; g_01679918 = g_01485720; g_0167991c = 0.0f; }

// @ 0x01311770
extern const float g_01485720;
extern float g_01679a34;
extern float g_01679a38;
extern float g_01679a3c;
void FUN_01311770() { g_01679a34 = 0.0f; g_01679a38 = g_01485720; g_01679a3c = 0.0f; }

// @ 0x01311b10
extern const float g_01485720;
extern float g_01679b50;
extern float g_01679b54;
extern float g_01679b58;
void FUN_01311b10() { g_01679b50 = 0.0f; g_01679b54 = g_01485720; g_01679b58 = 0.0f; }

// @ 0x01311e60
extern const float g_01485720;
extern float g_01679c6c;
extern float g_01679c70;
extern float g_01679c74;
void FUN_01311e60() { g_01679c6c = 0.0f; g_01679c70 = g_01485720; g_01679c74 = 0.0f; }

// @ 0x01312200
extern const float g_01485720;
extern float g_01679d88;
extern float g_01679d8c;
extern float g_01679d90;
void FUN_01312200() { g_01679d88 = 0.0f; g_01679d8c = g_01485720; g_01679d90 = 0.0f; }

// @ 0x01312550
extern const float g_01485720;
extern float g_01679ecc;
extern float g_01679ed0;
extern float g_01679ed4;
void FUN_01312550() { g_01679ecc = 0.0f; g_01679ed0 = g_01485720; g_01679ed4 = 0.0f; }

// @ 0x01312910
extern const float g_01485720;
extern float g_01679fe8;
extern float g_01679fec;
extern float g_01679ff0;
void FUN_01312910() { g_01679fe8 = 0.0f; g_01679fec = g_01485720; g_01679ff0 = 0.0f; }

// @ 0x01312c60
extern const float g_01485720;
extern float g_0167a100;
extern float g_0167a104;
extern float g_0167a108;
void FUN_01312c60() { g_0167a100 = 0.0f; g_0167a104 = g_01485720; g_0167a108 = 0.0f; }

// @ 0x0138e9e0
extern const float g_01485720;
extern float g_016c8c80;
extern float g_016c8c84;
extern float g_016c8c88;
void FUN_0138e9e0() { g_016c8c80 = 0.0f; g_016c8c84 = g_01485720; g_016c8c88 = 0.0f; }

// @ 0x0138f000
extern const float g_01485720;
extern float g_016c8f34;
extern float g_016c8f38;
extern float g_016c8f3c;
void FUN_0138f000() { g_016c8f34 = 0.0f; g_016c8f38 = g_01485720; g_016c8f3c = 0.0f; }

// @ 0x0138f790
extern const float g_01485720;
extern float g_016c924c;
extern float g_016c9250;
extern float g_016c9254;
void FUN_0138f790() { g_016c924c = 0.0f; g_016c9250 = g_01485720; g_016c9254 = 0.0f; }

// @ 0x0138fb70
extern const float g_01485720;
extern float g_016c94b8;
extern float g_016c94bc;
extern float g_016c94c0;
void FUN_0138fb70() { g_016c94b8 = 0.0f; g_016c94bc = g_01485720; g_016c94c0 = 0.0f; }

// @ 0x0138fdd0
extern const float g_01485720;
extern float g_016c953c;
extern float g_016c9540;
extern float g_016c9544;
void FUN_0138fdd0() { g_016c953c = 0.0f; g_016c9540 = g_01485720; g_016c9544 = 0.0f; }

// @ 0x01390b00
extern const float g_01485720;
extern float g_016c9bb8;
extern float g_016c9bbc;
extern float g_016c9bc0;
void FUN_01390b00() { g_016c9bb8 = 0.0f; g_016c9bbc = g_01485720; g_016c9bc0 = 0.0f; }

// @ 0x01390f40
extern const float g_01485720;
extern float g_016c9cf0;
extern float g_016c9cf4;
extern float g_016c9cf8;
void FUN_01390f40() { g_016c9cf0 = 0.0f; g_016c9cf4 = g_01485720; g_016c9cf8 = 0.0f; }

// @ 0x013b3230
extern const float g_01485720;
extern float g_016e4040;
extern float g_016e4044;
extern float g_016e4048;
void FUN_013b3230() { g_016e4040 = 0.0f; g_016e4044 = g_01485720; g_016e4048 = 0.0f; }
