// Generated by tools/matching/synth.py (template vec4_zero_init_sse). Do not edit by hand.
struct Vector4Z { volatile float x, y, z, w; Vector4Z(float a, float b, float c, float d) : x(a), y(b), z(c), w(d) {} };

// @ 0x01277d60
Vector4Z g_015e5080(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01278770
Vector4Z g_015e52f8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01278f20
Vector4Z g_015e5570(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012795a0
Vector4Z g_015e57e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01279c30
Vector4Z g_015e5a64(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127a2b0
Vector4Z g_015e5cec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127a910
Vector4Z g_015e5f68(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127af70
Vector4Z g_015e61e0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127b600
Vector4Z g_015e6458(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127bc60
Vector4Z g_015e66d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127c2c0
Vector4Z g_015e6948(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127c950
Vector4Z g_015e6bc0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127d000
Vector4Z g_015e6e40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127d660
Vector4Z g_015e70b8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127dcc0
Vector4Z g_015e7330(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127e320
Vector4Z g_015e75a8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127e980
Vector4Z g_015e7820(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127f000
Vector4Z g_015e7a98(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127f660
Vector4Z g_015e7d10(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0127fcc0
Vector4Z g_015e7f88(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01280320
Vector4Z g_015e8200(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01280980
Vector4Z g_015e8478(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01281000
Vector4Z g_015e86f0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01281660
Vector4Z g_015e8974(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01281d60
Vector4Z g_015e8bf8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012823c0
Vector4Z g_015e8e70(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01282a20
Vector4Z g_015e90e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01283090
Vector4Z g_015e9360(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012836f0
Vector4Z g_015e95d8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01283d50
Vector4Z g_015e9850(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012843b0
Vector4Z g_015e9ac8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01284a10
Vector4Z g_015e9d40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01285090
Vector4Z g_015e9fb8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012856f0
Vector4Z g_015ea230(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01285d50
Vector4Z g_015ea4a8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012863b0
Vector4Z g_015ea724(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01286a10
Vector4Z g_015ea9a0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01287090
Vector4Z g_015eac18(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012876f0
Vector4Z g_015eae90(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01287d50
Vector4Z g_015eb108(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012883b0
Vector4Z g_015eb380(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01288a10
Vector4Z g_015eb5f8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01289090
Vector4Z g_015eb87c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01289760
Vector4Z g_015ebaf8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01289dc0
Vector4Z g_015ebd70(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128a450
Vector4Z g_015ebfe8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128aab0
Vector4Z g_015ec260(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128b110
Vector4Z g_015ec4d8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128b770
Vector4Z g_015ec750(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128bdd0
Vector4Z g_015ec9c8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128c430
Vector4Z g_015ecc40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128ca90
Vector4Z g_015eceb8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128d0f0
Vector4Z g_015ed130(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128d750
Vector4Z g_015ed3a8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128ddb0
Vector4Z g_015ed620(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128e410
Vector4Z g_015ed898(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128ea70
Vector4Z g_015edb10(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128f0d0
Vector4Z g_015edd88(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128f760
Vector4Z g_015ee000(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0128fdf0
Vector4Z g_015ee278(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01290490
Vector4Z g_015ee500(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01290b10
Vector4Z g_015ee778(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01291170
Vector4Z g_015eea08(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01291890
Vector4Z g_015eec94(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01291f30
Vector4Z g_015eef18(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012925d0
Vector4Z g_015ef190(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01292c30
Vector4Z g_015ef408(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01293290
Vector4Z g_015ef680(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012938f0
Vector4Z g_015ef8f8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01293f80
Vector4Z g_015efb70(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01294600
Vector4Z g_015efde8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01294c60
Vector4Z g_015f0070(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01295310
Vector4Z g_015f02f0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01295970
Vector4Z g_015f0578(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01296000
Vector4Z g_015f07f0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01296660
Vector4Z g_015f0a78(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01296ce0
Vector4Z g_015f0cf0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01297370
Vector4Z g_015f0f68(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012979d0
Vector4Z g_015f11e0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01298030
Vector4Z g_015f1458(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01298690
Vector4Z g_015f16d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01298cf0
Vector4Z g_015f1948(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01299350
Vector4Z g_015f1bc0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012999e0
Vector4Z g_015f1e38(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129a060
Vector4Z g_015f20b8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129a700
Vector4Z g_015f2328(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129ad60
Vector4Z g_015f25a0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129b3f0
Vector4Z g_015f2818(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129ba50
Vector4Z g_015f2aa0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129c0b0
Vector4Z g_015f2d18(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129c740
Vector4Z g_015f2f90(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129cda0
Vector4Z g_015f3208(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129d400
Vector4Z g_015f3488(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129da60
Vector4Z g_015f3718(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129e7d0
Vector4Z g_015f3c08(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129ee30
Vector4Z g_015f3e80(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129f490
Vector4Z g_015f40fc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0129fb20
Vector4Z g_015f437c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a01b0
Vector4Z g_015f45f8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a0810
Vector4Z g_015f4870(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a0e70
Vector4Z g_015f4af8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a1500
Vector4Z g_015f4d74(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a1b70
Vector4Z g_015f5000(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a21f0
Vector4Z g_015f5428(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a2c20
Vector4Z g_015f57a4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a33a0
Vector4Z g_015f5a48(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a3a30
Vector4Z g_015f5cf0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a40b0
Vector4Z g_015f5f6c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a4720
Vector4Z g_015f6240(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a5000
Vector4Z g_015f64cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a5670
Vector4Z g_015f6750(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a5cd0
Vector4Z g_015f69cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a6350
Vector4Z g_015f6c48(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a69b0
Vector4Z g_015f6ec4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a7060
Vector4Z g_015f7140(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a76c0
Vector4Z g_015f73b8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a7d20
Vector4Z g_015f7630(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a83b0
Vector4Z g_015f78a8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a8a40
Vector4Z g_015f7b20(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a9110
Vector4Z g_015f7d9c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a97b0
Vector4Z g_015f8018(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012a9e40
Vector4Z g_015f8294(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012aa4c0
Vector4Z g_015f8510(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012aab20
Vector4Z g_015f8788(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ab190
Vector4Z g_015f8a00(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ab840
Vector4Z g_015f8c84(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012abf20
Vector4Z g_015f8ef8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ac5a0
Vector4Z g_015f9170(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012acc00
Vector4Z g_015f93e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ad260
Vector4Z g_015f9664(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ad8f0
Vector4Z g_015f994c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012adf80
Vector4Z g_015f9bc8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ae630
Vector4Z g_015f9e40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012aec90
Vector4Z g_015fa0d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012af340
Vector4Z g_015fa360(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012afaf0
Vector4Z g_015fa5e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b01b0
Vector4Z g_015fa860(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b0810
Vector4Z g_015faad8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b0e70
Vector4Z g_015fad50(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b14d0
Vector4Z g_015fafc8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b1b60
Vector4Z g_015fb268(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b21f0
Vector4Z g_015fb4e0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b2880
Vector4Z g_015fb758(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b2f10
Vector4Z g_015fb9d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b35a0
Vector4Z g_015fbc54(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b3c30
Vector4Z g_015fbed0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b4290
Vector4Z g_015fc14c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b4920
Vector4Z g_015fc3cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b5190
Vector4Z g_015fc648(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b57f0
Vector4Z g_015fc8d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b5eb0
Vector4Z g_015fcb48(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b6470
Vector4Z g_015fcdf8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b6a30
Vector4Z g_015fd05c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b7000
Vector4Z g_015fd2c4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b7600
Vector4Z g_015fd530(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b7c00
Vector4Z g_015fd794(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b81c0
Vector4Z g_015fda98(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b8780
Vector4Z g_015fdcfc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b8d80
Vector4Z g_015fdf64(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b9380
Vector4Z g_015fe1d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b9980
Vector4Z g_015fe444(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012b9f80
Vector4Z g_015fe6b4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ba5a0
Vector4Z g_015fe928(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012babe0
Vector4Z g_015feba4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bb1f0
Vector4Z g_015fee14(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bb7f0
Vector4Z g_015ff084(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bbdf0
Vector4Z g_015ff2f4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bc3b0
Vector4Z g_015ff564(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bc9b0
Vector4Z g_015ff7d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bcfb0
Vector4Z g_015ffa4c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bd5b0
Vector4Z g_015ffcbc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bdbc0
Vector4Z g_015fff2c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012be1c0
Vector4Z g_016001a0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012be800
Vector4Z g_01600404(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bee00
Vector4Z g_01600678(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bf400
Vector4Z g_016008ec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bf9c0
Vector4Z g_01600b5c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012bffc0
Vector4Z g_01600dcc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c05d0
Vector4Z g_0160103c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c0bc0
Vector4Z g_016012ac(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c11c0
Vector4Z g_01601514(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c17c0
Vector4Z g_01601788(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c1d90
Vector4Z g_016019f4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c2390
Vector4Z g_01601c60(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c2990
Vector4Z g_01601ec4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c2f90
Vector4Z g_0160212c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c3560
Vector4Z g_0160239c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c3b60
Vector4Z g_01602604(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c4170
Vector4Z g_01602888(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c4780
Vector4Z g_01602b34(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c4d80
Vector4Z g_01602da4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c5380
Vector4Z g_01603014(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c5980
Vector4Z g_01603288(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c5fc0
Vector4Z g_01604364(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c65c0
Vector4Z g_016045d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c6bc0
Vector4Z g_01604848(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c71e0
Vector4Z g_01604ab4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c77b0
Vector4Z g_01604d64(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c7e10
Vector4Z g_01604fe0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c8410
Vector4Z g_0160524c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c8a10
Vector4Z g_016054c4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c9060
Vector4Z g_01605734(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c9690
Vector4Z g_016059a4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012c9cc0
Vector4Z g_01605c24(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ca2e0
Vector4Z g_01605f44(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ca8d0
Vector4Z g_016061b4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012caed0
Vector4Z g_0160641c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cb4d0
Vector4Z g_016066b4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cbaf0
Vector4Z g_01606928(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cc0b0
Vector4Z g_01606c30(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cc920
Vector4Z g_01606ef0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ccf60
Vector4Z g_01607154(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cd5e0
Vector4Z g_016073c8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cdc20
Vector4Z g_01607630(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ce260
Vector4Z g_016078a4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ce8a0
Vector4Z g_01607b18(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ceee0
Vector4Z g_01607d88(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cf520
Vector4Z g_01607fec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012cfb60
Vector4Z g_01618260(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d01a0
Vector4Z g_016184c8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d07e0
Vector4Z g_01618730(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d0e20
Vector4Z g_01618994(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d1460
Vector4Z g_01618c04(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d1aa0
Vector4Z g_01618e88(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d2380
Vector4Z g_0161917c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d2a10
Vector4Z g_016193e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d3060
Vector4Z g_0161965c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d36a0
Vector4Z g_0161fd10(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d3d70
Vector4Z g_0161ffa0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d43b0
Vector4Z g_01620208(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d4a00
Vector4Z g_01624470(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d5060
Vector4Z g_016246d8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d5730
Vector4Z g_01628dac(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d5d70
Vector4Z g_01629018(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d63b0
Vector4Z g_0162927c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d69f0
Vector4Z g_016294f0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d7030
Vector4Z g_01629758(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d7670
Vector4Z g_016299d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d7de0
Vector4Z g_01629c50(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d8420
Vector4Z g_01629eb8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d8a70
Vector4Z g_0162a120(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d90b0
Vector4Z g_0162a3ec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d9720
Vector4Z g_0162a658(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012d9d60
Vector4Z g_0162a8c0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012da3a0
Vector4Z g_0162ab38(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012da9f0
Vector4Z g_0162ada0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012db030
Vector4Z g_0162b01c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012db670
Vector4Z g_0162b2a8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dbce0
Vector4Z g_0162b510(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dc320
Vector4Z g_0162b778(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dc960
Vector4Z g_0162e9f4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dcfa0
Vector4Z g_0162ec70(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dd650
Vector4Z g_0162ef1c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ddc90
Vector4Z g_0162f194(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012de2f0
Vector4Z g_0162f400(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012de930
Vector4Z g_0162f668(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012def70
Vector4Z g_0162f8d0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012df5e0
Vector4Z g_0162fb38(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012dfd00
Vector4Z g_0162fdd4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e0340
Vector4Z g_01630084(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e09b0
Vector4Z g_016302f0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e1000
Vector4Z g_01630588(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e16a0
Vector4Z g_01630800(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e1ce0
Vector4Z g_01630a64(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e2320
Vector4Z g_01630cf4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e2960
Vector4Z g_01630f60(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e3090
Vector4Z g_016311ec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e36d0
Vector4Z g_01632da4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e3d80
Vector4Z g_01633d3c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e4440
Vector4Z g_01633fdc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e5140
Vector4Z g_01634410(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e5790
Vector4Z g_01634674(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e5dd0
Vector4Z g_0163490c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e6410
Vector4Z g_01634b80(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e6a50
Vector4Z g_01634dec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e7090
Vector4Z g_01635078(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e7700
Vector4Z g_016352e0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e7d40
Vector4Z g_01635548(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e8380
Vector4Z g_016357b0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e89c0
Vector4Z g_01635a18(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e9000
Vector4Z g_01635c80(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e9650
Vector4Z g_01635ee8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012e9c90
Vector4Z g_0163614c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ea2d0
Vector4Z g_016363cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ea8d0
Vector4Z g_0163663c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012eaee0
Vector4Z g_016368b0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012eb530
Vector4Z g_01636b24(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ebb70
Vector4Z g_01636d94(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ec1e0
Vector4Z g_0163700c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ec7e0
Vector4Z g_01637280(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ece30
Vector4Z g_016374f4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ed430
Vector4Z g_01637764(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012eda30
Vector4Z g_016379d8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ee090
Vector4Z g_01637c68(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ee700
Vector4Z g_01637edc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012eed00
Vector4Z g_01638150(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ef350
Vector4Z g_016383f4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012ef950
Vector4Z g_01638664(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012eff10
Vector4Z g_016388d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f0540
Vector4Z g_01638b40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f0b40
Vector4Z g_01638dac(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f1140
Vector4Z g_01639020(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f1790
Vector4Z g_01639294(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f1d90
Vector4Z g_0163956c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f2420
Vector4Z g_016397d4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f2a20
Vector4Z g_01639a48(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f3090
Vector4Z g_01639cbc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f36d0
Vector4Z g_01639f2c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f3cd0
Vector4Z g_0163a19c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f42d0
Vector4Z g_0163a420(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f48e0
Vector4Z g_0163a694(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f4ea0
Vector4Z g_0163a8fc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f54a0
Vector4Z g_0163ab6c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012f8c60
Vector4Z g_0164c2b0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012fa030
Vector4Z g_0164ce54(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012faba0
Vector4Z g_0164d38c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012fb200
Vector4Z g_0164d5fc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012fbae0
Vector4Z g_0164d9cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x012fec50
Vector4Z g_0164eeec(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013016f0
Vector4Z g_0166bedc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01302450
Vector4Z g_0166c568(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01302d40
Vector4Z g_0166c830(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01303210
Vector4Z g_0166cad8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01303b00
Vector4Z g_0166d748(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01304530
Vector4Z g_0166df34(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01304880
Vector4Z g_0166e05c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01305000
Vector4Z g_0166e388(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01306520
Vector4Z g_0166ecbc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01306870
Vector4Z g_0166ede4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01307330
Vector4Z g_0166f298(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01307a00
Vector4Z g_0167594c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01307d50
Vector4Z g_016766e4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013080f0
Vector4Z g_016767fc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01308440
Vector4Z g_01676910(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013087e0
Vector4Z g_01676a30(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01308b80
Vector4Z g_01676b50(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01309210
Vector4Z g_01676c80(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013095b0
Vector4Z g_01676da0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01309950
Vector4Z g_01676ec0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01309cf0
Vector4Z g_01676fe0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130a090
Vector4Z g_01677100(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130a430
Vector4Z g_0167721c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130a780
Vector4Z g_01677334(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130aab0
Vector4Z g_0167744c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130ade0
Vector4Z g_0167755c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130b140
Vector4Z g_01677670(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130b4e0
Vector4Z g_01677790(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130b880
Vector4Z g_01677934(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130bc40
Vector4Z g_01677a50(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130c000
Vector4Z g_01677b6c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130c350
Vector4Z g_01677c84(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130c6a0
Vector4Z g_01677da0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130ca40
Vector4Z g_01677ec0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130cde0
Vector4Z g_01677fe0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130d190
Vector4Z g_01678100(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130d530
Vector4Z g_016782a0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130d8b0
Vector4Z g_016783bc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130dc00
Vector4Z g_016784cc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130df50
Vector4Z g_016785e4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130e2a0
Vector4Z g_01678700(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130e640
Vector4Z g_016788c0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130ea10
Vector4Z g_016789dc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130ed60
Vector4Z g_01678af4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130f0b0
Vector4Z g_01678c0c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130f400
Vector4Z g_01678d24(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130f750
Vector4Z g_01678e40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130faf0
Vector4Z g_01678f68(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0130ff00
Vector4Z g_016790ac(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01310290
Vector4Z g_016791c8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01310630
Vector4Z g_016792e8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013109f0
Vector4Z g_016794b8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01310e00
Vector4Z g_016795e0(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013111a0
Vector4Z g_01679800(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01311540
Vector4Z g_01679920(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013118e0
Vector4Z g_01679a40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01311c80
Vector4Z g_01679b5c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01311fd0
Vector4Z g_01679c78(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01312370
Vector4Z g_01679d94(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013126c0
Vector4Z g_01679ed8(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01312a80
Vector4Z g_01679ff4(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x01312dd0
Vector4Z g_0167a10c(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0138eb50
Vector4Z g_016c8cbc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0138f170
Vector4Z g_016c8f40(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0138f900
Vector4Z g_016c9258(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x0138ff40
Vector4Z g_016c9548(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013910b0
Vector4Z g_016c9cfc(0.0f, 0.0f, 0.0f, 0.0f);

// @ 0x013b33a0
Vector4Z g_016e407c(0.0f, 0.0f, 0.0f, 0.0f);
