// Generated by tools/matching/synth.py (template vec_reserve_div_stride_one_helper). Do not edit by hand.
extern "C" {
void* __cdecl EASTL_allocator_allocate(unsigned, const char*, int, int, const char*, int);
void __cdecl EASTL_allocator_deallocate(void*);
}

// @ 0x0079a3f0
extern const char s_0079a3f0[]; extern const char n_0079a3f0[];
struct E_0079a3f0 { char d[20]; };
void __cdecl h1_0079a3f0(E_0079a3f0*, E_0079a3f0*, E_0079a3f0*);
struct V_0079a3f0 {
  E_0079a3f0 *b, *e, *c;
  void f(unsigned n);
};
void V_0079a3f0::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_0079a3f0* nb = n ? (E_0079a3f0*)EASTL_allocator_allocate(n * sizeof(E_0079a3f0), n_0079a3f0, 0, 0, s_0079a3f0, 0xd1) : 0;
      h1_0079a3f0(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x009df630
extern const char s_009df630[]; extern const char n_009df630[];
struct E_009df630 { char d[12]; };
void __cdecl h1_009df630(E_009df630*, E_009df630*, E_009df630*);
struct V_009df630 {
  E_009df630 *b, *e, *c;
  void f(unsigned n);
};
void V_009df630::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_009df630* nb = n ? (E_009df630*)EASTL_allocator_allocate(n * sizeof(E_009df630), n_009df630, 0, 0, s_009df630, 0xd1) : 0;
      h1_009df630(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00b84a60
extern const char s_00b84a60[]; extern const char n_00b84a60[];
struct E_00b84a60 { char d[12]; };
void __cdecl h1_00b84a60(E_00b84a60*, E_00b84a60*, E_00b84a60*);
struct V_00b84a60 {
  E_00b84a60 *b, *e, *c;
  void f(unsigned n);
};
void V_00b84a60::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00b84a60* nb = n ? (E_00b84a60*)EASTL_allocator_allocate(n * sizeof(E_00b84a60), n_00b84a60, 0, 0, s_00b84a60, 0xd1) : 0;
      h1_00b84a60(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00baa200
extern const char s_00baa200[]; extern const char n_00baa200[];
struct E_00baa200 { char d[12]; };
void __cdecl h1_00baa200(E_00baa200*, E_00baa200*, E_00baa200*);
struct V_00baa200 {
  E_00baa200 *b, *e, *c;
  void f(unsigned n);
};
void V_00baa200::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00baa200* nb = n ? (E_00baa200*)EASTL_allocator_allocate(n * sizeof(E_00baa200), n_00baa200, 0, 0, s_00baa200, 0xd1) : 0;
      h1_00baa200(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00c00fb0
extern const char s_00c00fb0[]; extern const char n_00c00fb0[];
struct E_00c00fb0 { char d[20]; };
void __cdecl h1_00c00fb0(E_00c00fb0*, E_00c00fb0*, E_00c00fb0*);
struct V_00c00fb0 {
  E_00c00fb0 *b, *e, *c;
  void f(unsigned n);
};
void V_00c00fb0::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00c00fb0* nb = n ? (E_00c00fb0*)EASTL_allocator_allocate(n * sizeof(E_00c00fb0), n_00c00fb0, 0, 0, s_00c00fb0, 0xd1) : 0;
      h1_00c00fb0(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00c51240
extern const char s_00c51240[]; extern const char n_00c51240[];
struct E_00c51240 { char d[20]; };
void __cdecl h1_00c51240(E_00c51240*, E_00c51240*, E_00c51240*);
struct V_00c51240 {
  E_00c51240 *b, *e, *c;
  void f(unsigned n);
};
void V_00c51240::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00c51240* nb = n ? (E_00c51240*)EASTL_allocator_allocate(n * sizeof(E_00c51240), n_00c51240, 0, 0, s_00c51240, 0xd1) : 0;
      h1_00c51240(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00c8d890
extern const char s_00c8d890[]; extern const char n_00c8d890[];
struct E_00c8d890 { char d[12]; };
void __cdecl h1_00c8d890(E_00c8d890*, E_00c8d890*, E_00c8d890*);
struct V_00c8d890 {
  E_00c8d890 *b, *e, *c;
  void f(unsigned n);
};
void V_00c8d890::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00c8d890* nb = n ? (E_00c8d890*)EASTL_allocator_allocate(n * sizeof(E_00c8d890), n_00c8d890, 0, 0, s_00c8d890, 0xd1) : 0;
      h1_00c8d890(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}


// @ 0x00cc5440
extern const char s_00cc5440[]; extern const char n_00cc5440[];
struct E_00cc5440 { char d[36]; };
void __cdecl h1_00cc5440(E_00cc5440*, E_00cc5440*, E_00cc5440*);
struct V_00cc5440 {
  E_00cc5440 *b, *e, *c;
  void f(unsigned n);
};
void V_00cc5440::f(unsigned n) {
    if (n > (unsigned)(c - b)) {
      E_00cc5440* nb = n ? (E_00cc5440*)EASTL_allocator_allocate(n * sizeof(E_00cc5440), n_00cc5440, 0, 0, s_00cc5440, 0xd1) : 0;
      h1_00cc5440(b, e, nb);
      if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
      unsigned cnt = e - b;
      b = nb; e = nb + cnt; c = nb + n;
    }
}

