// Generated by tools/matching/synth.py (template vec_erase_vcall_dtor). Do not edit by hand.

// @ 0x005c2170
struct I_005c2170 { virtual void v0(); virtual void v1(); virtual void v2(); };
struct P_005c2170 { I_005c2170* p; };
P_005c2170* X_005c2170(P_005c2170*, P_005c2170*, P_005c2170*);
struct V_005c2170 { int a; P_005c2170* e; void f(P_005c2170*, P_005c2170*); };
void V_005c2170::f(P_005c2170* first, P_005c2170* last) {
  P_005c2170* p = X_005c2170(last, e, first);
  P_005c2170* end = e;
  for (P_005c2170* i = p; i < end; ++i) if (i->p) i->p->v2();
  e = (P_005c2170*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00663430
struct I_00663430 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); };
struct P_00663430 { I_00663430* p; };
P_00663430* X_00663430(P_00663430*, P_00663430*, P_00663430*);
struct V_00663430 { int a; P_00663430* e; void f(P_00663430*, P_00663430*); };
void V_00663430::f(P_00663430* first, P_00663430* last) {
  P_00663430* p = X_00663430(last, e, first);
  P_00663430* end = e;
  for (P_00663430* i = p; i < end; ++i) if (i->p) i->p->v3();
  e = (P_00663430*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x006ec840
struct I_006ec840 { virtual void v0(); virtual void v1(); };
struct P_006ec840 { I_006ec840* p; };
P_006ec840* X_006ec840(P_006ec840*, P_006ec840*, P_006ec840*);
struct V_006ec840 { int a; P_006ec840* e; void f(P_006ec840*, P_006ec840*); };
void V_006ec840::f(P_006ec840* first, P_006ec840* last) {
  P_006ec840* p = X_006ec840(last, e, first);
  P_006ec840* end = e;
  for (P_006ec840* i = p; i < end; ++i) if (i->p) i->p->v1();
  e = (P_006ec840*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00a8c4e0
struct I_00a8c4e0 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); };
struct P_00a8c4e0 { I_00a8c4e0* p; };
P_00a8c4e0* X_00a8c4e0(P_00a8c4e0*, P_00a8c4e0*, P_00a8c4e0*);
struct V_00a8c4e0 { int a; P_00a8c4e0* e; void f(P_00a8c4e0*, P_00a8c4e0*); };
void V_00a8c4e0::f(P_00a8c4e0* first, P_00a8c4e0* last) {
  P_00a8c4e0* p = X_00a8c4e0(last, e, first);
  P_00a8c4e0* end = e;
  for (P_00a8c4e0* i = p; i < end; ++i) if (i->p) i->p->v14();
  e = (P_00a8c4e0*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00ae6cc0
struct I_00ae6cc0 { virtual void v0(); virtual void v1(); virtual void v2(); };
struct P_00ae6cc0 { I_00ae6cc0* p; };
P_00ae6cc0* X_00ae6cc0(P_00ae6cc0*, P_00ae6cc0*, P_00ae6cc0*);
struct V_00ae6cc0 { int a; P_00ae6cc0* e; void f(P_00ae6cc0*, P_00ae6cc0*); };
void V_00ae6cc0::f(P_00ae6cc0* first, P_00ae6cc0* last) {
  P_00ae6cc0* p = X_00ae6cc0(last, e, first);
  P_00ae6cc0* end = e;
  for (P_00ae6cc0* i = p; i < end; ++i) if (i->p) i->p->v2();
  e = (P_00ae6cc0*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00ae6e70
struct I_00ae6e70 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); virtual void v15(); virtual void v16(); virtual void v17(); virtual void v18(); virtual void v19(); virtual void v20(); virtual void v21(); virtual void v22(); virtual void v23(); virtual void v24(); virtual void v25(); };
struct P_00ae6e70 { I_00ae6e70* p; };
P_00ae6e70* X_00ae6e70(P_00ae6e70*, P_00ae6e70*, P_00ae6e70*);
struct V_00ae6e70 { int a; P_00ae6e70* e; void f(P_00ae6e70*, P_00ae6e70*); };
void V_00ae6e70::f(P_00ae6e70* first, P_00ae6e70* last) {
  P_00ae6e70* p = X_00ae6e70(last, e, first);
  P_00ae6e70* end = e;
  for (P_00ae6e70* i = p; i < end; ++i) if (i->p) i->p->v25();
  e = (P_00ae6e70*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00b0dec0
struct I_00b0dec0 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); virtual void v15(); virtual void v16(); virtual void v17(); virtual void v18(); virtual void v19(); virtual void v20(); virtual void v21(); virtual void v22(); virtual void v23(); };
struct P_00b0dec0 { I_00b0dec0* p; };
P_00b0dec0* X_00b0dec0(P_00b0dec0*, P_00b0dec0*, P_00b0dec0*);
struct V_00b0dec0 { int a; P_00b0dec0* e; void f(P_00b0dec0*, P_00b0dec0*); };
void V_00b0dec0::f(P_00b0dec0* first, P_00b0dec0* last) {
  P_00b0dec0* p = X_00b0dec0(last, e, first);
  P_00b0dec0* end = e;
  for (P_00b0dec0* i = p; i < end; ++i) if (i->p) i->p->v23();
  e = (P_00b0dec0*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00b48e40
struct I_00b48e40 { virtual void v0(); virtual void v1(); virtual void v2(); virtual void v3(); virtual void v4(); virtual void v5(); virtual void v6(); virtual void v7(); virtual void v8(); virtual void v9(); virtual void v10(); virtual void v11(); virtual void v12(); virtual void v13(); virtual void v14(); virtual void v15(); virtual void v16(); virtual void v17(); virtual void v18(); virtual void v19(); virtual void v20(); virtual void v21(); virtual void v22(); virtual void v23(); virtual void v24(); virtual void v25(); virtual void v26(); virtual void v27(); virtual void v28(); virtual void v29(); virtual void v30(); virtual void v31(); virtual void v32(); virtual void v33(); virtual void v34(); virtual void v35(); virtual void v36(); virtual void v37(); virtual void v38(); virtual void v39(); virtual void v40(); virtual void v41(); virtual void v42(); virtual void v43(); virtual void v44(); virtual void v45(); virtual void v46(); virtual void v47(); virtual void v48(); };
struct P_00b48e40 { I_00b48e40* p; };
P_00b48e40* X_00b48e40(P_00b48e40*, P_00b48e40*, P_00b48e40*);
struct V_00b48e40 { int a; P_00b48e40* e; void f(P_00b48e40*, P_00b48e40*); };
void V_00b48e40::f(P_00b48e40* first, P_00b48e40* last) {
  P_00b48e40* p = X_00b48e40(last, e, first);
  P_00b48e40* end = e;
  for (P_00b48e40* i = p; i < end; ++i) if (i->p) i->p->v48();
  e = (P_00b48e40*)((char*)e - ((char*)last - (char*)first)); }


// @ 0x00e25bd0
struct I_00e25bd0 { virtual void v0(); virtual void v1(); };
struct P_00e25bd0 { I_00e25bd0* p; };
P_00e25bd0* X_00e25bd0(P_00e25bd0*, P_00e25bd0*, P_00e25bd0*);
struct V_00e25bd0 { int a; P_00e25bd0* e; void f(P_00e25bd0*, P_00e25bd0*); };
void V_00e25bd0::f(P_00e25bd0* first, P_00e25bd0* last) {
  P_00e25bd0* p = X_00e25bd0(last, e, first);
  P_00e25bd0* end = e;
  for (P_00e25bd0* i = p; i < end; ++i) if (i->p) i->p->v1();
  e = (P_00e25bd0*)((char*)e - ((char*)last - (char*)first)); }

