// Generated by tools/matching/synth.py (template vec_dtor_virt_elems_hdr_free). Do not edit by hand.
extern void __cdecl EASTL_allocator_deallocate(void*);

// @ 0x0059ee80
struct E_0059ee80 { virtual ~E_0059ee80(); int pad[5]; };
struct C_0059ee80 { E_0059ee80* b; E_0059ee80* e; void Run(); };
void C_0059ee80::Run() {
 E_0059ee80* last = e;
 for (E_0059ee80* i = b; i < last; ++i) i->~E_0059ee80();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x007f6d50
struct E_007f6d50 { virtual ~E_007f6d50(); int pad[34]; };
struct C_007f6d50 { E_007f6d50* b; E_007f6d50* e; void Run(); };
void C_007f6d50::Run() {
 E_007f6d50* last = e;
 for (E_007f6d50* i = b; i < last; ++i) i->~E_007f6d50();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x00ac8ec0
struct E_00ac8ec0 { virtual ~E_00ac8ec0(); int pad[2]; };
struct C_00ac8ec0 { E_00ac8ec0* b; E_00ac8ec0* e; void Run(); };
void C_00ac8ec0::Run() {
 E_00ac8ec0* last = e;
 for (E_00ac8ec0* i = b; i < last; ++i) i->~E_00ac8ec0();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x00b002a0
struct E_00b002a0 { virtual ~E_00b002a0(); int pad[8]; };
struct C_00b002a0 { E_00b002a0* b; E_00b002a0* e; void Run(); };
void C_00b002a0::Run() {
 E_00b002a0* last = e;
 for (E_00b002a0* i = b; i < last; ++i) i->~E_00b002a0();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x00bf1b60
struct E_00bf1b60 { virtual ~E_00bf1b60(); int pad[7]; };
struct C_00bf1b60 { E_00bf1b60* b; E_00bf1b60* e; void Run(); };
void C_00bf1b60::Run() {
 E_00bf1b60* last = e;
 for (E_00bf1b60* i = b; i < last; ++i) i->~E_00bf1b60();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x00cd57d0
struct E_00cd57d0 { virtual ~E_00cd57d0(); int pad[3]; };
struct C_00cd57d0 { E_00cd57d0* b; E_00cd57d0* e; void Run(); };
void C_00cd57d0::Run() {
 E_00cd57d0* last = e;
 for (E_00cd57d0* i = b; i < last; ++i) i->~E_00cd57d0();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}

// @ 0x00f12ac0
struct E_00f12ac0 { virtual ~E_00f12ac0(); int pad[27]; };
struct C_00f12ac0 { E_00f12ac0* b; E_00f12ac0* e; void Run(); };
void C_00f12ac0::Run() {
 E_00f12ac0* last = e;
 for (E_00f12ac0* i = b; i < last; ++i) i->~E_00f12ac0();
 if (b && ((int*)b)[-1]) EASTL_allocator_deallocate(b);
}
