// Generated by tools/matching/synth.py (template vec_push_back_addref_ptr). Do not edit by hand.

inline void* operator new(unsigned, void* p) { return p; }
struct RC { virtual void AddRef(); };
struct P { RC* p; P(const P& o) : p(o.p) { if (p) p->AddRef(); } };

// @ 0x005c42f0
struct W005c42f0 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_005c42f0(const P& v);
};
void W005c42f0::FUN_005c42f0(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x006794e0
struct W006794e0 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_006794e0(const P& v);
};
void W006794e0::FUN_006794e0(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x0082ccf0
struct W0082ccf0 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_0082ccf0(const P& v);
};
void W0082ccf0::FUN_0082ccf0(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x008e3620
struct W008e3620 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_008e3620(const P& v);
};
void W008e3620::FUN_008e3620(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x00a7f430
struct W00a7f430 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_00a7f430(const P& v);
};
void W00a7f430::FUN_00a7f430(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x00e1c7f0
struct W00e1c7f0 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_00e1c7f0(const P& v);
};
void W00e1c7f0::FUN_00e1c7f0(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }


// @ 0x00e26c40
struct W00e26c40 { int pad; P* b; P* e;
  void Ins(P* pos, const P& v);
  void FUN_00e26c40(const P& v);
};
void W00e26c40::FUN_00e26c40(const P& v) { if (b < e) { new (b++) P(v); } else Ins(b, v); }

