// Generated by tools/matching/synth.py (template vector_copy_ctor_div). Do not edit by hand.

// @ 0x007d6320
struct T_007d6320 { char d[120]; };
struct V_007d6320 {
  T_007d6320 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_007d6320& __thiscall FUN_007d6320(const V_007d6320* o);
};
void Ucopy_007d6320(T_007d6320** out, T_007d6320* f, T_007d6320* l, T_007d6320* d, const void* a);
V_007d6320& V_007d6320::FUN_007d6320(const V_007d6320* o) {
  const V_007d6320* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_007d6320((T_007d6320**)&o, p->b, p->e, b, o);
  e = (T_007d6320*)o;
  return *this;
}

// @ 0x009d86c0
struct T_009d86c0 { char d[56]; };
struct V_009d86c0 {
  T_009d86c0 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_009d86c0& __thiscall FUN_009d86c0(const V_009d86c0* o);
};
void Ucopy_009d86c0(T_009d86c0** out, T_009d86c0* f, T_009d86c0* l, T_009d86c0* d, const void* a);
V_009d86c0& V_009d86c0::FUN_009d86c0(const V_009d86c0* o) {
  const V_009d86c0* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_009d86c0((T_009d86c0**)&o, p->b, p->e, b, o);
  e = (T_009d86c0*)o;
  return *this;
}

// @ 0x00a0a520
struct T_00a0a520 { char d[28]; };
struct V_00a0a520 {
  T_00a0a520 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_00a0a520& __thiscall FUN_00a0a520(const V_00a0a520* o);
};
void Ucopy_00a0a520(T_00a0a520** out, T_00a0a520* f, T_00a0a520* l, T_00a0a520* d, const void* a);
V_00a0a520& V_00a0a520::FUN_00a0a520(const V_00a0a520* o) {
  const V_00a0a520* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_00a0a520((T_00a0a520**)&o, p->b, p->e, b, o);
  e = (T_00a0a520*)o;
  return *this;
}

// @ 0x00a9a310
struct T_00a9a310 { char d[28]; };
struct V_00a9a310 {
  T_00a9a310 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_00a9a310& __thiscall FUN_00a9a310(const V_00a9a310* o);
};
void Ucopy_00a9a310(T_00a9a310** out, T_00a9a310* f, T_00a9a310* l, T_00a9a310* d, const void* a);
V_00a9a310& V_00a9a310::FUN_00a9a310(const V_00a9a310* o) {
  const V_00a9a310* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_00a9a310((T_00a9a310**)&o, p->b, p->e, b, o);
  e = (T_00a9a310*)o;
  return *this;
}

// @ 0x00a9a370
struct T_00a9a370 { char d[28]; };
struct V_00a9a370 {
  T_00a9a370 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_00a9a370& __thiscall FUN_00a9a370(const V_00a9a370* o);
};
void Ucopy_00a9a370(T_00a9a370** out, T_00a9a370* f, T_00a9a370* l, T_00a9a370* d, const void* a);
V_00a9a370& V_00a9a370::FUN_00a9a370(const V_00a9a370* o) {
  const V_00a9a370* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_00a9a370((T_00a9a370**)&o, p->b, p->e, b, o);
  e = (T_00a9a370*)o;
  return *this;
}

// @ 0x00b1a350
struct T_00b1a350 { char d[56]; };
struct V_00b1a350 {
  T_00b1a350 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_00b1a350& __thiscall FUN_00b1a350(const V_00b1a350* o);
};
void Ucopy_00b1a350(T_00b1a350** out, T_00b1a350* f, T_00b1a350* l, T_00b1a350* d, const void* a);
V_00b1a350& V_00b1a350::FUN_00b1a350(const V_00b1a350* o) {
  const V_00b1a350* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_00b1a350((T_00b1a350**)&o, p->b, p->e, b, o);
  e = (T_00b1a350*)o;
  return *this;
}

// @ 0x00c93810
struct T_00c93810 { char d[28]; };
struct V_00c93810 {
  T_00c93810 *b, *e, *c; int al;
  void Buy(int n, const int* a);
  V_00c93810& __thiscall FUN_00c93810(const V_00c93810* o);
};
void Ucopy_00c93810(T_00c93810** out, T_00c93810* f, T_00c93810* l, T_00c93810* d, const void* a);
V_00c93810& V_00c93810::FUN_00c93810(const V_00c93810* o) {
  const V_00c93810* p = o;
  Buy(p->e - p->b, &p->al);
  Ucopy_00c93810((T_00c93810**)&o, p->b, p->e, b, o);
  e = (T_00c93810*)o;
  return *this;
}
