#!/usr/bin/env python3
"""Reverse Spore FNV name hashes using SporeModder-FX's name registries (GPL-3.0 reference data,
read in place, never copied into this repo).

usage: hashnames.py <refs dir> --resolve 0x4133fe05 [...]
       hashnames.py <refs dir> --key-inits        # name the static ResourceKey initializers
Registry lines are "name<TAB>0xhash" or a bare name (hash = FNV-1 of the lowercased name).
"""
import json, os, re, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "matching"))

def fnv(s):
    h = 0x811C9DC5
    for ch in s.encode("latin-1", "replace"):
        c = ch - 256 if ch >= 128 else ch
        c &= 0xFFFF
        if 0x41 <= c <= 0x5A:
            c += 32
        h = ((h * 0x01000193) & 0xFFFFFFFF) ^ c
    return h

def load(refs):
    table = {}
    for f in ("reg_file.txt", "reg_type.txt", "reg_property.txt", "reg_simulator.txt", "reg_simulator_stub.txt"):
        p = os.path.join(refs, f)
        if not os.path.exists(p):
            continue
        for line in open(p, encoding="utf-8", errors="replace"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = re.split(r"\t+", line)
            name = parts[0].strip()
            h = int(parts[1], 16) if len(parts) > 1 and parts[1].strip().startswith("0x") else fnv(name)
            table.setdefault(h, name)
    return table

if __name__ == "__main__":
    refs = sys.argv[1]
    t = load(refs)
    print("loaded %d names" % len(t), file=sys.stderr)
    if "--resolve" in sys.argv:
        for x in [a for a in sys.argv[sys.argv.index("--resolve") + 1:] if not a.startswith("--")]:
            print(x, t.get(int(x, 16), "?"))
    if "--key-inits" in sys.argv:
        from card import load_funcs, bounds
        import capstone
        md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
        root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        pats = json.load(open(os.path.join(root, "work/patterns.json")))
        grp = next(p for p in pats if p["pattern"].startswith("xor eax, eax ; mov dword ptr [A], A ; mov dword ptr [A], eax ; mov dword ptr [A], eax ; ret"))
        starts, _ = load_funcs()
        hit = 0; out = []
        for v in grp["vas"]:
            va = int(v, 16)
            ins = list(md.disasm(bounds(va, starts), va))
            m = re.match(r"dword ptr \[(0x[0-9a-f]+)\], (0x[0-9a-f]+)", ins[1].op_str)
            g, h = int(m.group(1), 16), int(m.group(2), 16)
            name = t.get(h)
            if name:
                hit += 1
                safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
                out.append("%08x k_%s_%08x  # hash 0x%08x = \"%s\" (SporeModder registry)\n" % (g, safe, g, h, name))
        open(os.path.join(root, "symbols/key_globals.txt"), "w").write("# Generated by tools/hashnames.py\n" + "".join(out))
        print("named %d / %d key globals" % (hit, len(grp["vas"])))
