#!/usr/bin/env python3
"""Project status: per-function coverage at each fidelity tier. Writes docs/STATUS.md."""
import csv, glob, os, re, subprocess
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W = lambda *p: os.path.join(ROOT, *p)

funcs = {}
for f in glob.glob(W("work/decomp_all/index_*.csv")):
    for addr, name, size, status, lines in csv.reader(open(f)):
        funcs[int(addr, 16)] = dict(name=name, size=int(size), status=status)
total = len(funcs)
decomp = sum(1 for v in funcs.values() if v["status"] == "ok")

lib = {}
for line in open(W("symbols/lib_names.txt")):
    p = line.split("#", 1)[0].split()
    if len(p) >= 2:
        lib[int(p[0], 16)] = (p[1].split("::")[0].replace("lib_", ""), p[1])
lib_in_funcs = {a: v for a, v in lib.items() if a in funcs}

exact = set()
nonmatching = set()
for f in glob.glob(W("match/slices/*/nonmatching.txt")):
    for line in open(f):
        p = line.split("#", 1)[0].split()
        if p:
            nonmatching.add(int(p[0], 16))
clones = set()
if os.path.exists(W("match/clones.txt")):
    for line in open(W("match/clones.txt")):
        p = line.split("#", 1)[0].split()
        if len(p) >= 3:
            clones.add(int(p[2], 16))
# C++ static-initializer table (__xc_a..__xc_z), the range passed to _initterm at 0x011E0F98.
import struct as _st
_img = open(W("work/SporeApp.analysis.bin"), "rb").read()
def _rva_off(rva):
    e = _st.unpack_from("<I", _img, 0x3C)[0]; n = _st.unpack_from("<H", _img, e + 6)[0]
    o = e + 24 + _st.unpack_from("<H", _img, e + 20)[0]
    for i in range(n):
        vs, va, rs, rp = _st.unpack_from("<IIII", _img, o + 40 * i + 8)
        if va <= rva < va + max(vs, rs):
            return rp + rva - va
XC_A, XC_Z = 0x013CC80C, 0x013EB098
xcu = set()
for a in range(XC_A, XC_Z, 4):
    v = _st.unpack_from("<I", _img, _rva_off(a - 0x400000))[0]
    if v:
        xcu.add(v)
synth = set(); synth_orig = set(); synth_shape = set()
for f in glob.glob(W("match/synth/*.manifest")):
    for line in open(f):
        p = line.split("#", 1)[0].split()
        if len(p) >= 3:
            va = int(p[2], 16)
            synth.add(va)
            (synth_shape if (va in xcu and not p[1].startswith("??__E")) else synth_orig).add(va)
for line in [l for m in [W("match/manifest.txt")] + glob.glob(W("match/slices/*/manifest.txt")) for l in open(m)]:
    p = line.split("#", 1)[0].split()
    if len(p) >= 3:
        exact.add(int(p[2], 16))

named = set()
for line in (l for f in glob.glob(W("symbols/*.txt")) for l in open(f)):
    p = line.split("#", 1)[0].split()
    if p:
        named.add(int(p[0], 16))
named |= set(lib_in_funcs)

bytes_total = sum(v["size"] for v in funcs.values())
def pct(n, d): return "%.2f%%" % (100.0 * n / d) if d else "-"
by_lib = {}
for tag, _ in lib_in_funcs.values():
    by_lib[tag] = by_lib.get(tag, 0) + 1
lib_bytes = sum(funcs[a]["size"] for a in lib_in_funcs)

game = set(funcs) - set(lib_in_funcs)          # third-party library code excluded (freebies)
G = len(game)
def row(label, items):
    n = len(items & game)
    return "| %s | %d | %s |" % (label, n, pct(n, G))
has_src = (exact | clones | nonmatching | synth)
out = ["# Status", "",
       "Generated by `tools/status.py`. Denominator = game functions only: all %d functions in the" % total,
       "Ghidra project minus %d third-party library functions (OpenSSL, libpng, zlib, libjpeg, CRT)," % len(lib_in_funcs),
       "which are excluded as freebies (built byte-exact from upstream source).", "",
       "| Tier | Functions | Share of game code |", "|---|---:|---:|",
       "| Game functions (denominator) | %d | 100%% |" % G,
       row("Ghidra pseudocode (readable, NOT compilable)", set(a for a, v in funcs.items() if v["status"] == "ok")),
       row("Named (recovered class/method/global names)", named),
       row("**Compilable source, byte-exact (hand/agent-written)**", exact),
       row("Compilable source, byte-exact via clone (same code, different globals)", clones - exact),
       row("Compilable source, byte-exact, template-generated, original form", synth_orig - exact - clones),
       row("Compilable source, byte-exact, template-generated, shape-only (static initializer written as a plain function)", synth_shape - synth_orig - exact - clones),
       row("Compilable source, behavioral only (not yet byte-exact)", nonmatching - exact),
       row("**Total with compilable source**", has_src),
       "", "Excluded third-party library functions: %d (%s)" % (len(lib_in_funcs), ", ".join("%s %d" % kv for kv in sorted(by_lib.items()))), ""]
open(W("docs/STATUS.md"), "w").write("\n".join(out))
print("\n".join(out))
